language: cpp

compiler:
  - gcc

branches:
  only:
    - lanl
  except:
    - gh-pages

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -y
  - sudo apt-get install --install-suggests -y g++ automake autoconf libtool libboost-all-dev openmpi-bin  libopenmpi-dev doxygen graphviz python2.7
  - sudo apt-get remove -y python3

before_script:
  - ./bootstrap
  - ./configure --with-boost --enable-mpiparallel --enable-multithread --enable-cpp11

script:
  - make check

after_success:
  - cd docs && doxygen doxygen.cfg
  - git checkout gh-pages
  - git checkout lanl docs
  - cp docs/sst-macroscale/html/* .
