language: cpp

compiler:
  - gcc

branches:
  only:
    - lanl
  except:
    - gh-pages

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -y
  - sudo apt-get install -y git g++-4.9  automake autoconf libtool libboost1.55-all-dev openmpi-bin  libopenmpi-dev doxygen graphviz python2.7
  - sudo apt-get remove -y python3

  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 10
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 10

before_script:
  - ./bootstrap.sh
  - ./configure --with-boost --enable-mpiparallel --enable-multithread --enable-cpp11

script:
  - make check

after_success:
  - cd docs && doxygen doxygen.cfg
  - git checkout gh-pages
  - git checkout lanl docs
  - cp docs/sst-macroscale/html/* .
