language: cpp

compiler:
  - g++

branches:
  except:
    - gh-pages

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install:
  # have newer versions of g++ available
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # have newer versions of boost available
  - sudo add-apt-repository -y ppa:boost-latest/ppa

  # install packages
  - sudo apt-get update -y
  - sudo apt-get install -y git g++-4.9 automake autoconf libtool libboost1.55-all-dev openmpi-bin libopenmpi-dev python2.7

  # force g++ to be g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 10
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 10

before_script:
  - ./bootstrap.sh
  - ./configure --with-boost --enable-cpp11 --enable-multithread --enable-mpiparallel  # LDFLAGS=-Wl,--no-as-needed

script:
  - make check