SST/macro: sstmac/common/c_params.h File Reference
c_params.h File Reference
#include <stdbool.h>
Functions
int get_int_param (char *str)
int get_optional_int_param (char *str, int val)
long get_long_param (char *str)
long get_optional_long_param (char *str, long val)
double get_double_param (char *str)
double get_optional_double_param (char *str, double val)
const char * get_param (char *str)
bool get_bool_param (char *str)
bool get_optional_bool_param (char *str, bool val)
const char * get_optional_param (char *str, char *val)
Function Documentation
bool get_bool_param (char * str)
Referenced by DeclareDebugSlot().
double get_double_param (char * str)
Referenced by DeclareDebugSlot().
int get_int_param (char * str)
Referenced by DeclareDebugSlot().
long get_long_param (char * str)
Referenced by DeclareDebugSlot().
bool get_optional_bool_param (char * str, bool val)
Referenced by DeclareDebugSlot().
double get_optional_double_param (char * str, double val)
Referenced by DeclareDebugSlot().
int get_optional_int_param (char * str, int val)
Referenced by DeclareDebugSlot().
long get_optional_long_param (char * str, long val)
Referenced by DeclareDebugSlot().
const char* get_optional_param (char * str, char * val)
Referenced by DeclareDebugSlot().
const char* get_param (char * str)
Referenced by DeclareDebugSlot(), sprockit::SpktFactory< service >::get_extra_param(), sprockit::SpktFactory1InitParam< T, U >::get_extra_param(), sprockit::SpktFactory2InitParams< T, U, V >::get_extra_param(), and sprockit::SpktFactory3InitParams< T, U, V, W >::get_extra_param().