SST/macro: sstmac::sw::service Class Reference
sstmac::sw::service Class Reference abstract
#include <service.h>
Public Member Functions
virtual std::string to_string () const
virtual void start ()
virtual void incoming_event (event *ev)=0
Public Member Functions inherited from sstmac::sw::library
virtual void unregister_all_libs ()
virtual std::string lib_name () const
virtual void init_os (operating_system *os)
virtual void consume_params (sprockit::sim_parameters *params)
operating_system * os () const
virtual ~library ()
Protected Member Functions
service ()
virtual ~service ()
Protected Member Functions inherited from sstmac::sw::library
library ()
void register_lib (library *lib)
This function is provided so that libraries can instantiate, register, and use other libraries.
virtual bool supported () const
This is usually convenient to define to check if the node was set up correctly to support what this library wants to do.
Additional Inherited Members
Static Public Member Functions inherited from sstmac::sw::library
static library * construct_lib (const std::string &libname)
static library * construct_lib (const std::string &libname, const software_id &sid)
static void register_builder (const std::string &libname, library_builder *builder)
Static Protected Member Functions inherited from sstmac::sw::library
static library_builder * builder (const std::string &name)
Protected Attributes inherited from sstmac::sw::library
operating_system * os_
std::string libname_
key::category key_cat_
Detailed Description
Definition at line 24 of file service.h.
Constructor & Destructor Documentation
sstmac::sw::service::service () protected
Referenced by start().
virtual sstmac::sw::service::~service () protected virtual
Referenced by start().
Member Function Documentation
virtual void sstmac::sw::service::incoming_event (event * ev) pure virtual
Implements sstmac::sw::library.
Implemented in sstmac::sumi_server, and sstmac::sw::launcher.
Referenced by start().
virtual void sstmac::sw::service::start () inline virtual
Reimplemented in sstmac::sw::launcher.
Definition at line 35 of file service.h.
References incoming_event(), service(), and ~service().
virtual std::string sstmac::sw::service::to_string () const inline virtual
Reimplemented from sstmac::sw::library.
Reimplemented in sstmac::sw::launcher.
Definition at line 30 of file service.h.
The documentation for this class was generated from the following file:
sstmac/software/libraries/service.h