SST/macro: sprockit::modal_mixin::ModalMixinBase Class Reference
sprockit::modal_mixin::ModalMixinBase Class Reference abstract
#include <util.h>
Protected Member Functions
ModalMixinBase ()
ModalMixinBase (bool disabled)
virtual std::string get_mode_name () const =0
virtual std::string get_baseof_name () const =0
virtual ~ModalMixinBase ()
void throw_method_called_in_wrong_mode (const std::string &method_name) const
void check_mode (const std::string &method_name) const
Protected Attributes
bool disabled_
Detailed Description
Definition at line 149 of file util.h.
Constructor & Destructor Documentation
sprockit::modal_mixin::ModalMixinBase::ModalMixinBase () inline protected
Definition at line 152 of file util.h.
sprockit::modal_mixin::ModalMixinBase::ModalMixinBase (bool disabled) inline protected
Definition at line 154 of file util.h.
virtual sprockit::modal_mixin::ModalMixinBase::~ModalMixinBase () inline protected virtual
Definition at line 159 of file util.h.
Member Function Documentation
void sprockit::modal_mixin::ModalMixinBase::check_mode (const std::string & method_name) const inline protected
Definition at line 173 of file util.h.
References disabled_, and throw_method_called_in_wrong_mode().
virtual std::string sprockit::modal_mixin::ModalMixinBase::get_baseof_name () const protected pure virtual
Referenced by throw_method_called_in_wrong_mode().
virtual std::string sprockit::modal_mixin::ModalMixinBase::get_mode_name () const protected pure virtual
Referenced by throw_method_called_in_wrong_mode().
void sprockit::modal_mixin::ModalMixinBase::throw_method_called_in_wrong_mode (const std::string & method_name) const inline protected
Definition at line 161 of file util.h.
References get_baseof_name(), get_mode_name(), and spkt_throw_printf.
Referenced by check_mode().
Member Data Documentation
bool sprockit::modal_mixin::ModalMixinBase::disabled_ protected
Definition at line 171 of file util.h.
Referenced by check_mode().
The documentation for this class was generated from the following file:
sprockit/sprockit/util.h