SST/macro: sstmac::hw::node Class Reference
sstmac::hw::node Class Reference abstract
#include <node.h>
Public Member Functions
virtual void set_event_manager (event_manager *man)
Set the eventmanager for this scheduler.
virtual ~node ()
virtual void finalize_init ()
Standard factory type initializer.
virtual void init_factory_params (sprockit::sim_parameters *params)
Standard factory type initializer.
void set_nic (nic *n)
Initializer used in stand-alone core.
void connect (int src_outport, int dst_inport, connection_type_t ty, connectable *mod, config *cfg)
connect
memory_model * mem () const
nic * get_nic () const
sw::operating_system * os () const
virtual std::string to_string () const
node_id addr () const
void fail_stop ()
Cause the node to crash.
void compute (timestamp t)
unique_msg_id allocate_unique_id ()
Choose a unique (64-bit) integer ID for a message.
virtual void execute_kernel (ami::COMP_FUNC func, event *data)=0
Make the node execute a particular compute function.
virtual void execute_kernel (ami::COMM_FUNC func, message *data)=0
Make the node execute a particular communication function.
virtual bool kernel_supported (ami::COMP_FUNC func) const =0
virtual bool kernel_supported (ami::COMM_FUNC func) const =0
virtual void handle (event *ev)
void launch (timestamp start, sw::launch_event *msg)
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Public Member Functions inherited from sstmac::hw::failable
bool failed () const
void fail ()
Public Member Functions inherited from sstmac::event_scheduler
virtual ~event_scheduler ()
void cancel_all_messages ()
void ipc_schedule (timestamp t, event_handler *handler, event *ev)
ipc_schedule Should only be called on stub handlers for which handler->ipc_handler() returns true
void schedule (timestamp t, event_handler *handler, event *ev)
Add an event to the event queue, where msg will get delivered to handler at time t.
void schedule (timestamp t, event_queue_entry *ev)
void schedule_now (event_queue_entry *ev)
void schedule_now (event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_queue_entry *ev)
void send_self_event (timestamp arrival, event *ev)
void send_delayed_self_event (timestamp delay, event *ev)
void send_now_self_event (event *ev)
void send_self_event_queue (timestamp arrival, event_queue_entry *ev)
void send_delayed_self_event_queue (timestamp delay, event_queue_entry *ev)
void send_now_self_event_queue (event_queue_entry *ev)
void register_stat (stat_collector *coll)
event_manager * event_mgr () const
timestamp now () const
get the current time
int nthread () const
Public Member Functions inherited from sstmac::event_handler
virtual ~event_handler ()
event_loc_id event_location () const
virtual bool ipc_handler () const
Whether an event handler is a "fake" handler that represents logical process boundary.
int thread_id () const
virtual void deadlock_check (event *ev)
virtual void deadlock_check ()
Protected Member Functions
node ()
void send_to_nic (network_message *netmsg)
Push a network message (operation at the MTL layer) onto the NIC.
void connect_nic ()
Protected Member Functions inherited from sstmac::hw::failable
failable ()
Protected Member Functions inherited from sstmac::event_scheduler
event_scheduler ()
Protected Member Functions inherited from sstmac::event_handler
event_handler ()
void init_loc_id (event_loc_id id)
void init_thread_id (int id)
Protected Attributes
sw::app_launch * env_
sw::operating_system * os_
node_id my_addr_
memory_model * mem_model_
processor * proc_
nic * nic_
int ncores_
int nsocket_
Protected Attributes inherited from sstmac::hw::failable
bool failed_
Protected Attributes inherited from sstmac::event_scheduler
uint32_t seqnum_
Private Member Functions
void build_launchers (sprockit::sim_parameters *params)
Private Attributes
std::list< sw::launch_event * > launchers_
unique_msg_id next_outgoing_id_
Additional Inherited Members
Public Types inherited from sstmac::hw::connectable
enum config_type_t {
RedundantConnection =0, WeightedConnection =1, FixedBandwidthConnection =2, FixedConnection =3,
BasicConnection =4
}
enum connection_type_t { output, input }
Static Public Member Functions inherited from sstmac::hw::connectable
static const char * str (connection_type_t ty)
Static Public Attributes inherited from sstmac::event_handler
static const int null_lpid = -1
static const int null_threadid = -1
Static Public Attributes inherited from sstmac::hw::connectable
static const int any_port = -1
Detailed Description
Definition at line 42 of file node.h.
Constructor & Destructor Documentation
virtual sstmac::hw::node::~node () virtual
sstmac::hw::node::node () protected
Referenced by allocate_unique_id().
Member Function Documentation
node_id sstmac::hw::node::addr () const inline
Returns
A unique integer identifier
Definition at line 126 of file node.h.
References compute(), fail_stop(), and my_addr_.
unique_msg_id sstmac::hw::node::allocate_unique_id () inline
Choose a unique (64-bit) integer ID for a message.
This will never be reused except for integer overflow.
Returns
A unique 64-bit integer
Definition at line 143 of file node.h.
References connect_nic(), execute_kernel(), handle(), kernel_supported(), next_outgoing_id_, node(), and send_to_nic().
void sstmac::hw::node::build_launchers (sprockit::sim_parameters * params) private
void sstmac::hw::node::compute (timestamp t)
Referenced by addr().
void sstmac::hw::node::connect (int src_outport, int dst_inport, connection_type_t ty, connectable * mod, config * cfg) virtual
connect
Parameters
src_outport The outgoing port at the source
dst_inport The incoming port at the destination
ty Whether we are configuring the input or output direction
mod The device currently being connected
cfg A struct with various special configuration options
Implements sstmac::hw::connectable.
Referenced by set_nic().
void sstmac::hw::node::connect_nic () protected
Referenced by allocate_unique_id().
virtual void sstmac::hw::node::execute_kernel (ami::COMP_FUNC func, event * data) pure virtual
Make the node execute a particular compute function.
Parameters
func Enum identifying the type of computation
data Event object encapsulating data/metadata for computation
Implemented in sstmac::hw::simple_node.
Referenced by allocate_unique_id().
virtual void sstmac::hw::node::execute_kernel (ami::COMM_FUNC func, message * data) pure virtual
Make the node execute a particular communication function.
Parameters
func Enum identifying the type of communication
data Event object encapsulating data/metadata for communication
Implemented in sstmac::hw::simple_node.
void sstmac::hw::node::fail_stop ()
Cause the node to crash.
This cancels all future events for this node.
Referenced by addr().
virtual void sstmac::hw::node::finalize_init () virtual
Standard factory type initializer.
Perform extra initialization work after all parameters have been read in.
Reimplemented from sprockit::factory_type.
Reimplemented in sstmac::hw::simple_node.
nic* sstmac::hw::node::get_nic () const inline
Returns
A handler wrapper for scheduling events to the NIC
Definition at line 104 of file node.h.
References nic_.
virtual void sstmac::hw::node::handle (event * ev) virtual
Reimplemented from sstmac::event_scheduler.
Referenced by allocate_unique_id().
virtual void sstmac::hw::node::init_factory_params (sprockit::sim_parameters * params) virtual
Standard factory type initializer.
Read in all parameters. The parameter object
Reimplemented in sstmac::hw::simple_node, and sstmac::hw::null_node.
virtual bool sstmac::hw::node::kernel_supported (ami::COMP_FUNC func) const pure virtual
Parameters
func Enum identifying the type of computation
Returns
Whether the given node and processor models supports the compute function
Implemented in sstmac::hw::simple_node.
Referenced by allocate_unique_id().
virtual bool sstmac::hw::node::kernel_supported (ami::COMM_FUNC func) const pure virtual
Parameters
func Enum identifying the type of communication
Returns
Whether the given node and nic models supports the comm function
Implemented in sstmac::hw::simple_node.
void sstmac::hw::node::launch (timestamp start, sw::launch_event * msg)
memory_model* sstmac::hw::node::mem () const inline
Returns
The object encapsulating the memory model
Definition at line 96 of file node.h.
References mem_model_.
sw::operating_system* sstmac::hw::node::os () const inline
Returns
The operating system managing apps on this node
Definition at line 112 of file node.h.
References os_, and to_string().
void sstmac::hw::node::send_to_nic (network_message * netmsg) protected
Push a network message (operation at the MTL layer) onto the NIC.
Parameters
netmsg
Referenced by allocate_unique_id().
virtual void sstmac::hw::node::set_event_manager (event_manager * m) virtual
Set the eventmanager for this scheduler.
Unfortunately, this always has to be called after an event_scheduler is constructed.
Parameters
m the simulation eventmanager
Reimplemented from sstmac::event_scheduler.
Reimplemented in sstmac::hw::simple_node.
void sstmac::hw::node::set_nic (nic * n) inline
Initializer used in stand-alone core.
Parameters
n The network interface object
Definition at line 83 of file node.h.
References connect(), and nic_.
virtual std::string sstmac::hw::node::to_string () const virtual
Returns
A unique string description of the node
Reimplemented from sstmac::event_scheduler.
Referenced by os().
Member Data Documentation
sw::app_launch* sstmac::hw::node::env_ protected
Definition at line 194 of file node.h.
std::list<sw::launch_event*> sstmac::hw::node::launchers_ private
Definition at line 214 of file node.h.
memory_model* sstmac::hw::node::mem_model_ protected
Definition at line 200 of file node.h.
Referenced by mem().
node_id sstmac::hw::node::my_addr_ protected
Definition at line 198 of file node.h.
Referenced by addr().
int sstmac::hw::node::ncores_ protected
Definition at line 206 of file node.h.
unique_msg_id sstmac::hw::node::next_outgoing_id_ private
Definition at line 215 of file node.h.
Referenced by allocate_unique_id().
nic* sstmac::hw::node::nic_ protected
Definition at line 204 of file node.h.
Referenced by get_nic(), and set_nic().
int sstmac::hw::node::nsocket_ protected
Definition at line 208 of file node.h.
sw::operating_system* sstmac::hw::node::os_ protected
Definition at line 196 of file node.h.
Referenced by os().
processor* sstmac::hw::node::proc_ protected
Definition at line 202 of file node.h.
The documentation for this class was generated from the following file:
sstmac/hardware/node/node.h