SST/macro: sstmac::hw::param_expander Class Reference
sstmac::hw::param_expander Class Reference
#include <param_expander.h>
Protected Member Functions
virtual double network_bandwidth_multiplier (sprockit::sim_parameters *params) const
virtual double switch_bandwidth_multiplier (sprockit::sim_parameters *params) const
virtual int switch_buffer_multiplier (sprockit::sim_parameters *params) const
Additional Inherited Members
Public Member Functions inherited from sstmac::param_expander
virtual ~param_expander ()
virtual void expand (sprockit::sim_parameters *params)=0
virtual void finalize_init ()
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Detailed Description
Definition at line 9 of file param_expander.h.
Member Function Documentation
virtual double sstmac::hw::param_expander::network_bandwidth_multiplier (sprockit::sim_parameters * params) const protected virtual
Reimplemented in sstmac::hw::packet_flow_param_expander.
virtual double sstmac::hw::param_expander::switch_bandwidth_multiplier (sprockit::sim_parameters * params) const protected virtual
Reimplemented in sstmac::hw::packet_flow_param_expander.
Referenced by sstmac::hw::packet_flow_param_expander::network_bandwidth_multiplier(), and sstmac::hw::packet_flow_param_expander::switch_bandwidth_multiplier().
virtual int sstmac::hw::param_expander::switch_buffer_multiplier (sprockit::sim_parameters * params) const protected virtual
Reimplemented in sstmac::hw::packet_flow_param_expander.
Referenced by sstmac::hw::packet_flow_param_expander::switch_buffer_multiplier().
The documentation for this class was generated from the following file:
sstmac/hardware/common/param_expander.h