SST/macro: sstmac::hw::packet_flow_param_expander Class Reference
sstmac::hw::packet_flow_param_expander Class Reference
#include <packet_flow_param_expander.h>
Public Member Functions
std::string to_string () const
virtual void expand (sprockit::sim_parameters *params)
Public Member Functions inherited from sstmac::param_expander
virtual ~param_expander ()
virtual void finalize_init ()
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Private Member Functions
void expand_amm1_nic (sprockit::sim_parameters *params, sprockit::sim_parameters *nic_params)
void expand_amm1_network (sprockit::sim_parameters *params, sprockit::sim_parameters *switch_params, int packet_size, bool set_xbar)
void expand_amm1_memory (sprockit::sim_parameters *params, sprockit::sim_parameters *mem_params)
void expand_amm2_memory (sprockit::sim_parameters *params, sprockit::sim_parameters *mem_params)
void expand_amm3_network (sprockit::sim_parameters *params, sprockit::sim_parameters *switch_params, int packet_size)
void expand_amm4_nic (sprockit::sim_parameters *params, sprockit::sim_parameters *top_params, sprockit::sim_parameters *nic_params)
void expand_amm4_network (sprockit::sim_parameters *params, sprockit::sim_parameters *top_params, sprockit::sim_parameters *nic_params, int packet_size)
double switch_bandwidth_multiplier (sprockit::sim_parameters *params) const
int switch_buffer_multiplier (sprockit::sim_parameters *params) const
double network_bandwidth_multiplier (sprockit::sim_parameters *params) const
Private Attributes
int buffer_depth_
bool tiled_switch_
Additional Inherited Members
Detailed Description
Definition at line 9 of file packet_flow_param_expander.h.
Member Function Documentation
virtual void sstmac::hw::packet_flow_param_expander::expand (sprockit::sim_parameters * params) virtual
Implements sstmac::param_expander.
Referenced by to_string().
void sstmac::hw::packet_flow_param_expander::expand_amm1_memory (sprockit::sim_parameters * params, sprockit::sim_parameters * mem_params) private
Referenced by to_string().
void sstmac::hw::packet_flow_param_expander::expand_amm1_network (sprockit::sim_parameters * params, sprockit::sim_parameters * switch_params, int packet_size, bool set_xbar) private
Referenced by to_string().
void sstmac::hw::packet_flow_param_expander::expand_amm1_nic (sprockit::sim_parameters * params, sprockit::sim_parameters * nic_params) private
Referenced by to_string().
void sstmac::hw::packet_flow_param_expander::expand_amm2_memory (sprockit::sim_parameters * params, sprockit::sim_parameters * mem_params) private
Referenced by to_string().
void sstmac::hw::packet_flow_param_expander::expand_amm3_network (sprockit::sim_parameters * params, sprockit::sim_parameters * switch_params, int packet_size) private
Referenced by to_string().
void sstmac::hw::packet_flow_param_expander::expand_amm4_network (sprockit::sim_parameters * params, sprockit::sim_parameters * top_params, sprockit::sim_parameters * nic_params, int packet_size) private
Referenced by to_string().
void sstmac::hw::packet_flow_param_expander::expand_amm4_nic (sprockit::sim_parameters * params, sprockit::sim_parameters * top_params, sprockit::sim_parameters * nic_params) private
Referenced by to_string().
double sstmac::hw::packet_flow_param_expander::network_bandwidth_multiplier (sprockit::sim_parameters * params) const inline private virtual
Reimplemented from sstmac::hw::param_expander.
Definition at line 60 of file packet_flow_param_expander.h.
References sstmac::hw::param_expander::network_bandwidth_multiplier(), and tiled_switch_.
double sstmac::hw::packet_flow_param_expander::switch_bandwidth_multiplier (sprockit::sim_parameters * params) const inline private virtual
Reimplemented from sstmac::hw::param_expander.
Definition at line 44 of file packet_flow_param_expander.h.
References sstmac::hw::param_expander::switch_bandwidth_multiplier(), and tiled_switch_.
int sstmac::hw::packet_flow_param_expander::switch_buffer_multiplier (sprockit::sim_parameters * params) const inline private virtual
Reimplemented from sstmac::hw::param_expander.
Definition at line 52 of file packet_flow_param_expander.h.
References sstmac::hw::param_expander::switch_buffer_multiplier(), and tiled_switch_.
std::string sstmac::hw::packet_flow_param_expander::to_string () const inline
Definition at line 14 of file packet_flow_param_expander.h.
References expand(), expand_amm1_memory(), expand_amm1_network(), expand_amm1_nic(), expand_amm2_memory(), expand_amm3_network(), expand_amm4_network(), and expand_amm4_nic().
Member Data Documentation
int sstmac::hw::packet_flow_param_expander::buffer_depth_ private
Definition at line 68 of file packet_flow_param_expander.h.
bool sstmac::hw::packet_flow_param_expander::tiled_switch_ private
Definition at line 70 of file packet_flow_param_expander.h.
Referenced by network_bandwidth_multiplier(), switch_bandwidth_multiplier(), and switch_buffer_multiplier().
The documentation for this class was generated from the following file:
sstmac/hardware/packet_flow/packet_flow_param_expander.h