SST/macro: sstmac::sw::sstmac_global_struct< T * > Class Template Reference
sstmac::sw::sstmac_global_struct< T * > Class Template Reference
#include <global_struct.h>
Public Member Functions
sstmac_global_struct ()
sstmac_global_struct (T *init)
operator T * ()
operator const T * () const
template<typename U >
T *& operator= (const sstmac_global_struct< U > &b)
T *& operator= (T *b)
template<typename U >
T *& operator= (U *b)
T *& operator-> ()
Public Member Functions inherited from sstmac::sw::sstmac_global_builtin< T * >
sstmac_global_builtin ()
sstmac_global_builtin (T *init)
virtual ~sstmac_global_builtin ()
virtual T *& get_val (int n=0) const
virtual std::string to_string () const
template<typename U >
T *& operator= (const sstmac_global_builtin< U > &b)
template<typename U >
T *& operator= (U *b)
T * operator++ ()
T * operator-- ()
T * operator++ (int dummy)
T * operator-- (int dummy)
template<typename U >
T * operator+ (const U &b)
template<typename U >
T * operator- (const U &b)
operator char * ()
operator int * ()
operator long * ()
operator void * ()
operator const char * () const
operator const int * () const
operator const long * () const
operator const void * () const
T & operator* ()
template<typename U >
bool operator== (const U &b) const
T * operator-> ()
T & operator[] (int idx)
T & operator[] (long idx)
const_iterator begin () const
const_iterator end () const
Private Types
typedef sstmac_global_builtin< T * > parent
Additional Inherited Members
Public Types inherited from sstmac::sw::sstmac_global_builtin< T * >
typedef val_map::const_iterator const_iterator
Protected Types inherited from sstmac::sw::sstmac_global_builtin< T * >
typedef spkt_unordered_map< long, T * > val_map
typedef T * Tptr
Protected Member Functions inherited from sstmac::sw::sstmac_global_builtin< T * >
bool check_init (process_context ptxt)
Protected Member Functions inherited from sstmac::sw::sstmac_global
process_context current_context () const
Protected Attributes inherited from sstmac::sw::sstmac_global_builtin< T * >
val_map vals_
T * init_
Detailed Description
template<typename T>
class sstmac::sw::sstmac_global_struct< T * >
Definition at line 88 of file global_struct.h.
Member Typedef Documentation
template<typename T > typedef sstmac_global_builtin<T*> sstmac::sw::sstmac_global_struct< T * >::parent private
Definition at line 90 of file global_struct.h.
Constructor & Destructor Documentation
template<typename T > sstmac::sw::sstmac_global_struct< T * >::sstmac_global_struct () inline explicit
Definition at line 93 of file global_struct.h.
template<typename T > sstmac::sw::sstmac_global_struct< T * >::sstmac_global_struct (T * init) inline explicit
Definition at line 97 of file global_struct.h.
Member Function Documentation
template<typename T > sstmac::sw::sstmac_global_struct< T * >::operator const T * () const inline
Definition at line 105 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T > sstmac::sw::sstmac_global_struct< T * >::operator T * () inline
Definition at line 101 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T > T*& sstmac::sw::sstmac_global_struct< T * >::operator-> () inline
Definition at line 133 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T > template<typename U > T*& sstmac::sw::sstmac_global_struct< T * >::operator= (const sstmac_global_struct< U > & b) inline
Definition at line 111 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T > T*& sstmac::sw::sstmac_global_struct< T * >::operator= (T * b) inline
Definition at line 118 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T > template<typename U > T*& sstmac::sw::sstmac_global_struct< T * >::operator= (U * b) inline
Definition at line 126 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
The documentation for this class was generated from the following file:
sstmac/software/process/global_struct.h