SST/macro: sstmac::stat_global_int Class Reference
sstmac::stat_global_int Class Reference
#include <stat_global_int.h>
Public Member Functions
stat_global_int ()
void collect (int value)
void simulation_finished (timestamp end)
This is to notify that the statistics collector is done.
void dump_local_data ()
After post-processing, this notifies the collector to dump data to a file.
void dump_global_data ()
After post-processing, this notifies the collector to dump data to a file.
void global_reduce (parallel_runtime *rt)
void clear ()
void reduce (stat_collector *coll)
void init_factory_params (sprockit::sim_parameters *params)
stat_global_int * clone_me (int id) const
stat_collector * clone () const
void set_label (std::string label)
Public Member Functions inherited from sstmac::stat_collector
virtual ~stat_collector ()
virtual std::string to_string () const
bool registered () const
virtual void set_id (int id)
int id () const
void set_registered (bool reg)
void add_suffix (const std::string &suffix)
std::string fileroot () const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Member Functions
void dump (const std::string &froot)
void clone_into (stat_global_int *cln) const
Protected Member Functions inherited from sstmac::stat_collector
stat_collector ()
void clone_into (stat_collector *cln) const
Protected Attributes
int value_
std::string label_
Protected Attributes inherited from sstmac::stat_collector
bool registered_
int id_
std::string fileroot_
Additional Inherited Members
Static Public Member Functions inherited from sstmac::stat_collector
static stat_collector * optional_build (sprockit::sim_parameters *params, const std::string &ns, const std::string &deflt, const char *suffix)
Static Protected Member Functions inherited from sstmac::stat_collector
static bool check_open (std::fstream &myfile, const std::string &fname, std::ios::openmode flags=std::ios::out)
Check to see if the file is open.
Detailed Description
Definition at line 10 of file stat_global_int.h.
Constructor & Destructor Documentation
sstmac::stat_global_int::stat_global_int ()
Referenced by clone_me().
Member Function Documentation
void sstmac::stat_global_int::clear () virtual
Implements sstmac::stat_collector.
stat_collector* sstmac::stat_global_int::clone () const inline virtual
Implements sstmac::stat_collector.
Definition at line 50 of file stat_global_int.h.
References clone_me().
void sstmac::stat_global_int::clone_into (stat_global_int * cln) const protected
Referenced by clone_me(), and set_label().
stat_global_int* sstmac::stat_global_int::clone_me (int id) const inline
Definition at line 41 of file stat_global_int.h.
References clone_into(), label_, sstmac::stat_collector::set_id(), set_label(), and stat_global_int().
Referenced by clone().
void sstmac::stat_global_int::collect (int value)
void sstmac::stat_global_int::dump (const std::string & froot) protected
Referenced by set_label().
void sstmac::stat_global_int::dump_global_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
void sstmac::stat_global_int::dump_local_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
void sstmac::stat_global_int::global_reduce (parallel_runtime * rt) virtual
Implements sstmac::stat_collector.
void sstmac::stat_global_int::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::stat_collector.
void sstmac::stat_global_int::reduce (stat_collector * coll) virtual
Implements sstmac::stat_collector.
void sstmac::stat_global_int::set_label (std::string label) inline
Definition at line 55 of file stat_global_int.h.
References clone_into(), dump(), and label_.
Referenced by clone_me().
void sstmac::stat_global_int::simulation_finished (timestamp end) virtual
This is to notify that the statistics collector is done.
Do any necessary data post-processing, but do NOT dump to file
Implements sstmac::stat_collector.
Member Data Documentation
std::string sstmac::stat_global_int::label_ protected
Definition at line 68 of file stat_global_int.h.
Referenced by clone_me(), and set_label().
int sstmac::stat_global_int::value_ protected
Definition at line 67 of file stat_global_int.h.
The documentation for this class was generated from the following file:
sstmac/common/stats/stat_global_int.h