SST/macro: sstmac::wrapper_payload Class Reference
sstmac::wrapper_payload Class Reference
Network payload that wraps a raw buffer.
#include <wrapper_payload.h>
Public Types
typedef sprockit::refcount_ptr< wrapper_payload > ptr
typedef sprockit::refcount_ptr< const wrapper_payload > const_ptr
Public Types inherited from sstmac::payload
typedef sprockit::refcount_ptr< payload > ptr
typedef sprockit::refcount_ptr< const payload > const_ptr
Public Member Functions
wrapper_payload ()
virtual ~wrapper_payload ()
payload::const_ptr clone () const
Clone this object.
void * data () const
virtual long byte_length () const
virtual payload::const_ptr add (const payload::const_ptr &other) const
Add operator.
virtual payload::const_ptr prod (const payload::const_ptr &other) const
virtual payload::const_ptr min (const payload::const_ptr &other) const
Less than comparator.
virtual payload::const_ptr max (const payload::const_ptr &other) const
Greater than comparator.
virtual bool equals (const payload::const_ptr &other) const
Equals comparator.
virtual payload::const_ptr logical_or (const payload::const_ptr &other) const
Logical or comparator.
virtual payload::const_ptr logical_xor (const payload::const_ptr &other) const
Logical xor comparator.
virtual payload::const_ptr logical_and (const payload::const_ptr &other) const
Logical and comparator.
virtual payload::const_ptr bitwise_or (const payload::const_ptr &other) const
virtual payload::const_ptr bitwise_xor (const payload::const_ptr &other) const
Logical xor comparator.
virtual payload::const_ptr bitwise_and (const payload::const_ptr &other) const
Logical and comparator.
virtual void serialize_order (serializer &ser)
virtual std::string to_string () const
Strinfier.
Public Member Functions inherited from sstmac::payload
virtual ~payload ()
Goodbye.
virtual void recover (sw::api *api)
virtual void assign (void *data)
Public Member Functions inherited from sprockit::ptr_type
ptr_type ()
int nreferences () const
virtual ~ptr_type ()
Public Member Functions inherited from sprockit::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
virtual ~serializable ()
Static Public Member Functions
static const_ptr construct (void *inval, size_t s)
static ptr construct ()
Static Public Member Functions inherited from sstmac::payload
static ptr null ()
Convenience function to get a null payload pointer.
Private Member Functions
ImplementSerializable (wrapper_payload) mutable void *base_
wrapper_payload (void *inval, size_t s)
Construction time.
Private Attributes
size_t size_
Additional Inherited Members
Protected Types inherited from sprockit::serializable
enum cxn_flag_t { ConstructorFlag }
Protected Member Functions inherited from sstmac::payload
payload ()
Empty protected constructor to enforce using construct()
Protected Member Functions inherited from sprockit::ptr_type
void incref ()
int decref ()
Detailed Description
Network payload that wraps a raw buffer.
Must be careful with this, or else false shared-memory things might happen.
Definition at line 26 of file wrapper_payload.h.
Member Typedef Documentation
typedef sprockit::refcount_ptr<const wrapper_payload> sstmac::wrapper_payload::const_ptr
Definition at line 43 of file wrapper_payload.h.
typedef sprockit::refcount_ptr<wrapper_payload> sstmac::wrapper_payload::ptr
Definition at line 42 of file wrapper_payload.h.
Constructor & Destructor Documentation
sstmac::wrapper_payload::wrapper_payload (void * inval, size_t s) inline private
Construction time.
Definition at line 36 of file wrapper_payload.h.
sstmac::wrapper_payload::wrapper_payload () inline
Definition at line 45 of file wrapper_payload.h.
Referenced by clone(), and construct().
virtual sstmac::wrapper_payload::~wrapper_payload () inline virtual
Definition at line 48 of file wrapper_payload.h.
Member Function Documentation
virtual payload::const_ptr sstmac::wrapper_payload::add (const payload::const_ptr & other) const inline virtual
Add operator.
Parameters
other
Returns
a smart pointer to a new valuepayload object
Implements sstmac::payload.
Definition at line 84 of file wrapper_payload.h.
virtual payload::const_ptr sstmac::wrapper_payload::bitwise_and (const payload::const_ptr & other) const inline virtual
Logical and comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 179 of file wrapper_payload.h.
References serialize_order(), and to_string().
virtual payload::const_ptr sstmac::wrapper_payload::bitwise_or (const payload::const_ptr & other) const inline virtual
Implements sstmac::payload.
Definition at line 159 of file wrapper_payload.h.
virtual payload::const_ptr sstmac::wrapper_payload::bitwise_xor (const payload::const_ptr & other) const inline virtual
Logical xor comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 169 of file wrapper_payload.h.
virtual long sstmac::wrapper_payload::byte_length () const inline virtual
Implements sstmac::payload.
Definition at line 74 of file wrapper_payload.h.
References size_.
payload::const_ptr sstmac::wrapper_payload::clone () const inline virtual
Clone this object.
Implements sstmac::payload.
Definition at line 64 of file wrapper_payload.h.
References wrapper_payload().
static const_ptr sstmac::wrapper_payload::construct (void * inval, size_t s) inline static
Definition at line 53 of file wrapper_payload.h.
References wrapper_payload().
static ptr sstmac::wrapper_payload::construct () inline static
Definition at line 58 of file wrapper_payload.h.
References wrapper_payload().
void* sstmac::wrapper_payload::data () const inline virtual
Implements sstmac::payload.
Definition at line 69 of file wrapper_payload.h.
virtual bool sstmac::wrapper_payload::equals (const payload::const_ptr & other) const inline virtual
Equals comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 123 of file wrapper_payload.h.
References ptr_safe_cast.
sstmac::wrapper_payload::ImplementSerializable (wrapper_payload) private
virtual payload::const_ptr sstmac::wrapper_payload::logical_and (const payload::const_ptr & other) const inline virtual
Logical and comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 154 of file wrapper_payload.h.
virtual payload::const_ptr sstmac::wrapper_payload::logical_or (const payload::const_ptr & other) const inline virtual
Logical or comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 134 of file wrapper_payload.h.
virtual payload::const_ptr sstmac::wrapper_payload::logical_xor (const payload::const_ptr & other) const inline virtual
Logical xor comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 144 of file wrapper_payload.h.
virtual payload::const_ptr sstmac::wrapper_payload::max (const payload::const_ptr & other) const inline virtual
Greater than comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 112 of file wrapper_payload.h.
virtual payload::const_ptr sstmac::wrapper_payload::min (const payload::const_ptr & other) const inline virtual
Less than comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 101 of file wrapper_payload.h.
virtual payload::const_ptr sstmac::wrapper_payload::prod (const payload::const_ptr & other) const inline virtual
Implements sstmac::payload.
Definition at line 90 of file wrapper_payload.h.
virtual void sstmac::wrapper_payload::serialize_order (serializer & ser) virtual
Implements sprockit::serializable.
Referenced by bitwise_and().
virtual std::string sstmac::wrapper_payload::to_string () const virtual
Strinfier.
Returns
a std::string description
Reimplemented from sstmac::payload.
Referenced by bitwise_and().
Member Data Documentation
size_t sstmac::wrapper_payload::size_ private
Definition at line 33 of file wrapper_payload.h.
Referenced by byte_length().
The documentation for this class was generated from the following file:
sstmac/common/messages/wrapper_payload.h