SST/macro: sstmac::transport_message Class Reference
sstmac::transport_message Class Reference
#include <message.h>
Protected Member Functions
void clone_into (transport_message *cln) const
void reverse ()
Protected Member Functions inherited from sstmac::hw::network_message
void clone_into (network_message *cln) const
Protected Member Functions inherited from sstmac::library_interface
library_interface (const std::string &libname)
library_interface ()
void clone_into (library_interface *cln) const
Private Member Functions
ImplementSerializable (transport_message) public
transport_message (sw::app_id aid, const sumi::message_ptr &msg, long byte_length)
virtual void serialize_order (serializer &ser)
sumi::message_ptr payload () const
std::string to_string () const
int dest () const
void set_dest (int dest)
int src () const
void set_src (int src)
void set_buffer (void *buf)
void * buffer () const
virtual void put_on_wire ()
void complete_transfer (void *buf)
::sstmac::hw::network_message * clone_injection_ack () const
Private Attributes
sumi::message_ptr payload_
void * buffer_
Additional Inherited Members
Public Member Functions inherited from sstmac::hw::network_message
network_message (sw::app_id aid, node_id toaddr, node_id fromaddr, sw::task_id src, sw::task_id dst, long payload_bytes)
network_message (sw::app_id aid, long payload_bytes)
network_message ()
virtual ~network_message ()
bool is_metadata () const
virtual void nic_reverse (type_t newtype)
bool is_nic_ack () const
node_id toaddr () const
node_id fromaddr () const
void set_toaddr (node_id addr)
void set_fromaddr (node_id addr)
void set_needs_ack (bool n)
virtual bool needs_ack () const
void convert_to_ack ()
void set_net_id (const network_id &id)
network_id net_id () const
uint64_t unique_id () const
sw::task_id source_task () const
sw::app_id aid () const
sw::task_id dest_task () const
type_t type () const
void set_type (type_t ty)
long source_thread (sw::operating_system *os) const
long dest_thread (sw::operating_system *os) const
long byte_length () const
Virtual function to return size.
Public Member Functions inherited from sstmac::message
virtual ~message ()
Public Member Functions inherited from sstmac::event
virtual bool is_packet () const
convenience methods
virtual bool is_credit () const
virtual bool is_failure () const
template<class T >
T * interface ()
Public Member Functions inherited from sprockit::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
virtual ~serializable ()
Public Member Functions inherited from sstmac::library_interface
std::string lib_name () const
Library name getter.
void set_lib_name (const std::string &name)
Library name setter.
void serialize_order (serializer &ser)
Static Public Member Functions inherited from sstmac::hw::network_message
static const char * tostr (nic_event_t mut)
static const char * tostr (type_t ty)
Public Attributes inherited from sstmac::hw::network_message
node_id toaddr_
node_id fromaddr_
Protected Types inherited from sprockit::serializable
enum cxn_flag_t { ConstructorFlag }
Protected Attributes inherited from sstmac::hw::network_message
int app_id_
int flow_id_
network_id net_id_
sw::app_id aid_
bool needs_ack_
sw::task_id src_task_
sw::task_id dest_task_
long bytes_
type_t type_
Protected Attributes inherited from sstmac::library_interface
std::string lib_name_
Detailed Description
Definition at line 13 of file message.h.
Constructor & Destructor Documentation
sstmac::transport_message::transport_message (sw::app_id aid, const sumi::message_ptr & msg, long byte_length) private
Referenced by ImplementSerializable().
Member Function Documentation
void* sstmac::transport_message::buffer () const inline private
Definition at line 64 of file message.h.
References buffer_, clone_injection_ack(), clone_into(), complete_transfer(), put_on_wire(), and reverse().
::sstmac::hw::network_message* sstmac::transport_message::clone_injection_ack () const private virtual
Reimplemented from sstmac::hw::network_message.
Referenced by buffer().
void sstmac::transport_message::clone_into (transport_message * cln) const protected
Referenced by buffer().
void sstmac::transport_message::complete_transfer (void * buf) private
Referenced by buffer().
int sstmac::transport_message::dest () const inline private
Definition at line 39 of file message.h.
References sstmac::hw::network_message::dest_task_.
sstmac::transport_message::ImplementSerializable (transport_message) inline private
Definition at line 18 of file message.h.
References sstmac::hw::network_message::aid(), sstmac::hw::network_message::byte_length(), serialize_order(), and transport_message().
sumi::message_ptr sstmac::transport_message::payload () const inline private
Definition at line 31 of file message.h.
References payload_, and to_string().
virtual void sstmac::transport_message::put_on_wire () private virtual
Reimplemented from sstmac::hw::network_message.
Referenced by buffer().
void sstmac::transport_message::reverse () protected virtual
Reimplemented from sstmac::hw::network_message.
Referenced by buffer().
virtual void sstmac::transport_message::serialize_order (serializer & ser) private virtual
Reimplemented from sstmac::hw::network_message.
Referenced by ImplementSerializable().
void sstmac::transport_message::set_buffer (void * buf) inline private
Definition at line 59 of file message.h.
References buffer_.
void sstmac::transport_message::set_dest (int dest) inline private
Definition at line 44 of file message.h.
References sstmac::hw::network_message::dest_task_.
void sstmac::transport_message::set_src (int src) inline private
Definition at line 54 of file message.h.
References sstmac::hw::network_message::src_task_.
int sstmac::transport_message::src () const inline private
Definition at line 49 of file message.h.
References sstmac::hw::network_message::src_task_.
std::string sstmac::transport_message::to_string () const private virtual
Reimplemented from sstmac::hw::network_message.
Referenced by payload().
Member Data Documentation
void* sstmac::transport_message::buffer_ private
Definition at line 86 of file message.h.
Referenced by buffer(), and set_buffer().
sumi::message_ptr sstmac::transport_message::payload_ private
Definition at line 85 of file message.h.
Referenced by payload().
The documentation for this class was generated from the following file:
sstmac/libraries/sumi/message.h