SST/macro: sstmac::sw::node_id_allocation Class Reference
sstmac::sw::node_id_allocation Class Reference
#include <node_id_allocation.h>
Public Member Functions
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual ~node_id_allocation () throw ()
virtual void allocate (int nnode_requested, node_set &allocation)
Get nodes.
Public Member Functions inherited from sstmac::sw::allocation_strategy
virtual void init_param1 (parallel_runtime *rt)
hw::topology * topol () const
void set_interconnect (hw::interconnect *ic)
virtual void set_topology (hw::topology *top)
virtual std::string to_string () const
virtual ~allocation_strategy () throw ()
virtual void release (const node_set &alloc)
Release a set of nodes back into the allocation.
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Static Public Member Functions
static void read_coordinate_file (const std::string &file, std::vector< node_id > &node_list, hw::topology *top)
Protected Attributes
std::string coord_file_
Protected Attributes inherited from sstmac::sw::allocation_strategy
hw::topology * topology_
hw::interconnect * interconn_
parallel_runtime * rt_
Additional Inherited Members
Protected Types inherited from sstmac::sw::allocation_strategy
typedef std::set< node_id > node_set
Protected Member Functions inherited from sstmac::sw::allocation_strategy
allocation_strategy ()
void validate_num_nodes (int num_nodes, const char *type)
Detailed Description
Definition at line 10 of file node_id_allocation.h.
Constructor & Destructor Documentation
virtual sstmac::sw::node_id_allocation::~node_id_allocation () throw () inline virtual
Definition at line 18 of file node_id_allocation.h.
References allocate(), and read_coordinate_file().
Member Function Documentation
virtual void sstmac::sw::node_id_allocation::allocate (int nnode, node_set & allocation) virtual
Get nodes.
Parameters
nnode number of nodes requested
allocation returns the nodes that have been allocated
Exceptions
value_error If not enough nodes are available, then this will throw. Nodes are removed from available and put into allocated.
Implements sstmac::sw::allocation_strategy.
Referenced by ~node_id_allocation().
virtual void sstmac::sw::node_id_allocation::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::sw::allocation_strategy.
static void sstmac::sw::node_id_allocation::read_coordinate_file (const std::string & file, std::vector< node_id > & node_list, hw::topology * top) static
Referenced by ~node_id_allocation().
Member Data Documentation
std::string sstmac::sw::node_id_allocation::coord_file_ protected
Definition at line 30 of file node_id_allocation.h.
The documentation for this class was generated from the following file:
sstmac/software/launch/node_id_allocation.h