SST/macro: sprockit::pvt::ser_unpacker Class Reference
sprockit::pvt::ser_unpacker Class Reference
#include <serialize_unpacker.h>
Public Member Functions
template<class T >
void unpack (T &t)
void unpack_buffer (void *buf, int size)
void unpack_string (std::string &str)
Public Member Functions inherited from sprockit::pvt::ser_buffer_accessor
template<class T >
T * next ()
char * next_str (size_t size)
size_t size () const
size_t max_size () const
void init (void *buffer, size_t size)
void clear ()
void reset ()
Additional Inherited Members
Protected Member Functions inherited from sprockit::pvt::ser_buffer_accessor
ser_buffer_accessor ()
Protected Attributes inherited from sprockit::pvt::ser_buffer_accessor
char * bufstart_
char * bufptr_
size_t size_
size_t max_size_
Detailed Description
Definition at line 9 of file serialize_unpacker.h.
Member Function Documentation
template<class T > void sprockit::pvt::ser_unpacker::unpack (T & t) inline
Definition at line 15 of file serialize_unpacker.h.
References sprockit::pvt::ser_buffer_accessor::size(), unpack_buffer(), and unpack_string().
Referenced by sprockit::serializer::binary(), sprockit::serializer::primitive(), and sprockit::serializer::unpack().
void sprockit::pvt::ser_unpacker::unpack_buffer (void * buf, int size)
Referenced by sprockit::serializer::binary(), and unpack().
void sprockit::pvt::ser_unpacker::unpack_string (std::string & str)
Referenced by unpack().
The documentation for this class was generated from the following file:
sprockit/sprockit/serialize_unpacker.h