SST/macro: sstmac::pair_payload< T1, T2 > Class Template Reference
sstmac::pair_payload< T1, T2 > Class Template Reference
Network payload consisting of a value with sensible copy semantics.
#include <pair_payload.h>
Public Types
typedef sprockit::refcount_ptr< pair_payload< T1, T2 > > ptr
typedef sprockit::refcount_ptr< const pair_payload< T1, T2 > > const_ptr
Public Types inherited from sstmac::payload
typedef sprockit::refcount_ptr< payload > ptr
typedef sprockit::refcount_ptr< const payload > const_ptr
Public Member Functions
virtual ~pair_payload ()
payload::const_ptr clone () const
Clone this object.
std::pair< T1, T2 > data_unconst ()
Access the underlying data in a non-const context.
const std::pair< T1, T2 > data () const
Access the underlying data in a const context.
virtual long byte_length () const
virtual const payload::const_ptr add (const payload::const_ptr &other) const
Add operator.
virtual const payload::const_ptr min (const payload::const_ptr &other) const
Less than comparator, to only be used for the minloc mpi operation.
virtual const payload::const_ptr max (const payload::const_ptr &other) const
Greater than comparator, to only be used for the maxloc operation.
virtual bool equals (const payload::const_ptr &other) const
Equals comparator.
const payload::const_ptr logical_or (const payload::const_ptr &other) const
Logical or comparator.
const payload::const_ptr logical_xor (const payload::const_ptr &other) const
Logical xor comparator.
const payload::const_ptr logical_and (const payload::const_ptr &other) const
Logical and comparator.
virtual void serialize_order (sprockit::spkt_serializer *ser) const
Serialize this object into the spkt_serializer, for running in parallel simulation.
virtual std::string to_string () const
Strinfier.
Public Member Functions inherited from sstmac::payload
virtual ~payload ()
Goodbye.
virtual void recover (sw::api *api)
virtual void assign (void *data)
virtual payload::const_ptr prod (const payload::const_ptr &other) const =0
virtual payload::const_ptr bitwise_or (const payload::const_ptr &other) const =0
virtual payload::const_ptr bitwise_xor (const payload::const_ptr &other) const =0
Pure virtual logical xor operator.
virtual payload::const_ptr bitwise_and (const payload::const_ptr &other) const =0
Pure virtual logical and operator.
Public Member Functions inherited from sprockit::ptr_type
ptr_type ()
int nreferences () const
virtual ~ptr_type ()
Public Member Functions inherited from sprockit::serializable
virtual const char * cls_name () const =0
virtual void serialize_order (sprockit::serializer &ser)=0
virtual uint32_t cls_id () const =0
virtual ~serializable ()
Static Public Member Functions
static pair_payload< T1, T2 >::const_ptr construct (const T1 &inval1, const T2 &inval2)
Construct a new valuepayload.
Static Public Member Functions inherited from sstmac::payload
static ptr null ()
Convenience function to get a null payload pointer.
Private Types
typedef pair_payload< T1, T2 > PairPayload
Private Member Functions
pair_payload (const T1 &inval1, const T2 &inval2, size_t size=sizeof(T1)+sizeof(T2))
Construction time.
pair_payload (const pair_payload< T1, T2 > &other, size_t size=sizeof(T1)+sizeof(T2))
Private copy constructor.
Private Attributes
T1 data1_
The data we keep.
T2 data2_
size_t size_
Additional Inherited Members
Protected Types inherited from sprockit::serializable
enum cxn_flag_t { ConstructorFlag }
Protected Member Functions inherited from sstmac::payload
payload ()
Empty protected constructor to enforce using construct()
Protected Member Functions inherited from sprockit::ptr_type
void incref ()
int decref ()
Detailed Description
template<typename T1, typename T2>
class sstmac::pair_payload< T1, T2 >
Network payload consisting of a value with sensible copy semantics.
Don't use this for pointer types, since you will break assumptions about const-ness or protection of underlying data.
Definition at line 28 of file pair_payload.h.
Member Typedef Documentation
template<typename T1, typename T2> typedef sprockit::refcount_ptr<const pair_payload<T1, T2> > sstmac::pair_payload< T1, T2 >::const_ptr
Definition at line 50 of file pair_payload.h.
template<typename T1, typename T2> typedef pair_payload<T1, T2> sstmac::pair_payload< T1, T2 >::PairPayload private
Definition at line 34 of file pair_payload.h.
template<typename T1, typename T2> typedef sprockit::refcount_ptr<pair_payload<T1, T2> > sstmac::pair_payload< T1, T2 >::ptr
Definition at line 49 of file pair_payload.h.
Constructor & Destructor Documentation
template<typename T1, typename T2> sstmac::pair_payload< T1, T2 >::pair_payload (const T1 & inval1, const T2 & inval2, size_t size = sizeof(T1) + sizeof(T2)) inline private
Construction time.
Definition at line 37 of file pair_payload.h.
template<typename T1, typename T2> sstmac::pair_payload< T1, T2 >::pair_payload (const pair_payload< T1, T2 > & other, size_t size = sizeof(T1) + sizeof(T2)) inline private
Private copy constructor.
Definition at line 43 of file pair_payload.h.
template<typename T1, typename T2> virtual sstmac::pair_payload< T1, T2 >::~pair_payload () inline virtual
Definition at line 53 of file pair_payload.h.
Member Function Documentation
template<typename T1, typename T2> virtual const payload::const_ptr sstmac::pair_payload< T1, T2 >::add (const payload::const_ptr & other) const inline virtual
Add operator.
Parameters
other
Returns
a smart pointer to a new valuepayload object
Implements sstmac::payload.
Definition at line 91 of file pair_payload.h.
References sstmac::pair_payload< T1, T2 >::construct(), sstmac::pair_payload< T1, T2 >::data(), and ptr_safe_cast.
template<typename T1, typename T2> virtual long sstmac::pair_payload< T1, T2 >::byte_length () const inline virtual
Implements sstmac::payload.
Definition at line 81 of file pair_payload.h.
References sstmac::pair_payload< T1, T2 >::size_.
template<typename T1, typename T2> payload::const_ptr sstmac::pair_payload< T1, T2 >::clone () const inline virtual
Clone this object.
Implements sstmac::payload.
Definition at line 64 of file pair_payload.h.
template<typename T1, typename T2> static pair_payload<T1, T2>::const_ptr sstmac::pair_payload< T1, T2 >::construct (const T1 & inval1, const T2 & inval2) inline static
Construct a new valuepayload.
Definition at line 58 of file pair_payload.h.
Referenced by sstmac::pair_payload< T1, T2 >::add(), sstmac::pairpayloadvector< T1, T2 >::add(), sstmac::pair_payload< T1, T2 >::max(), and sstmac::pair_payload< T1, T2 >::min().
template<typename T1, typename T2> const std::pair<T1, T2> sstmac::pair_payload< T1, T2 >::data () const inline virtual
Access the underlying data in a const context.
Implements sstmac::payload.
Definition at line 76 of file pair_payload.h.
References sstmac::pair_payload< T1, T2 >::data1_, and sstmac::pair_payload< T1, T2 >::data2_.
Referenced by sstmac::pair_payload< T1, T2 >::add(), sstmac::pairpayloadvector< T1, T2 >::add(), sstmac::pair_payload< T1, T2 >::equals(), sstmac::pairpayloadvector< T1, T2 >::equals(), and sstmac::pair_payload< T1, T2 >::min().
template<typename T1, typename T2> std::pair<T1, T2> sstmac::pair_payload< T1, T2 >::data_unconst () inline
Access the underlying data in a non-const context.
Definition at line 70 of file pair_payload.h.
References sstmac::pair_payload< T1, T2 >::data1_, and sstmac::pair_payload< T1, T2 >::data2_.
template<typename T1, typename T2> virtual bool sstmac::pair_payload< T1, T2 >::equals (const payload::const_ptr & other) const inline virtual
Equals comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 144 of file pair_payload.h.
References sstmac::pair_payload< T1, T2 >::data(), and ptr_safe_cast.
template<typename T1, typename T2> const payload::const_ptr sstmac::pair_payload< T1, T2 >::logical_and (const payload::const_ptr & other) const inline virtual
Logical and comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 179 of file pair_payload.h.
References spkt_throw_printf.
template<typename T1, typename T2> const payload::const_ptr sstmac::pair_payload< T1, T2 >::logical_or (const payload::const_ptr & other) const inline virtual
Logical or comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 157 of file pair_payload.h.
References spkt_throw_printf.
template<typename T1, typename T2> const payload::const_ptr sstmac::pair_payload< T1, T2 >::logical_xor (const payload::const_ptr & other) const inline virtual
Logical xor comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 168 of file pair_payload.h.
References spkt_throw_printf.
template<typename T1, typename T2> virtual const payload::const_ptr sstmac::pair_payload< T1, T2 >::max (const payload::const_ptr & other) const inline virtual
Greater than comparator, to only be used for the maxloc operation.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 125 of file pair_payload.h.
References sstmac::pair_payload< T1, T2 >::construct(), and ptr_safe_cast.
template<typename T1, typename T2> virtual const payload::const_ptr sstmac::pair_payload< T1, T2 >::min (const payload::const_ptr & other) const inline virtual
Less than comparator, to only be used for the minloc mpi operation.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 106 of file pair_payload.h.
References sstmac::pair_payload< T1, T2 >::construct(), sstmac::pair_payload< T1, T2 >::data(), and ptr_safe_cast.
template<typename T1, typename T2> virtual void sstmac::pair_payload< T1, T2 >::serialize_order (sprockit::spkt_serializer * ser) const inline virtual
Serialize this object into the spkt_serializer, for running in parallel simulation.
Parameters
ser the serializer to use
Definition at line 190 of file pair_payload.h.
References spkt_throw_printf.
template<typename T1, typename T2> virtual std::string sstmac::pair_payload< T1, T2 >::to_string () const inline virtual
Strinfier.
Returns
a std::string description
Reimplemented from sstmac::payload.
Definition at line 199 of file pair_payload.h.
Member Data Documentation
template<typename T1, typename T2> T1 sstmac::pair_payload< T1, T2 >::data1_ mutable private
The data we keep.
Definition at line 31 of file pair_payload.h.
Referenced by sstmac::pair_payload< T1, T2 >::data(), and sstmac::pair_payload< T1, T2 >::data_unconst().
template<typename T1, typename T2> T2 sstmac::pair_payload< T1, T2 >::data2_ mutable private
Definition at line 32 of file pair_payload.h.
Referenced by sstmac::pair_payload< T1, T2 >::data(), and sstmac::pair_payload< T1, T2 >::data_unconst().
template<typename T1, typename T2> size_t sstmac::pair_payload< T1, T2 >::size_ private
Definition at line 33 of file pair_payload.h.
Referenced by sstmac::pairpayloadvector< T1, T2 >::add(), and sstmac::pair_payload< T1, T2 >::byte_length().
The documentation for this class was generated from the following file:
sstmac/common/messages/pair_payload.h