SST/macro: sstmac::hw::packet_flow_nic Class Reference
sstmac::hw::packet_flow_nic Class Reference
Network interface compatible with sending packet trains.
#include <packet_flow_nic.h>
Public Member Functions
packet_flow_nic ()
std::string to_string () const
virtual void init_factory_params (sprockit::sim_parameters *params)
Initialize all member variables from the parameters object.
virtual ~packet_flow_nic () throw ()
void handle (event *ev)
void notify (int vn, message *msg)
virtual void connect (int src_outport, int dst_inport, connection_type_t ty, connectable *mod, config *cfg)
virtual void set_event_parent (event_scheduler *m)
Set the eventmanager for this scheduler.
timestamp injection_latency () const
double injection_bandwidth () const
int initial_credits () const
Public Member Functions inherited from sstmac::hw::nic
virtual ~nic ()
virtual void init_param1 (sprockit::factory_type *interconn)
Initialize the first construction parameter.
node_id addr () const
virtual void set_node (node *nd)
Set an event handler wrapper encapsulation the parent computational unit.
virtual void finalize_init ()
A final initialization function called for the object after all parameters have been read.
void mtl_handle (event *ev)
event_handler * mtl_handler () const
void internode_send (network_message *payload)
Perform the set of operations standard to all NICs.
void intranode_send (network_message *payload)
Perform the set of operations standard to all NICs for transfers within a node.
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Public Member Functions inherited from sstmac::hw::failable
bool failed () const
void fail ()
Public Member Functions inherited from sstmac::event_subscheduler
event_subscheduler ()
timestamp now () const
get the current time
void schedule (timestamp t, event_handler *handler, event *ev)
Add an event to the event queue, where msg will get delivered to handler at time t.
void schedule (timestamp t, event_queue_entry *ev)
void schedule_now (event_queue_entry *ev)
void schedule_now (event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_queue_entry *ev)
void send_self_event (timestamp arrival, event *ev)
void send_delayed_self_event (timestamp delay, event *ev)
void send_now_self_event (event *ev)
void send_self_event_queue (timestamp arrival, event_queue_entry *ev)
void send_delayed_self_event_queue (timestamp delay, event_queue_entry *ev)
void send_now_self_event_queue (event_queue_entry *ev)
event_scheduler * parent () const
Public Member Functions inherited from sstmac::event_handler
virtual ~event_handler ()
event_loc_id event_location () const
virtual bool ipc_handler () const
Whether an event handler is a "fake" handler that represents logical process boundary.
int thread_id () const
virtual void deadlock_check (event *ev)
virtual void deadlock_check ()
Protected Member Functions
virtual void do_send (network_message *payload)
Start the message sending and inject it into the network This performs all model-specific work.
Protected Member Functions inherited from sstmac::hw::nic
nic ()
void send_to_node (network_message *netmsg)
bool negligible_size (int bytes) const
void recv_message (message *msg)
The NIC can either receive an entire message (bypass the byte-transfer layer) or it can receive packets.
Protected Member Functions inherited from sstmac::hw::failable
failable ()
Protected Member Functions inherited from sstmac::event_handler
event_handler ()
void init_loc_id (event_loc_id id)
void init_thread_id (int id)
Protected Attributes
packetizer * packetizer_
timestamp inj_lat_
int injection_credits_
Protected Attributes inherited from sstmac::hw::nic
node_id my_addr_
int negligible_size_
interconnect * interconn_
node * parent_
Protected Attributes inherited from sstmac::hw::failable
bool failed_
Protected Attributes inherited from sstmac::event_subscheduler
event_scheduler * parent_
Additional Inherited Members
Public Types inherited from sstmac::hw::connectable
enum config_type_t {
RedundantConnection =0, WeightedConnection =1, FixedBandwidthConnection =2, FixedConnection =3,
BasicConnection =4
}
enum connection_type_t { output, input }
Static Public Member Functions inherited from sstmac::hw::nic
static void delete_statics ()
Delete all static variables associated with this class.
Static Public Member Functions inherited from sstmac::hw::connectable
static const char * str (connection_type_t ty)
Static Public Attributes inherited from sstmac::event_handler
static const int null_lpid = -1
static const int null_threadid = -1
Static Public Attributes inherited from sstmac::hw::connectable
static const int any_port = -1
Detailed Description
Network interface compatible with sending packet trains.
Definition at line 18 of file packet_flow_nic.h.
Constructor & Destructor Documentation
sstmac::hw::packet_flow_nic::packet_flow_nic ()
virtual sstmac::hw::packet_flow_nic::~packet_flow_nic () throw () virtual
Referenced by to_string().
Member Function Documentation
virtual void sstmac::hw::packet_flow_nic::connect (int src_outport, int dst_inport, connection_type_t ty, connectable * mod, config * cfg) virtual
Implements sstmac::hw::connectable.
Referenced by notify(), and sstmac::hw::packet_flow_netlink::to_string().
virtual void sstmac::hw::packet_flow_nic::do_send (network_message * payload) protected virtual
Start the message sending and inject it into the network This performs all model-specific work.
Parameters
payload The network message to send
Implements sstmac::hw::nic.
Referenced by initial_credits().
void sstmac::hw::packet_flow_nic::handle (event * ev) virtual
Implements sstmac::hw::nic.
Referenced by to_string(), and sstmac::hw::packet_flow_netlink::to_string().
virtual void sstmac::hw::packet_flow_nic::init_factory_params (sprockit::sim_parameters * params) virtual
Initialize all member variables from the parameters object.
Parameters
params
Reimplemented from sstmac::hw::nic.
Referenced by to_string(), and sstmac::hw::packet_flow_netlink::to_string().
int sstmac::hw::packet_flow_nic::initial_credits () const inline
Definition at line 68 of file packet_flow_nic.h.
References do_send(), and injection_credits_.
double sstmac::hw::packet_flow_nic::injection_bandwidth () const virtual
Implements sstmac::hw::nic.
Referenced by injection_latency().
timestamp sstmac::hw::packet_flow_nic::injection_latency () const inline virtual
Returns
The injection latency for moving a packet from the NIC to the first network router (or netlink block, etc)
Implements sstmac::hw::nic.
Definition at line 60 of file packet_flow_nic.h.
References inj_lat_, and injection_bandwidth().
void sstmac::hw::packet_flow_nic::notify (int vn, message * msg) inline virtual
Implements sstmac::hw::packetizer_callback.
Definition at line 44 of file packet_flow_nic.h.
References connect(), sstmac::hw::nic::recv_message(), and set_event_parent().
virtual void sstmac::hw::packet_flow_nic::set_event_parent (event_scheduler * m) virtual
Set the eventmanager for this scheduler.
Unfortunately, this always has to be called after an event_scheduler is constructed.
Parameters
m the simulation eventmanager
Reimplemented from sstmac::hw::nic.
Referenced by notify(), and sstmac::hw::packet_flow_netlink::to_string().
std::string sstmac::hw::packet_flow_nic::to_string () const inline virtual
Implements sstmac::hw::nic.
Definition at line 28 of file packet_flow_nic.h.
References sstmac::hw::nic::addr(), handle(), init_factory_params(), sstmac::event_subscheduler::parent(), sprockit::printf(), and ~packet_flow_nic().
Member Data Documentation
timestamp sstmac::hw::packet_flow_nic::inj_lat_ protected
Definition at line 78 of file packet_flow_nic.h.
Referenced by injection_latency().
int sstmac::hw::packet_flow_nic::injection_credits_ protected
Definition at line 79 of file packet_flow_nic.h.
Referenced by initial_credits().
packetizer* sstmac::hw::packet_flow_nic::packetizer_ protected
Definition at line 77 of file packet_flow_nic.h.
The documentation for this class was generated from the following file:
sstmac/hardware/packet_flow/packet_flow_nic.h