SST/macro: sstmac::SimulationQueue Class Reference
sstmac::SimulationQueue Class Reference
#include <driver.h>
Public Member Functions
SimulationQueue ()
Simulation * fork (sprockit::sim_parameters &params)
bool runJobsOnMaster () const
int maxParallelWorkers () const
void setNextWorker ()
void teardown ()
void init (int argc, char **argv)
void finalize ()
Simulation * fork (sprockit::sim_parameters *params)
Simulation * waitForForked ()
void clear (Simulation *sim)
void run (sprockit::sim_parameters *params, sim_stats &stats)
Simulation * sendScanPoint (char *bufferPtr, int nparams, int totalSize)
void rerun (sprockit::sim_parameters *params, sim_stats &stats)
void busyLoopMPI ()
void runScanPoint (char *buffer, sim_stats &stats)
int workerID () const
Static Public Member Functions
static void publishResults (double *results, int nresults)
Private Attributes
std::list< Simulation * > pending_
parallel_runtime * rt_
sprockit::sim_parameters template_params_
opts template_opts_
int nproc_
int me_
int next_worker_
bool first_run_
Static Private Attributes
static double * results_
static int num_results_
Detailed Description
Definition at line 209 of file driver.h.
Constructor & Destructor Documentation
sstmac::SimulationQueue::SimulationQueue ()
Member Function Documentation
void sstmac::SimulationQueue::busyLoopMPI ()
void sstmac::SimulationQueue::clear (Simulation * sim)
void sstmac::SimulationQueue::finalize ()
Simulation* sstmac::SimulationQueue::fork (sprockit::sim_parameters & params) inline
Definition at line 215 of file driver.h.
Simulation* sstmac::SimulationQueue::fork (sprockit::sim_parameters * params)
void sstmac::SimulationQueue::init (int argc, char ** argv)
int sstmac::SimulationQueue::maxParallelWorkers () const inline
Definition at line 225 of file driver.h.
static void sstmac::SimulationQueue::publishResults (double * results, int nresults) static
void sstmac::SimulationQueue::rerun (sprockit::sim_parameters * params, sim_stats & stats)
void sstmac::SimulationQueue::run (sprockit::sim_parameters * params, sim_stats & stats)
bool sstmac::SimulationQueue::runJobsOnMaster () const inline
Definition at line 220 of file driver.h.
void sstmac::SimulationQueue::runScanPoint (char * buffer, sim_stats & stats)
Simulation* sstmac::SimulationQueue::sendScanPoint (char * bufferPtr, int nparams, int totalSize)
void sstmac::SimulationQueue::setNextWorker () inline
Definition at line 231 of file driver.h.
References sstmac::finalize(), sstmac::init(), and sstmac::run().
void sstmac::SimulationQueue::teardown ()
Simulation* sstmac::SimulationQueue::waitForForked ()
int sstmac::SimulationQueue::workerID () const inline
Definition at line 266 of file driver.h.
Member Data Documentation
bool sstmac::SimulationQueue::first_run_ private
Definition at line 282 of file driver.h.
int sstmac::SimulationQueue::me_ private
Definition at line 280 of file driver.h.
int sstmac::SimulationQueue::next_worker_ private
Definition at line 281 of file driver.h.
int sstmac::SimulationQueue::nproc_ private
Definition at line 279 of file driver.h.
int sstmac::SimulationQueue::num_results_ static private
Definition at line 276 of file driver.h.
std::list<Simulation*> sstmac::SimulationQueue::pending_ private
Definition at line 271 of file driver.h.
double* sstmac::SimulationQueue::results_ static private
Definition at line 275 of file driver.h.
parallel_runtime* sstmac::SimulationQueue::rt_ private
Definition at line 272 of file driver.h.
opts sstmac::SimulationQueue::template_opts_ private
Definition at line 274 of file driver.h.
sprockit::sim_parameters sstmac::SimulationQueue::template_params_ private
Definition at line 273 of file driver.h.
The documentation for this class was generated from the following file:
sstmac/main/driver.h