SST/macro: sstmac::hw::crossbar Class Reference
sstmac::hw::crossbar Class Reference
The crossbar network generates a network which connects all nodes with only two hops: those to and from the crossbar.
#include <crossbar.h>
Public Member Functions
virtual std::string to_string () const
virtual ~crossbar ()
virtual void init_factory_params (sprockit::sim_parameters *params)
int diameter () const
std::string name () const
int ndimensions () const
The number of distinct 'dimensions' in the topology.
int ncoords () const
int num_leaf_switches () const
Structured topologies can be direct (torus) or indirect (fat tree).
virtual void connect_objects (internal_connectable_map &switches)
Given a set of connectables, connect them appropriately.
void configure_vc_routing (std::map< routing::algorithm_t, int > &m) const
void minimal_route_to_switch (switch_id current_sw_addr, switch_id dest_sw_addr, geometry_routable::path &path)
Implementation of topology::minimal_route_to_switch.
void minimal_route_to_coords (const coordinates &src_coords, const coordinates &dest_coords, geometry_routable::path &path)
Workhorse function for implementing minimal_route_to_switch and #minimal_route_to_node.
int minimal_distance (const coordinates &src_coords, const coordinates &dest_coords) const
The function accepts either source or node coordinates.
virtual void productive_path (int dim, const coordinates &src, const coordinates &dst, geometry_routable::path &path) const
virtual int convert_to_port (int dim, int dir) const
switch_id switch_number (const coordinates &coords) const
virtual int num_switches () const
Public Member Functions inherited from sstmac::hw::structured_topology
virtual ~structured_topology ()
virtual void build_internal_connectables (internal_connectable_map &connectables, sprockit::factory< connectable > *factory, partition *part, int my_rank, sprockit::sim_parameters *params, connectable *dummy)
virtual void build_endpoint_connectables (end_point_connectable_map &connectables, sprockit::factory< connectable > *factory, partition *part, int my_rank, sprockit::sim_parameters *params)
virtual void build_interface_connectables (int conc, end_point_connectable_map &connectables, sprockit::factory2< connectable > *nic_factory, partition *part, int my_rank, sprockit::sim_parameters *params, sprockit::factory_type *interconnect)
virtual void minimal_routes_to_coords (const coordinates &src_coords, const coordinates &dest_coords, geometry_routable::path &current_path, geometry_routable::path_set &paths)
virtual int endpoints_per_switch (switch_id addr) const
Given a switch address, return number of nodes connected to it.
virtual int num_nodes () const
virtual int num_endpoints () const
coordinates switch_coords (switch_id swid) const
Compute coordinates (e.g.
virtual coordinates node_coords (node_id nid) const
Compute coordinates (e.g.
coordinates endpoint_coords (node_id nid) const
virtual switch_id endpoint_to_ejection_switch (node_id nodeaddr, int &switch_port) const
virtual switch_id endpoint_to_injection_switch (node_id nodeaddr, int &switch_port) const
virtual int endpoint_to_ejection_port (node_id addr) const
virtual int endpoint_to_injection_port (node_id addr) const
virtual int endpoint_to_switch_port (node_id nid) const
void finalize_init ()
virtual void productive_paths (geometry_routable::path_set &paths, const coordinates &current, const coordinates &dst)
std::string label (node_id nid) const
std::string label (switch_id sid) const
virtual void minimal_routes_to_switch (switch_id current_sw_addr, switch_id dest_sw_addr, geometry_routable::path &current_path, geometry_routable::path_set &paths)
virtual void eject_paths_on_switch (node_id dest_addr, switch_id sw_addr, geometry_routable::path_set &paths) const
virtual int num_hops_to_node (node_id src, node_id dst) const
virtual std::vector< node_id > nodes_connected_to_injection_switch (switch_id swaddr) const
virtual std::vector< node_id > nodes_connected_to_ejection_switch (switch_id swid) const
virtual coordinates neighbor_at_port (switch_id sid, int port) const
virtual node_id node_addr (const coordinates &coords) const
virtual node_id node_addr (const coordinates &sw_coords, int port) const
virtual std::string default_router () const
virtual void send_partners (traffic_pattern::type_t ty, node_id src_node, std::vector< node_id > &partners) const
virtual void recv_partners (traffic_pattern::type_t ty, node_id src_node, std::vector< node_id > &partners) const
Protected Member Functions
virtual void compute_switch_coords (switch_id uid, coordinates &coords) const
Compute coordinates (e.g.
Protected Member Functions inherited from sstmac::hw::structured_topology
void configure_injection_geometry (std::vector< int > &redundancies)
virtual std::vector< node_id > nodes_connected_to_switch (switch_id swaddr) const
structured_topology ()
void partners (bool get_send_partner, traffic_pattern::type_t ty, node_id src, std::vector< node_id > &partner_list) const
virtual void nearest_neighbor_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
virtual void tornado_recv_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
virtual void tornado_send_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
virtual void bit_complement_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
Private Attributes
long size_
Additional Inherited Members
Protected Attributes inherited from sstmac::hw::structured_topology
int eject_geometric_id_
int injection_redundancy_
bool outputgraph_
Detailed Description
The crossbar network generates a network which connects all nodes with only two hops: those to and from the crossbar.
Definition at line 28 of file crossbar.h.
Constructor & Destructor Documentation
virtual sstmac::hw::crossbar::~crossbar () inline virtual
Definition at line 36 of file crossbar.h.
References init_factory_params().
Member Function Documentation
virtual void sstmac::hw::crossbar::compute_switch_coords (switch_id swid, coordinates & coords) const protected virtual
Compute coordinates (e.g.
X,Y,Z for 3D torus)
Parameters
swid The unique index defining a switch location
coords [inout] The unique coordinates of the switch
Implements sstmac::hw::structured_topology.
Referenced by num_switches().
void sstmac::hw::crossbar::configure_vc_routing (std::map< routing::algorithm_t, int > & m) const
Referenced by num_leaf_switches().
virtual void sstmac::hw::crossbar::connect_objects (internal_connectable_map & objects) virtual
Given a set of connectables, connect them appropriately.
Parameters
objects The set of objects to connect
cloner If in parallel mode, not all objects may exist. The factory creates missing objects.
Exceptions
value_error If invalid switchid is passed to cloner
Implements sstmac::hw::structured_topology.
Referenced by num_leaf_switches().
virtual int sstmac::hw::crossbar::convert_to_port (int dim, int dir) const virtual
Referenced by num_leaf_switches().
int sstmac::hw::crossbar::diameter () const inline virtual
Implements sstmac::hw::structured_topology.
Definition at line 42 of file crossbar.h.
References name().
virtual void sstmac::hw::crossbar::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::hw::structured_topology.
Referenced by ~crossbar().
int sstmac::hw::crossbar::minimal_distance (const coordinates & src_coords, const coordinates & dest_coords) const virtual
The function accepts either source or node coordinates.
This gives the minimal distance counting the number of hops between switches. If node coordinates are given, the last coordinate is just ignored.
Parameters
src_coords. The source coordinates. This can be either switch or node coordinates.
dest_coords. The destination coordinates. This can be either switch or node coordinates.
Returns
The number of hops to final destination
Implements sstmac::hw::structured_topology.
Referenced by num_leaf_switches().
void sstmac::hw::crossbar::minimal_route_to_coords (const coordinates & src_coords, const coordinates & dest_coords, geometry_routable::path & path) virtual
Workhorse function for implementing minimal_route_to_switch and #minimal_route_to_node.
Given source/dest coordinates, find the minimal path.
Parameters
current_sw_addr The addr of the current switch
dest_sw_addr The addr of the destination switch
path [inout] A complete path descriptor to the destination switch
Implements sstmac::hw::structured_topology.
Referenced by num_leaf_switches().
void sstmac::hw::crossbar::minimal_route_to_switch (switch_id current_sw_addr, switch_id dest_sw_addr, geometry_routable::path & path) virtual
Implementation of topology::minimal_route_to_switch.
For structured topologies, this basically just computes the coordinates of source, dest switch and calls minimal_route_to_coords.
Parameters
current_sw_addr The addr of the current switch
dest_sw_addr The addr of the destination switch
path [inout] A complete path descriptor to the destination switch
Reimplemented from sstmac::hw::structured_topology.
Referenced by num_leaf_switches().
std::string sstmac::hw::crossbar::name () const
Referenced by diameter().
int sstmac::hw::crossbar::ncoords () const inline
Definition at line 55 of file crossbar.h.
int sstmac::hw::crossbar::ndimensions () const inline virtual
The number of distinct 'dimensions' in the topology.
This can correspond directly to standard X,Y,Z dimensions or the the number of levels in a fat tree. The keyword topology_redundant vector should have this many entries.
Implements sstmac::hw::structured_topology.
Definition at line 50 of file crossbar.h.
int sstmac::hw::crossbar::num_leaf_switches () const inline virtual
Structured topologies can be direct (torus) or indirect (fat tree).
We therefore need to distinguish the total number of switches and the number of leaf switches - i.e. those directly connected to nodes. For direct topologies, num_switches and num_leaf_switches are the same. For indirect, num_leaf_switches < num_switches.
Returns
The number of leaf switches directly connected to compute nodes
Implements sstmac::hw::structured_topology.
Definition at line 60 of file crossbar.h.
References configure_vc_routing(), connect_objects(), convert_to_port(), minimal_distance(), minimal_route_to_coords(), minimal_route_to_switch(), productive_path(), and size_.
virtual int sstmac::hw::crossbar::num_switches () const inline virtual
Definition at line 104 of file crossbar.h.
References compute_switch_coords(), and size_.
virtual void sstmac::hw::crossbar::productive_path (int dim, const coordinates & src, const coordinates & dst, geometry_routable::path & path) const virtual
Parameters
dim The dimension you want to move in. You might need to traverse other dimensions FIRST before you make progress on this dimension.
src The coordinates of the source switch
dst The coordinates of the dest switch
path [inout] The path configuration for making progress on dim
Implements sstmac::hw::structured_topology.
Referenced by num_leaf_switches().
switch_id sstmac::hw::crossbar::switch_number (const coordinates & coords) const inline virtual
Implements sstmac::hw::structured_topology.
Definition at line 99 of file crossbar.h.
virtual std::string sstmac::hw::crossbar::to_string () const inline virtual
Definition at line 32 of file crossbar.h.
Member Data Documentation
long sstmac::hw::crossbar::size_ private
Definition at line 113 of file crossbar.h.
Referenced by num_leaf_switches(), and num_switches().
The documentation for this class was generated from the following file:
sstmac/hardware/topology/crossbar.h