SST/macro: sstmac::hw::fat_tree_dmodk_router Class Reference
sstmac::hw::fat_tree_dmodk_router Class Reference
The fat_tree_dmodk_router class Router encapsulating the special routing computations that must occur on a fat tree topology.
#include <fat_tree_dmodk_router.h>
Public Member Functions
virtual ~fat_tree_dmodk_router ()
fat_tree_dmodk_router ()
virtual void productive_paths_to_switch (switch_id dst, structured_routable::path_set &paths)
virtual std::string to_string () const
Public Member Functions inherited from sstmac::hw::fat_tree_router
virtual ~fat_tree_router ()
fat_tree_router ()
virtual void finalize_init ()
void init_factory_params (sprockit::sim_parameters *params)
void set_topology (topology *top)
set_topology Set the topology to be used for route computations.
virtual void route (packet *pkt)
Public Member Functions inherited from sstmac::hw::structured_router
virtual ~structured_router ()
virtual void set_switch (network_switch *sw)
set_switch Set the parent switch using this router to perform route computations
void minimal_route_to_node (node_id node_addr, structured_routable::path &path)
void minimal_routes_to_node (node_id node_addr, structured_routable::path &current_path, structured_routable::path_set &paths)
minimal_routes_to_node Special version of routing function that computes all possible minimal paths.
Protected Member Functions
void minimal_route_to_switch (switch_id sw_addr, structured_routable::path &path)
Protected Member Functions inherited from sstmac::hw::fat_tree_router
void build_rng ()
build_rng Build the random number generator for selecting paths
int choose_up_minimal_path ()
choose_up_path
int number_minimal_paths (packet *pkt) const
number_paths
Protected Member Functions inherited from sstmac::hw::structured_router
structured_router (routing::algorithm_t algo)
Additional Inherited Members
Protected Attributes inherited from sstmac::hw::fat_tree_router
int l_
int k_
int myL_
int logicalid_
std::map< long, int > inports_
RNG::Combo * rng_
long num_leaf_switches_reachable_
long num_leaf_switches_per_path_
long level_relative_id_
long min_reachable_leaf_id_
long max_reachable_leaf_id_
long seed_
int numpicked_
int pickstart_
int numpicktop_
int pickstarttop_
Protected Attributes inherited from sstmac::hw::structured_router
structured_topology * regtop_
Detailed Description
The fat_tree_dmodk_router class Router encapsulating the special routing computations that must occur on a fat tree topology.
Definition at line 25 of file fat_tree_dmodk_router.h.
Constructor & Destructor Documentation
virtual sstmac::hw::fat_tree_dmodk_router::~fat_tree_dmodk_router () virtual
sstmac::hw::fat_tree_dmodk_router::fat_tree_dmodk_router () inline
Definition at line 31 of file fat_tree_dmodk_router.h.
References productive_paths_to_switch().
Member Function Documentation
void sstmac::hw::fat_tree_dmodk_router::minimal_route_to_switch (switch_id sw_addr, structured_routable::path & path) protected virtual
Reimplemented from sstmac::hw::fat_tree_router.
Referenced by to_string().
virtual void sstmac::hw::fat_tree_dmodk_router::productive_paths_to_switch (switch_id dst, structured_routable::path_set & paths) virtual
Reimplemented from sstmac::hw::fat_tree_router.
Referenced by fat_tree_dmodk_router().
virtual std::string sstmac::hw::fat_tree_dmodk_router::to_string () const inline virtual
Reimplemented from sstmac::hw::fat_tree_router.
Definition at line 42 of file fat_tree_dmodk_router.h.
References minimal_route_to_switch().
The documentation for this class was generated from the following file:
sstmac/hardware/router/fat_tree_dmodk_router.h