SST/macro: sumi::sumi_transport Class Reference
sumi::sumi_transport Class Reference
#include <sumi_transport.h>
Public Member Functions
sumi_transport ()
virtual void init ()
virtual void finalize ()
virtual void init_factory_params (sprockit::sim_parameters *params)
void finalize_init ()
virtual ~sumi_transport ()
virtual sumi::message_ptr handle (sstmac::transport_message *msg)
collective_done_message::ptr collective_block (sumi::collective::type_t ty, int tag)
Block on a collective of a particular type and tag until that collective is complete.
void cq_notify ()
double wall_time () const
message::ptr block_until_message ()
message::ptr block_until_message (double timeout)
void ping_timeout (pinger *pnger)
void incoming_event (sstmac::event *ev)
Public Member Functions inherited from sstmac::sumi_api
sumi_api ()
virtual ~sumi_api ()
virtual void init_param1 (const sstmac::sw::software_id &sid)
virtual void init_os (sstmac::sw::operating_system *os)
sumi::message_ptr poll_until_notification ()
sumi::message_ptr poll_until_notification (timestamp timeout)
void incoming_message (transport_message *msg)
void transport_send (long byte_length, const sumi::message_ptr &msg, int ty, int dst, bool needs_ack, void *buffer=0)
bool blocked () const
Public Member Functions inherited from sstmac::sw::api
api (const key::category &ty)
api ()
virtual ~api ()
timestamp now () const
void schedule (timestamp t, event_queue_entry *ev)
void schedule_delay (timestamp t, event_queue_entry *ev)
virtual void start_api_call ()
virtual void end_api_call ()
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Public Member Functions inherited from sstmac::sw::library
virtual void unregister_all_libs ()
virtual std::string to_string () const
virtual std::string lib_name () const
virtual void consume_params (sprockit::sim_parameters *params)
operating_system * os () const
virtual ~library ()
Public Member Functions inherited from sstmac::sw::process_manager
virtual ~process_manager ()
int get_partner (node_id addr) const
node_id my_addr () const
void kill_node ()
void kill_process ()
Protected Member Functions
void do_smsg_send (int dst, const message::ptr &msg)
void do_rdma_put (int dst, const message::ptr &msg)
void do_rdma_get (int src, const message::ptr &msg)
void do_nvram_get (int src, const message::ptr &msg)
void do_send_terminate (int dst)
void do_send_ping_request (int dst)
void delayed_transport_handle (const message::ptr &msg)
void schedule_ping_timeout (pinger *pnger, double to)
void schedule_next_heartbeat ()
void go_die ()
void go_revive ()
Protected Member Functions inherited from sstmac::sw::library
library ()
void register_lib (library *lib)
This function is provided so that libraries can instantiate, register, and use other libraries.
virtual bool supported () const
This is usually convenient to define to check if the node was set up correctly to support what this library wants to do.
Additional Inherited Members
Static Public Member Functions inherited from sstmac::sw::library
static library * construct_lib (const std::string &libname)
static library * construct_lib (const std::string &libname, const software_id &sid)
static void register_builder (const std::string &libname, library_builder *builder)
Static Protected Member Functions inherited from sstmac::sw::library
static library_builder * builder (const std::string &name)
Protected Attributes inherited from sstmac::sumi_api
event_loc_id loc_
int rank_
int nproc_
Protected Attributes inherited from sstmac::sw::api
Timer * timer_
long startcount_
long endcount_
lib_compute_time * compute_
software_id sid_
Protected Attributes inherited from sstmac::sw::library
operating_system * os_
std::string libname_
key::category key_cat_
Static Protected Attributes inherited from sstmac::sw::api
static bool hostcompute_
Detailed Description
Definition at line 15 of file sumi_transport.h.
Constructor & Destructor Documentation
sumi::sumi_transport::sumi_transport ()
virtual sumi::sumi_transport::~sumi_transport () inline virtual
Definition at line 34 of file sumi_transport.h.
References block_until_message(), collective_block(), cq_notify(), handle(), ping_timeout(), and wall_time().
Member Function Documentation
message::ptr sumi::sumi_transport::block_until_message ()
Referenced by ~sumi_transport().
message::ptr sumi::sumi_transport::block_until_message (double timeout)
collective_done_message::ptr sumi::sumi_transport::collective_block (sumi::collective::type_t ty, int tag)
Block on a collective of a particular type and tag until that collective is complete.
Parameters
ty
tag
Returns
Referenced by ~sumi_transport().
void sumi::sumi_transport::cq_notify ()
Referenced by ~sumi_transport().
void sumi::sumi_transport::delayed_transport_handle (const message::ptr & msg) protected
Referenced by incoming_event().
void sumi::sumi_transport::do_nvram_get (int src, const message::ptr & msg) protected
Referenced by incoming_event().
void sumi::sumi_transport::do_rdma_get (int src, const message::ptr & msg) protected
Referenced by incoming_event().
void sumi::sumi_transport::do_rdma_put (int dst, const message::ptr & msg) protected
Referenced by incoming_event().
void sumi::sumi_transport::do_send_ping_request (int dst) protected
Referenced by incoming_event().
void sumi::sumi_transport::do_send_terminate (int dst) protected
Referenced by incoming_event().
void sumi::sumi_transport::do_smsg_send (int dst, const message::ptr & msg) protected
Referenced by incoming_event().
virtual void sumi::sumi_transport::finalize () virtual
Reimplemented from sstmac::sumi_api.
void sumi::sumi_transport::finalize_init () virtual
Reimplemented from sprockit::factory_type.
void sumi::sumi_transport::go_die () protected
Referenced by incoming_event().
void sumi::sumi_transport::go_revive () protected
Referenced by incoming_event().
virtual sumi::message_ptr sumi::sumi_transport::handle (sstmac::transport_message * msg) virtual
Implements sstmac::sumi_api.
Referenced by ~sumi_transport().
void sumi::sumi_transport::incoming_event (sstmac::event * ev) inline virtual
Implements sstmac::sw::library.
Definition at line 65 of file sumi_transport.h.
References delayed_transport_handle(), do_nvram_get(), do_rdma_get(), do_rdma_put(), do_send_ping_request(), do_send_terminate(), do_smsg_send(), go_die(), go_revive(), schedule_next_heartbeat(), and schedule_ping_timeout().
virtual void sumi::sumi_transport::init () virtual
Reimplemented from sstmac::sumi_api.
virtual void sumi::sumi_transport::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::sumi_api.
void sumi::sumi_transport::ping_timeout (pinger * pnger)
Referenced by ~sumi_transport().
void sumi::sumi_transport::schedule_next_heartbeat () protected
Referenced by incoming_event().
void sumi::sumi_transport::schedule_ping_timeout (pinger * pnger, double to) protected
Referenced by incoming_event().
double sumi::sumi_transport::wall_time () const
Referenced by ~sumi_transport().
The documentation for this class was generated from the following file:
sstmac/libraries/sumi/sumi_transport.h