SST/macro: sstmac::native::skeleton_app_manager Class Reference
sstmac::native::skeleton_app_manager Class Reference
#include <skeleton_app_manager.h>
Public Member Functions
void init_factory_params (sprockit::sim_parameters *params)
std::string to_string () const
Public Member Functions inherited from sstmac::native::indexing_app_manager
virtual ~indexing_app_manager ()
virtual int nproc () const
node_id node_assignment (int rank) const
const std::list< int > & rank_assignment (node_id nid) const
sw::launch_info * launch_info () const
void allocate_and_index_jobs ()
void set_interconnect (hw::interconnect *interconn)
Public Member Functions inherited from sstmac::sw::app_manager
virtual ~app_manager ()
virtual void init_param1 (sw::app_id aid)
virtual void init_param2 (parallel_runtime *rt)
hw::topology * topol () const
hw::interconnect * interconn () const
hw::node * node_at (node_id nid) const
void add_hostname (sw::task_id tid, const std::string &name, node_id addr)
void setenv (const std::string &name, const std::string &value)
std::string getenv (const std::string &name) const
std::string hostname (sw::task_id tid) const
node_id node_address (const std::string &hostname) const
node_id node_for_task (sw::task_id tid) const
void set_node_address (sw::task_id tid, node_id n)
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Static Public Member Functions
static void parse_launch_cmd (sprockit::sim_parameters *params, int &nproc, int &procs_per_node, std::vector< int > &affinities)
Static Public Member Functions inherited from sstmac::sw::app_manager
static app_manager * static_app_manager (int aid, sprockit::sim_parameters *params)
Protected Member Functions
void parse_launch_cmd (sprockit::sim_parameters *params)
Protected Member Functions inherited from sstmac::native::indexing_app_manager
void init_launch_info ()
Protected Member Functions inherited from sstmac::sw::app_manager
app_manager ()
Static Protected Member Functions
static void parse_aprun (const std::string &cmd, int &nproc, int &nproc_per_node, std::vector< int > &core_affinities)
Protected Attributes
int procs_per_node_
Protected Attributes inherited from sstmac::native::indexing_app_manager
sw::allocation_strategy * allocator_
sw::index_strategy * indexer_
std::vector< node_id > rank_to_node_indexing_
std::vector< std::list< int > > node_to_rank_indexing_
sw::launch_info * linfo_
int nproc_
Protected Attributes inherited from sstmac::sw::app_manager
parallel_runtime * rt_
hw::topology * top_
hw::interconnect * interconn_
sw::app * app_template_
sw::app_id aid_
std::string appname_
std::vector< int > core_affinities_
task_to_node_map nodeids_
task_to_hostname_map hostnames_
hostname_to_addr_map inet_addrs_
shell_var_map shell_env_
Private Member Functions
virtual void do_allocate_and_index_jobs ()
Additional Inherited Members
Protected Types inherited from sstmac::sw::app_manager
typedef spkt_unordered_map< sw::task_id, node_id > task_to_node_map
typedef spkt_unordered_map< sw::task_id, std::string > task_to_hostname_map
typedef spkt_unordered_map< std::string, std::string > shell_var_map
typedef spkt_unordered_map< std::string, node_id > hostname_to_addr_map
Detailed Description
Definition at line 10 of file skeleton_app_manager.h.
Member Function Documentation
virtual void sstmac::native::skeleton_app_manager::do_allocate_and_index_jobs () private virtual
Implements sstmac::native::indexing_app_manager.
void sstmac::native::skeleton_app_manager::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::native::indexing_app_manager.
static void sstmac::native::skeleton_app_manager::parse_aprun (const std::string & cmd, int & nproc, int & nproc_per_node, std::vector< int > & core_affinities) static protected
static void sstmac::native::skeleton_app_manager::parse_launch_cmd (sprockit::sim_parameters * params, int & nproc, int & procs_per_node, std::vector< int > & affinities) static
Referenced by to_string().
void sstmac::native::skeleton_app_manager::parse_launch_cmd (sprockit::sim_parameters * params) protected
std::string sstmac::native::skeleton_app_manager::to_string () const inline
Definition at line 19 of file skeleton_app_manager.h.
References sstmac::native::indexing_app_manager::nproc(), and parse_launch_cmd().
Member Data Documentation
int sstmac::native::skeleton_app_manager::procs_per_node_ protected
Definition at line 31 of file skeleton_app_manager.h.
The documentation for this class was generated from the following file:
sstmac/backends/native/skeleton_app_manager.h