SST/macro: sstmac::hw::packet_flow_sender Class Reference
sstmac::hw::packet_flow_sender Class Reference abstract
#include <packet_flow_sender.h>
Public Member Functions
virtual ~packet_flow_sender ()
void set_acker (event_handler *acker)
virtual void set_input (int my_inport, int dst_outport, event_handler *input)=0
virtual void set_output (int my_outport, int dst_inport, event_handler *output)=0
virtual void init_credits (int port, int num_credits)=0
virtual int num_initial_credits () const =0
void handle_payload (packet_flow_payload *msg)
void set_event_location (node_id nid)
void set_event_location (switch_id sid)
void set_congestion_spyplot (stat_spyplot *plot)
bool accumulate_delay () const
void set_accumulate_delay (bool flag)
std::string to_string () const
virtual std::string packet_flow_name () const =0
void set_update_vc (bool flag)
Public Member Functions inherited from sstmac::hw::packet_flow_handler
packet_flow_handler ()
virtual ~packet_flow_handler ()
virtual void handle (event *ev)
virtual void handle_credit (packet_flow_credit *msg)=0
int thread_id () const
Public Member Functions inherited from sstmac::event_subscheduler
event_subscheduler ()
timestamp now () const
get the current time
void schedule (timestamp t, event_handler *handler, event *ev)
Add an event to the event queue, where msg will get delivered to handler at time t.
void schedule (timestamp t, event_queue_entry *ev)
void schedule_now (event_queue_entry *ev)
void schedule_now (event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_queue_entry *ev)
void send_self_event (timestamp arrival, event *ev)
void send_delayed_self_event (timestamp delay, event *ev)
void send_now_self_event (event *ev)
void send_self_event_queue (timestamp arrival, event_queue_entry *ev)
void send_delayed_self_event_queue (timestamp delay, event_queue_entry *ev)
void send_now_self_event_queue (event_queue_entry *ev)
virtual void set_event_parent (event_scheduler *m)
Set the eventmanager for this scheduler.
event_scheduler * parent () const
Public Member Functions inherited from sstmac::event_handler
virtual ~event_handler ()
event_loc_id event_location () const
virtual bool ipc_handler () const
Whether an event handler is a "fake" handler that represents logical process boundary.
int thread_id () const
virtual void deadlock_check (event *ev)
virtual void deadlock_check ()
Protected Member Functions
packet_flow_sender (const timestamp &send_lat, const timestamp &credit_lat)
packet_flow_sender ()
void send_credit (const packet_flow_input &src, packet_flow_payload *payload, timestamp packet_tail_leaves)
void send (packet_flow_bandwidth_arbitrator *arb, packet_flow_payload *msg, const packet_flow_input &src, const packet_flow_output &dest)
virtual void do_handle_payload (packet_flow_payload *msg)=0
Protected Member Functions inherited from sstmac::event_handler
event_handler ()
void init_loc_id (event_loc_id id)
void init_thread_id (int id)
Protected Attributes
stat_spyplot * congestion_spyplot_
event_handler * acker_
timestamp send_lat_
timestamp credit_lat_
bool acc_delay_
bool update_vc_
Protected Attributes inherited from sstmac::event_subscheduler
event_scheduler * parent_
Additional Inherited Members
Static Public Attributes inherited from sstmac::event_handler
static const int null_lpid = -1
static const int null_threadid = -1
Detailed Description
Definition at line 16 of file packet_flow_sender.h.
Constructor & Destructor Documentation
virtual sstmac::hw::packet_flow_sender::~packet_flow_sender () inline virtual
Definition at line 20 of file packet_flow_sender.h.
sstmac::hw::packet_flow_sender::packet_flow_sender (const timestamp & send_lat, const timestamp & credit_lat) protected
sstmac::hw::packet_flow_sender::packet_flow_sender () protected
Referenced by set_update_vc().
Member Function Documentation
bool sstmac::hw::packet_flow_sender::accumulate_delay () const inline
Definition at line 63 of file packet_flow_sender.h.
References acc_delay_.
virtual void sstmac::hw::packet_flow_sender::do_handle_payload (packet_flow_payload * msg) protected pure virtual
Implemented in sstmac::hw::packet_flow_injection_buffer, sstmac::hw::packet_flow_crossbar, sstmac::hw::packet_flow_eject_buffer, sstmac::hw::packet_flow_network_buffer, and sstmac::hw::packet_flow_NtoM_queue.
Referenced by handle_payload(), sstmac::hw::packet_flow_eject_buffer::packet_flow_eject_buffer(), set_update_vc(), sstmac::hw::packet_flow_injection_buffer::space_to_send(), and sstmac::hw::packet_flow_network_buffer::~packet_flow_network_buffer().
void sstmac::hw::packet_flow_sender::handle_payload (packet_flow_payload * msg) inline virtual
Implements sstmac::hw::packet_flow_handler.
Definition at line 42 of file packet_flow_sender.h.
References do_handle_payload(), and sstmac::event_subscheduler::now().
virtual void sstmac::hw::packet_flow_sender::init_credits (int port, int num_credits) pure virtual
Implemented in sstmac::hw::packet_flow_injection_buffer, sstmac::hw::packet_flow_eject_buffer, sstmac::hw::packet_flow_network_buffer, and sstmac::hw::packet_flow_NtoM_queue.
Referenced by sstmac::hw::packet_flow_eject_buffer::packet_flow_name(), set_acker(), and sstmac::hw::packet_flow_network_buffer::~packet_flow_network_buffer().
virtual int sstmac::hw::packet_flow_sender::num_initial_credits () const pure virtual
Implemented in sstmac::hw::packet_flow_infinite_buffer, sstmac::hw::packet_flow_finite_buffer, and sstmac::hw::packet_flow_NtoM_queue.
Referenced by set_acker(), and sstmac::hw::packet_flow_infinite_buffer::set_input().
virtual std::string sstmac::hw::packet_flow_sender::packet_flow_name () const pure virtual
Implemented in sstmac::hw::packet_flow_crossbar, sstmac::hw::packet_flow_injection_buffer, sstmac::hw::packet_flow_muxer, sstmac::hw::packet_flow_eject_buffer, sstmac::hw::packet_flow_demuxer, and sstmac::hw::packet_flow_network_buffer.
Referenced by set_accumulate_delay().
void sstmac::hw::packet_flow_sender::send (packet_flow_bandwidth_arbitrator * arb, packet_flow_payload * msg, const packet_flow_input & src, const packet_flow_output & dest) protected
Referenced by set_update_vc().
void sstmac::hw::packet_flow_sender::send_credit (const packet_flow_input & src, packet_flow_payload * payload, timestamp packet_tail_leaves) protected
Referenced by set_update_vc().
void sstmac::hw::packet_flow_sender::set_accumulate_delay (bool flag) inline
Definition at line 68 of file packet_flow_sender.h.
References acc_delay_, packet_flow_name(), and to_string().
void sstmac::hw::packet_flow_sender::set_acker (event_handler * acker) inline
Definition at line 23 of file packet_flow_sender.h.
References acker_, init_credits(), num_initial_credits(), set_input(), and set_output().
void sstmac::hw::packet_flow_sender::set_congestion_spyplot (stat_spyplot * plot) inline
Definition at line 58 of file packet_flow_sender.h.
References congestion_spyplot_.
void sstmac::hw::packet_flow_sender::set_event_location (node_id nid) inline
Definition at line 48 of file packet_flow_sender.h.
References sstmac::event_handler::init_loc_id().
void sstmac::hw::packet_flow_sender::set_event_location (switch_id sid) inline
Definition at line 53 of file packet_flow_sender.h.
References sstmac::event_handler::init_loc_id().
virtual void sstmac::hw::packet_flow_sender::set_input (int my_inport, int dst_outport, event_handler * input) pure virtual
Implemented in sstmac::hw::packet_flow_infinite_buffer, sstmac::hw::packet_flow_finite_buffer, and sstmac::hw::packet_flow_NtoM_queue.
Referenced by set_acker(), and sstmac::hw::packet_flow_finite_buffer::~packet_flow_finite_buffer().
virtual void sstmac::hw::packet_flow_sender::set_output (int my_outport, int dst_inport, event_handler * output) pure virtual
Implemented in sstmac::hw::packet_flow_NtoM_queue, and sstmac::hw::packet_flow_buffer.
Referenced by set_acker().
void sstmac::hw::packet_flow_sender::set_update_vc (bool flag) inline
Definition at line 79 of file packet_flow_sender.h.
References do_handle_payload(), packet_flow_sender(), send(), send_credit(), and update_vc_.
std::string sstmac::hw::packet_flow_sender::to_string () const virtual
Reimplemented from sstmac::hw::packet_flow_handler.
Referenced by set_accumulate_delay().
Member Data Documentation
bool sstmac::hw::packet_flow_sender::acc_delay_ protected
Definition at line 113 of file packet_flow_sender.h.
Referenced by accumulate_delay(), and set_accumulate_delay().
event_handler* sstmac::hw::packet_flow_sender::acker_ protected
Definition at line 107 of file packet_flow_sender.h.
Referenced by set_acker().
stat_spyplot* sstmac::hw::packet_flow_sender::congestion_spyplot_ protected
Definition at line 105 of file packet_flow_sender.h.
Referenced by set_congestion_spyplot().
timestamp sstmac::hw::packet_flow_sender::credit_lat_ protected
Definition at line 111 of file packet_flow_sender.h.
timestamp sstmac::hw::packet_flow_sender::send_lat_ protected
Definition at line 109 of file packet_flow_sender.h.
bool sstmac::hw::packet_flow_sender::update_vc_ protected
Definition at line 115 of file packet_flow_sender.h.
Referenced by set_update_vc().
The documentation for this class was generated from the following file:
sstmac/hardware/packet_flow/packet_flow_sender.h