SST/macro: sstmac::native::manager Class Reference
sstmac::native::manager Class Reference abstract
The owner of a discrete-event network simulation.
#include <manager.h>
Public Member Functions
manager ()
virtual std::string to_string () const
virtual ~manager () throw ()
Goodbye.
void init_factory_params (sprockit::sim_parameters *params)
virtual timestamp run (timestamp until)=0
virtual void stop ()=0
virtual void finish ()=0
sstmac::hw::interconnect * interconn () const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Static Public Member Functions
static int compute_max_nproc (sprockit::sim_parameters *params)
Protected Member Functions
void build_app (int appnum, sprockit::sim_parameters *params)
void build_apps (sprockit::sim_parameters *params)
Static Protected Member Functions
static int compute_max_nproc_for_app (sprockit::sim_parameters *app_params)
Protected Attributes
sstmac::sw::app_id next_ppid_
Next parallel process id.
std::map< int, sw::app_manager * > app_managers_
std::map< int, timestamp > app_starts_
sstmac::hw::interconnect * interconnect_
parallel_runtime * rt_
Detailed Description
The owner of a discrete-event network simulation.
All time progression is handled by this object and messages between nodes are managed here as well.
Definition at line 35 of file manager.h.
Constructor & Destructor Documentation
sstmac::native::manager::manager ()
virtual sstmac::native::manager::~manager () throw () virtual
Goodbye.
Referenced by to_string().
Member Function Documentation
void sstmac::native::manager::build_app (int appnum, sprockit::sim_parameters * params) protected
Referenced by interconn().
void sstmac::native::manager::build_apps (sprockit::sim_parameters * params) protected
Referenced by interconn().
static int sstmac::native::manager::compute_max_nproc (sprockit::sim_parameters * params) static
Referenced by interconn().
static int sstmac::native::manager::compute_max_nproc_for_app (sprockit::sim_parameters * app_params) static protected
Referenced by interconn().
virtual void sstmac::native::manager::finish () pure virtual
Implemented in sstmac::native::macro_manager.
Referenced by to_string().
void sstmac::native::manager::init_factory_params (sprockit::sim_parameters * params)
Referenced by to_string().
sstmac::hw::interconnect* sstmac::native::manager::interconn () const inline
Definition at line 59 of file manager.h.
References build_app(), build_apps(), compute_max_nproc(), compute_max_nproc_for_app(), and interconnect_.
virtual timestamp sstmac::native::manager::run (timestamp until) pure virtual
Implemented in sstmac::native::macro_manager.
Referenced by to_string().
virtual void sstmac::native::manager::stop () pure virtual
Implemented in sstmac::native::macro_manager.
Referenced by to_string().
virtual std::string sstmac::native::manager::to_string () const inline virtual
Definition at line 41 of file manager.h.
References finish(), init_factory_params(), run(), stop(), and ~manager().
Member Data Documentation
std::map<int, sw::app_manager*> sstmac::native::manager::app_managers_ protected
Definition at line 80 of file manager.h.
std::map<int, timestamp> sstmac::native::manager::app_starts_ protected
Definition at line 81 of file manager.h.
sstmac::hw::interconnect* sstmac::native::manager::interconnect_ protected
Definition at line 83 of file manager.h.
Referenced by interconn().
sstmac::sw::app_id sstmac::native::manager::next_ppid_ protected
Next parallel process id.
Definition at line 78 of file manager.h.
parallel_runtime* sstmac::native::manager::rt_ protected
Definition at line 84 of file manager.h.
The documentation for this class was generated from the following file:
sstmac/backends/native/manager.h