SST/macro: sstmac::hw::ugal_router Class Reference
sstmac::hw::ugal_router Class Reference
#include <ugal_routing.h>
Public Member Functions
virtual void init_factory_params (sprockit::sim_parameters *params)
std::string to_string () const
void route (packet *pkt)
virtual void finalize_init ()
Public Member Functions inherited from sstmac::hw::valiant_router
virtual ~valiant_router ()
virtual void route (packet *pkt, geometry_routable::path_set &paths)
int num_stages () const
Public Member Functions inherited from sstmac::hw::minimal_router
virtual ~minimal_router ()
std::string to_string () const
Public Member Functions inherited from sstmac::hw::structured_router
virtual void set_topology (topology *top)
virtual void set_switch (network_switch *sw)
void minimal_route_to_node (node_id node_addr, geometry_routable::path &path)
void minimal_routes_to_node (node_id node_addr, geometry_routable::path &current_path, geometry_routable::path_set &path)
virtual void minimal_route_to_switch (switch_id sw_addr, geometry_routable::path &path)
virtual void productive_paths_to_switch (switch_id dst, geometry_routable::path_set &paths)
Protected Member Functions
next_action_t initial_step (geometry_routable *rtbl, packet *pkt)
Different for pure valiant and UGAL.
virtual int first_stage_vc (int topology_vc)
The topology object specifies a virtual based purely on geometry.
virtual int second_stage_vc (int topology_vc)
The topology object specifies a virtual based purely on geometry.
int zero_stage_vc (int topology_vc)
In adition to the valiant stages, ugal has a minimal stage.
int num_stages () const
Protected Member Functions inherited from sstmac::hw::valiant_router
next_action_t intermediate_step (geometry_routable *rtbl, packet *pkt)
next_action_t next_routing_stage (packet *pkt)
void configure_intermediate_path (geometry_routable::path &path)
void configure_final_path (geometry_routable::path &path)
void route_valiant (packet *pkt)
Protected Attributes
int val_threshold_
int val_preference_factor_
Protected Attributes inherited from sstmac::hw::structured_router
structured_topology * regtop_
Additional Inherited Members
Protected Types inherited from sstmac::hw::valiant_router
enum next_action_t { minimal, intermediate_switch, final_node }
Detailed Description
Definition at line 9 of file ugal_routing.h.
Member Function Documentation
virtual void sstmac::hw::ugal_router::finalize_init () virtual
Reimplemented from sstmac::hw::valiant_router.
Referenced by to_string().
virtual int sstmac::hw::ugal_router::first_stage_vc (int topology_vc) inline protected virtual
The topology object specifies a virtual based purely on geometry.
However, the final virtual channel on both geometry and routing algorithm. In this case, we need a separate set of virtual channels depending on whether we are in the first stage, routing to the intermediate switch, or the second stage, routing to the final switch.
Parameters
topology_vc The geometry-specific virtual channel
Returns
The first stage virtual channel
Reimplemented from sstmac::hw::valiant_router.
Definition at line 43 of file ugal_routing.h.
virtual void sstmac::hw::ugal_router::init_factory_params (sprockit::sim_parameters * params) virtual
next_action_t sstmac::hw::ugal_router::initial_step (geometry_routable * rtbl, packet * pkt) protected virtual
Different for pure valiant and UGAL.
Reimplemented from sstmac::hw::valiant_router.
Referenced by to_string().
int sstmac::hw::ugal_router::num_stages () const inline protected
Definition at line 74 of file ugal_routing.h.
void sstmac::hw::ugal_router::route (packet * pkt) virtual
Reimplemented from sstmac::hw::valiant_router.
Referenced by to_string().
virtual int sstmac::hw::ugal_router::second_stage_vc (int topology_vc) inline protected virtual
The topology object specifies a virtual based purely on geometry.
However, the final virtual channel on both geometry and routing algorithm. In this case, we need a separate set of virtual channels depending on whether we are in the first stage, routing to the intermediate switch, or the second stage, routing to the final switch.
Parameters
topology_vc The geometry-specific virtual channel
Returns
The second stage virtual channel
Reimplemented from sstmac::hw::valiant_router.
Definition at line 58 of file ugal_routing.h.
std::string sstmac::hw::ugal_router::to_string () const inline virtual
Reimplemented from sstmac::hw::valiant_router.
Definition at line 18 of file ugal_routing.h.
References finalize_init(), initial_step(), and route().
int sstmac::hw::ugal_router::zero_stage_vc (int topology_vc) inline protected
In adition to the valiant stages, ugal has a minimal stage.
This requires another set of virtual channels.
Parameters
topology_vc The geometry-specific virtual channel
Returns
The zero stage virtual channel
Definition at line 69 of file ugal_routing.h.
Member Data Documentation
int sstmac::hw::ugal_router::val_preference_factor_ protected
Definition at line 80 of file ugal_routing.h.
int sstmac::hw::ugal_router::val_threshold_ protected
Definition at line 79 of file ugal_routing.h.
The documentation for this class was generated from the following file:
sstmac/hardware/router/ugal_routing.h