SST/macro: sstmac::hw::simple_param_expander Class Reference
sstmac::hw::simple_param_expander Class Reference
#include <simple_param_expander.h>
Public Member Functions
std::string to_string () const
virtual void expand (sprockit::sim_parameters *params)
Public Member Functions inherited from sprockit::param_expander
virtual ~param_expander ()
virtual void expand (sim_parameters *params)=0
virtual void finalize_init ()
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Protected Member Functions
void expand_amm1_nic (sprockit::sim_parameters *params, sprockit::sim_parameters *nic_params, sprockit::sim_parameters *switch_params)
void expand_amm1_network (sprockit::sim_parameters *params, sprockit::sim_parameters *switch_params)
void expand_amm1_memory (sprockit::sim_parameters *params, sprockit::sim_parameters *mem_params)
void expand_amm2_memory (sprockit::sim_parameters *params, sprockit::sim_parameters *mem_params)
void expand_amm3_network (sprockit::sim_parameters *params, sprockit::sim_parameters *switch_params)
void expand_amm4_nic (sprockit::sim_parameters *params, sprockit::sim_parameters *nic_params, sprockit::sim_parameters *switch_params)
Protected Member Functions inherited from sstmac::hw::param_expander
virtual double network_bandwidth_multiplier (sprockit::sim_parameters *params) const
virtual double switch_bandwidth_multiplier (sprockit::sim_parameters *params) const
virtual int switch_buffer_multiplier (sprockit::sim_parameters *params) const
Detailed Description
Definition at line 10 of file simple_param_expander.h.
Member Function Documentation
virtual void sstmac::hw::simple_param_expander::expand (sprockit::sim_parameters * params) virtual
Referenced by to_string().
void sstmac::hw::simple_param_expander::expand_amm1_memory (sprockit::sim_parameters * params, sprockit::sim_parameters * mem_params) protected
Referenced by to_string().
void sstmac::hw::simple_param_expander::expand_amm1_network (sprockit::sim_parameters * params, sprockit::sim_parameters * switch_params) protected
Referenced by to_string().
void sstmac::hw::simple_param_expander::expand_amm1_nic (sprockit::sim_parameters * params, sprockit::sim_parameters * nic_params, sprockit::sim_parameters * switch_params) protected
Referenced by to_string().
void sstmac::hw::simple_param_expander::expand_amm2_memory (sprockit::sim_parameters * params, sprockit::sim_parameters * mem_params) protected
Referenced by to_string().
void sstmac::hw::simple_param_expander::expand_amm3_network (sprockit::sim_parameters * params, sprockit::sim_parameters * switch_params) protected
Referenced by to_string().
void sstmac::hw::simple_param_expander::expand_amm4_nic (sprockit::sim_parameters * params, sprockit::sim_parameters * nic_params, sprockit::sim_parameters * switch_params) protected
Referenced by to_string().
std::string sstmac::hw::simple_param_expander::to_string () const inline
Definition at line 15 of file simple_param_expander.h.
References expand(), expand_amm1_memory(), expand_amm1_network(), expand_amm1_nic(), expand_amm2_memory(), expand_amm3_network(), and expand_amm4_nic().
The documentation for this class was generated from the following file:
sstmac/hardware/analytic/simple/simple_param_expander.h