SST/macro: sstmac::sw::sstmac_global_struct< T > Class Template Reference
sstmac::sw::sstmac_global_struct< T > Class Template Reference
#include <global_struct.h>
Public Member Functions
sstmac_global_struct ()
sstmac_global_struct (const T &init)
operator T * ()
operator const T * () const
template<typename U >
T & operator= (const sstmac_global_struct< U > &b)
T & operator= (T *b)
template<typename U >
T & operator= (const U &b)
T *& operator-> ()
operator T ()
T & operator* ()
Public Member Functions inherited from sstmac::sw::sstmac_global_builtin< T >
sstmac_global_builtin ()
sstmac_global_builtin (T init)
sstmac_global_builtin (const sstmac_global_builtin< T > &other)
virtual ~sstmac_global_builtin ()
void print_all () const
virtual T & get_val () const
virtual std::string to_string () const
template<typename U >
T & operator= (const U &b)
template<typename U >
T & operator+= (const U &b)
template<typename U >
T & operator-= (const U &b)
template<typename U >
T & operator*= (const U &b)
template<typename U >
T & operator/= (const U &b)
template<typename U >
bool operator== (const U &b) const
template<typename U >
bool operator!= (const U &b) const
operator T & ()
T operator++ (int dummy)
T operator-- (int dummy)
T operator++ ()
T operator-- ()
operator double () const
operator int () const
operator bool () const
operator size_t () const
operator long () const
operator long long () const
template<typename U >
T operator+ (const U &b) const
template<typename U >
T operator- (const U &b) const
template<typename U >
T operator/ (const U &b) const
template<typename U >
T operator<< (const U &b) const
template<typename U >
T operator>> (const U &b) const
template<typename U >
T operator% (const U &b) const
template<typename U >
T operator* (const U &b) const
T * operator& () const
template<typename U >
bool operator> (const U &b)
template<typename U >
bool operator< (const U &b)
void delete_vals ()
const_iterator begin () const
const_iterator end () const
Private Types
typedef sstmac_global_builtin< T > parent
Additional Inherited Members
Public Types inherited from sstmac::sw::sstmac_global_builtin< T >
typedef val_map::const_iterator const_iterator
Protected Member Functions inherited from sstmac::sw::sstmac_global
process_context current_context () const
Detailed Description
template<typename T>
class sstmac::sw::sstmac_global_struct< T >
Definition at line 21 of file global_struct.h.
Member Typedef Documentation
template<typename T> typedef sstmac_global_builtin<T> sstmac::sw::sstmac_global_struct< T >::parent private
Definition at line 23 of file global_struct.h.
Constructor & Destructor Documentation
template<typename T> sstmac::sw::sstmac_global_struct< T >::sstmac_global_struct () inline explicit
Definition at line 26 of file global_struct.h.
template<typename T> sstmac::sw::sstmac_global_struct< T >::sstmac_global_struct (const T & init) inline explicit
Definition at line 30 of file global_struct.h.
Member Function Documentation
template<typename T> sstmac::sw::sstmac_global_struct< T >::operator const T * () const inline
Definition at line 38 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> sstmac::sw::sstmac_global_struct< T >::operator T () inline
Definition at line 71 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> sstmac::sw::sstmac_global_struct< T >::operator T * () inline
Definition at line 34 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> T& sstmac::sw::sstmac_global_struct< T >::operator* () inline
Definition at line 80 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> T*& sstmac::sw::sstmac_global_struct< T >::operator-> () inline
Definition at line 66 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T& sstmac::sw::sstmac_global_struct< T >::operator= (const sstmac_global_struct< U > & b) inline
Definition at line 44 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> T& sstmac::sw::sstmac_global_struct< T >::operator= (T * b) inline
Definition at line 51 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T& sstmac::sw::sstmac_global_struct< T >::operator= (const U & b) inline
Definition at line 59 of file global_struct.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
The documentation for this class was generated from the following file:
sstmac/software/process/global_struct.h