SST/macro: sstmac::hw::hypercube Class Reference
sstmac::hw::hypercube Class Reference
#include <hypercube.h>
Public Member Functions
virtual std::string to_string () const
virtual ~hypercube ()
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual void productive_path (int dim, const coordinates &src, const coordinates &dst, routing_info::path &path) const
std::string name () const
void minimal_route_to_coords (const coordinates &src_coords, const coordinates &dest_coords, routing_info::path &path) const
Workhorse function for implementing minimal_route_to_switch and #minimal_route_to_node.
virtual void connect_objects (internal_connectable_map &switches)
Given a set of connectables, connect them appropriately.
virtual int convert_to_port (int dim, int dir) const
int minimal_distance (const coordinates &src_coords, const coordinates &dest_coords) const
The function accepts either source or node coordinates.
Public Member Functions inherited from sstmac::hw::hdtorus
virtual ~hdtorus ()
int shortest_distance (int dim, int src, int dst) const
int distance (int dim, int dir, int src, int dst) const
void down_path (int dim, const coordinates &src, const coordinates &dst, routing_info::path &path) const
void up_path (int dim, const coordinates &src, const coordinates &dst, routing_info::path &path) const
bool shortest_path_positive (int dim, const coordinates &src, const coordinates &dst) const
void pick_vc (routing_info::path &path) const
switch_id switch_number (const coordinates &v) const
int diameter () const
std::string name () const
const std::vector< int > & dimensions () const
Returns the vector giving each dimension of the torus.
coordinates neighbor_at_port (switch_id sid, int port)
virtual int num_switches () const
virtual int num_leaf_switches () const
Structured topologies can be direct (torus) or indirect (fat tree).
void configure_geometric_paths (std::vector< int > &redundancies)
virtual int ndimensions () const
The number of distinct 'dimensions' in the topology.
void partners (traffic_pattern::type_t ty, const coordinates &src_sw_coords, std::list< node_id > &partners) const
void configure_vc_routing (std::map< routing::algorithm_t, int > &m) const
Public Member Functions inherited from sstmac::hw::cartesian_topology
const std::vector< int > & red () const
virtual void minimal_routes_to_switch (switch_id current_sw_addr, switch_id dest_sw_addr, routing_info::path &current_path, routing_info::path_set &paths) const
Public Member Functions inherited from sstmac::hw::structured_topology
virtual ~structured_topology ()
virtual void build_internal_connectables (internal_connectable_map &connectables, sprockit::factory< connectable > *factory, partition *part, int my_rank, sprockit::sim_parameters *params, connectable *dummy)
virtual void build_endpoint_connectables (end_point_connectable_map &connectables, sprockit::factory< connectable > *factory, partition *part, int my_rank, sprockit::sim_parameters *params)
virtual void build_interface_connectables (int conc, end_point_connectable_map &connectables, sprockit::factory2< connectable > *nic_factory, partition *part, int my_rank, sprockit::sim_parameters *params, sprockit::factory_type *interconnect)
virtual void minimal_routes_to_coords (const coordinates &src_coords, const coordinates &dest_coords, routing_info::path &current_path, routing_info::path_set &paths) const
virtual int endpoints_per_switch (switch_id addr) const
Given a switch address, return number of nodes connected to it.
virtual int num_nodes () const
virtual int num_endpoints () const
coordinates switch_coords (switch_id swid) const
Compute coordinates (e.g.
virtual coordinates node_coords (node_id nid) const
Compute coordinates (e.g.
coordinates endpoint_coords (node_id nid) const
virtual switch_id endpoint_to_ejection_switch (node_id nodeaddr, int &switch_port) const
virtual switch_id endpoint_to_injection_switch (node_id nodeaddr, int &switch_port) const
virtual int endpoint_to_ejection_port (node_id addr) const
virtual int endpoint_to_injection_port (node_id addr) const
virtual int endpoint_to_switch_port (node_id nid) const
void finalize_init ()
virtual void productive_paths (routing_info::path_set &paths, const coordinates &current, const coordinates &dst)
std::string label (node_id nid) const
std::string label (switch_id sid) const
virtual void minimal_route_to_switch (switch_id current_sw_addr, switch_id dest_sw_addr, routing_info::path &path) const
Implementation of topology::minimal_route_to_switch.
virtual void eject_paths_on_switch (node_id dest_addr, switch_id sw_addr, routing_info::path_set &paths) const
virtual int num_hops_to_node (node_id src, node_id dst) const
virtual std::vector< node_id > nodes_connected_to_injection_switch (switch_id swaddr) const
virtual std::vector< node_id > nodes_connected_to_ejection_switch (switch_id swid) const
virtual node_id node_addr (const coordinates &coords) const
virtual node_id node_addr (const coordinates &sw_coords, int port) const
virtual std::string default_router () const
virtual void send_partners (traffic_pattern::type_t ty, node_id src_node, std::vector< node_id > &partners) const
virtual void recv_partners (traffic_pattern::type_t ty, node_id src_node, std::vector< node_id > &partners) const
Protected Attributes
int radix_
int ndim_
std::vector< int > dim_to_outport_
Protected Attributes inherited from sstmac::hw::hdtorus
int diameter_
long num_switches_
std::vector< int > dimensions_
Protected Attributes inherited from sstmac::hw::cartesian_topology
std::vector< int > red_
Protected Attributes inherited from sstmac::hw::structured_topology
int eject_geometric_id_
int injection_redundancy_
bool outputgraph_
Additional Inherited Members
Public Types inherited from sstmac::hw::hdtorus
enum direction_t { pos = 0, neg = 1 }
Protected Member Functions inherited from sstmac::hw::hdtorus
virtual void compute_switch_coords (switch_id uid, coordinates &coords) const
Compute coordinates (e.g.
void nearest_neighbor_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
void bit_complement_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
void tornado_send_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
void tornado_recv_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
virtual void connect_dim (int dim, connectable *center, connectable *plus, connectable *minus)
Protected Member Functions inherited from sstmac::hw::structured_topology
void configure_injection_geometry (std::vector< int > &redundancies)
virtual std::vector< node_id > nodes_connected_to_switch (switch_id swaddr) const
structured_topology ()
void partners (bool get_send_partner, traffic_pattern::type_t ty, node_id src, std::vector< node_id > &partner_list) const
Detailed Description
Definition at line 22 of file hypercube.h.
Constructor & Destructor Documentation
virtual sstmac::hw::hypercube::~hypercube () inline virtual
Definition at line 31 of file hypercube.h.
References connect_objects(), convert_to_port(), init_factory_params(), minimal_distance(), minimal_route_to_coords(), name(), and productive_path().
Member Function Documentation
virtual void sstmac::hw::hypercube::connect_objects (internal_connectable_map & objects) virtual
Given a set of connectables, connect them appropriately.
Parameters
objects The set of objects to connect
cloner If in parallel mode, not all objects may exist. The factory creates missing objects.
Exceptions
value_error If invalid switchid is passed to cloner
Reimplemented from sstmac::hw::hdtorus.
Referenced by ~hypercube().
virtual int sstmac::hw::hypercube::convert_to_port (int dim, int dir) const virtual
Reimplemented from sstmac::hw::hdtorus.
Referenced by ~hypercube().
virtual void sstmac::hw::hypercube::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::hw::hdtorus.
Referenced by ~hypercube().
int sstmac::hw::hypercube::minimal_distance (const coordinates & src_coords, const coordinates & dest_coords) const virtual
The function accepts either source or node coordinates.
This gives the minimal distance counting the number of hops between switches. If node coordinates are given, the last coordinate is just ignored.
Parameters
src_coords. The source coordinates. This can be either switch or node coordinates.
dest_coords. The destination coordinates. This can be either switch or node coordinates.
Returns
The number of hops to final destination
Reimplemented from sstmac::hw::hdtorus.
Referenced by ~hypercube().
void sstmac::hw::hypercube::minimal_route_to_coords (const coordinates & src_coords, const coordinates & dest_coords, routing_info::path & path) const virtual
Workhorse function for implementing minimal_route_to_switch and #minimal_route_to_node.
Given source/dest coordinates, find the minimal path.
Parameters
current_sw_addr The addr of the current switch
dest_sw_addr The addr of the destination switch
path [inout] A complete path descriptor to the destination switch
Reimplemented from sstmac::hw::hdtorus.
Referenced by ~hypercube().
std::string sstmac::hw::hypercube::name () const
Referenced by ~hypercube().
virtual void sstmac::hw::hypercube::productive_path (int dim, const coordinates & src, const coordinates & dst, routing_info::path & path) const virtual
Parameters
dim The dimension you want to move in. You might need to traverse other dimensions FIRST before you make progress on this dimension.
src The coordinates of the source switch
dst The coordinates of the dest switch
path [inout] The path configuration for making progress on dim
Reimplemented from sstmac::hw::hdtorus.
Referenced by ~hypercube().
virtual std::string sstmac::hw::hypercube::to_string () const inline virtual
Reimplemented from sstmac::hw::hdtorus.
Definition at line 27 of file hypercube.h.
Member Data Documentation
std::vector<int> sstmac::hw::hypercube::dim_to_outport_ protected
Definition at line 66 of file hypercube.h.
int sstmac::hw::hypercube::ndim_ protected
Definition at line 65 of file hypercube.h.
int sstmac::hw::hypercube::radix_ protected
Definition at line 64 of file hypercube.h.
The documentation for this class was generated from the following file:
sstmac/hardware/topology/hypercube.h