SST/macro: sstmac::sw::app_manager Class Reference
sstmac::sw::app_manager Class Reference abstract
#include <app_manager.h>
Public Member Functions
virtual ~app_manager ()
virtual int nproc () const =0
virtual node_id node_assignment (int rank) const =0
virtual const std::list< int > & rank_assignment (node_id nid) const =0
virtual void init_param1 (sw::app_id aid)
virtual void init_param2 (parallel_runtime *rt)
virtual void set_interconnect (hw::interconnect *interconn)
virtual void init_factory_params (sprockit::sim_parameters *params)
hw::topology * topol () const
hw::interconnect * interconn () const
hw::node * node_at (node_id nid) const
virtual void allocate_and_index_jobs ()=0
virtual sw::launch_info * launch_info () const =0
void add_hostname (sw::task_id tid, const std::string &name, node_id addr)
void setenv (const std::string &name, const std::string &value)
std::string getenv (const std::string &name) const
std::string hostname (sw::task_id tid) const
node_id node_address (const std::string &hostname) const
node_id node_for_task (sw::task_id tid) const
void set_node_address (sw::task_id tid, node_id n)
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Static Public Member Functions
static app_manager * static_app_manager (int aid, sprockit::sim_parameters *params)
Protected Types
typedef spkt_unordered_map< sw::task_id, node_id > task_to_node_map
typedef spkt_unordered_map< sw::task_id, std::string > task_to_hostname_map
typedef spkt_unordered_map< std::string, std::string > shell_var_map
typedef spkt_unordered_map< std::string, node_id > hostname_to_addr_map
Protected Member Functions
app_manager ()
Protected Attributes
parallel_runtime * rt_
hw::topology * top_
hw::interconnect * interconn_
sw::app * app_template_
sw::app_id aid_
std::string appname_
std::vector< int > core_affinities_
task_to_node_map nodeids_
task_to_hostname_map hostnames_
hostname_to_addr_map inet_addrs_
shell_var_map shell_env_
Static Private Attributes
static std::map< int, app_manager * > static_app_managers_
Detailed Description
Definition at line 34 of file app_manager.h.
Member Typedef Documentation
typedef spkt_unordered_map<std::string, node_id> sstmac::sw::app_manager::hostname_to_addr_map protected
Definition at line 118 of file app_manager.h.
typedef spkt_unordered_map<std::string, std::string> sstmac::sw::app_manager::shell_var_map protected
Definition at line 117 of file app_manager.h.
typedef spkt_unordered_map<sw::task_id, std::string> sstmac::sw::app_manager::task_to_hostname_map protected
Definition at line 116 of file app_manager.h.
typedef spkt_unordered_map<sw::task_id, node_id> sstmac::sw::app_manager::task_to_node_map protected
Definition at line 115 of file app_manager.h.
Constructor & Destructor Documentation
virtual sstmac::sw::app_manager::~app_manager () virtual
sstmac::sw::app_manager::app_manager () protected
Member Function Documentation
void sstmac::sw::app_manager::add_hostname (sw::task_id tid, const std::string & name, node_id addr)
Referenced by interconn().
virtual void sstmac::sw::app_manager::allocate_and_index_jobs () pure virtual
Implemented in sstmac::native::indexing_app_manager.
Referenced by interconn().
std::string sstmac::sw::app_manager::getenv (const std::string & name) const
Referenced by setenv().
std::string sstmac::sw::app_manager::hostname (sw::task_id tid) const
Referenced by setenv().
virtual void sstmac::sw::app_manager::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented in sstmac::native::indexing_app_manager, sstmac::native::dumpi_app_manager, and sstmac::native::skeleton_app_manager.
Referenced by init_param2().
virtual void sstmac::sw::app_manager::init_param1 (sw::app_id aid) inline virtual
Definition at line 52 of file app_manager.h.
References aid_.
virtual void sstmac::sw::app_manager::init_param2 (parallel_runtime * rt) inline virtual
Definition at line 57 of file app_manager.h.
References init_factory_params(), interconn(), rt_, and set_interconnect().
hw::interconnect* sstmac::sw::app_manager::interconn () const inline
Definition at line 73 of file app_manager.h.
References add_hostname(), allocate_and_index_jobs(), interconn_, launch_info(), and node_at().
Referenced by init_param2(), and sstmac::native::indexing_app_manager::launch_info().
virtual sw::launch_info* sstmac::sw::app_manager::launch_info () const pure virtual
Implemented in sstmac::native::indexing_app_manager.
Referenced by interconn().
node_id sstmac::sw::app_manager::node_address (const std::string & hostname) const
Referenced by setenv().
virtual node_id sstmac::sw::app_manager::node_assignment (int rank) const pure virtual
Implemented in sstmac::native::indexing_app_manager.
hw::node* sstmac::sw::app_manager::node_at (node_id nid) const
Referenced by interconn().
node_id sstmac::sw::app_manager::node_for_task (sw::task_id tid) const
Referenced by setenv().
virtual int sstmac::sw::app_manager::nproc () const pure virtual
Implemented in sstmac::native::indexing_app_manager.
virtual const std::list<int>& sstmac::sw::app_manager::rank_assignment (node_id nid) const pure virtual
Implemented in sstmac::native::indexing_app_manager.
virtual void sstmac::sw::app_manager::set_interconnect (hw::interconnect * interconn) virtual
Reimplemented in sstmac::native::indexing_app_manager.
Referenced by init_param2().
void sstmac::sw::app_manager::set_node_address (sw::task_id tid, node_id n) inline
Definition at line 107 of file app_manager.h.
References nodeids_, and static_app_manager().
void sstmac::sw::app_manager::setenv (const std::string & name, const std::string & value) inline
Definition at line 90 of file app_manager.h.
References getenv(), hostname(), node_address(), node_for_task(), and shell_env_.
static app_manager* sstmac::sw::app_manager::static_app_manager (int aid, sprockit::sim_parameters * params) static
Referenced by set_node_address().
hw::topology* sstmac::sw::app_manager::topol () const inline
Definition at line 68 of file app_manager.h.
References top_.
Member Data Documentation
sw::app_id sstmac::sw::app_manager::aid_ protected
Definition at line 128 of file app_manager.h.
Referenced by init_param1().
sw::app* sstmac::sw::app_manager::app_template_ protected
Definition at line 126 of file app_manager.h.
std::string sstmac::sw::app_manager::appname_ protected
Definition at line 130 of file app_manager.h.
std::vector<int> sstmac::sw::app_manager::core_affinities_ protected
Definition at line 132 of file app_manager.h.
task_to_hostname_map sstmac::sw::app_manager::hostnames_ protected
Definition at line 136 of file app_manager.h.
hostname_to_addr_map sstmac::sw::app_manager::inet_addrs_ protected
Definition at line 138 of file app_manager.h.
hw::interconnect* sstmac::sw::app_manager::interconn_ protected
Definition at line 124 of file app_manager.h.
Referenced by interconn().
task_to_node_map sstmac::sw::app_manager::nodeids_ protected
Definition at line 134 of file app_manager.h.
Referenced by set_node_address().
parallel_runtime* sstmac::sw::app_manager::rt_ protected
Definition at line 120 of file app_manager.h.
Referenced by init_param2().
shell_var_map sstmac::sw::app_manager::shell_env_ protected
Definition at line 140 of file app_manager.h.
Referenced by setenv().
std::map<int, app_manager*> sstmac::sw::app_manager::static_app_managers_ static private
Definition at line 145 of file app_manager.h.
hw::topology* sstmac::sw::app_manager::top_ protected
Definition at line 122 of file app_manager.h.
Referenced by topol().
The documentation for this class was generated from the following file:
sstmac/software/process/app_manager.h