SST/macro: sstmac::stat_spyplot Class Reference
sstmac::stat_spyplot Class Reference
this stat_collector class keeps a spy plot
#include <stat_spyplot.h>
Public Member Functions
virtual std::string to_string () const
virtual void simulation_finished (timestamp end)
This is to notify that the statistics collector is done.
virtual void dump_to_file (const std::string &froot)
virtual void dump_local_data ()
After post-processing, this notifies the collector to dump data to a file.
virtual void dump_global_data ()
After post-processing, this notifies the collector to dump data to a file.
virtual void reduce (stat_collector *coll)
virtual void global_reduce (parallel_runtime *rt)
virtual void clear ()
virtual ~stat_spyplot ()
virtual void add_one (int source, int dest)
virtual void add (int source, int dest, long num)
virtual stat_spyplot * clone_me (int id) const
virtual stat_collector * clone () const
stat_spyplot ()
Public Member Functions inherited from sstmac::stat_collector
virtual ~stat_collector ()
void init_factory_params (sprockit::sim_parameters *params)
bool registered () const
virtual void set_id (int id)
int id () const
void set_registered (bool reg)
void add_suffix (const std::string &suffix)
std::string fileroot () const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Types
typedef spkt_unordered_map< int, long > long_map
typedef spkt_unordered_map< int, long_map > spyplot_map
Protected Member Functions
void clone_into (stat_spyplot *cln) const
Protected Member Functions inherited from sstmac::stat_collector
stat_collector ()
void clone_into (stat_collector *cln) const
Protected Attributes
spyplot_map vals_
int max_dest_
Protected Attributes inherited from sstmac::stat_collector
bool registered_
int id_
std::string fileroot_
Additional Inherited Members
Static Protected Member Functions inherited from sstmac::stat_collector
static bool check_open (std::fstream &myfile, const std::string &fname, std::ios::openmode flags=std::ios::out)
Check to see if the file is open.
Detailed Description
this stat_collector class keeps a spy plot
Definition at line 28 of file stat_spyplot.h.
Member Typedef Documentation
typedef spkt_unordered_map<int, long> sstmac::stat_spyplot::long_map protected
Definition at line 88 of file stat_spyplot.h.
typedef spkt_unordered_map<int, long_map> sstmac::stat_spyplot::spyplot_map protected
Definition at line 89 of file stat_spyplot.h.
Constructor & Destructor Documentation
virtual sstmac::stat_spyplot::~stat_spyplot () inline virtual
Definition at line 59 of file stat_spyplot.h.
References add(), and add_one().
sstmac::stat_spyplot::stat_spyplot () inline
Definition at line 81 of file stat_spyplot.h.
References clone_into().
Referenced by clone_me().
Member Function Documentation
virtual void sstmac::stat_spyplot::add (int source, int dest, long num) virtual
Reimplemented in sstmac::stat_spyplot_png.
Referenced by sstmac::stat_spyplot_png::to_string(), and ~stat_spyplot().
virtual void sstmac::stat_spyplot::add_one (int source, int dest) virtual
Referenced by ~stat_spyplot().
virtual void sstmac::stat_spyplot::clear () virtual
Implements sstmac::stat_collector.
Referenced by to_string().
virtual stat_collector* sstmac::stat_spyplot::clone () const inline virtual
Implements sstmac::stat_collector.
Reimplemented in sstmac::stat_spyplot_png.
Definition at line 77 of file stat_spyplot.h.
References clone_me().
void sstmac::stat_spyplot::clone_into (stat_spyplot * cln) const protected
Referenced by sstmac::stat_spyplot_png::clone(), clone_me(), sstmac::stat_spyplot_png::clone_me(), and stat_spyplot().
virtual stat_spyplot* sstmac::stat_spyplot::clone_me (int id) const inline virtual
Reimplemented in sstmac::stat_spyplot_png.
Definition at line 69 of file stat_spyplot.h.
References clone_into(), sstmac::stat_collector::set_id(), and stat_spyplot().
Referenced by clone(), and sstmac::stat_spyplot_png::clone().
virtual void sstmac::stat_spyplot::dump_global_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
Referenced by to_string().
virtual void sstmac::stat_spyplot::dump_local_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
Referenced by to_string().
virtual void sstmac::stat_spyplot::dump_to_file (const std::string & froot) virtual
Reimplemented in sstmac::stat_spyplot_png.
Referenced by to_string(), and sstmac::stat_spyplot_png::to_string().
virtual void sstmac::stat_spyplot::global_reduce (parallel_runtime * rt) virtual
Implements sstmac::stat_collector.
Referenced by to_string().
virtual void sstmac::stat_spyplot::reduce (stat_collector * coll) virtual
Implements sstmac::stat_collector.
Referenced by to_string().
virtual void sstmac::stat_spyplot::simulation_finished (timestamp end) virtual
This is to notify that the statistics collector is done.
Do any necessary data post-processing, but do NOT dump to file
Implements sstmac::stat_collector.
Referenced by to_string().
virtual std::string sstmac::stat_spyplot::to_string () const inline virtual
Reimplemented from sstmac::stat_collector.
Reimplemented in sstmac::stat_spyplot_png.
Definition at line 33 of file stat_spyplot.h.
References clear(), dump_global_data(), dump_local_data(), dump_to_file(), global_reduce(), reduce(), and simulation_finished().
Member Data Documentation
int sstmac::stat_spyplot::max_dest_ protected
Definition at line 91 of file stat_spyplot.h.
spyplot_map sstmac::stat_spyplot::vals_ protected
Definition at line 90 of file stat_spyplot.h.
The documentation for this class was generated from the following file:
sstmac/common/stats/stat_spyplot.h