SST/macro: sstmac::hw::null_nic Class Reference
sstmac::hw::null_nic Class Reference
#include <null_nic.h>
Public Member Functions
virtual ~null_nic () throw ()
std::string to_string () const
void init_factory_params (sprockit::sim_parameters *params)
Initialize all member variables from the parameters object.
Public Member Functions inherited from sstmac::hw::simple_nic
simple_nic ()
virtual ~simple_nic ()
Goodbye.
virtual void finalize_init ()
A final initialization function called for the object after all parameters have been read.
void handle (event *ev)
virtual void connect (int src_outport, int dst_inport, connection_type_t ty, connectable *mod, config *cfg)
connect
timestamp injection_latency () const
double injection_bandwidth () const
Public Member Functions inherited from sstmac::hw::nic
virtual ~nic ()
virtual void init_param1 (sprockit::factory_type *interconn)
Initialize the first construction parameter.
node_id addr () const
virtual void set_node (node *nd)
Set an event handler wrapper encapsulation the parent computational unit.
void mtl_handle (event *ev)
event_handler * mtl_handler () const
void internode_send (network_message *payload)
Perform the set of operations standard to all NICs.
void intranode_send (network_message *payload)
Perform the set of operations standard to all NICs for transfers within a node.
virtual void set_event_parent (event_scheduler *m)
Set the eventmanager for this scheduler.
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Public Member Functions inherited from sstmac::hw::failable
bool failed () const
void fail ()
Public Member Functions inherited from sstmac::event_subscheduler
event_subscheduler ()
timestamp now () const
get the current time
void schedule (timestamp t, event_handler *handler, event *ev)
Add an event to the event queue, where msg will get delivered to handler at time t.
void schedule (timestamp t, event_queue_entry *ev)
void schedule_now (event_queue_entry *ev)
void schedule_now (event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_queue_entry *ev)
void send_self_event (timestamp arrival, event *ev)
void send_delayed_self_event (timestamp delay, event *ev)
void send_now_self_event (event *ev)
void send_self_event_queue (timestamp arrival, event_queue_entry *ev)
void send_delayed_self_event_queue (timestamp delay, event_queue_entry *ev)
void send_now_self_event_queue (event_queue_entry *ev)
event_scheduler * parent () const
Public Member Functions inherited from sstmac::event_handler
virtual ~event_handler ()
event_loc_id event_location () const
virtual bool ipc_handler () const
Whether an event handler is a "fake" handler that represents logical process boundary.
int thread_id () const
virtual void deadlock_check (event *ev)
virtual void deadlock_check ()
Additional Inherited Members
Public Types inherited from sstmac::hw::connectable
enum config_type_t {
RedundantConnection =0, WeightedConnection =1, FixedBandwidthConnection =2, FixedConnection =3,
BasicConnection =4
}
enum connection_type_t { output, input }
Static Public Member Functions inherited from sstmac::hw::nic
static void delete_statics ()
Delete all static variables associated with this class.
Static Public Member Functions inherited from sstmac::hw::connectable
static const char * str (connection_type_t ty)
Static Public Attributes inherited from sstmac::event_handler
static const int null_lpid = -1
static const int null_threadid = -1
Static Public Attributes inherited from sstmac::hw::connectable
static const int any_port = -1
Protected Member Functions inherited from sstmac::hw::simple_nic
virtual void do_send (network_message *msg)
Start the message sending and inject it into the network.
Protected Member Functions inherited from sstmac::hw::nic
nic ()
void send_to_node (network_message *netmsg)
bool negligible_size (int bytes) const
void recv_message (message *msg)
The NIC can either receive an entire message (bypass the byte-transfer layer) or it can receive packets.
Protected Member Functions inherited from sstmac::hw::failable
failable ()
Protected Member Functions inherited from sstmac::event_handler
event_handler ()
void init_loc_id (event_loc_id id)
void init_thread_id (int id)
Protected Attributes inherited from sstmac::hw::simple_nic
double inj_bw_inverse_
timestamp inj_lat_
timestamp next_free_
Protected Attributes inherited from sstmac::hw::nic
node_id my_addr_
int negligible_size_
interconnect * interconn_
node * parent_
Protected Attributes inherited from sstmac::hw::failable
bool failed_
Protected Attributes inherited from sstmac::event_subscheduler
event_scheduler * parent_
Detailed Description
Definition at line 12 of file null_nic.h.
Constructor & Destructor Documentation
virtual sstmac::hw::null_nic::~null_nic () throw () inline virtual
Definition at line 17 of file null_nic.h.
Member Function Documentation
void sstmac::hw::null_nic::init_factory_params (sprockit::sim_parameters * params) virtual
Initialize all member variables from the parameters object.
Parameters
params
Reimplemented from sstmac::hw::simple_nic.
Referenced by to_string().
std::string sstmac::hw::null_nic::to_string () const inline virtual
Reimplemented from sstmac::hw::simple_nic.
Definition at line 20 of file null_nic.h.
References init_factory_params(), sstmac::hw::nic::my_addr_, and sprockit::printf().
The documentation for this class was generated from the following file:
sstmac/hardware/analytic/simple/null_nic.h