SST/macro: sstmac::sw::unblock_event Class Reference
sstmac::sw::unblock_event Class Reference
#include <unblock_event.h>
Public Member Functions
unblock_event (operating_system *os, key *k)
std::string to_string () const
virtual void execute ()
Protected Attributes
operating_system * os_
key * key_
Protected Attributes inherited from sstmac::event_queue_entry
timestamp time_
event_loc_id dst_loc_
event_loc_id src_loc_
uint32_t seqnum_
A unique sequence number from the source.
Detailed Description
Definition at line 24 of file unblock_event.h.
Constructor & Destructor Documentation
sstmac::sw::unblock_event::unblock_event (operating_system * os, key * k)
Member Function Documentation
virtual void sstmac::sw::unblock_event::execute () virtual
Implements sstmac::event_queue_entry.
Referenced by to_string(), and sstmac::sw::timeout_event::to_string().
std::string sstmac::sw::unblock_event::to_string () const inline virtual
Implements sstmac::event_queue_entry.
Definition at line 31 of file unblock_event.h.
References execute().
Member Data Documentation
key* sstmac::sw::unblock_event::key_ protected
Definition at line 39 of file unblock_event.h.
operating_system* sstmac::sw::unblock_event::os_ protected
Definition at line 38 of file unblock_event.h.
The documentation for this class was generated from the following file:
sstmac/software/libraries/unblock_event.h