SST/macro: sstmac::event_handler Class Reference
sstmac::event_handler Class Reference abstract
The main interface for something that can respond to an event (sst_message).
#include <event_handler.h>
Public Member Functions
virtual std::string to_string () const =0
virtual ~event_handler ()
virtual void handle (event *ev)=0
event_loc_id event_location () const
virtual bool ipc_handler () const
Whether an event handler is a "fake" handler that represents logical process boundary.
int thread_id () const
virtual void deadlock_check (event *ev)
virtual void deadlock_check ()
Static Public Attributes
static const int null_lpid = -1
static const int null_threadid = -1
Protected Member Functions
event_handler ()
void init_loc_id (event_loc_id id)
void init_thread_id (int id)
Private Attributes
event_loc_id loc_id_
int thread_id_
Detailed Description
The main interface for something that can respond to an event (sst_message).
Definition at line 24 of file event_handler.h.
Constructor & Destructor Documentation
sstmac::event_handler::event_handler () inline protected
Definition at line 50 of file event_handler.h.
References to_string().
virtual sstmac::event_handler::~event_handler () inline virtual
Definition at line 57 of file event_handler.h.
References handle().
Member Function Documentation
virtual void sstmac::event_handler::deadlock_check (event * ev) inline virtual
Definition at line 83 of file event_handler.h.
virtual void sstmac::event_handler::deadlock_check () inline virtual
Reimplemented in sstmac::hw::packet_flow_network_buffer, and sstmac::hw::packet_flow_NtoM_queue.
Definition at line 86 of file event_handler.h.
Referenced by sstmac::hw::packet_flow_network_buffer::set_sanity_params().
event_loc_id sstmac::event_handler::event_location () const inline
Definition at line 63 of file event_handler.h.
References loc_id_.
Referenced by sstmac::hw::packet_flow_buffer::input_location(), and sstmac::hw::packet_flow_buffer::output_location().
virtual void sstmac::event_handler::handle (event * ev) pure virtual
Implemented in sstmac::event_subscheduler, sstmac::hw::node, sstmac::event_callback_2_args< Cls, Fxn, Arg1, Arg2 >, sstmac::hw::packet_flow_netlink, sstmac::hw::nic, sstmac::event_callback_1_args< Cls, Fxn, Arg1 >, sstmac::hw::packet_flow_handler, sstmac::event_scheduler, sstmac::event_callback_instance< Cls, Fxn >, sstmac::integrated_connectable_wrapper, sstmac::hw::simple_nic, sstmac::hw::packet_flow_nic, sstmac::event_callback, and sstmac::hw::packet_flow_packetizer.
Referenced by ~event_handler().
void sstmac::event_handler::init_loc_id (event_loc_id id) inline protected
Definition at line 90 of file event_handler.h.
References loc_id_.
Referenced by sstmac::event_callback::event_callback(), sstmac::sw::operating_system::set_addr(), sstmac::hw::packet_flow_sender::set_event_location(), and sstmac::event_subscheduler::set_event_parent().
void sstmac::event_handler::init_thread_id (int id) inline protected
Definition at line 95 of file event_handler.h.
References thread_id_.
Referenced by sstmac::event_subscheduler::set_event_parent().
virtual bool sstmac::event_handler::ipc_handler () const inline virtual
Whether an event handler is a "fake" handler that represents logical process boundary.
Messages scheduled here are sent to another process.
Returns
If this is an IPC stub handler
Definition at line 73 of file event_handler.h.
int sstmac::event_handler::thread_id () const inline
Definition at line 78 of file event_handler.h.
References thread_id_.
Referenced by sstmac::hw::packet_flow_NtoM_queue::thread_id(), and sstmac::hw::packet_flow_handler::thread_id().
virtual std::string sstmac::event_handler::to_string () const pure virtual
Implemented in sstmac::event_subscheduler, sstmac::hw::packet_flow_demuxer, sstmac::hw::node, sstmac::hw::packet_flow_netlink, sstmac::hw::packet_flow_sender, sstmac::hw::packet_flow_handler, sstmac::event_scheduler, sstmac::hw::nic, sstmac::hw::simple_nic, sstmac::integrated_connectable_wrapper, sstmac::hw::packet_flow_nic_packetizer, sstmac::event_callback, sstmac::hw::packet_flow_nic, and sstmac::hw::null_nic.
Referenced by event_handler().
Member Data Documentation
event_loc_id sstmac::event_handler::loc_id_ private
Definition at line 101 of file event_handler.h.
Referenced by event_location(), and init_loc_id().
const int sstmac::event_handler::null_lpid = -1 static
Definition at line 27 of file event_handler.h.
const int sstmac::event_handler::null_threadid = -1 static
Definition at line 28 of file event_handler.h.
int sstmac::event_handler::thread_id_ private
Definition at line 102 of file event_handler.h.
Referenced by init_thread_id(), and thread_id().
The documentation for this class was generated from the following file:
sstmac/common/event_handler.h