SST/macro: sstmac::thread_safe_int_t< Integer > Class Template Reference
sstmac::thread_safe_int_t< Integer > Class Template Reference
#include <thread_safe_int.h>
Public Member Functions
template<class Y >
thread_safe_int_t (const Y &y)
template<class Y >
Integer & operator= (const Y &y)
Integer operator++ ()
Integer operator++ (int i)
operator Integer ()
Public Member Functions inherited from sstmac::lockable
void lock ()
void unlock ()
Protected Attributes
Integer value_
Detailed Description
template<class Integer>
class sstmac::thread_safe_int_t< Integer >
Definition at line 15 of file thread_safe_int.h.
Constructor & Destructor Documentation
template<class Integer > template<class Y > sstmac::thread_safe_int_t< Integer >::thread_safe_int_t (const Y & y) inline
Definition at line 21 of file thread_safe_int.h.
Member Function Documentation
template<class Integer > sstmac::thread_safe_int_t< Integer >::operator Integer () inline
Definition at line 50 of file thread_safe_int.h.
References sstmac::thread_safe_int_t< Integer >::value_.
template<class Integer > Integer sstmac::thread_safe_int_t< Integer >::operator++ () inline
Definition at line 33 of file thread_safe_int.h.
References sstmac::lockable::lock(), sstmac::lockable::unlock(), and sstmac::thread_safe_int_t< Integer >::value_.
template<class Integer > Integer sstmac::thread_safe_int_t< Integer >::operator++ (int i) inline
Definition at line 42 of file thread_safe_int.h.
References sstmac::lockable::lock(), sstmac::lockable::unlock(), and sstmac::thread_safe_int_t< Integer >::value_.
template<class Integer > template<class Y > Integer& sstmac::thread_safe_int_t< Integer >::operator= (const Y & y) inline
Definition at line 27 of file thread_safe_int.h.
References sstmac::thread_safe_int_t< Integer >::value_.
Member Data Documentation
template<class Integer > Integer sstmac::thread_safe_int_t< Integer >::value_ protected
Definition at line 55 of file thread_safe_int.h.
Referenced by sstmac::thread_safe_int_t< Integer >::operator Integer(), sstmac::thread_safe_int_t< Integer >::operator++(), and sstmac::thread_safe_int_t< Integer >::operator=().
The documentation for this class was generated from the following file:
sstmac/common/thread_safe_int.h