SST/macro: sumi::parsedumpi_callbacks Class Reference
sumi::parsedumpi_callbacks Class Reference
Populate C-style callbacks for a libundumpi parser.
#include <parsedumpi_callbacks.h>
Public Types
enum if_unimplemented { IGNORE, PRINT, ABORT }
Accepted actions to be taken for unimplemented functions.
Public Member Functions
parsedumpi_callbacks (parsedumpi *parent)
Populate callbacks.
void set_initialized (bool flag)
bool initialized () const
void parse_stream (const std::string &filename, bool print_progress, double percent_terminate)
Start parsing.
Private Types
typedef std::map< dumpi_comm, MPI_Comm > mpicomm_map_t
Map dumpi request identifiers to objects.
typedef std::map< dumpi_request, MPI_Request > request_map_t
typedef std::map< dumpi_group, MPI_Group > mpigroup_map_t
typedef std::map< dumpi_op, MPI_Op > mpiop_map_t
typedef std::map< dumpi_datatype, MPI_Datatype > mpitype_map_t
Private Member Functions
void init_maps ()
Initialize maps (datatypes etc.). Called at constrution.
void start_mpi (const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf)
Indicate that we are starting an MPI call.
void end_mpi (const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf)
Indicate that we have completed an MPI call.
mpi_api * getmpi ()
Access the mpiapi.
void store_request (dumpi_request id, MPI_Request request)
Store a single request handle.
MPI_Request * get_request_ptr (dumpi_request id)
Get a single request handle.
MPI_Request * get_requests (int count, const dumpi_request *dumpireq)
Get a group of request handles.
void complete_request (dumpi_request id)
Remove a request from the map.
template<typename Iter >
void complete_requests (Iter begin, Iter end)
Complete multiple requests.
void nullify_request (dumpi_request rid)
void nullify_requests (int count, const dumpi_request *trace_requests)
int get_mpiid (dumpi_source id)
Get an mpiid.
int get_mpitag (dumpi_tag tag) const
Get an mpi tag.
void add_mpitype (dumpi_datatype id, MPI_Datatype mpit)
Add a new mpi type.
void erase_mpitype (dumpi_datatype id)
Erase the mapping for an mpi type. Does not erase built-in mpi types.
MPI_Datatype get_mpitype (dumpi_datatype id)
Access mpi type.
MPI_Datatype * get_mpitypes (int count, const dumpi_datatype *id)
Access mpi type.
void add_mpicomm (dumpi_comm id, MPI_Comm comm)
Add a new mpi comm.
void erase_mpicomm (dumpi_comm id)
Erase the mapping for an mpi comm. Does not erase built-in comms.
MPI_Comm get_mpicomm (dumpi_comm id)
Access an mpi communicator.
void add_mpigroup (dumpi_group id, MPI_Group comm)
Add a new mpi group.
void erase_mpigroup (dumpi_group id)
Erase the mapping for an mpi group. Does not erase built-in group.
MPI_Group get_mpigroup (dumpi_group id)
Access an mpi communicator.
void add_mpiop (dumpi_op id, MPI_Op op)
Add a new mpi op.
void erase_mpiop (dumpi_op id)
Erase the mapping for an mpi op. Does not erase built-in operations.
MPI_Op get_mpiop (dumpi_op id)
Access an mpi opunicator.
void set_callbacks ()
Define all callback routines.
Static Private Member Functions
static int on_MPI_Send (const dumpi_send *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Bsend (const dumpi_bsend *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Ssend (const dumpi_ssend *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Rsend (const dumpi_rsend *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Recv (const dumpi_recv *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Get_count (const dumpi_get_count *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Buffer_attach (const dumpi_buffer_attach *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Buffer_detach (const dumpi_buffer_detach *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Isend (const dumpi_isend *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Ibsend (const dumpi_ibsend *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Issend (const dumpi_issend *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Irsend (const dumpi_irsend *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Irecv (const dumpi_irecv *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Wait (const dumpi_wait *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Test (const dumpi_test *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Request_free (const dumpi_request_free *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Waitany (const dumpi_waitany *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int waitany_pessimistic (const dumpi_waitany *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
Variant implemenation of MPI_Waitany: Simulator waits for exactly the request matched by the trace file (pessimistic wait).
static int on_MPI_Testany (const dumpi_testany *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int testany_pessimistic (const dumpi_testany *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
Variant implementation of MPI_Testany: Simulator waits for exactly the request matched by the trace file (pessimistic test).
static int on_MPI_Waitall (const dumpi_waitall *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Testall (const dumpi_testall *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Waitsome (const dumpi_waitsome *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Testsome (const dumpi_testsome *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Iprobe (const dumpi_iprobe *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Probe (const dumpi_probe *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Cancel (const dumpi_cancel *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Test_cancelled (const dumpi_test_cancelled *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Send_init (const dumpi_send_init *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Bsend_init (const dumpi_bsend_init *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Ssend_init (const dumpi_ssend_init *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Rsend_init (const dumpi_rsend_init *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Recv_init (const dumpi_recv_init *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Start (const dumpi_start *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Startall (const dumpi_startall *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Sendrecv (const dumpi_sendrecv *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Sendrecv_replace (const dumpi_sendrecv_replace *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_contiguous (const dumpi_type_contiguous *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_vector (const dumpi_type_vector *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_hvector (const dumpi_type_hvector *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_indexed (const dumpi_type_indexed *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_hindexed (const dumpi_type_hindexed *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_struct (const dumpi_type_struct *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Address (const dumpi_address *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_extent (const dumpi_type_extent *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_size (const dumpi_type_size *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_lb (const dumpi_type_lb *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_ub (const dumpi_type_ub *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_commit (const dumpi_type_commit *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_free (const dumpi_type_free *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Get_elements (const dumpi_get_elements *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Pack (const dumpi_pack *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Unpack (const dumpi_unpack *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Pack_size (const dumpi_pack_size *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Barrier (const dumpi_barrier *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Bcast (const dumpi_bcast *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Gather (const dumpi_gather *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Gatherv (const dumpi_gatherv *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Scatter (const dumpi_scatter *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Scatterv (const dumpi_scatterv *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Allgather (const dumpi_allgather *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Allgatherv (const dumpi_allgatherv *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Alltoall (const dumpi_alltoall *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Alltoallv (const dumpi_alltoallv *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Reduce (const dumpi_reduce *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Op_create (const dumpi_op_create *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Op_free (const dumpi_op_free *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Allreduce (const dumpi_allreduce *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Reduce_scatter (const dumpi_reduce_scatter *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Scan (const dumpi_scan *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Group_size (const dumpi_group_size *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Group_rank (const dumpi_group_rank *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Group_translate_ranks (const dumpi_group_translate_ranks *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Group_compare (const dumpi_group_compare *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_group (const dumpi_comm_group *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Group_union (const dumpi_group_union *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Group_intersection (const dumpi_group_intersection *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Group_difference (const dumpi_group_difference *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Group_incl (const dumpi_group_incl *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Group_excl (const dumpi_group_excl *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Group_range_incl (const dumpi_group_range_incl *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Group_range_excl (const dumpi_group_range_excl *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Group_free (const dumpi_group_free *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_size (const dumpi_comm_size *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_rank (const dumpi_comm_rank *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_compare (const dumpi_comm_compare *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_dup (const dumpi_comm_dup *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_create (const dumpi_comm_create *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_split (const dumpi_comm_split *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_free (const dumpi_comm_free *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_test_inter (const dumpi_comm_test_inter *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_remote_size (const dumpi_comm_remote_size *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_remote_group (const dumpi_comm_remote_group *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Intercomm_create (const dumpi_intercomm_create *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Intercomm_merge (const dumpi_intercomm_merge *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Keyval_create (const dumpi_keyval_create *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Keyval_free (const dumpi_keyval_free *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Attr_put (const dumpi_attr_put *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Attr_get (const dumpi_attr_get *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Attr_delete (const dumpi_attr_delete *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Topo_test (const dumpi_topo_test *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Cart_create (const dumpi_cart_create *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Dims_create (const dumpi_dims_create *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Graph_create (const dumpi_graph_create *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Graphdims_get (const dumpi_graphdims_get *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Graph_get (const dumpi_graph_get *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Cartdim_get (const dumpi_cartdim_get *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Cart_get (const dumpi_cart_get *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Cart_rank (const dumpi_cart_rank *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Cart_coords (const dumpi_cart_coords *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Graph_neighbors_count (const dumpi_graph_neighbors_count *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Graph_neighbors (const dumpi_graph_neighbors *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Cart_shift (const dumpi_cart_shift *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Cart_sub (const dumpi_cart_sub *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Cart_map (const dumpi_cart_map *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Graph_map (const dumpi_graph_map *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Get_processor_name (const dumpi_get_processor_name *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Get_version (const dumpi_get_version *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Errhandler_create (const dumpi_errhandler_create *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Errhandler_set (const dumpi_errhandler_set *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Errhandler_get (const dumpi_errhandler_get *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Errhandler_free (const dumpi_errhandler_free *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Error_string (const dumpi_error_string *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Error_class (const dumpi_error_class *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Wtime (const dumpi_wtime *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Wtick (const dumpi_wtick *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Init (const dumpi_init *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Finalize (const dumpi_finalize *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Initialized (const dumpi_initialized *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Abort (const dumpi_abort *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Close_port (const dumpi_close_port *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_accept (const dumpi_comm_accept *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_connect (const dumpi_comm_connect *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_disconnect (const dumpi_comm_disconnect *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_get_parent (const dumpi_comm_get_parent *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_join (const dumpi_comm_join *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_spawn (const dumpi_comm_spawn *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_spawn_multiple (const dumpi_comm_spawn_multiple *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Lookup_name (const dumpi_lookup_name *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Open_port (const dumpi_open_port *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Publish_name (const dumpi_publish_name *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Unpublish_name (const dumpi_unpublish_name *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Accumulate (const dumpi_accumulate *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Get (const dumpi_get *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Put (const dumpi_put *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_complete (const dumpi_win_complete *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_create (const dumpi_win_create *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_fence (const dumpi_win_fence *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_free (const dumpi_win_free *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_get_group (const dumpi_win_get_group *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_lock (const dumpi_win_lock *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_post (const dumpi_win_post *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_start (const dumpi_win_start *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_test (const dumpi_win_test *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_unlock (const dumpi_win_unlock *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_wait (const dumpi_win_wait *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Alltoallw (const dumpi_alltoallw *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Exscan (const dumpi_exscan *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Add_error_class (const dumpi_add_error_class *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Add_error_code (const dumpi_add_error_code *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Add_error_string (const dumpi_add_error_string *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_call_errhandler (const dumpi_comm_call_errhandler *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_create_keyval (const dumpi_comm_create_keyval *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_delete_attr (const dumpi_comm_delete_attr *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_free_keyval (const dumpi_comm_free_keyval *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_get_attr (const dumpi_comm_get_attr *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_get_name (const dumpi_comm_get_name *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_set_attr (const dumpi_comm_set_attr *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_set_name (const dumpi_comm_set_name *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_call_errhandler (const dumpi_file_call_errhandler *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Grequest_complete (const dumpi_grequest_complete *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Grequest_start (const dumpi_grequest_start *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Init_thread (const dumpi_init_thread *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Is_thread_main (const dumpi_is_thread_main *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Query_thread (const dumpi_query_thread *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Status_set_cancelled (const dumpi_status_set_cancelled *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Status_set_elements (const dumpi_status_set_elements *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_create_keyval (const dumpi_type_create_keyval *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_delete_attr (const dumpi_type_delete_attr *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_dup (const dumpi_type_dup *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_free_keyval (const dumpi_type_free_keyval *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_get_attr (const dumpi_type_get_attr *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_get_contents (const dumpi_type_get_contents *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_get_envelope (const dumpi_type_get_envelope *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_get_name (const dumpi_type_get_name *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_set_attr (const dumpi_type_set_attr *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_set_name (const dumpi_type_set_name *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_match_size (const dumpi_type_match_size *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_call_errhandler (const dumpi_win_call_errhandler *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_create_keyval (const dumpi_win_create_keyval *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_delete_attr (const dumpi_win_delete_attr *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_free_keyval (const dumpi_win_free_keyval *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_get_attr (const dumpi_win_get_attr *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_get_name (const dumpi_win_get_name *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_set_attr (const dumpi_win_set_attr *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_set_name (const dumpi_win_set_name *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Alloc_mem (const dumpi_alloc_mem *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_create_errhandler (const dumpi_comm_create_errhandler *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_get_errhandler (const dumpi_comm_get_errhandler *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Comm_set_errhandler (const dumpi_comm_set_errhandler *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_create_errhandler (const dumpi_file_create_errhandler *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_get_errhandler (const dumpi_file_get_errhandler *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_set_errhandler (const dumpi_file_set_errhandler *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Finalized (const dumpi_finalized *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Free_mem (const dumpi_free_mem *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Get_address (const dumpi_get_address *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Info_create (const dumpi_info_create *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Info_delete (const dumpi_info_delete *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Info_dup (const dumpi_info_dup *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Info_free (const dumpi_info_free *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Info_get (const dumpi_info_get *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Info_get_nkeys (const dumpi_info_get_nkeys *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Info_get_nthkey (const dumpi_info_get_nthkey *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Info_get_valuelen (const dumpi_info_get_valuelen *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Info_set (const dumpi_info_set *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Pack_external (const dumpi_pack_external *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Pack_external_size (const dumpi_pack_external_size *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Request_get_status (const dumpi_request_get_status *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_create_darray (const dumpi_type_create_darray *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_create_hindexed (const dumpi_type_create_hindexed *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_create_hvector (const dumpi_type_create_hvector *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_create_indexed_block (const dumpi_type_create_indexed_block *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_create_resized (const dumpi_type_create_resized *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_create_struct (const dumpi_type_create_struct *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_create_subarray (const dumpi_type_create_subarray *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_get_extent (const dumpi_type_get_extent *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Type_get_true_extent (const dumpi_type_get_true_extent *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Unpack_external (const dumpi_unpack_external *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_create_errhandler (const dumpi_win_create_errhandler *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_get_errhandler (const dumpi_win_get_errhandler *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Win_set_errhandler (const dumpi_win_set_errhandler *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_open (const dumpi_file_open *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_close (const dumpi_file_close *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_delete (const dumpi_file_delete *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_set_size (const dumpi_file_set_size *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_preallocate (const dumpi_file_preallocate *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_get_size (const dumpi_file_get_size *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_get_group (const dumpi_file_get_group *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_get_amode (const dumpi_file_get_amode *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_set_info (const dumpi_file_set_info *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_get_info (const dumpi_file_get_info *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_set_view (const dumpi_file_set_view *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_get_view (const dumpi_file_get_view *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_read_at (const dumpi_file_read_at *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_read_at_all (const dumpi_file_read_at_all *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_write_at (const dumpi_file_write_at *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_write_at_all (const dumpi_file_write_at_all *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_iread_at (const dumpi_file_iread_at *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_iwrite_at (const dumpi_file_iwrite_at *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_read (const dumpi_file_read *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_read_all (const dumpi_file_read_all *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_write (const dumpi_file_write *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_write_all (const dumpi_file_write_all *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_iread (const dumpi_file_iread *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_iwrite (const dumpi_file_iwrite *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_seek (const dumpi_file_seek *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_get_position (const dumpi_file_get_position *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_get_byte_offset (const dumpi_file_get_byte_offset *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_read_shared (const dumpi_file_read_shared *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_write_shared (const dumpi_file_write_shared *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_iread_shared (const dumpi_file_iread_shared *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_iwrite_shared (const dumpi_file_iwrite_shared *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_read_ordered (const dumpi_file_read_ordered *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_write_ordered (const dumpi_file_write_ordered *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_seek_shared (const dumpi_file_seek_shared *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_get_position_shared (const dumpi_file_get_position_shared *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_read_at_all_begin (const dumpi_file_read_at_all_begin *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_read_at_all_end (const dumpi_file_read_at_all_end *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_write_at_all_begin (const dumpi_file_write_at_all_begin *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_write_at_all_end (const dumpi_file_write_at_all_end *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_read_all_begin (const dumpi_file_read_all_begin *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_read_all_end (const dumpi_file_read_all_end *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_write_all_begin (const dumpi_file_write_all_begin *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_write_all_end (const dumpi_file_write_all_end *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_read_ordered_begin (const dumpi_file_read_ordered_begin *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_read_ordered_end (const dumpi_file_read_ordered_end *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_write_ordered_begin (const dumpi_file_write_ordered_begin *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_write_ordered_end (const dumpi_file_write_ordered_end *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_get_type_extent (const dumpi_file_get_type_extent *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_Register_datarep (const dumpi_register_datarep *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_set_atomicity (const dumpi_file_set_atomicity *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_get_atomicity (const dumpi_file_get_atomicity *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPI_File_sync (const dumpi_file_sync *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPIO_Test (const dumpio_test *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPIO_Wait (const dumpio_wait *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPIO_Testall (const dumpio_testall *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPIO_Waitall (const dumpio_waitall *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPIO_Testany (const dumpio_testany *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPIO_Waitany (const dumpio_waitany *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPIO_Waitsome (const dumpio_waitsome *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
static int on_MPIO_Testsome (const dumpio_testsome *prm, uint16_t thread, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, void *uarg)
Private Attributes
parsedumpi * parent_
The parent for this callback-driven parser.
dumpi_clock trace_compute_start_
The dumpi timestamp at which we finished the most recent MPI call.
std::vector< int64_t > perfctr_compute_start_
The state of perfcounters when the most recent MPI call was finished.
request_map_t request_
mpitype_map_t mpitype_
MPI types. Gets pre-populated with all the standard datatypes.
dumpi_sizeof datatype_sizes_
Dumpi also (as of version 0.6 or so) contains datatype sizes.
mpicomm_map_t mpicomm_
MPI communicators.
mpigroup_map_t mpigroups_
mpiop_map_t mpiop_
MPI operations.
bool initialized_
Static Private Attributes
static libundumpi_callbacks * cbacks_
The callback struct we are using.
Friends
class parsedumpi_unit_test
int pass (void *uarg, const dumpi_time *cpu, const dumpi_time *wall, const dumpi_perfinfo *perf, const char *fxn)
int not_implemented (const char *fxn)
Detailed Description
Populate C-style callbacks for a libundumpi parser.
Definition at line 26 of file parsedumpi_callbacks.h.
Member Typedef Documentation
typedef std::map<dumpi_comm, MPI_Comm> sumi::parsedumpi_callbacks::mpicomm_map_t private
Map dumpi request identifiers to objects.
Definition at line 56 of file parsedumpi_callbacks.h.
typedef std::map<dumpi_group, MPI_Group> sumi::parsedumpi_callbacks::mpigroup_map_t private
Definition at line 58 of file parsedumpi_callbacks.h.
typedef std::map<dumpi_op, MPI_Op> sumi::parsedumpi_callbacks::mpiop_map_t private
Definition at line 59 of file parsedumpi_callbacks.h.
typedef std::map<dumpi_datatype, MPI_Datatype> sumi::parsedumpi_callbacks::mpitype_map_t private
Definition at line 60 of file parsedumpi_callbacks.h.
typedef std::map<dumpi_request, MPI_Request> sumi::parsedumpi_callbacks::request_map_t private
Definition at line 57 of file parsedumpi_callbacks.h.
Member Enumeration Documentation
enum sumi::parsedumpi_callbacks::if_unimplemented
Accepted actions to be taken for unimplemented functions.
These could be function pointers, but wrapping those in python leads to incredibly hard-to-read code.
Enumerator
IGNORE
PRINT
ABORT
Definition at line 37 of file parsedumpi_callbacks.h.
Constructor & Destructor Documentation
sumi::parsedumpi_callbacks::parsedumpi_callbacks (parsedumpi * parent)
Populate callbacks.
Member Function Documentation
void sumi::parsedumpi_callbacks::add_mpicomm (dumpi_comm id, MPI_Comm comm) private
Add a new mpi comm.
Referenced by get_mpitag().
void sumi::parsedumpi_callbacks::add_mpigroup (dumpi_group id, MPI_Group comm) private
Add a new mpi group.
Referenced by get_mpitag().
void sumi::parsedumpi_callbacks::add_mpiop (dumpi_op id, MPI_Op op) private
Add a new mpi op.
Referenced by get_mpitag().
void sumi::parsedumpi_callbacks::add_mpitype (dumpi_datatype id, MPI_Datatype mpit) private
Add a new mpi type.
Referenced by get_mpitag().
void sumi::parsedumpi_callbacks::complete_request (dumpi_request id) private
Remove a request from the map.
Referenced by getmpi().
template<typename Iter > void sumi::parsedumpi_callbacks::complete_requests (Iter begin, Iter end) private
Complete multiple requests.
Referenced by getmpi().
void sumi::parsedumpi_callbacks::end_mpi (const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf) private
Indicate that we have completed an MPI call.
Referenced by initialized().
void sumi::parsedumpi_callbacks::erase_mpicomm (dumpi_comm id) private
Erase the mapping for an mpi comm. Does not erase built-in comms.
Referenced by get_mpitag().
void sumi::parsedumpi_callbacks::erase_mpigroup (dumpi_group id) private
Erase the mapping for an mpi group. Does not erase built-in group.
Referenced by get_mpitag().
void sumi::parsedumpi_callbacks::erase_mpiop (dumpi_op id) private
Erase the mapping for an mpi op. Does not erase built-in operations.
Referenced by get_mpitag().
void sumi::parsedumpi_callbacks::erase_mpitype (dumpi_datatype id) private
Erase the mapping for an mpi type. Does not erase built-in mpi types.
Referenced by get_mpitag().
MPI_Comm sumi::parsedumpi_callbacks::get_mpicomm (dumpi_comm id) private
Access an mpi communicator.
Referenced by get_mpitag().
MPI_Group sumi::parsedumpi_callbacks::get_mpigroup (dumpi_group id) private
Access an mpi communicator.
Referenced by get_mpitag().
int sumi::parsedumpi_callbacks::get_mpiid (dumpi_source id) private
Get an mpiid.
Special handling for MPI_ROOT and MPI_ANY_SOURCE.
Referenced by getmpi().
MPI_Op sumi::parsedumpi_callbacks::get_mpiop (dumpi_op id) private
Access an mpi opunicator.
Referenced by get_mpitag().
int sumi::parsedumpi_callbacks::get_mpitag (dumpi_tag tag) const inline private
Get an mpi tag.
Special handling for MPI_ANY_TAG.
Definition at line 148 of file parsedumpi_callbacks.h.
References add_mpicomm(), add_mpigroup(), add_mpiop(), add_mpitype(), erase_mpicomm(), erase_mpigroup(), erase_mpiop(), erase_mpitype(), get_mpicomm(), get_mpigroup(), get_mpiop(), get_mpitype(), get_mpitypes(), on_MPI_Abort(), on_MPI_Accumulate(), on_MPI_Add_error_class(), on_MPI_Add_error_code(), on_MPI_Add_error_string(), on_MPI_Address(), on_MPI_Allgather(), on_MPI_Allgatherv(), on_MPI_Alloc_mem(), on_MPI_Allreduce(), on_MPI_Alltoall(), on_MPI_Alltoallv(), on_MPI_Alltoallw(), on_MPI_Attr_delete(), on_MPI_Attr_get(), on_MPI_Attr_put(), on_MPI_Barrier(), on_MPI_Bcast(), on_MPI_Bsend(), on_MPI_Bsend_init(), on_MPI_Buffer_attach(), on_MPI_Buffer_detach(), on_MPI_Cancel(), on_MPI_Cart_coords(), on_MPI_Cart_create(), on_MPI_Cart_get(), on_MPI_Cart_map(), on_MPI_Cart_rank(), on_MPI_Cart_shift(), on_MPI_Cart_sub(), on_MPI_Cartdim_get(), on_MPI_Close_port(), on_MPI_Comm_accept(), on_MPI_Comm_call_errhandler(), on_MPI_Comm_compare(), on_MPI_Comm_connect(), on_MPI_Comm_create(), on_MPI_Comm_create_errhandler(), on_MPI_Comm_create_keyval(), on_MPI_Comm_delete_attr(), on_MPI_Comm_disconnect(), on_MPI_Comm_dup(), on_MPI_Comm_free(), on_MPI_Comm_free_keyval(), on_MPI_Comm_get_attr(), on_MPI_Comm_get_errhandler(), on_MPI_Comm_get_name(), on_MPI_Comm_get_parent(), on_MPI_Comm_group(), on_MPI_Comm_join(), on_MPI_Comm_rank(), on_MPI_Comm_remote_group(), on_MPI_Comm_remote_size(), on_MPI_Comm_set_attr(), on_MPI_Comm_set_errhandler(), on_MPI_Comm_set_name(), on_MPI_Comm_size(), on_MPI_Comm_spawn(), on_MPI_Comm_spawn_multiple(), on_MPI_Comm_split(), on_MPI_Comm_test_inter(), on_MPI_Dims_create(), on_MPI_Errhandler_create(), on_MPI_Errhandler_free(), on_MPI_Errhandler_get(), on_MPI_Errhandler_set(), on_MPI_Error_class(), on_MPI_Error_string(), on_MPI_Exscan(), on_MPI_File_call_errhandler(), on_MPI_File_close(), on_MPI_File_create_errhandler(), on_MPI_File_delete(), on_MPI_File_get_amode(), on_MPI_File_get_atomicity(), on_MPI_File_get_byte_offset(), on_MPI_File_get_errhandler(), on_MPI_File_get_group(), on_MPI_File_get_info(), on_MPI_File_get_position(), on_MPI_File_get_position_shared(), on_MPI_File_get_size(), on_MPI_File_get_type_extent(), on_MPI_File_get_view(), on_MPI_File_iread(), on_MPI_File_iread_at(), on_MPI_File_iread_shared(), on_MPI_File_iwrite(), on_MPI_File_iwrite_at(), on_MPI_File_iwrite_shared(), on_MPI_File_open(), on_MPI_File_preallocate(), on_MPI_File_read(), on_MPI_File_read_all(), on_MPI_File_read_all_begin(), on_MPI_File_read_all_end(), on_MPI_File_read_at(), on_MPI_File_read_at_all(), on_MPI_File_read_at_all_begin(), on_MPI_File_read_at_all_end(), on_MPI_File_read_ordered(), on_MPI_File_read_ordered_begin(), on_MPI_File_read_ordered_end(), on_MPI_File_read_shared(), on_MPI_File_seek(), on_MPI_File_seek_shared(), on_MPI_File_set_atomicity(), on_MPI_File_set_errhandler(), on_MPI_File_set_info(), on_MPI_File_set_size(), on_MPI_File_set_view(), on_MPI_File_sync(), on_MPI_File_write(), on_MPI_File_write_all(), on_MPI_File_write_all_begin(), on_MPI_File_write_all_end(), on_MPI_File_write_at(), on_MPI_File_write_at_all(), on_MPI_File_write_at_all_begin(), on_MPI_File_write_at_all_end(), on_MPI_File_write_ordered(), on_MPI_File_write_ordered_begin(), on_MPI_File_write_ordered_end(), on_MPI_File_write_shared(), on_MPI_Finalize(), on_MPI_Finalized(), on_MPI_Free_mem(), on_MPI_Gather(), on_MPI_Gatherv(), on_MPI_Get(), on_MPI_Get_address(), on_MPI_Get_count(), on_MPI_Get_elements(), on_MPI_Get_processor_name(), on_MPI_Get_version(), on_MPI_Graph_create(), on_MPI_Graph_get(), on_MPI_Graph_map(), on_MPI_Graph_neighbors(), on_MPI_Graph_neighbors_count(), on_MPI_Graphdims_get(), on_MPI_Grequest_complete(), on_MPI_Grequest_start(), on_MPI_Group_compare(), on_MPI_Group_difference(), on_MPI_Group_excl(), on_MPI_Group_free(), on_MPI_Group_incl(), on_MPI_Group_intersection(), on_MPI_Group_range_excl(), on_MPI_Group_range_incl(), on_MPI_Group_rank(), on_MPI_Group_size(), on_MPI_Group_translate_ranks(), on_MPI_Group_union(), on_MPI_Ibsend(), on_MPI_Info_create(), on_MPI_Info_delete(), on_MPI_Info_dup(), on_MPI_Info_free(), on_MPI_Info_get(), on_MPI_Info_get_nkeys(), on_MPI_Info_get_nthkey(), on_MPI_Info_get_valuelen(), on_MPI_Info_set(), on_MPI_Init(), on_MPI_Init_thread(), on_MPI_Initialized(), on_MPI_Intercomm_create(), on_MPI_Intercomm_merge(), on_MPI_Iprobe(), on_MPI_Irecv(), on_MPI_Irsend(), on_MPI_Is_thread_main(), on_MPI_Isend(), on_MPI_Issend(), on_MPI_Keyval_create(), on_MPI_Keyval_free(), on_MPI_Lookup_name(), on_MPI_Op_create(), on_MPI_Op_free(), on_MPI_Open_port(), on_MPI_Pack(), on_MPI_Pack_external(), on_MPI_Pack_external_size(), on_MPI_Pack_size(), on_MPI_Probe(), on_MPI_Publish_name(), on_MPI_Put(), on_MPI_Query_thread(), on_MPI_Recv(), on_MPI_Recv_init(), on_MPI_Reduce(), on_MPI_Reduce_scatter(), on_MPI_Register_datarep(), on_MPI_Request_free(), on_MPI_Request_get_status(), on_MPI_Rsend(), on_MPI_Rsend_init(), on_MPI_Scan(), on_MPI_Scatter(), on_MPI_Scatterv(), on_MPI_Send(), on_MPI_Send_init(), on_MPI_Sendrecv(), on_MPI_Sendrecv_replace(), on_MPI_Ssend(), on_MPI_Ssend_init(), on_MPI_Start(), on_MPI_Startall(), on_MPI_Status_set_cancelled(), on_MPI_Status_set_elements(), on_MPI_Test(), on_MPI_Test_cancelled(), on_MPI_Testall(), on_MPI_Testany(), on_MPI_Testsome(), on_MPI_Topo_test(), on_MPI_Type_commit(), on_MPI_Type_contiguous(), on_MPI_Type_create_darray(), on_MPI_Type_create_hindexed(), on_MPI_Type_create_hvector(), on_MPI_Type_create_indexed_block(), on_MPI_Type_create_keyval(), on_MPI_Type_create_resized(), on_MPI_Type_create_struct(), on_MPI_Type_create_subarray(), on_MPI_Type_delete_attr(), on_MPI_Type_dup(), on_MPI_Type_extent(), on_MPI_Type_free(), on_MPI_Type_free_keyval(), on_MPI_Type_get_attr(), on_MPI_Type_get_contents(), on_MPI_Type_get_envelope(), on_MPI_Type_get_extent(), on_MPI_Type_get_name(), on_MPI_Type_get_true_extent(), on_MPI_Type_hindexed(), on_MPI_Type_hvector(), on_MPI_Type_indexed(), on_MPI_Type_lb(), on_MPI_Type_match_size(), on_MPI_Type_set_attr(), on_MPI_Type_set_name(), on_MPI_Type_size(), on_MPI_Type_struct(), on_MPI_Type_ub(), on_MPI_Type_vector(), on_MPI_Unpack(), on_MPI_Unpack_external(), on_MPI_Unpublish_name(), on_MPI_Wait(), on_MPI_Waitall(), on_MPI_Waitany(), on_MPI_Waitsome(), on_MPI_Win_call_errhandler(), on_MPI_Win_complete(), on_MPI_Win_create(), on_MPI_Win_create_errhandler(), on_MPI_Win_create_keyval(), on_MPI_Win_delete_attr(), on_MPI_Win_fence(), on_MPI_Win_free(), on_MPI_Win_free_keyval(), on_MPI_Win_get_attr(), on_MPI_Win_get_errhandler(), on_MPI_Win_get_group(), on_MPI_Win_get_name(), on_MPI_Win_lock(), on_MPI_Win_post(), on_MPI_Win_set_attr(), on_MPI_Win_set_errhandler(), on_MPI_Win_set_name(), on_MPI_Win_start(), on_MPI_Win_test(), on_MPI_Win_unlock(), on_MPI_Win_wait(), on_MPI_Wtick(), on_MPI_Wtime(), on_MPIO_Test(), on_MPIO_Testall(), on_MPIO_Testany(), on_MPIO_Testsome(), on_MPIO_Wait(), on_MPIO_Waitall(), on_MPIO_Waitany(), on_MPIO_Waitsome(), set_callbacks(), testany_pessimistic(), and waitany_pessimistic().
MPI_Datatype sumi::parsedumpi_callbacks::get_mpitype (dumpi_datatype id) private
Access mpi type.
Exceptions
sprockit::value_error if no mapping exists for this datatype.
Referenced by get_mpitag().
MPI_Datatype* sumi::parsedumpi_callbacks::get_mpitypes (int count, const dumpi_datatype * id) private
Access mpi type.
Exceptions
sprockit::value_error if no mapping exists for this datatype.
Referenced by get_mpitag().
MPI_Request* sumi::parsedumpi_callbacks::get_request_ptr (dumpi_request id) private
Get a single request handle.
Referenced by getmpi().
MPI_Request* sumi::parsedumpi_callbacks::get_requests (int count, const dumpi_request * dumpireq) private
Get a group of request handles.
Referenced by getmpi().
mpi_api* sumi::parsedumpi_callbacks::getmpi () inline private
Access the mpiapi.
Definition at line 118 of file parsedumpi_callbacks.h.
References complete_request(), complete_requests(), get_mpiid(), get_request_ptr(), get_requests(), sumi::parsedumpi::mpi(), nullify_request(), nullify_requests(), and store_request().
void sumi::parsedumpi_callbacks::init_maps () private
Initialize maps (datatypes etc.). Called at constrution.
Referenced by initialized().
bool sumi::parsedumpi_callbacks::initialized () const inline
Definition at line 90 of file parsedumpi_callbacks.h.
References end_mpi(), init_maps(), initialized_, parse_stream(), and start_mpi().
void sumi::parsedumpi_callbacks::nullify_request (dumpi_request rid) private
Referenced by getmpi().
void sumi::parsedumpi_callbacks::nullify_requests (int count, const dumpi_request * trace_requests) private
Referenced by getmpi().
static int sumi::parsedumpi_callbacks::on_MPI_Abort (const dumpi_abort * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Accumulate (const dumpi_accumulate * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Add_error_class (const dumpi_add_error_class * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Add_error_code (const dumpi_add_error_code * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Add_error_string (const dumpi_add_error_string * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Address (const dumpi_address * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Allgather (const dumpi_allgather * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Allgatherv (const dumpi_allgatherv * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Alloc_mem (const dumpi_alloc_mem * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Allreduce (const dumpi_allreduce * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Alltoall (const dumpi_alltoall * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Alltoallv (const dumpi_alltoallv * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Alltoallw (const dumpi_alltoallw * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Attr_delete (const dumpi_attr_delete * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Attr_get (const dumpi_attr_get * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Attr_put (const dumpi_attr_put * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Barrier (const dumpi_barrier * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Bcast (const dumpi_bcast * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Bsend (const dumpi_bsend * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Bsend_init (const dumpi_bsend_init * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Buffer_attach (const dumpi_buffer_attach * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Buffer_detach (const dumpi_buffer_detach * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Cancel (const dumpi_cancel * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Cart_coords (const dumpi_cart_coords * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Cart_create (const dumpi_cart_create * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Cart_get (const dumpi_cart_get * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Cart_map (const dumpi_cart_map * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Cart_rank (const dumpi_cart_rank * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Cart_shift (const dumpi_cart_shift * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Cart_sub (const dumpi_cart_sub * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Cartdim_get (const dumpi_cartdim_get * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Close_port (const dumpi_close_port * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_accept (const dumpi_comm_accept * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_call_errhandler (const dumpi_comm_call_errhandler * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_compare (const dumpi_comm_compare * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_connect (const dumpi_comm_connect * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_create (const dumpi_comm_create * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_create_errhandler (const dumpi_comm_create_errhandler * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_create_keyval (const dumpi_comm_create_keyval * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_delete_attr (const dumpi_comm_delete_attr * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_disconnect (const dumpi_comm_disconnect * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_dup (const dumpi_comm_dup * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_free (const dumpi_comm_free * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_free_keyval (const dumpi_comm_free_keyval * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_get_attr (const dumpi_comm_get_attr * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_get_errhandler (const dumpi_comm_get_errhandler * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_get_name (const dumpi_comm_get_name * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_get_parent (const dumpi_comm_get_parent * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_group (const dumpi_comm_group * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_join (const dumpi_comm_join * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_rank (const dumpi_comm_rank * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_remote_group (const dumpi_comm_remote_group * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_remote_size (const dumpi_comm_remote_size * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_set_attr (const dumpi_comm_set_attr * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_set_errhandler (const dumpi_comm_set_errhandler * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_set_name (const dumpi_comm_set_name * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_size (const dumpi_comm_size * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_spawn (const dumpi_comm_spawn * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_spawn_multiple (const dumpi_comm_spawn_multiple * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_split (const dumpi_comm_split * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Comm_test_inter (const dumpi_comm_test_inter * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Dims_create (const dumpi_dims_create * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Errhandler_create (const dumpi_errhandler_create * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Errhandler_free (const dumpi_errhandler_free * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Errhandler_get (const dumpi_errhandler_get * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Errhandler_set (const dumpi_errhandler_set * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Error_class (const dumpi_error_class * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Error_string (const dumpi_error_string * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Exscan (const dumpi_exscan * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_call_errhandler (const dumpi_file_call_errhandler * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_close (const dumpi_file_close * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_create_errhandler (const dumpi_file_create_errhandler * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_delete (const dumpi_file_delete * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_get_amode (const dumpi_file_get_amode * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_get_atomicity (const dumpi_file_get_atomicity * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_get_byte_offset (const dumpi_file_get_byte_offset * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_get_errhandler (const dumpi_file_get_errhandler * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_get_group (const dumpi_file_get_group * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_get_info (const dumpi_file_get_info * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_get_position (const dumpi_file_get_position * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_get_position_shared (const dumpi_file_get_position_shared * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_get_size (const dumpi_file_get_size * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_get_type_extent (const dumpi_file_get_type_extent * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_get_view (const dumpi_file_get_view * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_iread (const dumpi_file_iread * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_iread_at (const dumpi_file_iread_at * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_iread_shared (const dumpi_file_iread_shared * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_iwrite (const dumpi_file_iwrite * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_iwrite_at (const dumpi_file_iwrite_at * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_iwrite_shared (const dumpi_file_iwrite_shared * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_open (const dumpi_file_open * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_preallocate (const dumpi_file_preallocate * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_read (const dumpi_file_read * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_read_all (const dumpi_file_read_all * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_read_all_begin (const dumpi_file_read_all_begin * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_read_all_end (const dumpi_file_read_all_end * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_read_at (const dumpi_file_read_at * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_read_at_all (const dumpi_file_read_at_all * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_read_at_all_begin (const dumpi_file_read_at_all_begin * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_read_at_all_end (const dumpi_file_read_at_all_end * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_read_ordered (const dumpi_file_read_ordered * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_read_ordered_begin (const dumpi_file_read_ordered_begin * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_read_ordered_end (const dumpi_file_read_ordered_end * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_read_shared (const dumpi_file_read_shared * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_seek (const dumpi_file_seek * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_seek_shared (const dumpi_file_seek_shared * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_set_atomicity (const dumpi_file_set_atomicity * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_set_errhandler (const dumpi_file_set_errhandler * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_set_info (const dumpi_file_set_info * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_set_size (const dumpi_file_set_size * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_set_view (const dumpi_file_set_view * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_sync (const dumpi_file_sync * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_write (const dumpi_file_write * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_write_all (const dumpi_file_write_all * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_write_all_begin (const dumpi_file_write_all_begin * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_write_all_end (const dumpi_file_write_all_end * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_write_at (const dumpi_file_write_at * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_write_at_all (const dumpi_file_write_at_all * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_write_at_all_begin (const dumpi_file_write_at_all_begin * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_write_at_all_end (const dumpi_file_write_at_all_end * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_write_ordered (const dumpi_file_write_ordered * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_write_ordered_begin (const dumpi_file_write_ordered_begin * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_write_ordered_end (const dumpi_file_write_ordered_end * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_File_write_shared (const dumpi_file_write_shared * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Finalize (const dumpi_finalize * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Finalized (const dumpi_finalized * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Free_mem (const dumpi_free_mem * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Gather (const dumpi_gather * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Gatherv (const dumpi_gatherv * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Get (const dumpi_get * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Get_address (const dumpi_get_address * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Get_count (const dumpi_get_count * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Get_elements (const dumpi_get_elements * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Get_processor_name (const dumpi_get_processor_name * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Get_version (const dumpi_get_version * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Graph_create (const dumpi_graph_create * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Graph_get (const dumpi_graph_get * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Graph_map (const dumpi_graph_map * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Graph_neighbors (const dumpi_graph_neighbors * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Graph_neighbors_count (const dumpi_graph_neighbors_count * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Graphdims_get (const dumpi_graphdims_get * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Grequest_complete (const dumpi_grequest_complete * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Grequest_start (const dumpi_grequest_start * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Group_compare (const dumpi_group_compare * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Group_difference (const dumpi_group_difference * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Group_excl (const dumpi_group_excl * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Group_free (const dumpi_group_free * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Group_incl (const dumpi_group_incl * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Group_intersection (const dumpi_group_intersection * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Group_range_excl (const dumpi_group_range_excl * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Group_range_incl (const dumpi_group_range_incl * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Group_rank (const dumpi_group_rank * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Group_size (const dumpi_group_size * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Group_translate_ranks (const dumpi_group_translate_ranks * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Group_union (const dumpi_group_union * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Ibsend (const dumpi_ibsend * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Info_create (const dumpi_info_create * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Info_delete (const dumpi_info_delete * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Info_dup (const dumpi_info_dup * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Info_free (const dumpi_info_free * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Info_get (const dumpi_info_get * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Info_get_nkeys (const dumpi_info_get_nkeys * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Info_get_nthkey (const dumpi_info_get_nthkey * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Info_get_valuelen (const dumpi_info_get_valuelen * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Info_set (const dumpi_info_set * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Init (const dumpi_init * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Init_thread (const dumpi_init_thread * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Initialized (const dumpi_initialized * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Intercomm_create (const dumpi_intercomm_create * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Intercomm_merge (const dumpi_intercomm_merge * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Iprobe (const dumpi_iprobe * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Irecv (const dumpi_irecv * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Irsend (const dumpi_irsend * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Is_thread_main (const dumpi_is_thread_main * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Isend (const dumpi_isend * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Issend (const dumpi_issend * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Keyval_create (const dumpi_keyval_create * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Keyval_free (const dumpi_keyval_free * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Lookup_name (const dumpi_lookup_name * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Op_create (const dumpi_op_create * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Op_free (const dumpi_op_free * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Open_port (const dumpi_open_port * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Pack (const dumpi_pack * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Pack_external (const dumpi_pack_external * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Pack_external_size (const dumpi_pack_external_size * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Pack_size (const dumpi_pack_size * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Probe (const dumpi_probe * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Publish_name (const dumpi_publish_name * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Put (const dumpi_put * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Query_thread (const dumpi_query_thread * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Recv (const dumpi_recv * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Recv_init (const dumpi_recv_init * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Reduce (const dumpi_reduce * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Reduce_scatter (const dumpi_reduce_scatter * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Register_datarep (const dumpi_register_datarep * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Request_free (const dumpi_request_free * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Request_get_status (const dumpi_request_get_status * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Rsend (const dumpi_rsend * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Rsend_init (const dumpi_rsend_init * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Scan (const dumpi_scan * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Scatter (const dumpi_scatter * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Scatterv (const dumpi_scatterv * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Send (const dumpi_send * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Send_init (const dumpi_send_init * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Sendrecv (const dumpi_sendrecv * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Sendrecv_replace (const dumpi_sendrecv_replace * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Ssend (const dumpi_ssend * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Ssend_init (const dumpi_ssend_init * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Start (const dumpi_start * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Startall (const dumpi_startall * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Status_set_cancelled (const dumpi_status_set_cancelled * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Status_set_elements (const dumpi_status_set_elements * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Test (const dumpi_test * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Test_cancelled (const dumpi_test_cancelled * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Testall (const dumpi_testall * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Testany (const dumpi_testany * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Testsome (const dumpi_testsome * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Topo_test (const dumpi_topo_test * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_commit (const dumpi_type_commit * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_contiguous (const dumpi_type_contiguous * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_create_darray (const dumpi_type_create_darray * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_create_hindexed (const dumpi_type_create_hindexed * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_create_hvector (const dumpi_type_create_hvector * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_create_indexed_block (const dumpi_type_create_indexed_block * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_create_keyval (const dumpi_type_create_keyval * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_create_resized (const dumpi_type_create_resized * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_create_struct (const dumpi_type_create_struct * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_create_subarray (const dumpi_type_create_subarray * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_delete_attr (const dumpi_type_delete_attr * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_dup (const dumpi_type_dup * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_extent (const dumpi_type_extent * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_free (const dumpi_type_free * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_free_keyval (const dumpi_type_free_keyval * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_get_attr (const dumpi_type_get_attr * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_get_contents (const dumpi_type_get_contents * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_get_envelope (const dumpi_type_get_envelope * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_get_extent (const dumpi_type_get_extent * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_get_name (const dumpi_type_get_name * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_get_true_extent (const dumpi_type_get_true_extent * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_hindexed (const dumpi_type_hindexed * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_hvector (const dumpi_type_hvector * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_indexed (const dumpi_type_indexed * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_lb (const dumpi_type_lb * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_match_size (const dumpi_type_match_size * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_set_attr (const dumpi_type_set_attr * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_set_name (const dumpi_type_set_name * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_size (const dumpi_type_size * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_struct (const dumpi_type_struct * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_ub (const dumpi_type_ub * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Type_vector (const dumpi_type_vector * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Unpack (const dumpi_unpack * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Unpack_external (const dumpi_unpack_external * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Unpublish_name (const dumpi_unpublish_name * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Wait (const dumpi_wait * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Waitall (const dumpi_waitall * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Waitany (const dumpi_waitany * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Waitsome (const dumpi_waitsome * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_call_errhandler (const dumpi_win_call_errhandler * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_complete (const dumpi_win_complete * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_create (const dumpi_win_create * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_create_errhandler (const dumpi_win_create_errhandler * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_create_keyval (const dumpi_win_create_keyval * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_delete_attr (const dumpi_win_delete_attr * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_fence (const dumpi_win_fence * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_free (const dumpi_win_free * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_free_keyval (const dumpi_win_free_keyval * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_get_attr (const dumpi_win_get_attr * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_get_errhandler (const dumpi_win_get_errhandler * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_get_group (const dumpi_win_get_group * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_get_name (const dumpi_win_get_name * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_lock (const dumpi_win_lock * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_post (const dumpi_win_post * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_set_attr (const dumpi_win_set_attr * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_set_errhandler (const dumpi_win_set_errhandler * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_set_name (const dumpi_win_set_name * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_start (const dumpi_win_start * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_test (const dumpi_win_test * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_unlock (const dumpi_win_unlock * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Win_wait (const dumpi_win_wait * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Wtick (const dumpi_wtick * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPI_Wtime (const dumpi_wtime * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPIO_Test (const dumpio_test * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPIO_Testall (const dumpio_testall * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPIO_Testany (const dumpio_testany * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPIO_Testsome (const dumpio_testsome * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPIO_Wait (const dumpio_wait * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPIO_Waitall (const dumpio_waitall * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPIO_Waitany (const dumpio_waitany * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::on_MPIO_Waitsome (const dumpio_waitsome * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Referenced by get_mpitag().
void sumi::parsedumpi_callbacks::parse_stream (const std::string & filename, bool print_progress, double percent_terminate)
Start parsing.
parse_stream
Parameters
filename
print_progress Whether to print progress - usually only true for rank 0
percent_terminate -1 indicates run to end, otherwise terminate at some percent - only rank 0 shoudl cause termination
Referenced by initialized().
void sumi::parsedumpi_callbacks::set_callbacks () private
Define all callback routines.
Referenced by get_mpitag().
void sumi::parsedumpi_callbacks::set_initialized (bool flag) inline
Definition at line 85 of file parsedumpi_callbacks.h.
void sumi::parsedumpi_callbacks::start_mpi (const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf) private
Indicate that we are starting an MPI call.
Referenced by initialized().
void sumi::parsedumpi_callbacks::store_request (dumpi_request id, MPI_Request request) private
Store a single request handle.
Referenced by getmpi().
static int sumi::parsedumpi_callbacks::testany_pessimistic (const dumpi_testany * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Variant implementation of MPI_Testany: Simulator waits for exactly the request matched by the trace file (pessimistic test).
Referenced by get_mpitag().
static int sumi::parsedumpi_callbacks::waitany_pessimistic (const dumpi_waitany * prm, uint16_t thread, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, void * uarg) static private
Variant implemenation of MPI_Waitany: Simulator waits for exactly the request matched by the trace file (pessimistic wait).
Referenced by get_mpitag().
Friends And Related Function Documentation
int not_implemented (const char * fxn) friend
friend class parsedumpi_unit_test friend
Definition at line 28 of file parsedumpi_callbacks.h.
int pass (void * uarg, const dumpi_time * cpu, const dumpi_time * wall, const dumpi_perfinfo * perf, const char * fxn) friend
Member Data Documentation
libundumpi_callbacks* sumi::parsedumpi_callbacks::cbacks_ static private
The callback struct we are using.
This is pretty big (2.4 K), but at least it can be shared.
Definition at line 47 of file parsedumpi_callbacks.h.
dumpi_sizeof sumi::parsedumpi_callbacks::datatype_sizes_ private
Dumpi also (as of version 0.6 or so) contains datatype sizes.
Definition at line 68 of file parsedumpi_callbacks.h.
bool sumi::parsedumpi_callbacks::initialized_ private
Definition at line 78 of file parsedumpi_callbacks.h.
Referenced by initialized().
mpicomm_map_t sumi::parsedumpi_callbacks::mpicomm_ private
MPI communicators.
Definition at line 71 of file parsedumpi_callbacks.h.
mpigroup_map_t sumi::parsedumpi_callbacks::mpigroups_ private
Definition at line 73 of file parsedumpi_callbacks.h.
mpiop_map_t sumi::parsedumpi_callbacks::mpiop_ private
MPI operations.
Definition at line 76 of file parsedumpi_callbacks.h.
mpitype_map_t sumi::parsedumpi_callbacks::mpitype_ private
MPI types. Gets pre-populated with all the standard datatypes.
Definition at line 65 of file parsedumpi_callbacks.h.
parsedumpi* sumi::parsedumpi_callbacks::parent_ private
The parent for this callback-driven parser.
Can be safely held by raw pointer, since the parent holds this object by value.
Definition at line 43 of file parsedumpi_callbacks.h.
std::vector<int64_t> sumi::parsedumpi_callbacks::perfctr_compute_start_ private
The state of perfcounters when the most recent MPI call was finished.
Definition at line 53 of file parsedumpi_callbacks.h.
request_map_t sumi::parsedumpi_callbacks::request_ private
Definition at line 62 of file parsedumpi_callbacks.h.
dumpi_clock sumi::parsedumpi_callbacks::trace_compute_start_ private
The dumpi timestamp at which we finished the most recent MPI call.
Definition at line 50 of file parsedumpi_callbacks.h.
The documentation for this class was generated from the following file:
sstmac/skeletons/sumi_undumpi/parsedumpi_callbacks.h