SST/macro: sstmac::sw::cpuset_compute_scheduler Class Reference
sstmac::sw::cpuset_compute_scheduler Class Reference
#include <cpuset_compute_scheduler.h>
Public Member Functions
cpuset_compute_scheduler ()
void configure (int ncore, int nsocket)
void reserve_core (thread *thr)
void release_core (thread *thr)
compute_scheduler * clone (operating_system *os) const
Protected Member Functions
void clone_into (cpuset_compute_scheduler *cln) const
Private Member Functions
void allocate_core (int core)
void deallocate_core (int core)
Static Private Member Functions
static int available_core (int ncore, uint64_t cpumask)
Private Attributes
uint64_t available_cores_
std::list< thread * > pending_threads_
Detailed Description
Definition at line 9 of file cpuset_compute_scheduler.h.
Constructor & Destructor Documentation
sstmac::sw::cpuset_compute_scheduler::cpuset_compute_scheduler () inline
Definition at line 12 of file cpuset_compute_scheduler.h.
References configure(), release_core(), and reserve_core().
Referenced by clone().
Member Function Documentation
void sstmac::sw::cpuset_compute_scheduler::allocate_core (int core) inline private
Definition at line 40 of file cpuset_compute_scheduler.h.
References available_cores_.
static int sstmac::sw::cpuset_compute_scheduler::available_core (int ncore, uint64_t cpumask) static private
Referenced by clone_into().
compute_scheduler* sstmac::sw::cpuset_compute_scheduler::clone (operating_system * os) const inline
Definition at line 23 of file cpuset_compute_scheduler.h.
References clone_into(), and cpuset_compute_scheduler().
void sstmac::sw::cpuset_compute_scheduler::clone_into (cpuset_compute_scheduler * cln) const inline protected
Definition at line 32 of file cpuset_compute_scheduler.h.
References available_core(), and available_cores_.
Referenced by clone().
void sstmac::sw::cpuset_compute_scheduler::configure (int ncore, int nsocket)
Referenced by cpuset_compute_scheduler().
void sstmac::sw::cpuset_compute_scheduler::deallocate_core (int core) inline private
Definition at line 44 of file cpuset_compute_scheduler.h.
References available_cores_.
void sstmac::sw::cpuset_compute_scheduler::release_core (thread * thr)
Referenced by cpuset_compute_scheduler().
void sstmac::sw::cpuset_compute_scheduler::reserve_core (thread * thr)
Referenced by cpuset_compute_scheduler().
Member Data Documentation
uint64_t sstmac::sw::cpuset_compute_scheduler::available_cores_ private
Definition at line 49 of file cpuset_compute_scheduler.h.
Referenced by allocate_core(), clone_into(), and deallocate_core().
std::list<thread*> sstmac::sw::cpuset_compute_scheduler::pending_threads_ private
Definition at line 50 of file cpuset_compute_scheduler.h.
The documentation for this class was generated from the following file:
sstmac/software/process/cpuset_compute_scheduler.h