SST/macro: sstmac::sw::sstmac_global_builtin_arr< T, N > Class Template Reference
sstmac::sw::sstmac_global_builtin_arr< T, N > Class Template Reference
#include <global_builtin_array.h>
Public Types
typedef val_map::const_iterator const_iterator
typedef T static_arr [N]
Public Member Functions
sstmac_global_builtin_arr ()
sstmac_global_builtin_arr (static_arr init)
sstmac_global_builtin_arr (const sstmac_global_builtin_arr< T, N > &other)
virtual ~sstmac_global_builtin_arr ()
void print_all () const
virtual T * get_val () const
virtual std::string to_string () const
template<typename U >
T * operator= (const U &b)
template<typename U >
bool operator== (const U &b) const
template<typename U >
bool operator!= (const U &b) const
template<typename U >
operator U ()
T * operator++ (int dummy)
T * operator-- (int dummy)
T * operator++ ()
T * operator-- ()
operator void * () const
operator double * () const
operator int * () const
operator bool * () const
operator size_t * () const
operator long * () const
operator long long * () const
template<typename U >
T * operator+ (const U &b) const
template<typename U >
T * operator- (const U &b) const
T & operator* ()
T & operator[] (int idx)
T & operator[] (long idx)
T ** operator& () const
template<typename U >
bool operator> (const U &b)
template<typename U >
bool operator< (const U &b)
const_iterator begin () const
const_iterator end () const
Private Types
typedef spkt_unordered_map
< long, T * > val_map
Private Attributes
val_map vals_
T * init_
Additional Inherited Members
Protected Member Functions inherited from sstmac::sw::sstmac_global
process_context current_context () const
Detailed Description
template<typename T, int N>
class sstmac::sw::sstmac_global_builtin_arr< T, N >
Definition at line 22 of file global_builtin_array.h.
Member Typedef Documentation
template<typename T, int N> typedef val_map::const_iterator sstmac::sw::sstmac_global_builtin_arr< T, N >::const_iterator
Definition at line 31 of file global_builtin_array.h.
template<typename T, int N> typedef T sstmac::sw::sstmac_global_builtin_arr< T, N >::static_arr[N]
Definition at line 32 of file global_builtin_array.h.
template<typename T, int N> typedef spkt_unordered_map<long, T*> sstmac::sw::sstmac_global_builtin_arr< T, N >::val_map private
Definition at line 26 of file global_builtin_array.h.
Constructor & Destructor Documentation
template<typename T, int N> sstmac::sw::sstmac_global_builtin_arr< T, N >::sstmac_global_builtin_arr () inline explicit
Definition at line 35 of file global_builtin_array.h.
template<typename T, int N> sstmac::sw::sstmac_global_builtin_arr< T, N >::sstmac_global_builtin_arr (static_arr init) inline explicit
Definition at line 40 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::init_, and memcpy().
template<typename T, int N> sstmac::sw::sstmac_global_builtin_arr< T, N >::sstmac_global_builtin_arr (const sstmac_global_builtin_arr< T, N > & other) inline
Definition at line 45 of file global_builtin_array.h.
References spkt_throw_printf.
template<typename T, int N> virtual sstmac::sw::sstmac_global_builtin_arr< T, N >::~sstmac_global_builtin_arr () inline virtual
Definition at line 51 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::init_, and sstmac::sw::sstmac_global_builtin_arr< T, N >::vals_.
Member Function Documentation
template<typename T, int N> const_iterator sstmac::sw::sstmac_global_builtin_arr< T, N >::begin () const inline
Definition at line 232 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::vals_.
template<typename T, int N> const_iterator sstmac::sw::sstmac_global_builtin_arr< T, N >::end () const inline
Definition at line 236 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::vals_.
template<typename T, int N> virtual T* sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val () const inline virtual
Definition at line 68 of file global_builtin_array.h.
References sstmac::sw::sstmac_global::current_context(), sstmac::sw::sstmac_global_builtin_arr< T, N >::init_, memcpy(), sstmac::sw::process_context::none, spkt_throw_printf, and sstmac::sw::sstmac_global_builtin_arr< T, N >::vals_.
Referenced by sstmac::sw::sstmac_global_builtin_arr< T, N >::operator bool *(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator double *(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator int *(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator long *(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator long long *(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator size_t *(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator U(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator void *(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator!=(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator&(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator*(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator+(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator++(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator-(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator--(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator<(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator=(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator==(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator>(), sstmac::sw::sstmac_global_builtin_arr< T, N >::operator[](), and sstmac::sw::sstmac_global_builtin_arr< T, N >::to_string().
template<typename T, int N> sstmac::sw::sstmac_global_builtin_arr< T, N >::operator bool * () const inline
Definition at line 163 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> sstmac::sw::sstmac_global_builtin_arr< T, N >::operator double * () const inline
Definition at line 155 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> sstmac::sw::sstmac_global_builtin_arr< T, N >::operator int * () const inline
Definition at line 159 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> sstmac::sw::sstmac_global_builtin_arr< T, N >::operator long * () const inline
Definition at line 171 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> sstmac::sw::sstmac_global_builtin_arr< T, N >::operator long long * () const inline
Definition at line 175 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> sstmac::sw::sstmac_global_builtin_arr< T, N >::operator size_t * () const inline
Definition at line 167 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> template<typename U > sstmac::sw::sstmac_global_builtin_arr< T, N >::operator U () inline
Definition at line 122 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> sstmac::sw::sstmac_global_builtin_arr< T, N >::operator void * () const inline
Definition at line 151 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> template<typename U > bool sstmac::sw::sstmac_global_builtin_arr< T, N >::operator!= (const U & b) const inline
Definition at line 115 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> T** sstmac::sw::sstmac_global_builtin_arr< T, N >::operator& () const inline
Definition at line 211 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> T& sstmac::sw::sstmac_global_builtin_arr< T, N >::operator* () inline
Definition at line 194 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> template<typename U > T* sstmac::sw::sstmac_global_builtin_arr< T, N >::operator+ (const U & b) const inline
Definition at line 181 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> T* sstmac::sw::sstmac_global_builtin_arr< T, N >::operator++ (int dummy) inline
Definition at line 128 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> T* sstmac::sw::sstmac_global_builtin_arr< T, N >::operator++ () inline
Definition at line 140 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> template<typename U > T* sstmac::sw::sstmac_global_builtin_arr< T, N >::operator- (const U & b) const inline
Definition at line 187 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> T* sstmac::sw::sstmac_global_builtin_arr< T, N >::operator-- (int dummy) inline
Definition at line 134 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> T* sstmac::sw::sstmac_global_builtin_arr< T, N >::operator-- () inline
Definition at line 146 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> template<typename U > bool sstmac::sw::sstmac_global_builtin_arr< T, N >::operator< (const U & b) inline
Definition at line 225 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> template<typename U > T* sstmac::sw::sstmac_global_builtin_arr< T, N >::operator= (const U & b) inline
Definition at line 99 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> template<typename U > bool sstmac::sw::sstmac_global_builtin_arr< T, N >::operator== (const U & b) const inline
Definition at line 107 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> template<typename U > bool sstmac::sw::sstmac_global_builtin_arr< T, N >::operator> (const U & b) inline
Definition at line 217 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> T& sstmac::sw::sstmac_global_builtin_arr< T, N >::operator[] (int idx) inline
Definition at line 199 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> T& sstmac::sw::sstmac_global_builtin_arr< T, N >::operator[] (long idx) inline
Definition at line 205 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
template<typename T, int N> void sstmac::sw::sstmac_global_builtin_arr< T, N >::print_all () const inline
Definition at line 60 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::vals_.
template<typename T, int N> virtual std::string sstmac::sw::sstmac_global_builtin_arr< T, N >::to_string () const inline virtual
Definition at line 91 of file global_builtin_array.h.
References sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val().
Member Data Documentation
template<typename T, int N> T* sstmac::sw::sstmac_global_builtin_arr< T, N >::init_ private
Definition at line 28 of file global_builtin_array.h.
Referenced by sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val(), sstmac::sw::sstmac_global_builtin_arr< T, N >::sstmac_global_builtin_arr(), and sstmac::sw::sstmac_global_builtin_arr< T, N >::~sstmac_global_builtin_arr().
template<typename T, int N> val_map sstmac::sw::sstmac_global_builtin_arr< T, N >::vals_ private
Definition at line 27 of file global_builtin_array.h.
Referenced by sstmac::sw::sstmac_global_builtin_arr< T, N >::begin(), sstmac::sw::sstmac_global_builtin_arr< T, N >::end(), sstmac::sw::sstmac_global_builtin_arr< T, N >::get_val(), sstmac::sw::sstmac_global_builtin_arr< T, N >::print_all(), and sstmac::sw::sstmac_global_builtin_arr< T, N >::~sstmac_global_builtin_arr().
The documentation for this class was generated from the following file:
sstmac/software/process/global_builtin_array.h