SST/macro: sstmac::tutorial::actor Class Reference
sstmac::tutorial::actor Class Reference abstract
#include <actor.h>
Public Member Functions
virtual void act ()=0
virtual ~actor ()
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual actor * clone () const =0
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Attributes
std::string biggest_fan_
Detailed Description
Definition at line 6 of file actor.h.
Constructor & Destructor Documentation
virtual sstmac::tutorial::actor::~actor () inline virtual
Definition at line 14 of file actor.h.
References clone(), and init_factory_params().
Member Function Documentation
virtual void sstmac::tutorial::actor::act () pure virtual
Implemented in sstmac::tutorial::mandy_patinkin, and sstmac::tutorial::christopher_guest.
virtual actor* sstmac::tutorial::actor::clone () const pure virtual
Referenced by ~actor().
virtual void sstmac::tutorial::actor::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented in sstmac::tutorial::mandy_patinkin, and sstmac::tutorial::christopher_guest.
Referenced by ~actor().
Member Data Documentation
std::string sstmac::tutorial::actor::biggest_fan_ protected
Definition at line 23 of file actor.h.
The documentation for this class was generated from the following file:
docs/developer/tutorials/programming/factories/actor.h