SST/macro: sstmac::tutorial::christopher_guest Class Reference
sstmac::tutorial::christopher_guest Class Reference
#include <guest.h>
Public Member Functions
std::string to_string () const
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual void act ()
Public Member Functions inherited from sstmac::tutorial::actor
virtual ~actor ()
virtual actor * clone () const =0
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Attributes
int num_fingers_
Protected Attributes inherited from sstmac::tutorial::actor
std::string biggest_fan_
Detailed Description
Definition at line 6 of file guest.h.
Member Function Documentation
virtual void sstmac::tutorial::christopher_guest::act () virtual
Implements sstmac::tutorial::actor.
Referenced by to_string().
virtual void sstmac::tutorial::christopher_guest::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::tutorial::actor.
Referenced by to_string().
std::string sstmac::tutorial::christopher_guest::to_string () const inline
Definition at line 12 of file guest.h.
References act(), and init_factory_params().
Member Data Documentation
int sstmac::tutorial::christopher_guest::num_fingers_ protected
Definition at line 23 of file guest.h.
The documentation for this class was generated from the following file:
docs/developer/tutorials/programming/factories/guest.h