SST/macro: sstmac::sw::lib_compute_memmove Class Reference
sstmac::sw::lib_compute_memmove Class Reference
#include <lib_compute_memmove.h>
Public Member Functions
virtual ~lib_compute_memmove ()
lib_compute_memmove (software_id id)
lib_compute_memmove (const std::string &libname)
virtual void unregister_all_libs ()
virtual bool supported () const
void consume_params (sprockit::sim_parameters *params)
void incoming_event (event *ev)
void read (long bytes)
void write (long bytes)
void copy (long bytes)
Public Member Functions inherited from sstmac::sw::lib_compute_inst
lib_compute_inst (software_id id)
lib_compute_inst (const std::string &id)
virtual ~lib_compute_inst ()
void compute_inst (compute_event *msg)
void compute_detailed (uint64_t flops, uint64_t nintops, uint64_t bytes)
void compute_loop (uint64_t nloops, uint32_t flops_per_loop, uint32_t intops_per_loop, uint32_t bytes_per_loop)
void incoming_event (event *ev)
Static Public Member Functions
static std::string static_name (const std::string &n)
Static Public Attributes
static key::category key_category
Protected Member Functions
void init ()
void do_access (long bytes)
Protected Attributes
int access_width_bytes_
Protected Attributes inherited from sstmac::sw::lib_compute_inst
double loop_overhead_
Static Protected Attributes
static const long unlimited_page_size = -1
static const long default_page_size = unlimited_page_size
Detailed Description
Definition at line 20 of file lib_compute_memmove.h.
Constructor & Destructor Documentation
virtual sstmac::sw::lib_compute_memmove::~lib_compute_memmove () inline virtual
Definition at line 28 of file lib_compute_memmove.h.
References lib_compute_memmove(), and unregister_all_libs().
sstmac::sw::lib_compute_memmove::lib_compute_memmove (software_id id)
Referenced by ~lib_compute_memmove().
sstmac::sw::lib_compute_memmove::lib_compute_memmove (const std::string & libname)
Member Function Documentation
void sstmac::sw::lib_compute_memmove::consume_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::sw::lib_compute_inst.
Referenced by static_name().
void sstmac::sw::lib_compute_memmove::copy (long bytes)
Referenced by incoming_event().
void sstmac::sw::lib_compute_memmove::do_access (long bytes) protected
void sstmac::sw::lib_compute_memmove::incoming_event (event * ev) inline
Definition at line 50 of file lib_compute_memmove.h.
References copy(), sstmac::sw::library::incoming_event(), read(), and write().
void sstmac::sw::lib_compute_memmove::init () protected
void sstmac::sw::lib_compute_memmove::read (long bytes)
Referenced by sstmac::sw::lib_compute_loops::compute_array_init(), and incoming_event().
static std::string sstmac::sw::lib_compute_memmove::static_name (const std::string & n) inline static
Definition at line 39 of file lib_compute_memmove.h.
References consume_params(), and supported().
virtual bool sstmac::sw::lib_compute_memmove::supported () const virtual
Reimplemented from sstmac::sw::lib_compute_inst.
Reimplemented in sstmac::sw::lib_compute_loops, and sstmac::sw::lib_compute_matrix.
Referenced by static_name(), sstmac::sw::lib_compute_matrix::supported(), and sstmac::sw::lib_compute_loops::supported().
virtual void sstmac::sw::lib_compute_memmove::unregister_all_libs () virtual
Referenced by ~lib_compute_memmove().
void sstmac::sw::lib_compute_memmove::write (long bytes)
Referenced by incoming_event().
Member Data Documentation
int sstmac::sw::lib_compute_memmove::access_width_bytes_ protected
Definition at line 76 of file lib_compute_memmove.h.
const long sstmac::sw::lib_compute_memmove::default_page_size = unlimited_page_size static protected
Definition at line 67 of file lib_compute_memmove.h.
key::category sstmac::sw::lib_compute_memmove::key_category static
Definition at line 25 of file lib_compute_memmove.h.
const long sstmac::sw::lib_compute_memmove::unlimited_page_size = -1 static protected
Definition at line 66 of file lib_compute_memmove.h.
The documentation for this class was generated from the following file:
sstmac/software/libraries/compute/lib_compute_memmove.h