SST/macro: sstmac::occupied_block_partition Class Reference
sstmac::occupied_block_partition Class Reference
#include <sim_partition.h>
Public Member Functions
occupied_block_partition (parallel_runtime *rt)
virtual ~occupied_block_partition ()
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual void partition_switches ()
virtual void finalize_init ()
int thread_for_local_switch (int local_idx) const
Public Member Functions inherited from sstmac::block_partition
block_partition (parallel_runtime *rt)
virtual ~block_partition ()
Public Member Functions inherited from sstmac::partition
virtual std::string to_string () const
virtual ~partition ()
hw::index_subset * subset (int lpid) const
int * num_switches_per_lp ()
int local_switch (int idx) const
int * local_switches ()
int * switch_to_lpid ()
int num_switches_total () const
int local_num_switches () const
int lpid_for_switch (int switch_id) const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Protected Attributes
int occupied_switches_
int unoccupied_switches_
int occupied_per_lp_
int unoccupied_per_lp_
int my_num_occupied_
int my_num_unoccupied_
int occupied_per_thread_
int unoccupied_per_thread_
Protected Attributes inherited from sstmac::block_partition
hw::topology * fake_top_
Protected Attributes inherited from sstmac::partition
int * switch_to_lpid_
int * num_switches_per_lp_
int * local_switches_
int num_switches_total_
int local_num_switches_
int switches_per_thread_
int nthread_
int nproc_
int me_
parallel_runtime * rt_
std::vector< hw::index_subset * > subsets_
Additional Inherited Members
Protected Member Functions inherited from sstmac::partition
partition (parallel_runtime *rt)
void init_local_switches ()
Detailed Description
Definition at line 225 of file sim_partition.h.
Constructor & Destructor Documentation
sstmac::occupied_block_partition::occupied_block_partition (parallel_runtime * rt) inline
Definition at line 229 of file sim_partition.h.
References sprockit::factory_type::finalize_init(), sprockit::factory_type::init_factory_params(), and sstmac::partition::thread_for_local_switch().
virtual sstmac::occupied_block_partition::~occupied_block_partition () virtual
Member Function Documentation
virtual void sstmac::occupied_block_partition::finalize_init () virtual
Reimplemented from sstmac::block_partition.
virtual void sstmac::occupied_block_partition::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::block_partition.
virtual void sstmac::occupied_block_partition::partition_switches () virtual
Reimplemented from sstmac::block_partition.
int sstmac::occupied_block_partition::thread_for_local_switch (int local_idx) const virtual
Reimplemented from sstmac::partition.
Member Data Documentation
int sstmac::occupied_block_partition::my_num_occupied_ protected
Definition at line 250 of file sim_partition.h.
int sstmac::occupied_block_partition::my_num_unoccupied_ protected
Definition at line 251 of file sim_partition.h.
int sstmac::occupied_block_partition::occupied_per_lp_ protected
Definition at line 248 of file sim_partition.h.
int sstmac::occupied_block_partition::occupied_per_thread_ protected
Definition at line 252 of file sim_partition.h.
int sstmac::occupied_block_partition::occupied_switches_ protected
Definition at line 246 of file sim_partition.h.
int sstmac::occupied_block_partition::unoccupied_per_lp_ protected
Definition at line 249 of file sim_partition.h.
int sstmac::occupied_block_partition::unoccupied_per_thread_ protected
Definition at line 253 of file sim_partition.h.
int sstmac::occupied_block_partition::unoccupied_switches_ protected
Definition at line 247 of file sim_partition.h.
The documentation for this class was generated from the following file:
sstmac/backends/common/sim_partition.h