SST/macro: sstmac::sw::process_manager Class Reference
sstmac::sw::process_manager Class Reference
#include <pmi.h>
Public Member Functions
virtual void init_param1 (const software_id &sid)
virtual void init_os (operating_system *os)
virtual ~process_manager ()
int get_partner (node_id addr) const
node_id my_addr () const
void kill_node ()
void kill_process ()
Private Types
typedef spkt_unordered_map< int, node_id > proc_to_node_map
typedef spkt_unordered_map< int, proc_to_node_map > app_to_proc_to_node_map
typedef spkt_unordered_map< node_id, int > node_to_proc_map
typedef spkt_unordered_map< int, node_to_proc_map > app_to_node_to_proc_map
Private Attributes
node_id my_addr_
operating_system * my_os_
software_id sid_
Static Private Attributes
static app_to_proc_to_node_map node_map_
static app_to_node_to_proc_map proc_map_
Detailed Description
Definition at line 17 of file pmi.h.
Member Typedef Documentation
typedef spkt_unordered_map<int, node_to_proc_map> sstmac::sw::process_manager::app_to_node_to_proc_map private
Definition at line 47 of file pmi.h.
typedef spkt_unordered_map<int, proc_to_node_map> sstmac::sw::process_manager::app_to_proc_to_node_map private
Definition at line 43 of file pmi.h.
typedef spkt_unordered_map<node_id, int> sstmac::sw::process_manager::node_to_proc_map private
Definition at line 45 of file pmi.h.
typedef spkt_unordered_map<int, node_id> sstmac::sw::process_manager::proc_to_node_map private
Definition at line 41 of file pmi.h.
Constructor & Destructor Documentation
virtual sstmac::sw::process_manager::~process_manager () virtual
Member Function Documentation
int sstmac::sw::process_manager::get_partner (node_id addr) const
virtual void sstmac::sw::process_manager::init_os (operating_system * os) virtual
Reimplemented in sstmac::sumi_api.
virtual void sstmac::sw::process_manager::init_param1 (const software_id & sid) virtual
Reimplemented in sstmac::sumi_api.
void sstmac::sw::process_manager::kill_node ()
Referenced by my_addr().
void sstmac::sw::process_manager::kill_process ()
Referenced by my_addr().
node_id sstmac::sw::process_manager::my_addr () const inline
Definition at line 32 of file pmi.h.
References kill_node(), kill_process(), and my_addr_.
Member Data Documentation
node_id sstmac::sw::process_manager::my_addr_ private
Definition at line 53 of file pmi.h.
Referenced by my_addr().
operating_system* sstmac::sw::process_manager::my_os_ private
Definition at line 55 of file pmi.h.
app_to_proc_to_node_map sstmac::sw::process_manager::node_map_ static private
Definition at line 49 of file pmi.h.
app_to_node_to_proc_map sstmac::sw::process_manager::proc_map_ static private
Definition at line 51 of file pmi.h.
software_id sstmac::sw::process_manager::sid_ private
Definition at line 57 of file pmi.h.
The documentation for this class was generated from the following file:
sstmac/software/process/pmi.h