SST/macro: sstmac::tutorial::mandy_patinkin Class Reference
sstmac::tutorial::mandy_patinkin Class Reference
#include <patinkin.h>
Public Member Functions
std::string to_string () const
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual void act ()
Public Member Functions inherited from sstmac::tutorial::actor
virtual ~actor ()
virtual actor * clone () const =0
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Static Public Member Functions
static ptr construct (sprockit::sim_parameters *params)
Protected Attributes
std::string sword_hand_
Protected Attributes inherited from sstmac::tutorial::actor
std::string biggest_fan_
Detailed Description
Definition at line 6 of file patinkin.h.
Member Function Documentation
virtual void sstmac::tutorial::mandy_patinkin::act () virtual
Implements sstmac::tutorial::actor.
Referenced by construct().
static ptr sstmac::tutorial::mandy_patinkin::construct (sprockit::sim_parameters * params) inline static
Definition at line 17 of file patinkin.h.
References act(), and init_factory_params().
virtual void sstmac::tutorial::mandy_patinkin::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::tutorial::actor.
Referenced by construct().
std::string sstmac::tutorial::mandy_patinkin::to_string () const inline
Definition at line 12 of file patinkin.h.
Member Data Documentation
std::string sstmac::tutorial::mandy_patinkin::sword_hand_ protected
Definition at line 28 of file patinkin.h.
The documentation for this class was generated from the following file:
docs/developer/tutorials/programming/factories/patinkin.h