SST/macro: sstmac::sumi_queue Class Reference
sstmac::sumi_queue Class Reference
#include <sumi_api.h>
Public Member Functions
std::string to_string () const
sumi_queue (sstmac::sw::operating_system *os)
sumi_queue ()
~sumi_queue ()
transport_message * poll_until_message ()
transport_message * poll_until_message (timestamp timeout)
void put_message (transport_message *message)
bool blocked () const
Private Attributes
std::list< transport_message * > pending_messages_
std::list< sstmac::sw::key * > blocked_keys_
sstmac::sw::operating_system * os_
Detailed Description
Definition at line 20 of file sumi_api.h.
Constructor & Destructor Documentation
sstmac::sumi_queue::sumi_queue (sstmac::sw::operating_system * os)
sstmac::sumi_queue::sumi_queue ()
Referenced by to_string().
sstmac::sumi_queue::~sumi_queue ()
Referenced by to_string().
Member Function Documentation
bool sstmac::sumi_queue::blocked () const inline
Definition at line 45 of file sumi_api.h.
References blocked_keys_.
transport_message* sstmac::sumi_queue::poll_until_message ()
Referenced by to_string().
transport_message* sstmac::sumi_queue::poll_until_message (timestamp timeout)
void sstmac::sumi_queue::put_message (transport_message * message)
Referenced by to_string().
std::string sstmac::sumi_queue::to_string () const inline
Definition at line 25 of file sumi_api.h.
References poll_until_message(), put_message(), sumi_queue(), and ~sumi_queue().
Member Data Documentation
std::list<sstmac::sw::key*> sstmac::sumi_queue::blocked_keys_ private
Definition at line 52 of file sumi_api.h.
Referenced by blocked().
sstmac::sw::operating_system* sstmac::sumi_queue::os_ private
Definition at line 54 of file sumi_api.h.
std::list<transport_message*> sstmac::sumi_queue::pending_messages_ private
Definition at line 50 of file sumi_api.h.
The documentation for this class was generated from the following file:
sstmac/libraries/sumi/sumi_api.h