SST/macro: sstmac::hw::minimal_router Class Reference
sstmac::hw::minimal_router Class Reference
#include <minimal_routing.h>
Public Member Functions
virtual ~minimal_router ()
virtual void route (packet *pkt)
std::string to_string () const
virtual void finalize_init ()
Public Member Functions inherited from sstmac::hw::structured_router
virtual void set_topology (topology *top)
virtual void set_switch (network_switch *sw)
void minimal_route_to_node (node_id node_addr, geometry_routable::path &path)
void minimal_routes_to_node (node_id node_addr, geometry_routable::path &current_path, geometry_routable::path_set &path)
virtual void minimal_route_to_switch (switch_id sw_addr, geometry_routable::path &path)
virtual void productive_paths_to_switch (switch_id dst, geometry_routable::path_set &paths)
Protected Member Functions
virtual void route (packet *pkt, geometry_routable::path_set &paths)
Additional Inherited Members
Protected Attributes inherited from sstmac::hw::structured_router
structured_topology * regtop_
Detailed Description
Definition at line 9 of file minimal_routing.h.
Constructor & Destructor Documentation
virtual sstmac::hw::minimal_router::~minimal_router () inline virtual
Definition at line 14 of file minimal_routing.h.
References route().
Member Function Documentation
virtual void sstmac::hw::minimal_router::finalize_init () virtual
Reimplemented from sstmac::hw::structured_router.
Reimplemented in sstmac::hw::valiant_router, sstmac::hw::ugal_router, and sstmac::hw::minimal_adaptive_router.
Referenced by to_string().
virtual void sstmac::hw::minimal_router::route (packet * pkt) virtual
Reimplemented in sstmac::hw::ugal_router, sstmac::hw::minimal_adaptive_router, and sstmac::hw::valiant_router.
Referenced by to_string(), and ~minimal_router().
virtual void sstmac::hw::minimal_router::route (packet * pkt, geometry_routable::path_set & paths) protected virtual
Reimplemented in sstmac::hw::valiant_router.
std::string sstmac::hw::minimal_router::to_string () const inline
Definition at line 20 of file minimal_routing.h.
References finalize_init(), and route().
The documentation for this class was generated from the following file:
sstmac/hardware/router/minimal_routing.h