SST/macro: sstmac::hw::geometry_routable Class Reference
sstmac::hw::geometry_routable Class Reference
#include <routable.h>
Classes
struct path
class path_set
Public Types
enum metadata_slot { valiant_stage, final_stage, crossed_timeline }
Public Member Functions
node_id toaddr () const
node_id fromaddr () const
void set_toaddr (node_id to)
void set_fromaddr (node_id from)
path & current_path ()
void assign_path (const path &pth)
void check_vc ()
virtual int vc () const
int port () const
void serialize_order (serializer &ser)
void set_dest_switch (switch_id sid)
switch_id dest_switch () const
Protected Member Functions
geometry_routable ()
geometry_routable (node_id toaddr, node_id fromaddr)
Private Attributes
node_id toaddr_
node_id fromaddr_
path path_
switch_id dest_switch_
Detailed Description
Definition at line 11 of file routable.h.
Member Enumeration Documentation
enum sstmac::hw::geometry_routable::metadata_slot
Enumerator
valiant_stage
final_stage
crossed_timeline
Definition at line 14 of file routable.h.
Constructor & Destructor Documentation
sstmac::hw::geometry_routable::geometry_routable () inline protected
Definition at line 154 of file routable.h.
References fromaddr(), and toaddr().
sstmac::hw::geometry_routable::geometry_routable (node_id toaddr, node_id fromaddr) protected
Member Function Documentation
void sstmac::hw::geometry_routable::assign_path (const path & pth) inline
Definition at line 120 of file routable.h.
References path_.
void sstmac::hw::geometry_routable::check_vc () inline
Definition at line 125 of file routable.h.
References path_, sstmac::hw::routing::uninitialized, and sstmac::hw::geometry_routable::path::vc.
path& sstmac::hw::geometry_routable::current_path () inline
Definition at line 115 of file routable.h.
References path_.
switch_id sstmac::hw::geometry_routable::dest_switch () const inline
Definition at line 149 of file routable.h.
References dest_switch_.
node_id sstmac::hw::geometry_routable::fromaddr () const inline
Definition at line 100 of file routable.h.
References fromaddr_.
Referenced by geometry_routable().
int sstmac::hw::geometry_routable::port () const inline
Definition at line 136 of file routable.h.
References sstmac::hw::geometry_routable::path::outport, path_, and serialize_order().
void sstmac::hw::geometry_routable::serialize_order (serializer & ser)
Referenced by port().
void sstmac::hw::geometry_routable::set_dest_switch (switch_id sid) inline
Definition at line 144 of file routable.h.
References dest_switch_.
void sstmac::hw::geometry_routable::set_fromaddr (node_id from) inline
Definition at line 110 of file routable.h.
References fromaddr_.
void sstmac::hw::geometry_routable::set_toaddr (node_id to) inline
Definition at line 105 of file routable.h.
References toaddr_.
node_id sstmac::hw::geometry_routable::toaddr () const inline
Definition at line 95 of file routable.h.
References toaddr_.
Referenced by geometry_routable().
virtual int sstmac::hw::geometry_routable::vc () const inline virtual
Definition at line 131 of file routable.h.
References path_, and sstmac::hw::geometry_routable::path::vc.
Member Data Documentation
switch_id sstmac::hw::geometry_routable::dest_switch_ private
Definition at line 165 of file routable.h.
Referenced by dest_switch(), and set_dest_switch().
node_id sstmac::hw::geometry_routable::fromaddr_ private
Definition at line 161 of file routable.h.
Referenced by fromaddr(), and set_fromaddr().
path sstmac::hw::geometry_routable::path_ private
Definition at line 163 of file routable.h.
Referenced by assign_path(), check_vc(), current_path(), port(), and vc().
node_id sstmac::hw::geometry_routable::toaddr_ private
Definition at line 159 of file routable.h.
Referenced by set_toaddr(), and toaddr().
The documentation for this class was generated from the following file:
sstmac/hardware/router/routable.h