SST/macro: sprockit::refcount_ptr< T > Class Template Reference
sprockit::refcount_ptr< T > Class Template Reference
#include <refcount_ptr.h>
Public Member Functions
refcount_ptr ()
template<class U >
refcount_ptr (const refcount_ptr< U > &rhs)
refcount_ptr (const refcount_ptr &rhs)
refcount_ptr (T *rhs)
~refcount_ptr ()
T * get () const
template<class U >
refcount_ptr< T > & operator= (const refcount_ptr< U > &rhs)
refcount_ptr< T > & operator= (const refcount_ptr &rhs)
refcount_ptr< T > & operator= (T *rhs)
operator bool () const
T * operator-> () const
bool null () const
Private Member Functions
template<class U >
void decref (U *ptr)
template<class U >
void incref (U *ptr)
Private Attributes
T * ptr
Friends
template<class U >
class refcount_ptr
Detailed Description
template<class T>
class sprockit::refcount_ptr< T >
Definition at line 25 of file refcount_ptr.h.
Constructor & Destructor Documentation
template<class T> sprockit::refcount_ptr< T >::refcount_ptr () inline
Definition at line 44 of file refcount_ptr.h.
template<class T> template<class U > sprockit::refcount_ptr< T >::refcount_ptr (const refcount_ptr< U > & rhs) inline
Definition at line 48 of file refcount_ptr.h.
References sprockit::refcount_ptr< T >::incref().
template<class T> sprockit::refcount_ptr< T >::refcount_ptr (const refcount_ptr< T > & rhs) inline
Definition at line 52 of file refcount_ptr.h.
References sprockit::refcount_ptr< T >::incref().
template<class T> sprockit::refcount_ptr< T >::refcount_ptr (T * rhs) inline
Definition at line 56 of file refcount_ptr.h.
References sprockit::refcount_ptr< T >::incref().
template<class T> sprockit::refcount_ptr< T >::~refcount_ptr () inline
Definition at line 60 of file refcount_ptr.h.
References sprockit::refcount_ptr< T >::decref().
Member Function Documentation
template<class T> template<class U > void sprockit::refcount_ptr< T >::decref (U * ptr) inline private
Definition at line 31 of file refcount_ptr.h.
References sprockit::refcount_ptr< T >::ptr, and ref_decrement_return.
Referenced by sprockit::refcount_ptr< T >::operator=(), and sprockit::refcount_ptr< T >::~refcount_ptr().
template<class T> T* sprockit::refcount_ptr< T >::get () const inline
Definition at line 65 of file refcount_ptr.h.
References sprockit::refcount_ptr< T >::ptr.
Referenced by sprockit::__safe_ptr_cast__(), sprockit::refcount_ptr< T >::null(), sprockit::serialize< sprockit::refcount_ptr< T > >::operator()(), sprockit::serialize< const sprockit::refcount_ptr< T > >::operator()(), and sprockit::serialize< sprockit::refcount_ptr< const T > >::operator()().
template<class T> template<class U > void sprockit::refcount_ptr< T >::incref (U * ptr) inline private
Definition at line 39 of file refcount_ptr.h.
References ref_increment.
Referenced by sprockit::refcount_ptr< T >::operator=(), and sprockit::refcount_ptr< T >::refcount_ptr().
template<class T> bool sprockit::refcount_ptr< T >::null () const inline
Definition at line 104 of file refcount_ptr.h.
References sprockit::refcount_ptr< T >::get(), and sprockit::refcount_ptr< T >::ptr.
template<class T> sprockit::refcount_ptr< T >::operator bool () const inline
Definition at line 94 of file refcount_ptr.h.
template<class T> T* sprockit::refcount_ptr< T >::operator-> () const inline
Definition at line 99 of file refcount_ptr.h.
References sprockit::refcount_ptr< T >::ptr.
template<class T> template<class U > refcount_ptr<T>& sprockit::refcount_ptr< T >::operator= (const refcount_ptr< U > & rhs) inline
Definition at line 71 of file refcount_ptr.h.
References sprockit::refcount_ptr< T >::decref(), sprockit::refcount_ptr< T >::incref(), and sprockit::refcount_ptr< T >::ptr.
template<class T> refcount_ptr<T>& sprockit::refcount_ptr< T >::operator= (const refcount_ptr< T > & rhs) inline
Definition at line 79 of file refcount_ptr.h.
References sprockit::refcount_ptr< T >::decref(), sprockit::refcount_ptr< T >::incref(), and sprockit::refcount_ptr< T >::ptr.
template<class T> refcount_ptr<T>& sprockit::refcount_ptr< T >::operator= (T * rhs) inline
Definition at line 87 of file refcount_ptr.h.
References sprockit::refcount_ptr< T >::decref(), and sprockit::refcount_ptr< T >::incref().
Friends And Related Function Documentation
template<class T> template<class U > friend class refcount_ptr friend
Definition at line 26 of file refcount_ptr.h.
Member Data Documentation
template<class T> T* sprockit::refcount_ptr< T >::ptr private
Definition at line 28 of file refcount_ptr.h.
Referenced by sprockit::refcount_ptr< T >::decref(), sprockit::refcount_ptr< T >::get(), sprockit::refcount_ptr< T >::null(), sprockit::refcount_ptr< T >::operator->(), and sprockit::refcount_ptr< T >::operator=().
The documentation for this class was generated from the following file:
sprockit/sprockit/refcount_ptr.h