SST/macro: sstmac::sw::lib_compute_matrix Class Reference
sstmac::sw::lib_compute_matrix Class Reference
#include <lib_compute_matrix.h>
Public Member Functions
lib_compute_matrix (software_id id)
virtual ~lib_compute_matrix ()
void double_mxm (long nrow, long nlink, long ncol, long nthread=1)
void double_add (long nrow, long ncol, long nthread=1)
void double_copy (long nrow, long ncol, long nthread=1)
Public Member Functions inherited from sstmac::sw::lib_compute_memmove
virtual ~lib_compute_memmove ()
lib_compute_memmove (software_id id)
lib_compute_memmove (const std::string &libname)
virtual void unregister_all_libs ()
void consume_params (sprockit::sim_parameters *params)
void incoming_event (event *ev)
void read (long bytes)
void write (long bytes)
void copy (long bytes)
Public Member Functions inherited from sstmac::sw::lib_compute_inst
lib_compute_inst (software_id id)
lib_compute_inst (const std::string &id)
virtual ~lib_compute_inst ()
void compute_inst (compute_event *msg)
void compute_detailed (uint64_t flops, uint64_t nintops, uint64_t bytes)
void compute_loop (uint64_t nloops, uint32_t flops_per_loop, uint32_t intops_per_loop, uint32_t bytes_per_loop)
void incoming_event (event *ev)
Protected Member Functions
void double_compute (long ndata_read, long working_set_size_read, long ndata_write, long working_set_size_write, long nadd, long nmult, long nmultadd, long nthread)
virtual bool supported () const
Protected Member Functions inherited from sstmac::sw::lib_compute_memmove
void init ()
void do_access (long bytes)
Protected Attributes
bool doing_memory_
Protected Attributes inherited from sstmac::sw::lib_compute_memmove
int access_width_bytes_
Protected Attributes inherited from sstmac::sw::lib_compute_inst
double loop_overhead_
Additional Inherited Members
Static Public Member Functions inherited from sstmac::sw::lib_compute_memmove
static std::string static_name (const std::string &n)
Static Public Attributes inherited from sstmac::sw::lib_compute_memmove
static key::category key_category
Static Protected Attributes inherited from sstmac::sw::lib_compute_memmove
static const long unlimited_page_size = -1
static const long default_page_size = unlimited_page_size
Detailed Description
Definition at line 21 of file lib_compute_matrix.h.
Constructor & Destructor Documentation
sstmac::sw::lib_compute_matrix::lib_compute_matrix (software_id id) inline
Definition at line 27 of file lib_compute_matrix.h.
virtual sstmac::sw::lib_compute_matrix::~lib_compute_matrix () inline virtual
Definition at line 33 of file lib_compute_matrix.h.
References double_add(), double_compute(), double_copy(), and double_mxm().
Member Function Documentation
void sstmac::sw::lib_compute_matrix::double_add (long nrow, long ncol, long nthread = 1)
Referenced by ~lib_compute_matrix().
void sstmac::sw::lib_compute_matrix::double_compute (long ndata_read, long working_set_size_read, long ndata_write, long working_set_size_write, long nadd, long nmult, long nmultadd, long nthread) protected
Referenced by ~lib_compute_matrix().
void sstmac::sw::lib_compute_matrix::double_copy (long nrow, long ncol, long nthread = 1)
Referenced by ~lib_compute_matrix().
void sstmac::sw::lib_compute_matrix::double_mxm (long nrow, long nlink, long ncol, long nthread = 1)
Referenced by ~lib_compute_matrix().
virtual bool sstmac::sw::lib_compute_matrix::supported () const inline protected virtual
Reimplemented from sstmac::sw::lib_compute_memmove.
Definition at line 51 of file lib_compute_matrix.h.
References sstmac::sw::lib_compute_memmove::supported(), and sstmac::sw::lib_compute_inst::supported().
Member Data Documentation
bool sstmac::sw::lib_compute_matrix::doing_memory_ protected
Definition at line 56 of file lib_compute_matrix.h.
The documentation for this class was generated from the following file:
sstmac/software/libraries/compute/lib_compute_matrix.h