SST/macro: RNG::mersenne_twister Class Reference
RNG::mersenne_twister Class Reference
Updated Mersenne twister.
#include <mersenne_twister.h>
Public Member Functions
virtual std::string to_string () const
virtual ~mersenne_twister ()
Cleanup.
virtual rngint_t value ()
Get a value in the interval [0,numeric_limits<rngint_t>::max()].
virtual void vec_reseed (const std::vector< rngint_t > &seeds)
Reseed the generator. This is an expensive operation.
virtual int nseed ()
The number of seeds employed by this generator.
Public Member Functions inherited from RNG::UniformInteger
virtual ~UniformInteger ()
rngint_t value_in_range (rngint_t range)
virtual double realvalue (bool include_zero=true, bool include_one=true)
Return a random value in the interval [0,1], (0,1], [0,1), or (0,1)
void reseed ()
void reseed (rngint_t)
void reseed (rngint_t, rngint_t)
void reseed (rngint_t, rngint_t, rngint_t)
void reseed (rngint_t, rngint_t, rngint_t, rngint_t)
Static Public Member Functions
static mersenne_twister * construct (uint64_t seed)
Create a new twister.
Private Member Functions
void reseed (uint64_t seed)
mersenne_twister (uint64_t seed)
Like normally for SST/macro types, constructor is private.
Private Attributes
std::vector< uint64_t > mt_
The array for the state vector. Of length 'state_vector_length_'.
size_t mti_
The current position in the state vector ('mti' in original code).
Static Private Attributes
static const int state_vector_length_
State vector length defaults to 312 entries ('NN' in original code).
static const int mask_length_
I believe this is a mask length, defaults to 156 ('MM' in original).
Detailed Description
Updated Mersenne twister.
Copyright (C) 2004, Makoto Matsumoto and Takuji Nishimura, All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
The names of its contributors may not be used to endorse or promote products derived from this software without specific prior written permission.
Modified to fit into the SST/macroscale code structure and to eliminate global (static) state.
Definition at line 106 of file mersenne_twister.h.
Constructor & Destructor Documentation
RNG::mersenne_twister::mersenne_twister (uint64_t seed) private
Like normally for SST/macro types, constructor is private.
virtual RNG::mersenne_twister::~mersenne_twister () virtual
Cleanup.
Referenced by to_string().
Member Function Documentation
static mersenne_twister* RNG::mersenne_twister::construct (uint64_t seed) static
Create a new twister.
Referenced by to_string().
virtual int RNG::mersenne_twister::nseed () inline virtual
The number of seeds employed by this generator.
The generator will accept any value up to state_vector_length_.
Implements RNG::UniformInteger.
Definition at line 142 of file mersenne_twister.h.
References state_vector_length_.
void RNG::mersenne_twister::reseed (uint64_t seed) private
virtual std::string RNG::mersenne_twister::to_string () const inline virtual
Definition at line 124 of file mersenne_twister.h.
References construct(), value(), vec_reseed(), and ~mersenne_twister().
virtual rngint_t RNG::mersenne_twister::value () virtual
Get a value in the interval [0,numeric_limits<rngint_t>::max()].
Implements RNG::UniformInteger.
Referenced by to_string().
virtual void RNG::mersenne_twister::vec_reseed (const std::vector< rngint_t > & seeds) virtual
Reseed the generator. This is an expensive operation.
Implements RNG::UniformInteger.
Referenced by to_string().
Member Data Documentation
const int RNG::mersenne_twister::mask_length_ static private
I believe this is a mask length, defaults to 156 ('MM' in original).
Definition at line 111 of file mersenne_twister.h.
std::vector<uint64_t> RNG::mersenne_twister::mt_ private
The array for the state vector. Of length 'state_vector_length_'.
Definition at line 113 of file mersenne_twister.h.
size_t RNG::mersenne_twister::mti_ private
The current position in the state vector ('mti' in original code).
Definition at line 115 of file mersenne_twister.h.
const int RNG::mersenne_twister::state_vector_length_ static private
State vector length defaults to 312 entries ('NN' in original code).
Definition at line 109 of file mersenne_twister.h.
Referenced by nseed().
The documentation for this class was generated from the following file:
sstmac/common/mersenne_twister.h