SST/macro: sstmac::hw::packet_flow_network_buffer Class Reference
sstmac::hw::packet_flow_network_buffer Class Reference
#include <packet_flow_buffer.h>
Public Member Functions
packet_flow_network_buffer ()
packet_flow_network_buffer (const timestamp &send_lat, const timestamp &credit_lat, int max_num_bytes, int num_vc, int packet_size, packet_flow_bandwidth_arbitrator *arb)
virtual ~packet_flow_network_buffer ()
int queue_length () const
void init_credits (int port, int num_credits)
void handle_credit (packet_flow_credit *msg)
void do_handle_payload (packet_flow_payload *msg)
std::string packet_flow_name () const
void set_sanity_params (bool queue_depth_reporting, int queue_depth_delta)
void deadlock_check ()
void deadlock_check (message *msg)
Public Member Functions inherited from sstmac::hw::packet_flow_finite_buffer
virtual ~packet_flow_finite_buffer ()
virtual void set_input (int this_inport, int src_outport, event_handler *input)
long size_bytes () const
int num_initial_credits () const
Public Member Functions inherited from sstmac::hw::packet_flow_buffer
virtual ~packet_flow_buffer ()
virtual void set_output (int this_outport, int dst_inport, event_handler *output)
event_loc_id output_location () const
event_loc_id input_location () const
Public Member Functions inherited from sstmac::hw::packet_flow_sender
virtual ~packet_flow_sender ()
void set_acker (event_handler *acker)
void handle_payload (packet_flow_payload *msg)
void set_event_location (node_id nid)
void set_event_location (switch_id sid)
void set_congestion_spyplot (stat_spyplot *plot)
bool accumulate_delay () const
void set_accumulate_delay (bool flag)
std::string to_string () const
void set_update_vc (bool flag)
Public Member Functions inherited from sstmac::hw::packet_flow_handler
packet_flow_handler ()
virtual ~packet_flow_handler ()
virtual void handle (event *ev)
int thread_id () const
Public Member Functions inherited from sstmac::event_subscheduler
event_subscheduler ()
timestamp now () const
get the current time
void schedule (timestamp t, event_handler *handler, event *ev)
Add an event to the event queue, where msg will get delivered to handler at time t.
void schedule (timestamp t, event_queue_entry *ev)
void schedule_now (event_queue_entry *ev)
void schedule_now (event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_queue_entry *ev)
void send_self_event (timestamp arrival, event *ev)
void send_delayed_self_event (timestamp delay, event *ev)
void send_now_self_event (event *ev)
void send_self_event_queue (timestamp arrival, event_queue_entry *ev)
void send_delayed_self_event_queue (timestamp delay, event_queue_entry *ev)
void send_now_self_event_queue (event_queue_entry *ev)
virtual void set_event_parent (event_scheduler *m)
Set the eventmanager for this scheduler.
event_scheduler * parent () const
Public Member Functions inherited from sstmac::event_handler
virtual ~event_handler ()
event_loc_id event_location () const
virtual bool ipc_handler () const
Whether an event handler is a "fake" handler that represents logical process boundary.
int thread_id () const
virtual void deadlock_check (event *ev)
Protected Attributes
int num_vc_
std::vector< payload_queue > queues_
std::vector< int > credits_
Protected Attributes inherited from sstmac::hw::packet_flow_finite_buffer
long size_bytes_
Protected Attributes inherited from sstmac::hw::packet_flow_buffer
packet_flow_bandwidth_arbitrator * arb_
packet_flow_input input_
packet_flow_output output_
long bytes_delayed_
Protected Attributes inherited from sstmac::hw::packet_flow_sender
stat_spyplot * congestion_spyplot_
event_handler * acker_
timestamp send_lat_
timestamp credit_lat_
bool acc_delay_
bool update_vc_
Protected Attributes inherited from sstmac::event_subscheduler
event_scheduler * parent_
Private Member Functions
void build_blocked_messages ()
Private Attributes
std::set< int > deadlocked_channels_
std::map< int, std::list< packet_flow_payload * > > blocked_messages_
bool queue_depth_reporting_
int queue_depth_delta_
int packet_size_
Additional Inherited Members
Static Public Attributes inherited from sstmac::event_handler
static const int null_lpid = -1
static const int null_threadid = -1
Protected Member Functions inherited from sstmac::hw::packet_flow_finite_buffer
packet_flow_finite_buffer (const timestamp &send_lat, const timestamp &credit_lat, int max_num_bytes, packet_flow_bandwidth_arbitrator *arb)
packet_flow_finite_buffer ()
Protected Member Functions inherited from sstmac::hw::packet_flow_buffer
packet_flow_buffer (const timestamp &send_lat, const timestamp &credit_lat, packet_flow_bandwidth_arbitrator *arb)
packet_flow_buffer ()
std::string buffer_string (const char *name) const
Protected Member Functions inherited from sstmac::hw::packet_flow_sender
packet_flow_sender (const timestamp &send_lat, const timestamp &credit_lat)
packet_flow_sender ()
void send_credit (const packet_flow_input &src, packet_flow_payload *payload, timestamp packet_tail_leaves)
void send (packet_flow_bandwidth_arbitrator *arb, packet_flow_payload *msg, const packet_flow_input &src, const packet_flow_output &dest)
Protected Member Functions inherited from sstmac::event_handler
event_handler ()
void init_loc_id (event_loc_id id)
void init_thread_id (int id)
Static Protected Attributes inherited from sstmac::hw::packet_flow_buffer
static const int my_outport = 0
static const int my_inport = 0
Detailed Description
Definition at line 126 of file packet_flow_buffer.h.
Constructor & Destructor Documentation
sstmac::hw::packet_flow_network_buffer::packet_flow_network_buffer () inline
Definition at line 130 of file packet_flow_buffer.h.
sstmac::hw::packet_flow_network_buffer::packet_flow_network_buffer (const timestamp & send_lat, const timestamp & credit_lat, int max_num_bytes, int num_vc, int packet_size, packet_flow_bandwidth_arbitrator * arb)
virtual sstmac::hw::packet_flow_network_buffer::~packet_flow_network_buffer () inline virtual
Definition at line 140 of file packet_flow_buffer.h.
References sstmac::hw::packet_flow_sender::do_handle_payload(), sstmac::hw::packet_flow_handler::handle_credit(), sstmac::hw::packet_flow_sender::init_credits(), and sstmac::hw::packet_flow_buffer::queue_length().
Member Function Documentation
void sstmac::hw::packet_flow_network_buffer::build_blocked_messages () private
void sstmac::hw::packet_flow_network_buffer::deadlock_check () virtual
Reimplemented from sstmac::event_handler.
void sstmac::hw::packet_flow_network_buffer::deadlock_check (message * msg)
void sstmac::hw::packet_flow_network_buffer::do_handle_payload (packet_flow_payload * msg) virtual
Implements sstmac::hw::packet_flow_sender.
void sstmac::hw::packet_flow_network_buffer::handle_credit (packet_flow_credit * msg) virtual
Implements sstmac::hw::packet_flow_handler.
void sstmac::hw::packet_flow_network_buffer::init_credits (int port, int num_credits) virtual
Implements sstmac::hw::packet_flow_sender.
std::string sstmac::hw::packet_flow_network_buffer::packet_flow_name () const inline virtual
Implements sstmac::hw::packet_flow_sender.
Definition at line 155 of file packet_flow_buffer.h.
int sstmac::hw::packet_flow_network_buffer::queue_length () const virtual
Reimplemented from sstmac::hw::packet_flow_buffer.
void sstmac::hw::packet_flow_network_buffer::set_sanity_params (bool queue_depth_reporting, int queue_depth_delta) inline
Definition at line 160 of file packet_flow_buffer.h.
References sstmac::event_handler::deadlock_check().
Member Data Documentation
std::map<int, std::list<packet_flow_payload*> > sstmac::hw::packet_flow_network_buffer::blocked_messages_ private
Definition at line 179 of file packet_flow_buffer.h.
std::vector<int> sstmac::hw::packet_flow_network_buffer::credits_ protected
Definition at line 172 of file packet_flow_buffer.h.
std::set<int> sstmac::hw::packet_flow_network_buffer::deadlocked_channels_ private
Definition at line 178 of file packet_flow_buffer.h.
int sstmac::hw::packet_flow_network_buffer::num_vc_ protected
Definition at line 170 of file packet_flow_buffer.h.
int sstmac::hw::packet_flow_network_buffer::packet_size_ private
Definition at line 182 of file packet_flow_buffer.h.
int sstmac::hw::packet_flow_network_buffer::queue_depth_delta_ private
Definition at line 181 of file packet_flow_buffer.h.
bool sstmac::hw::packet_flow_network_buffer::queue_depth_reporting_ private
Definition at line 180 of file packet_flow_buffer.h.
std::vector<payload_queue> sstmac::hw::packet_flow_network_buffer::queues_ protected
Definition at line 171 of file packet_flow_buffer.h.
The documentation for this class was generated from the following file:
sstmac/hardware/packet_flow/packet_flow_buffer.h