SST/macro: sstmac::sw::simple_compute_scheduler Class Reference
sstmac::sw::simple_compute_scheduler Class Reference
#include <simple_compute_scheduler.h>
Public Member Functions
simple_compute_scheduler ()
void reserve_core (thread *thr)
void release_core (thread *thr)
compute_scheduler * clone (operating_system *os) const
Private Attributes
std::list< thread * > pending_threads_
int ncore_active_
Detailed Description
Definition at line 9 of file simple_compute_scheduler.h.
Constructor & Destructor Documentation
sstmac::sw::simple_compute_scheduler::simple_compute_scheduler () inline
Definition at line 12 of file simple_compute_scheduler.h.
References release_core(), and reserve_core().
Referenced by clone().
Member Function Documentation
compute_scheduler* sstmac::sw::simple_compute_scheduler::clone (operating_system * os) const inline
Definition at line 19 of file simple_compute_scheduler.h.
References simple_compute_scheduler().
void sstmac::sw::simple_compute_scheduler::release_core (thread * thr)
Referenced by simple_compute_scheduler().
void sstmac::sw::simple_compute_scheduler::reserve_core (thread * thr)
Referenced by simple_compute_scheduler().
Member Data Documentation
int sstmac::sw::simple_compute_scheduler::ncore_active_ private
Definition at line 28 of file simple_compute_scheduler.h.
std::list<thread*> sstmac::sw::simple_compute_scheduler::pending_threads_ private
Definition at line 27 of file simple_compute_scheduler.h.
The documentation for this class was generated from the following file:
sstmac/software/process/simple_compute_scheduler.h