SST/macro: sstmac::hw::processor Class Reference
sstmac::hw::processor Class Reference abstract
An interface for processor models.
#include <processor.h>
Public Member Functions
virtual ~processor ()
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual void finalize_init ()
virtual void init_param1 (memory_model *mem)
virtual void init_param2 (node *nd)
void compute (event *ev)
virtual void do_compute (sw::compute_event *cev)=0
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Static Public Member Functions
static void delete_statics ()
Protected Member Functions
processor ()
Protected Attributes
double freq_
double mem_freq_
memory_model * mem_
node * node_
Detailed Description
An interface for processor models.
Definition at line 32 of file processor.h.
Constructor & Destructor Documentation
virtual sstmac::hw::processor::~processor () virtual
sstmac::hw::processor::processor () protected
Referenced by init_param2().
Member Function Documentation
void sstmac::hw::processor::compute (event * ev)
Referenced by init_param2().
static void sstmac::hw::processor::delete_statics () static
Referenced by init_param2().
virtual void sstmac::hw::processor::do_compute (sw::compute_event * cev) pure virtual
Implemented in sstmac::hw::instruction_processor, and sstmac::hw::simple_processor.
Referenced by init_param2().
virtual void sstmac::hw::processor::finalize_init () virtual
Reimplemented from sprockit::factory_type.
Reimplemented in sstmac::hw::instruction_processor, and sstmac::hw::simple_processor.
virtual void sstmac::hw::processor::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented in sstmac::hw::instruction_processor.
virtual void sstmac::hw::processor::init_param1 (memory_model * mem) inline virtual
Definition at line 46 of file processor.h.
References mem_.
virtual void sstmac::hw::processor::init_param2 (node * nd) inline virtual
Definition at line 51 of file processor.h.
References compute(), delete_statics(), do_compute(), node_, and processor().
Member Data Documentation
double sstmac::hw::processor::freq_ protected
Definition at line 68 of file processor.h.
memory_model* sstmac::hw::processor::mem_ protected
Definition at line 71 of file processor.h.
Referenced by init_param1().
double sstmac::hw::processor::mem_freq_ protected
Definition at line 69 of file processor.h.
node* sstmac::hw::processor::node_ protected
Definition at line 72 of file processor.h.
Referenced by init_param2().
The documentation for this class was generated from the following file:
sstmac/hardware/processor/processor.h