SST/macro: sstmac::sw::dumpi_indexer Class Reference
sstmac::sw::dumpi_indexer Class Reference
#include <dumpi_indexer.h>
Public Member Functions
void set_topology (hw::topology *top)
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual ~dumpi_indexer () throw ()
void allocate (const app_id &aid, const node_set &nodes, int ppn, std::vector< node_id > &result, int nproc)
Assign processes to nodes.
Public Member Functions inherited from sstmac::sw::index_strategy
virtual std::string to_string () const
virtual void init_param1 (parallel_runtime *rt)
virtual ~index_strategy () throw ()
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Member Functions
node_id node_id_from_hostname (const std::string &hostname)
node_id node_id_from_coordinates (int ncoord, int *coordinates)
Protected Member Functions inherited from sstmac::sw::index_strategy
index_strategy ()
int validate_nproc (int ppn, int num_nodes, int nproc, const char *name) const
Protected Attributes
std::string metaname_
hw::structured_topology * regtop_
Protected Attributes inherited from sstmac::sw::index_strategy
hw::topology * topology_
parallel_runtime * rt_
Additional Inherited Members
Public Types inherited from sstmac::sw::index_strategy
typedef std::set< node_id > node_set
Detailed Description
Definition at line 22 of file dumpi_indexer.h.
Constructor & Destructor Documentation
virtual sstmac::sw::dumpi_indexer::~dumpi_indexer () throw () inline virtual
Definition at line 32 of file dumpi_indexer.h.
References allocate(), node_id_from_coordinates(), and node_id_from_hostname().
Member Function Documentation
void sstmac::sw::dumpi_indexer::allocate (const app_id & aid, const node_set & allocation, int ppn, std::vector< node_id > & result, int nproc) virtual
Assign processes to nodes.
Parameters
aid The application ID for the application whose processes are being indexed
nodes is the list of unique nodes to be used for the allocation
ppn is the nominal number of processes allocated on each node.
result is the resulting vector of length nodes (size nproc)
nproc the total number of processes to allocate
Exceptions
value_error if nodes.empty()
value_error if ppn <= 0
value_error if nodes.size()*ppn < nproc
Implements sstmac::sw::index_strategy.
Referenced by ~dumpi_indexer().
virtual void sstmac::sw::dumpi_indexer::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::sw::index_strategy.
node_id sstmac::sw::dumpi_indexer::node_id_from_coordinates (int ncoord, int * coordinates) protected
Referenced by ~dumpi_indexer().
node_id sstmac::sw::dumpi_indexer::node_id_from_hostname (const std::string & hostname) protected
Referenced by ~dumpi_indexer().
void sstmac::sw::dumpi_indexer::set_topology (hw::topology * top) virtual
Reimplemented from sstmac::sw::index_strategy.
Member Data Documentation
std::string sstmac::sw::dumpi_indexer::metaname_ protected
Definition at line 47 of file dumpi_indexer.h.
hw::structured_topology* sstmac::sw::dumpi_indexer::regtop_ protected
Definition at line 49 of file dumpi_indexer.h.
The documentation for this class was generated from the following file:
sstmac/software/launch/dumpi_indexer.h