SST/macro: sstmac::hw::packetizer Class Reference
sstmac::hw::packetizer Class Reference abstract
#include <packetizer.h>
Classes
struct pending_send
Public Member Functions
void start (int vn, message *payload)
void packetArrived (int vn, packet *pkt)
void sendWhatYouCan (int vn)
void setNotify (packetizer_callback *handler)
int packetSize () const
virtual void init_factory_params (sprockit::sim_parameters *params)
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Public Member Functions inherited from sstmac::event_subscheduler
event_subscheduler ()
timestamp now () const
get the current time
virtual std::string to_string () const
virtual void handle (event *ev)
void schedule (timestamp t, event_handler *handler, event *ev)
Add an event to the event queue, where msg will get delivered to handler at time t.
void schedule (timestamp t, event_queue_entry *ev)
void schedule_now (event_queue_entry *ev)
void schedule_now (event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_queue_entry *ev)
void send_self_event (timestamp arrival, event *ev)
void send_delayed_self_event (timestamp delay, event *ev)
void send_now_self_event (event *ev)
void send_self_event_queue (timestamp arrival, event_queue_entry *ev)
void send_delayed_self_event_queue (timestamp delay, event_queue_entry *ev)
void send_now_self_event_queue (event_queue_entry *ev)
virtual void set_event_parent (event_scheduler *m)
Set the eventmanager for this scheduler.
event_scheduler * parent () const
Public Member Functions inherited from sstmac::event_handler
virtual ~event_handler ()
event_loc_id event_location () const
virtual bool ipc_handler () const
Whether an event handler is a "fake" handler that represents logical process boundary.
int thread_id () const
virtual void deadlock_check (event *ev)
virtual void deadlock_check ()
Protected Member Functions
void bytesArrived (int vn, uint64_t unique_id, int bytes, message *parent)
Protected Member Functions inherited from sstmac::event_handler
event_handler ()
void init_loc_id (event_loc_id id)
void init_thread_id (int id)
Private Member Functions
virtual void inject (int vn, long bytes, long byte_offset, message *payload)=0
virtual bool spaceToSend (int vn, int num_bits) const =0
Private Attributes
recv_cq completion_queue_
std::map< int, std::list< pending_send > > pending_
int packet_size_
packetizer_callback * notifier_
Additional Inherited Members
Static Public Attributes inherited from sstmac::event_handler
static const int null_lpid = -1
static const int null_threadid = -1
Protected Attributes inherited from sstmac::event_subscheduler
event_scheduler * parent_
Detailed Description
Definition at line 23 of file packetizer.h.
Member Function Documentation
void sstmac::hw::packetizer::bytesArrived (int vn, uint64_t unique_id, int bytes, message * parent) protected
virtual void sstmac::hw::packetizer::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented in sstmac::hw::packet_flow_memory_packetizer, and sstmac::hw::packet_flow_nic_packetizer.
Referenced by sstmac::hw::packet_flow_nic_packetizer::to_string().
virtual void sstmac::hw::packetizer::inject (int vn, long bytes, long byte_offset, message * payload) private pure virtual
Implemented in sstmac::hw::packet_flow_memory_packetizer, and sstmac::hw::packet_flow_nic_packetizer.
Referenced by sstmac::hw::packet_flow_nic_packetizer::to_string().
void sstmac::hw::packetizer::packetArrived (int vn, packet * pkt)
int sstmac::hw::packetizer::packetSize () const inline
Definition at line 39 of file packetizer.h.
void sstmac::hw::packetizer::sendWhatYouCan (int vn)
void sstmac::hw::packetizer::setNotify (packetizer_callback * handler) inline
Definition at line 35 of file packetizer.h.
Referenced by sstmac::hw::packet_flow_nic_packetizer::to_string().
virtual bool sstmac::hw::packetizer::spaceToSend (int vn, int num_bits) const private pure virtual
Implemented in sstmac::hw::packet_flow_memory_packetizer, and sstmac::hw::packet_flow_nic_packetizer.
Referenced by sstmac::hw::packet_flow_nic_packetizer::to_string().
void sstmac::hw::packetizer::start (int vn, message * payload)
Member Data Documentation
recv_cq sstmac::hw::packetizer::completion_queue_ private
Definition at line 58 of file packetizer.h.
packetizer_callback* sstmac::hw::packetizer::notifier_ private
Definition at line 70 of file packetizer.h.
int sstmac::hw::packetizer::packet_size_ private
Definition at line 68 of file packetizer.h.
std::map<int, std::list<pending_send> > sstmac::hw::packetizer::pending_ private
Definition at line 66 of file packetizer.h.
The documentation for this class was generated from the following file:
sstmac/hardware/common/packetizer.h