SST/macro: sstmac::sw::launcher Class Reference
sstmac::sw::launcher Class Reference
A launcher that can be cooperatively scheduled by a very naive scheduler.
#include <launcher.h>
Public Member Functions
launcher ()
virtual std::string to_string () const
virtual ~launcher () throw ()
Hasta la vista.
virtual void incoming_event (event *ev)
virtual void start ()
Public Member Functions inherited from sstmac::sw::library
virtual void unregister_all_libs ()
virtual std::string lib_name () const
virtual void init_os (operating_system *os)
virtual void consume_params (sprockit::sim_parameters *params)
operating_system * os () const
virtual ~library ()
Protected Attributes
bool is_completed_
spkt_unordered_map< app_id, int > num_apps_launched_
Protected Attributes inherited from sstmac::sw::library
operating_system * os_
std::string libname_
key::category key_cat_
Additional Inherited Members
Static Public Member Functions inherited from sstmac::sw::library
static library * construct_lib (const std::string &libname)
static library * construct_lib (const std::string &libname, const software_id &sid)
static void register_builder (const std::string &libname, library_builder *builder)
Protected Member Functions inherited from sstmac::sw::service
service ()
virtual ~service ()
Protected Member Functions inherited from sstmac::sw::library
library ()
void register_lib (library *lib)
This function is provided so that libraries can instantiate, register, and use other libraries.
virtual bool supported () const
This is usually convenient to define to check if the node was set up correctly to support what this library wants to do.
Static Protected Member Functions inherited from sstmac::sw::library
static library_builder * builder (const std::string &name)
Detailed Description
A launcher that can be cooperatively scheduled by a very naive scheduler.
Definition at line 24 of file launcher.h.
Constructor & Destructor Documentation
sstmac::sw::launcher::launcher ()
virtual sstmac::sw::launcher::~launcher () throw () virtual
Hasta la vista.
Referenced by to_string().
Member Function Documentation
virtual void sstmac::sw::launcher::incoming_event (event * ev) virtual
Implements sstmac::sw::service.
Referenced by to_string().
virtual void sstmac::sw::launcher::start () virtual
Reimplemented from sstmac::sw::service.
Referenced by to_string().
virtual std::string sstmac::sw::launcher::to_string () const inline virtual
Reimplemented from sstmac::sw::service.
Definition at line 32 of file launcher.h.
References incoming_event(), start(), and ~launcher().
Member Data Documentation
bool sstmac::sw::launcher::is_completed_ protected
Definition at line 46 of file launcher.h.
spkt_unordered_map<app_id, int> sstmac::sw::launcher::num_apps_launched_ protected
Definition at line 48 of file launcher.h.
The documentation for this class was generated from the following file:
sstmac/software/launch/launcher.h