SST/macro: sstmac::hw::network_message Class Reference
sstmac::hw::network_message Class Reference
#include <network_message.h>
Public Member Functions
network_message (node_id toaddr, node_id fromaddr, sw::task_id src, sw::task_id dst, long payload_bytes)
network_message (long payload_bytes)
network_message ()
virtual ~network_message ()
bool is_metadata () const
virtual network_message * clone_injection_ack () const
routing::algorithm_t route_algo () const
virtual void nic_reverse (type_t newtype)
void set_route_algo (routing::algorithm_t algo)
bool is_nic_ack () const
node_id toaddr () const
virtual void put_on_wire ()
node_id fromaddr () const
void set_toaddr (node_id addr)
void set_fromaddr (node_id addr)
void set_needs_ack (bool n)
virtual bool needs_ack () const
virtual void serialize_order (serializer &ser)
Serialize this message during parallel simulation.
void convert_to_ack ()
void set_net_id (const network_id &id)
network_id net_id () const
uint64_t unique_id () const
sw::task_id source_task () const
sw::task_id dest_task () const
type_t type () const
void set_type (type_t ty)
long source_thread (sw::operating_system *os) const
long dest_thread (sw::operating_system *os) const
virtual void reverse ()
long byte_length () const
Virtual function to return size.
Public Member Functions inherited from sstmac::message
virtual ~message ()
virtual std::string to_string () const
message ()
Public Member Functions inherited from sstmac::event
virtual bool is_packet () const
convenience methods
virtual bool is_credit () const
virtual bool is_failure () const
template<class T >
T * interface ()
Public Member Functions inherited from sprockit::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
virtual ~serializable ()
Static Public Member Functions
static const char * tostr (nic_event_t mut)
static const char * tostr (type_t ty)
Public Attributes
node_id toaddr_
node_id fromaddr_
Protected Member Functions
void clone_into (network_message *cln) const
Protected Attributes
network_id net_id_
bool needs_ack_
routing::algorithm_t route_algo_
sw::task_id src_task_
sw::task_id dest_task_
long bytes_
type_t type_
Protected Attributes inherited from sstmac::message
sw::key * key_
Private Types
enum type_t {
null_netmsg_type =0, rdma_get_request =1, rdma_get_sent_ack =2, rdma_get_nack =3,
rdma_put_sent_ack =4, rdma_put_nack =5, payload_sent_ack =6, payload =7,
rdma_get_payload =8, rdma_put_payload =9, nvram_get_request =10, nvram_get_payload =11,
failure_notification =12
}
Additional Inherited Members
Protected Types inherited from sprockit::serializable
enum cxn_flag_t { ConstructorFlag }
Detailed Description
Definition at line 12 of file network_message.h.
Member Enumeration Documentation
enum sstmac::hw::network_message::type_t private
Enumerator
null_netmsg_type
rdma_get_request
rdma_get_sent_ack
rdma_get_nack
rdma_put_sent_ack
rdma_put_nack
payload_sent_ack
payload
rdma_get_payload
rdma_put_payload
nvram_get_request
nvram_get_payload
failure_notification
Definition at line 25 of file network_message.h.
Constructor & Destructor Documentation
sstmac::hw::network_message::network_message (node_id toaddr, node_id fromaddr, sw::task_id src, sw::task_id dst, long payload_bytes)
sstmac::hw::network_message::network_message (long payload_bytes)
sstmac::hw::network_message::network_message ()
Referenced by clone_injection_ack().
virtual sstmac::hw::network_message::~network_message () inline virtual
Definition at line 52 of file network_message.h.
References is_metadata(), and tostr().
Member Function Documentation
long sstmac::hw::network_message::byte_length () const virtual
Virtual function to return size.
Child classes should impement this if they want any size tracked / modeled.
Returns
Zero size, meant to be implemented by children.
Implements sstmac::message.
Referenced by sstmac::transport_message::ImplementSerializable(), and set_type().
virtual network_message* sstmac::hw::network_message::clone_injection_ack () const inline virtual
Reimplemented in sstmac::transport_message.
Definition at line 64 of file network_message.h.
References clone_into(), and network_message().
void sstmac::hw::network_message::clone_into (network_message * cln) const protected
Referenced by clone_injection_ack().
void sstmac::hw::network_message::convert_to_ack ()
Referenced by needs_ack().
sw::task_id sstmac::hw::network_message::dest_task () const inline
Definition at line 147 of file network_message.h.
References dest_task_.
long sstmac::hw::network_message::dest_thread (sw::operating_system * os) const
Referenced by set_type().
node_id sstmac::hw::network_message::fromaddr () const inline virtual
Implements sstmac::message.
Definition at line 95 of file network_message.h.
References fromaddr_.
bool sstmac::hw::network_message::is_metadata () const
Referenced by ~network_message().
bool sstmac::hw::network_message::is_nic_ack () const
Referenced by set_route_algo().
virtual bool sstmac::hw::network_message::needs_ack () const inline virtual
Definition at line 115 of file network_message.h.
References convert_to_ack(), needs_ack_, payload, serialize_order(), and type_.
network_id sstmac::hw::network_message::net_id () const inline
Definition at line 132 of file network_message.h.
References net_id_.
virtual void sstmac::hw::network_message::nic_reverse (type_t newtype) virtual
Referenced by route_algo().
virtual void sstmac::hw::network_message::put_on_wire () virtual
Reimplemented in sstmac::transport_message.
Referenced by toaddr().
virtual void sstmac::hw::network_message::reverse () virtual
Reimplemented in sstmac::transport_message.
Referenced by set_type().
routing::algorithm_t sstmac::hw::network_message::route_algo () const inline
Definition at line 71 of file network_message.h.
References nic_reverse(), and route_algo_.
virtual void sstmac::hw::network_message::serialize_order (serializer & ser) virtual
Serialize this message during parallel simulation.
Parameters
ser The serializer to use
Reimplemented from sstmac::message.
Reimplemented in sstmac::transport_message.
Referenced by needs_ack().
void sstmac::hw::network_message::set_fromaddr (node_id addr) inline
Definition at line 105 of file network_message.h.
References fromaddr_.
void sstmac::hw::network_message::set_needs_ack (bool n) inline
Definition at line 110 of file network_message.h.
References needs_ack_.
void sstmac::hw::network_message::set_net_id (const network_id & id) inline
Definition at line 127 of file network_message.h.
References net_id_.
void sstmac::hw::network_message::set_route_algo (routing::algorithm_t algo) inline
Definition at line 79 of file network_message.h.
References is_nic_ack(), and route_algo_.
void sstmac::hw::network_message::set_toaddr (node_id addr) inline
Definition at line 100 of file network_message.h.
References toaddr_.
void sstmac::hw::network_message::set_type (type_t ty) inline
Definition at line 157 of file network_message.h.
References byte_length(), dest_thread(), reverse(), source_thread(), and type_.
sw::task_id sstmac::hw::network_message::source_task () const inline
Definition at line 142 of file network_message.h.
References src_task_.
long sstmac::hw::network_message::source_thread (sw::operating_system * os) const
Referenced by set_type().
node_id sstmac::hw::network_message::toaddr () const inline virtual
Implements sstmac::message.
Definition at line 87 of file network_message.h.
References put_on_wire(), and toaddr_.
static const char* sstmac::hw::network_message::tostr (nic_event_t mut) static
Referenced by ~network_message().
static const char* sstmac::hw::network_message::tostr (type_t ty) static
type_t sstmac::hw::network_message::type () const inline
Definition at line 152 of file network_message.h.
References type_.
uint64_t sstmac::hw::network_message::unique_id () const inline virtual
Implements sstmac::message.
Definition at line 137 of file network_message.h.
References net_id_.
Member Data Documentation
long sstmac::hw::network_message::bytes_ protected
Definition at line 192 of file network_message.h.
sw::task_id sstmac::hw::network_message::dest_task_ protected
Definition at line 190 of file network_message.h.
Referenced by sstmac::transport_message::dest(), dest_task(), and sstmac::transport_message::set_dest().
node_id sstmac::hw::network_message::fromaddr_
Definition at line 175 of file network_message.h.
Referenced by fromaddr(), and set_fromaddr().
bool sstmac::hw::network_message::needs_ack_ protected
Definition at line 184 of file network_message.h.
Referenced by needs_ack(), and set_needs_ack().
network_id sstmac::hw::network_message::net_id_ protected
Definition at line 182 of file network_message.h.
Referenced by net_id(), set_net_id(), and unique_id().
routing::algorithm_t sstmac::hw::network_message::route_algo_ protected
Definition at line 186 of file network_message.h.
Referenced by route_algo(), and set_route_algo().
sw::task_id sstmac::hw::network_message::src_task_ protected
Definition at line 188 of file network_message.h.
Referenced by sstmac::transport_message::set_src(), source_task(), and sstmac::transport_message::src().
node_id sstmac::hw::network_message::toaddr_
Definition at line 173 of file network_message.h.
Referenced by set_toaddr(), and toaddr().
type_t sstmac::hw::network_message::type_ protected
Definition at line 194 of file network_message.h.
Referenced by needs_ack(), set_type(), and type().
The documentation for this class was generated from the following file:
sstmac/hardware/network/network_message.h