SST/macro: sstmac::sw::lib_sleep Class Reference
sstmac::sw::lib_sleep Class Reference
#include <lib_sleep.h>
Public Member Functions
virtual ~lib_sleep ()
lib_sleep (software_id id)
lib_sleep (const std::string &id)
virtual void incoming_event (event *ev)
void sleep (timestamp time)
virtual bool supported () const
This is usually convenient to define to check if the node was set up correctly to support what this library wants to do.
Public Member Functions inherited from sstmac::sw::library
virtual void unregister_all_libs ()
virtual std::string to_string () const
virtual std::string lib_name () const
virtual void init_os (operating_system *os)
virtual void consume_params (sprockit::sim_parameters *params)
operating_system * os () const
virtual ~library ()
Static Public Attributes
static key::category key_category
Additional Inherited Members
Static Public Member Functions inherited from sstmac::sw::library
static library * construct_lib (const std::string &libname)
static library * construct_lib (const std::string &libname, const software_id &sid)
static void register_builder (const std::string &libname, library_builder *builder)
Protected Member Functions inherited from sstmac::sw::library
library ()
void register_lib (library *lib)
This function is provided so that libraries can instantiate, register, and use other libraries.
Static Protected Member Functions inherited from sstmac::sw::library
static library_builder * builder (const std::string &name)
Protected Attributes inherited from sstmac::sw::library
operating_system * os_
std::string libname_
key::category key_cat_
Detailed Description
Definition at line 22 of file lib_sleep.h.
Constructor & Destructor Documentation
virtual sstmac::sw::lib_sleep::~lib_sleep () inline virtual
Definition at line 29 of file lib_sleep.h.
References lib_sleep().
sstmac::sw::lib_sleep::lib_sleep (software_id id)
Referenced by ~lib_sleep().
sstmac::sw::lib_sleep::lib_sleep (const std::string & id)
Member Function Documentation
virtual void sstmac::sw::lib_sleep::incoming_event (event * ev) inline virtual
Implements sstmac::sw::library.
Definition at line 37 of file lib_sleep.h.
References sstmac::sw::library::incoming_event(), sleep(), and supported().
void sstmac::sw::lib_sleep::sleep (timestamp time)
Referenced by incoming_event().
virtual bool sstmac::sw::lib_sleep::supported () const virtual
This is usually convenient to define to check if the node was set up correctly to support what this library wants to do.
This function is not currently a strict part of an interface.
Returns
true if the hardware supports this libraries functions
Reimplemented from sstmac::sw::library.
Referenced by incoming_event().
Member Data Documentation
key::category sstmac::sw::lib_sleep::key_category static
Definition at line 25 of file lib_sleep.h.
The documentation for this class was generated from the following file:
sstmac/software/libraries/compute/lib_sleep.h