SST/macro: sstmac::hw::minimal_adaptive_router Class Reference
sstmac::hw::minimal_adaptive_router Class Reference
#include <minad_routing.h>
Public Member Functions
virtual std::string to_string () const
virtual void route (packet *pkt)
virtual void finalize_init ()
Public Member Functions inherited from sstmac::hw::minimal_router
virtual ~minimal_router ()
std::string to_string () const
Public Member Functions inherited from sstmac::hw::structured_router
virtual void set_topology (topology *top)
virtual void set_switch (network_switch *sw)
void minimal_route_to_node (node_id node_addr, routing_info::path &path)
void minimal_routes_to_node (node_id node_addr, routing_info::path &current_path, routing_info::path_set &path)
virtual void minimal_route_to_switch (switch_id sw_addr, routing_info::path &path)
virtual void productive_paths_to_switch (switch_id dst, routing_info::path_set &paths)
Additional Inherited Members
Protected Member Functions inherited from sstmac::hw::minimal_router
virtual void route (packet *pkt, routing_info::path_set &paths)
Protected Attributes inherited from sstmac::hw::structured_router
structured_topology * regtop_
Detailed Description
Definition at line 9 of file minad_routing.h.
Member Function Documentation
virtual void sstmac::hw::minimal_adaptive_router::finalize_init () virtual
Reimplemented from sstmac::hw::minimal_router.
Referenced by to_string().
virtual void sstmac::hw::minimal_adaptive_router::route (packet * pkt) virtual
Reimplemented from sstmac::hw::minimal_router.
Referenced by to_string().
virtual std::string sstmac::hw::minimal_adaptive_router::to_string () const inline virtual
Definition at line 15 of file minad_routing.h.
References finalize_init(), and route().
The documentation for this class was generated from the following file:
sstmac/hardware/router/minad_routing.h