SST/macro: sstmac::hw::xpress_ring Class Reference
sstmac::hw::xpress_ring Class Reference
#include <xpressring.h>
Public Types
enum port_t { up_port = 0, down_port = 1, jump_up_port = 2, jump_down_port = 3 }
enum stride_t { jump = 0, step = 1 }
Public Member Functions
virtual ~xpress_ring ()
virtual std::string to_string () const
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual void connect_objects (internal_connectable_map &objects)
Given a set of connectables, connect them appropriately.
virtual long num_leaf_switches () const
Structured topologies can be direct (torus) or indirect (fat tree).
virtual void minimal_route_to_coords (const coordinates &src_coords, const coordinates &dest_coords, structured_routable::path &path) const
Workhorse function for implementing minimal_route_to_switch and #minimal_route_to_node.
virtual int minimal_distance (const coordinates &src_coords, const coordinates &dest_coords) const
The function accepts either source or node coordinates.
virtual int ndimensions () const
The number of distinct 'dimensions' in the topology.
virtual switch_id switch_number (const coordinates &coords) const
virtual void productive_path (int dim, const coordinates &src, const coordinates &dst, structured_routable::path &path) const
virtual int radix () const
virtual long num_switches () const
int diameter () const
virtual int convert_to_port (int dim, int dir) const
Public Member Functions inherited from sstmac::hw::structured_topology
virtual ~structured_topology ()
virtual void build_internal_connectables (internal_connectable_map &connectables, sprockit::factory< connectable > *factory, partition *part, int my_rank, sprockit::sim_parameters *params, connectable *dummy)
virtual void build_endpoint_connectables (end_point_connectable_map &connectables, sprockit::factory< connectable > *factory, partition *part, int my_rank, sprockit::sim_parameters *params)
virtual void build_interface_connectables (int conc, end_point_connectable_map &connectables, sprockit::factory2< connectable > *nic_factory, partition *part, int my_rank, sprockit::sim_parameters *params, sprockit::factory_type *interconnect)
virtual void minimal_routes_to_coords (const coordinates &src_coords, const coordinates &dest_coords, structured_routable::path &current_path, structured_routable::path_set &paths) const
virtual int endpoints_per_switch (switch_id addr) const
Given a switch address, return number of nodes connected to it.
virtual int num_nodes () const
virtual int num_endpoints () const
coordinates switch_coords (switch_id swid) const
Compute coordinates (e.g.
virtual coordinates node_coords (node_id nid) const
Compute coordinates (e.g.
coordinates endpoint_coords (node_id nid) const
virtual switch_id endpoint_to_ejection_switch (node_id nodeaddr, int &switch_port) const
virtual switch_id endpoint_to_injection_switch (node_id nodeaddr, int &switch_port) const
virtual int endpoint_to_ejection_port (node_id addr) const
virtual int endpoint_to_injection_port (node_id addr) const
virtual int endpoint_to_switch_port (node_id nid) const
void finalize_init ()
virtual void productive_paths (structured_routable::path_set &paths, const coordinates &current, const coordinates &dst)
std::string label (node_id nid) const
std::string label (switch_id sid) const
virtual void minimal_route_to_switch (switch_id current_sw_addr, switch_id dest_sw_addr, structured_routable::path &path) const
Implementation of topology::minimal_route_to_switch.
virtual void minimal_routes_to_switch (switch_id current_sw_addr, switch_id dest_sw_addr, structured_routable::path &current_path, structured_routable::path_set &paths) const
virtual void eject_paths_on_switch (node_id dest_addr, switch_id sw_addr, structured_routable::path_set &paths) const
virtual int num_hops_to_node (node_id src, node_id dst) const
virtual std::vector< node_id > nodes_connected_to_injection_switch (switch_id swaddr) const
virtual std::vector< node_id > nodes_connected_to_ejection_switch (switch_id swid) const
virtual coordinates neighbor_at_port (switch_id sid, int port) const
virtual node_id node_addr (const coordinates &coords) const
virtual node_id node_addr (const coordinates &sw_coords, int port) const
virtual void send_partners (traffic_pattern::type_t ty, node_id src_node, std::vector< node_id > &partners) const
virtual void recv_partners (traffic_pattern::type_t ty, node_id src_node, std::vector< node_id > &partners) const
Protected Member Functions
virtual void compute_switch_coords (switch_id swid, coordinates &coords) const
Compute coordinates (e.g.
int num_hops (int total_distance) const
Protected Member Functions inherited from sstmac::hw::structured_topology
void configure_injection_geometry (std::vector< int > &redundancies)
virtual std::vector< node_id > nodes_connected_to_switch (switch_id swaddr) const
structured_topology ()
void partners (bool get_send_partner, traffic_pattern::type_t ty, node_id src, std::vector< node_id > &partner_list) const
virtual void nearest_neighbor_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
virtual void tornado_recv_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
virtual void tornado_send_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
virtual void bit_complement_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
Protected Attributes
int ring_size_
int jump_size_
Protected Attributes inherited from sstmac::hw::structured_topology
int eject_geometric_id_
int injection_redundancy_
bool outputgraph_
Detailed Description
Definition at line 6 of file xpressring.h.
Member Enumeration Documentation
enum sstmac::hw::xpress_ring::port_t
Enumerator
up_port
down_port
jump_up_port
jump_down_port
Definition at line 10 of file xpressring.h.
enum sstmac::hw::xpress_ring::stride_t
Enumerator
jump
step
Definition at line 17 of file xpressring.h.
Constructor & Destructor Documentation
virtual sstmac::hw::xpress_ring::~xpress_ring () inline virtual
Definition at line 22 of file xpressring.h.
Member Function Documentation
virtual void sstmac::hw::xpress_ring::compute_switch_coords (switch_id swid, coordinates & coords) const protected virtual
Compute coordinates (e.g.
X,Y,Z for 3D torus)
Parameters
swid The unique index defining a switch location
coords [inout] The unique coordinates of the switch
Implements sstmac::hw::structured_topology.
Referenced by num_switches().
virtual void sstmac::hw::xpress_ring::connect_objects (internal_connectable_map & objects) virtual
Given a set of connectables, connect them appropriately.
Parameters
objects The set of objects to connect
cloner If in parallel mode, not all objects may exist. The factory creates missing objects.
Exceptions
value_error If invalid switchid is passed to cloner
Implements sstmac::hw::structured_topology.
Referenced by to_string().
virtual int sstmac::hw::xpress_ring::convert_to_port (int dim, int dir) const virtual
Referenced by num_switches().
int sstmac::hw::xpress_ring::diameter () const virtual
Implements sstmac::hw::structured_topology.
Referenced by num_switches().
virtual void sstmac::hw::xpress_ring::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::hw::structured_topology.
Referenced by to_string().
virtual int sstmac::hw::xpress_ring::minimal_distance (const coordinates & src_coords, const coordinates & dest_coords) const virtual
The function accepts either source or node coordinates.
This gives the minimal distance counting the number of hops between switches. If node coordinates are given, the last coordinate is just ignored.
Parameters
src_coords. The source coordinates. This can be either switch or node coordinates.
dest_coords. The destination coordinates. This can be either switch or node coordinates.
Returns
The number of hops to final destination
Implements sstmac::hw::structured_topology.
Referenced by to_string().
virtual void sstmac::hw::xpress_ring::minimal_route_to_coords (const coordinates & src_coords, const coordinates & dest_coords, structured_routable::path & path) const virtual
Workhorse function for implementing minimal_route_to_switch and #minimal_route_to_node.
Given source/dest coordinates, find the minimal path.
Parameters
current_sw_addr The addr of the current switch
dest_sw_addr The addr of the destination switch
path [inout] A complete path descriptor to the destination switch
Implements sstmac::hw::structured_topology.
Referenced by to_string().
virtual int sstmac::hw::xpress_ring::ndimensions () const virtual
The number of distinct 'dimensions' in the topology.
This can correspond directly to standard X,Y,Z dimensions or the the number of levels in a fat tree. The keyword topology_redundant vector should have this many entries.
Implements sstmac::hw::structured_topology.
Referenced by to_string().
int sstmac::hw::xpress_ring::num_hops (int total_distance) const protected
Referenced by num_switches().
virtual long sstmac::hw::xpress_ring::num_leaf_switches () const virtual
Structured topologies can be direct (torus) or indirect (fat tree).
We therefore need to distinguish the total number of switches and the number of leaf switches - i.e. those directly connected to nodes. For direct topologies, num_switches and num_leaf_switches are the same. For indirect, num_leaf_switches < num_switches.
Returns
The number of leaf switches directly connected to compute nodes
Implements sstmac::hw::structured_topology.
Referenced by to_string().
virtual long sstmac::hw::xpress_ring::num_switches () const inline virtual
Definition at line 114 of file xpressring.h.
References compute_switch_coords(), convert_to_port(), diameter(), num_hops(), and ring_size_.
virtual void sstmac::hw::xpress_ring::productive_path (int dim, const coordinates & src, const coordinates & dst, structured_routable::path & path) const virtual
Parameters
dim The dimension you want to move in. You might need to traverse other dimensions FIRST before you make progress on this dimension.
src The coordinates of the source switch
dst The coordinates of the dest switch
path [inout] The path configuration for making progress on dim
Implements sstmac::hw::structured_topology.
Referenced by to_string().
virtual int sstmac::hw::xpress_ring::radix () const inline virtual
Definition at line 109 of file xpressring.h.
virtual switch_id sstmac::hw::xpress_ring::switch_number (const coordinates & coords) const virtual
Implements sstmac::hw::structured_topology.
Referenced by to_string().
virtual std::string sstmac::hw::xpress_ring::to_string () const inline virtual
Definition at line 25 of file xpressring.h.
References connect_objects(), init_factory_params(), minimal_distance(), minimal_route_to_coords(), ndimensions(), num_leaf_switches(), productive_path(), and switch_number().
Member Data Documentation
int sstmac::hw::xpress_ring::jump_size_ protected
Definition at line 139 of file xpressring.h.
int sstmac::hw::xpress_ring::ring_size_ protected
Definition at line 137 of file xpressring.h.
Referenced by num_switches().
The documentation for this class was generated from the following file:
docs/developer/tutorials/programming/topology/xpressring.h