SST/macro: sstmac::hw::null_scheduler Class Reference
sstmac::hw::null_scheduler Class Reference
#include <null_scheduler.h>
Public Member Functions
std::string to_string () const
virtual compute_scheduler * clone (node_id nid, sw::operating_system *os) const
void handle (sst_message *msg)
Protected Member Functions
bool find_open_core (const sw::compute_message *&msg, int &core_assignment)
void start_next_suspended (int core)
void add_suspended (const sw::compute_message *&msg, int core)
Detailed Description
Definition at line 9 of file null_scheduler.h.
Member Function Documentation
void sstmac::hw::null_scheduler::add_suspended (const sw::compute_message *& msg, int core) protected
Referenced by handle().
virtual compute_scheduler* sstmac::hw::null_scheduler::clone (node_id nid, sw::operating_system * os) const virtual
Referenced by to_string().
bool sstmac::hw::null_scheduler::find_open_core (const sw::compute_message *& msg, int & core_assignment) protected
Referenced by handle().
void sstmac::hw::null_scheduler::handle (sst_message * msg) inline
Definition at line 22 of file null_scheduler.h.
References add_suspended(), find_open_core(), and start_next_suspended().
void sstmac::hw::null_scheduler::start_next_suspended (int core) protected
Referenced by handle().
std::string sstmac::hw::null_scheduler::to_string () const inline
Definition at line 14 of file null_scheduler.h.
References clone().
The documentation for this class was generated from the following file:
sstmac/software/process/null_scheduler.h