SST/macro: sstmac::message Class Reference
sstmac::message Class Reference abstract
A class describing an event.
#include <sst_message.h>
Public Member Functions
virtual ~message ()
virtual std::string to_string () const
message ()
virtual long byte_length () const =0
Virtual function to return size.
virtual void serialize_order (serializer &ser)
Serialize this message during parallel simulation.
virtual node_id toaddr () const =0
virtual node_id fromaddr () const =0
virtual uint64_t unique_id () const =0
Public Member Functions inherited from sstmac::event
void serialize_order (serializer &ser)
virtual bool is_packet () const
convenience methods
virtual bool is_credit () const
virtual bool is_failure () const
template<class T >
T * interface ()
Public Member Functions inherited from sprockit::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
virtual ~serializable ()
Protected Attributes
sw::key * key_
Additional Inherited Members
Protected Types inherited from sprockit::serializable
enum cxn_flag_t { ConstructorFlag }
Detailed Description
A class describing an event.
Definition at line 32 of file sst_message.h.
Constructor & Destructor Documentation
virtual sstmac::message::~message () inline virtual
Definition at line 38 of file sst_message.h.
sstmac::message::message ()
Referenced by to_string().
Member Function Documentation
virtual long sstmac::message::byte_length () const pure virtual
Virtual function to return size.
Child classes should impement this if they want any size tracked / modeled.
Returns
Zero size, meant to be implemented by children.
Implemented in sstmac::hw::network_message, and sstmac::hw::memory_message.
Referenced by to_string().
virtual node_id sstmac::message::fromaddr () const pure virtual
Implemented in sstmac::hw::network_message, and sstmac::hw::memory_message.
Referenced by to_string().
virtual void sstmac::message::serialize_order (serializer & ser) virtual
Serialize this message during parallel simulation.
Parameters
ser The serializer to use
Implements sprockit::serializable.
Reimplemented in sstmac::hw::network_message, and sstmac::transport_message.
Referenced by to_string().
virtual std::string sstmac::message::to_string () const inline virtual
Implements sstmac::event.
Reimplemented in sstmac::transport_message.
Definition at line 41 of file sst_message.h.
References byte_length(), fromaddr(), message(), serialize_order(), toaddr(), and unique_id().
virtual node_id sstmac::message::toaddr () const pure virtual
Implemented in sstmac::hw::network_message, and sstmac::hw::memory_message.
Referenced by to_string().
virtual uint64_t sstmac::message::unique_id () const pure virtual
Implemented in sstmac::hw::network_message, and sstmac::hw::memory_message.
Referenced by to_string().
Member Data Documentation
sw::key* sstmac::message::key_ protected
Definition at line 75 of file sst_message.h.
The documentation for this class was generated from the following file:
sstmac/common/messages/sst_message.h