SST/macro: sstmac::bitwisevaluepayload< T > Class Template Reference
sstmac::bitwisevaluepayload< T > Class Template Reference
Network payload consisting of a value with sensible copy semantics.
#include <value_payload.h>
Public Types
typedef sprockit::refcount_ptr< bitwisevaluepayload< T > > ptr
typedef sprockit::refcount_ptr< const bitwisevaluepayload< T > > const_ptr
Public Types inherited from sstmac::payload
typedef sprockit::refcount_ptr< payload > ptr
typedef sprockit::refcount_ptr< const payload > const_ptr
Public Member Functions
virtual ~bitwisevaluepayload ()
payload::const_ptr clone () const
Clone this object.
payload::const_ptr bitwise_or (const payload::const_ptr &other) const
Logical or comparator.
payload::const_ptr bitwise_xor (const payload::const_ptr &other) const
Logical xor comparator.
payload::const_ptr bitwise_and (const payload::const_ptr &other) const
Logical and comparator.
virtual void serialize_order (sstmac::serializer &ser)
virtual std::string to_string () const
Strinfier.
Public Member Functions inherited from sstmac::payload
virtual ~payload ()
Goodbye.
virtual void recover (sw::api *api)
virtual void assign (void *data)
Public Member Functions inherited from sprockit::ptr_type
ptr_type ()
int nreferences () const
virtual ~ptr_type ()
Public Member Functions inherited from sprockit::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
virtual ~serializable ()
Static Public Member Functions
static bitwisevaluepayload::const_ptr construct (const T &inval)
Construct a new valuepayload.
static bitwisevaluepayload::const_ptr construct (const T &inval, size_t s)
template<typename Other >
static bitwisevaluepayload::const_ptr construct (const Other &inval)
Construct a new valuepayload with type conversion.
static bitwisevaluepayload::ptr construct ()
Static Public Member Functions inherited from sstmac::payload
static ptr null ()
Convenience function to get a null payload pointer.
Protected Member Functions
bitwisevaluepayload (const T &inval, size_t size=sizeof(T))
Construction time.
template<typename Other >
bitwisevaluepayload (const Other &inval, size_t size=sizeof(T))
Construction with type conversion.
bitwisevaluepayload (const value_payload< T > &other, size_t size=sizeof(T))
Private copy constructor.
bitwisevaluepayload ()
Protected Member Functions inherited from sstmac::value_payload< T >
value_payload (const T &inval, size_t size=sizeof(T))
template<typename Other >
value_payload (const Other &inval, size_t size=sizeof(T))
Construction with type conversion.
value_payload (const value_payload< T > &other, size_t size=sizeof(T))
Private copy constructor.
Protected Member Functions inherited from sstmac::payload
payload ()
Empty protected constructor to enforce using construct()
Protected Member Functions inherited from sprockit::ptr_type
void incref ()
int decref ()
Additional Inherited Members
Protected Types inherited from sprockit::serializable
enum cxn_flag_t { ConstructorFlag }
Protected Attributes inherited from sstmac::value_payload< T >
T data_
The data we keep.
size_t size_
Detailed Description
template<typename T>
class sstmac::bitwisevaluepayload< T >
Network payload consisting of a value with sensible copy semantics.
Don't use this for pointer types, since you will break assumptions about const-ness or protection of underlying data.
Definition at line 316 of file value_payload.h.
Member Typedef Documentation
template<typename T> typedef sprockit::refcount_ptr<const bitwisevaluepayload<T> > sstmac::bitwisevaluepayload< T >::const_ptr
Definition at line 320 of file value_payload.h.
template<typename T> typedef sprockit::refcount_ptr<bitwisevaluepayload<T> > sstmac::bitwisevaluepayload< T >::ptr
Definition at line 319 of file value_payload.h.
Constructor & Destructor Documentation
template<typename T> virtual sstmac::bitwisevaluepayload< T >::~bitwisevaluepayload () inline virtual
Definition at line 323 of file value_payload.h.
template<typename T> sstmac::bitwisevaluepayload< T >::bitwisevaluepayload (const T & inval, size_t size = sizeof(T)) inline protected
Construction time.
Definition at line 429 of file value_payload.h.
template<typename T> template<typename Other > sstmac::bitwisevaluepayload< T >::bitwisevaluepayload (const Other & inval, size_t size = sizeof(T)) inline protected
Construction with type conversion.
Definition at line 435 of file value_payload.h.
template<typename T> sstmac::bitwisevaluepayload< T >::bitwisevaluepayload (const value_payload< T > & other, size_t size = sizeof(T)) inline protected
Private copy constructor.
Definition at line 440 of file value_payload.h.
template<typename T> sstmac::bitwisevaluepayload< T >::bitwisevaluepayload () inline protected
Definition at line 444 of file value_payload.h.
Member Function Documentation
template<typename T> payload::const_ptr sstmac::bitwisevaluepayload< T >::bitwise_and (const payload::const_ptr & other) const inline virtual
Logical and comparator.
Parameters
other
Returns
Reimplemented from sstmac::value_payload< T >.
Definition at line 398 of file value_payload.h.
References sstmac::value_payload< T >::data(), and ptr_safe_cast.
template<typename T> payload::const_ptr sstmac::bitwisevaluepayload< T >::bitwise_or (const payload::const_ptr & other) const inline virtual
Logical or comparator.
Parameters
other
Returns
Reimplemented from sstmac::value_payload< T >.
Definition at line 360 of file value_payload.h.
References sstmac::value_payload< T >::data(), and ptr_safe_cast.
template<typename T> payload::const_ptr sstmac::bitwisevaluepayload< T >::bitwise_xor (const payload::const_ptr & other) const inline virtual
Logical xor comparator.
Parameters
other
Returns
Reimplemented from sstmac::value_payload< T >.
Definition at line 379 of file value_payload.h.
References sstmac::value_payload< T >::data(), and ptr_safe_cast.
template<typename T> payload::const_ptr sstmac::bitwisevaluepayload< T >::clone () const inline virtual
Clone this object.
Reimplemented from sstmac::value_payload< T >.
Definition at line 350 of file value_payload.h.
template<typename T> static bitwisevaluepayload::const_ptr sstmac::bitwisevaluepayload< T >::construct (const T & inval) inline static
Construct a new valuepayload.
Definition at line 327 of file value_payload.h.
template<typename T> static bitwisevaluepayload::const_ptr sstmac::bitwisevaluepayload< T >::construct (const T & inval, size_t s) inline static
Definition at line 332 of file value_payload.h.
template<typename T> template<typename Other > static bitwisevaluepayload::const_ptr sstmac::bitwisevaluepayload< T >::construct (const Other & inval) inline static
Construct a new valuepayload with type conversion.
Definition at line 339 of file value_payload.h.
template<typename T> static bitwisevaluepayload::ptr sstmac::bitwisevaluepayload< T >::construct () inline static
Definition at line 344 of file value_payload.h.
template<typename T> virtual void sstmac::bitwisevaluepayload< T >::serialize_order (sstmac::serializer & ser) inline virtual
Reimplemented from sstmac::value_payload< T >.
Definition at line 412 of file value_payload.h.
References sstmac::value_payload< T >::serialize_order().
template<typename T> virtual std::string sstmac::bitwisevaluepayload< T >::to_string () const inline virtual
Strinfier.
Returns
a std::string description
Reimplemented from sstmac::value_payload< T >.
Definition at line 421 of file value_payload.h.
References sstmac::value_payload< T >::data().
The documentation for this class was generated from the following file:
sstmac/common/messages/value_payload.h