SST/macro: sstmac::sw::threading_interface Class Reference
sstmac::sw::threading_interface Class Reference abstract
#include <threading_interface.h>
Public Member Functions
virtual ~threading_interface ()
virtual threading_interface * copy ()=0
virtual void init_context ()=0
virtual void destroy_context ()=0
virtual void start_context (int physical_thread_id, void *stack, size_t stacksize, void(*func)(void *), void *args, threading_interface *yield_to)=0
Start a new context.
virtual void swap_context (threading_interface *to)=0
Swap context.
virtual void complete_context (threading_interface *to)=0
This is called when we have completed running the thread.
Detailed Description
Definition at line 24 of file threading_interface.h.
Constructor & Destructor Documentation
virtual sstmac::sw::threading_interface::~threading_interface () inline virtual
Definition at line 27 of file threading_interface.h.
References complete_context(), copy(), destroy_context(), init_context(), start_context(), and swap_context().
Member Function Documentation
virtual void sstmac::sw::threading_interface::complete_context (threading_interface * to) pure virtual
This is called when we have completed running the thread.
It is called in the from context.
Implemented in sstmac::sw::threading_pth.
Referenced by ~threading_interface().
virtual threading_interface* sstmac::sw::threading_interface::copy () pure virtual
Implemented in sstmac::sw::threading_pth.
Referenced by ~threading_interface().
virtual void sstmac::sw::threading_interface::destroy_context () pure virtual
Implemented in sstmac::sw::threading_pth.
Referenced by ~threading_interface().
virtual void sstmac::sw::threading_interface::init_context () pure virtual
Implemented in sstmac::sw::threading_pth.
Referenced by ~threading_interface().
virtual void sstmac::sw::threading_interface::start_context (int physical_thread_id, void * stack, size_t stacksize, void(*)(void *) func, void * args, threading_interface * yield_to) pure virtual
Start a new context.
Implemented in sstmac::sw::threading_pth.
Referenced by ~threading_interface().
virtual void sstmac::sw::threading_interface::swap_context (threading_interface * to) pure virtual
Swap context.
Implemented in sstmac::sw::threading_pth.
Referenced by ~threading_interface().
The documentation for this class was generated from the following file:
sstmac/software/threading/threading_interface.h