SST/macro: sstmac::sw::launch_info Class Reference
sstmac::sw::launch_info Class Reference
#include <launch_info.h>
Public Member Functions
launch_info (app *app, app_id aid, long num_tasks, const std::vector< int > &core_affinities)
virtual std::string to_string () const
int core_affinity (int intranode_rank) const
app_id aid () const
app * app_template () const
virtual ~launch_info ()
Protected Attributes
app * apptype_
app_id aid_
long num_tasks_
std::vector< int > core_affinities_
Detailed Description
Definition at line 22 of file launch_info.h.
Constructor & Destructor Documentation
sstmac::sw::launch_info::launch_info (app * app, app_id aid, long num_tasks, const std::vector< int > & core_affinities)
virtual sstmac::sw::launch_info::~launch_info () virtual
Referenced by app_template().
Member Function Documentation
app_id sstmac::sw::launch_info::aid () const inline
Definition at line 39 of file launch_info.h.
References aid_.
app* sstmac::sw::launch_info::app_template () const inline
Definition at line 44 of file launch_info.h.
References apptype_, and ~launch_info().
int sstmac::sw::launch_info::core_affinity (int intranode_rank) const
Referenced by to_string().
virtual std::string sstmac::sw::launch_info::to_string () const inline virtual
Definition at line 31 of file launch_info.h.
References core_affinity().
Member Data Documentation
app_id sstmac::sw::launch_info::aid_ protected
Definition at line 53 of file launch_info.h.
Referenced by aid().
app* sstmac::sw::launch_info::apptype_ protected
Definition at line 51 of file launch_info.h.
Referenced by app_template().
std::vector<int> sstmac::sw::launch_info::core_affinities_ protected
Definition at line 57 of file launch_info.h.
long sstmac::sw::launch_info::num_tasks_ protected
Definition at line 55 of file launch_info.h.
The documentation for this class was generated from the following file:
sstmac/software/launch/launch_info.h