SST/macro: sprockit::debug_int Class Reference
sprockit::debug_int Class Reference
#include <debug.h>
Public Member Functions
debug_int (int slot)
debug_int ()
debug_int & operator~ ()
void init (int slot)
debug_int & operator= (const debug_int &rhs)
operator bool () const
std::string to_string () const
Public Attributes
uint64_t fields
Detailed Description
Definition at line 24 of file debug.h.
Constructor & Destructor Documentation
sprockit::debug_int::debug_int (int slot) inline
Definition at line 27 of file debug.h.
References init().
sprockit::debug_int::debug_int () inline
Definition at line 31 of file debug.h.
References fields.
Member Function Documentation
void sprockit::debug_int::init (int slot) inline
Definition at line 42 of file debug.h.
References fields.
Referenced by debug_int().
sprockit::debug_int::operator bool () const inline
Definition at line 51 of file debug.h.
References fields, and to_string().
debug_int& sprockit::debug_int::operator= (const debug_int & rhs) inline
Definition at line 46 of file debug.h.
References fields.
debug_int& sprockit::debug_int::operator~ () inline
Definition at line 36 of file debug.h.
References fields.
std::string sprockit::debug_int::to_string () const
Referenced by operator bool().
Member Data Documentation
uint64_t sprockit::debug_int::fields
Definition at line 58 of file debug.h.
Referenced by debug_int(), init(), operator bool(), sprockit::operator&(), operator=(), sprockit::operator|(), and operator~().
The documentation for this class was generated from the following file:
sprockit/sprockit/debug.h