SST/macro: sstmac::hw::routing_info Class Reference
sstmac::hw::routing_info Class Reference
#include <routing_info.h>
Classes
struct path
class path_set
Public Types
enum metadata_slot { valiant_stage, final_stage, crossed_timeline }
Public Member Functions
routing_info ()
path & current_path ()
void assign_path (const path &pth)
void check_vc ()
virtual int vc () const
int port () const
routing::algorithm_t route_algo () const
void set_route_algo (routing::algorithm_t algo)
void init_default_algo (routing::algorithm_t algo)
void set_dest_switch (switch_id sid)
switch_id dest_switch () const
Static Public Member Functions
static const char * tostr (routing::algorithm_t algo)
Static Public Attributes
static const int uninitialized = -123
Protected Attributes
path path_
switch_id dest_switch_
routing::algorithm_t algo_
Detailed Description
Definition at line 26 of file routing_info.h.
Member Enumeration Documentation
enum sstmac::hw::routing_info::metadata_slot
Enumerator
valiant_stage
final_stage
crossed_timeline
Definition at line 29 of file routing_info.h.
Constructor & Destructor Documentation
sstmac::hw::routing_info::routing_info () inline
Definition at line 102 of file routing_info.h.
References tostr().
Member Function Documentation
void sstmac::hw::routing_info::assign_path (const path & pth) inline
Definition at line 116 of file routing_info.h.
References path_.
void sstmac::hw::routing_info::check_vc () inline
Definition at line 121 of file routing_info.h.
References path_, uninitialized, and sstmac::hw::routing_info::path::vc.
path& sstmac::hw::routing_info::current_path () inline
Definition at line 111 of file routing_info.h.
References path_.
switch_id sstmac::hw::routing_info::dest_switch () const inline
Definition at line 157 of file routing_info.h.
References dest_switch_.
void sstmac::hw::routing_info::init_default_algo (routing::algorithm_t algo) inline
Definition at line 147 of file routing_info.h.
References algo_, and sstmac::hw::routing::deflt.
int sstmac::hw::routing_info::port () const inline
Definition at line 132 of file routing_info.h.
References sstmac::hw::routing_info::path::outport, and path_.
Referenced by sstmac::hw::routable::port().
routing::algorithm_t sstmac::hw::routing_info::route_algo () const inline
Definition at line 137 of file routing_info.h.
References algo_.
Referenced by sstmac::hw::routable::algo().
void sstmac::hw::routing_info::set_dest_switch (switch_id sid) inline
Definition at line 152 of file routing_info.h.
References dest_switch_.
void sstmac::hw::routing_info::set_route_algo (routing::algorithm_t algo) inline
Definition at line 142 of file routing_info.h.
References algo_.
Referenced by sstmac::hw::routable::set_algo().
static const char* sstmac::hw::routing_info::tostr (routing::algorithm_t algo) static
Referenced by routing_info().
virtual int sstmac::hw::routing_info::vc () const inline virtual
Definition at line 127 of file routing_info.h.
References path_, and sstmac::hw::routing_info::path::vc.
Referenced by sstmac::hw::routable::vc().
Member Data Documentation
routing::algorithm_t sstmac::hw::routing_info::algo_ protected
Definition at line 164 of file routing_info.h.
Referenced by init_default_algo(), route_algo(), and set_route_algo().
switch_id sstmac::hw::routing_info::dest_switch_ protected
Definition at line 163 of file routing_info.h.
Referenced by dest_switch(), and set_dest_switch().
path sstmac::hw::routing_info::path_ protected
Definition at line 162 of file routing_info.h.
Referenced by assign_path(), check_vc(), current_path(), port(), and vc().
const int sstmac::hw::routing_info::uninitialized = -123 static
Definition at line 35 of file routing_info.h.
Referenced by check_vc().
The documentation for this class was generated from the following file:
sstmac/hardware/router/routing_info.h