SST/macro: sprockit::output Class Reference
sprockit::output Class Reference
#include <output.h>
Static Public Member Functions
static std::ostream & out0 ()
static std::ostream & outn ()
static std::ostream & err0 ()
static std::ostream & errn ()
static void init_out0 (std::ostream *out0)
static void init_outn (std::ostream *outn)
static void init_err0 (std::ostream *err0)
static void init_errn (std::ostream *errn)
Static Protected Attributes
static std::ostream * out0_
static std::ostream * outn_
static std::ostream * err0_
static std::ostream * errn_
Detailed Description
Definition at line 14 of file output.h.
Member Function Documentation
static std::ostream& sprockit::output::err0 () inline static
Definition at line 28 of file output.h.
References err0_.
Referenced by init_err0().
static std::ostream& sprockit::output::errn () inline static
Definition at line 33 of file output.h.
References errn_.
Referenced by init_errn().
static void sprockit::output::init_err0 (std::ostream * err0) inline static
Definition at line 48 of file output.h.
References err0(), and err0_.
static void sprockit::output::init_errn (std::ostream * errn) inline static
Definition at line 53 of file output.h.
References errn(), and errn_.
static void sprockit::output::init_out0 (std::ostream * out0) inline static
Definition at line 38 of file output.h.
References out0(), and out0_.
static void sprockit::output::init_outn (std::ostream * outn) inline static
Definition at line 43 of file output.h.
References outn(), and outn_.
static std::ostream& sprockit::output::out0 () inline static
Definition at line 18 of file output.h.
References out0_.
Referenced by init_out0().
static std::ostream& sprockit::output::outn () inline static
Definition at line 23 of file output.h.
References outn_.
Referenced by init_outn().
Member Data Documentation
std::ostream* sprockit::output::err0_ static protected
Definition at line 60 of file output.h.
Referenced by err0(), and init_err0().
std::ostream* sprockit::output::errn_ static protected
Definition at line 61 of file output.h.
Referenced by errn(), and init_errn().
std::ostream* sprockit::output::out0_ static protected
Definition at line 58 of file output.h.
Referenced by init_out0(), and out0().
std::ostream* sprockit::output::outn_ static protected
Definition at line 59 of file output.h.
Referenced by init_outn(), and outn().
The documentation for this class was generated from the following file:
sprockit/sprockit/output.h