SST/macro: sprockit::metadata_bits< integer > Class Template Reference
sprockit::metadata_bits< integer > Class Template Reference
#include <metadata_bits.h>
Public Member Functions
bool bit (int bitnum) const
void clear ()
void set_bit (int bitnum)
void unset_bit (int bitnum)
integer bit_integer () const
void set_bit_integer (integer i)
metadata_bits ()
metadata_bits (const metadata_bits &mdata)
Public Attributes
integer metadata_
Detailed Description
template<class integer>
class sprockit::metadata_bits< integer >
Definition at line 9 of file metadata_bits.h.
Constructor & Destructor Documentation
template<class integer> sprockit::metadata_bits< integer >::metadata_bits () inline
Definition at line 42 of file metadata_bits.h.
template<class integer> sprockit::metadata_bits< integer >::metadata_bits (const metadata_bits< integer > & mdata) inline
Definition at line 47 of file metadata_bits.h.
Member Function Documentation
template<class integer> bool sprockit::metadata_bits< integer >::bit (int bitnum) const inline
Definition at line 13 of file metadata_bits.h.
Referenced by sstmac::hw::structured_routable::path::metadata_bit().
template<class integer> integer sprockit::metadata_bits< integer >::bit_integer () const inline
Definition at line 33 of file metadata_bits.h.
template<class integer> void sprockit::metadata_bits< integer >::clear () inline
Definition at line 18 of file metadata_bits.h.
Referenced by sstmac::hw::structured_routable::path::clear_metadata().
template<class integer> void sprockit::metadata_bits< integer >::set_bit (int bitnum) inline
Definition at line 23 of file metadata_bits.h.
Referenced by sstmac::hw::structured_routable::path::set_metadata_bit().
template<class integer> void sprockit::metadata_bits< integer >::set_bit_integer (integer i) inline
Definition at line 38 of file metadata_bits.h.
template<class integer> void sprockit::metadata_bits< integer >::unset_bit (int bitnum) inline
Definition at line 28 of file metadata_bits.h.
Referenced by sstmac::hw::structured_routable::path::unset_metadata_bit().
Member Data Documentation
template<class integer> integer sprockit::metadata_bits< integer >::metadata_
Definition at line 53 of file metadata_bits.h.
Referenced by sprockit::metadata_bits< uint32_t >::bit(), sprockit::metadata_bits< uint32_t >::bit_integer(), sprockit::metadata_bits< uint32_t >::clear(), sprockit::metadata_bits< uint32_t >::set_bit(), sprockit::metadata_bits< uint32_t >::set_bit_integer(), and sprockit::metadata_bits< uint32_t >::unset_bit().
The documentation for this class was generated from the following file:
sprockit/sprockit/metadata_bits.h