SST/macro: sstmac::message_buffer_cache Class Reference
sstmac::message_buffer_cache Class Reference
#include <message_buffer_cache.h>
Public Member Functions
std::string to_string () const
void * pop ()
void push (void *buffer)
message_buffer_cache (int buf_size, int num_bufs_window)
message_buffer_cache ()
void init (int buf_size, int num_bufs_window)
Protected Attributes
std::list< void * > buffers_
int buf_size_
int num_bufs_window_
Detailed Description
Definition at line 9 of file message_buffer_cache.h.
Constructor & Destructor Documentation
sstmac::message_buffer_cache::message_buffer_cache (int buf_size, int num_bufs_window) inline
Definition at line 24 of file message_buffer_cache.h.
sstmac::message_buffer_cache::message_buffer_cache () inline
Definition at line 30 of file message_buffer_cache.h.
Member Function Documentation
void sstmac::message_buffer_cache::init (int buf_size, int num_bufs_window) inline
Definition at line 33 of file message_buffer_cache.h.
References buf_size_, and num_bufs_window_.
void* sstmac::message_buffer_cache::pop ()
Referenced by to_string().
void sstmac::message_buffer_cache::push (void * buffer)
Referenced by to_string().
std::string sstmac::message_buffer_cache::to_string () const inline
Definition at line 14 of file message_buffer_cache.h.
References pop(), and push().
Member Data Documentation
int sstmac::message_buffer_cache::buf_size_ protected
Definition at line 41 of file message_buffer_cache.h.
Referenced by init().
std::list<void*> sstmac::message_buffer_cache::buffers_ protected
Definition at line 39 of file message_buffer_cache.h.
int sstmac::message_buffer_cache::num_bufs_window_ protected
Definition at line 43 of file message_buffer_cache.h.
Referenced by init().
The documentation for this class was generated from the following file:
sstmac/common/messages/message_buffer_cache.h