SST/macro: sstmac::hw::butterfly Class Reference
sstmac::hw::butterfly Class Reference
The butterfly class Encapsulates a butterfly topology as described in "High Performance Datacenter Networks" by Abts and Kim.
#include <butterfly.h>
Public Member Functions
virtual std::string to_string () const
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual ~butterfly ()
virtual int num_switches () const
void minimal_route_to_coords (const coordinates &src_coords, const coordinates &dest_coords, structured_routable::path &path) const
Workhorse function for implementing minimal_route_to_switch and #minimal_route_to_node.
int minimal_distance (const coordinates &src_coords, const coordinates &dest_coords) const
The function accepts either source or node coordinates.
switch_id switch_number (const coordinates &coords) const
virtual void connect_objects (internal_connectable_map &switches)
Given a set of connectables, connect them appropriately.
switch_id endpoint_to_ejection_switch (node_id nodeaddr, int &switch_port) const
virtual int convert_to_port (int dim, int dir) const
int ndimensions () const
Each level in a kary-nfly counts as a dimension.
std::vector< node_id > nodes_connected_to_injection_switch (switch_id swaddr) const
std::vector< node_id > nodes_connected_to_ejection_switch (switch_id swaddr) const
void productive_paths (structured_routable::path_set &paths, const coordinates &current, const coordinates &dst)
Public Member Functions inherited from sstmac::hw::abstract_butterfly
virtual ~abstract_butterfly ()
int kary () const
kary
int nfly () const
nfly
int num_switches_per_col () const
num_switches_per_col The butterfly is physically laid out as a 2D-graid of cols and rows
virtual int num_leaf_switches () const
num_switches_per_col The butterfly is physically laid out as a 2D-graid of cols and rows.
int diameter () const
virtual void productive_path (int dim, const coordinates &src, const coordinates &dst, structured_routable::path &path) const
void configure_vc_routing (std::map< routing::algorithm_t, int > &m) const
Public Member Functions inherited from sstmac::hw::structured_topology
virtual ~structured_topology ()
virtual void build_internal_connectables (internal_connectable_map &connectables, sprockit::factory< connectable > *factory, partition *part, int my_rank, sprockit::sim_parameters *params, connectable *dummy)
virtual void build_endpoint_connectables (end_point_connectable_map &connectables, sprockit::factory< connectable > *factory, partition *part, int my_rank, sprockit::sim_parameters *params)
virtual void build_interface_connectables (int conc, end_point_connectable_map &connectables, sprockit::factory2< connectable > *nic_factory, partition *part, int my_rank, sprockit::sim_parameters *params, sprockit::factory_type *interconnect)
virtual void minimal_routes_to_coords (const coordinates &src_coords, const coordinates &dest_coords, structured_routable::path &current_path, structured_routable::path_set &paths) const
virtual int endpoints_per_switch (switch_id addr) const
Given a switch address, return number of nodes connected to it.
virtual int num_nodes () const
virtual int num_endpoints () const
coordinates switch_coords (switch_id swid) const
Compute coordinates (e.g.
virtual coordinates node_coords (node_id nid) const
Compute coordinates (e.g.
coordinates endpoint_coords (node_id nid) const
virtual switch_id endpoint_to_injection_switch (node_id nodeaddr, int &switch_port) const
virtual int endpoint_to_ejection_port (node_id addr) const
virtual int endpoint_to_injection_port (node_id addr) const
virtual int endpoint_to_switch_port (node_id nid) const
void finalize_init ()
std::string label (node_id nid) const
std::string label (switch_id sid) const
virtual void minimal_route_to_switch (switch_id current_sw_addr, switch_id dest_sw_addr, structured_routable::path &path) const
Implementation of topology::minimal_route_to_switch.
virtual void minimal_routes_to_switch (switch_id current_sw_addr, switch_id dest_sw_addr, structured_routable::path &current_path, structured_routable::path_set &paths) const
virtual void eject_paths_on_switch (node_id dest_addr, switch_id sw_addr, structured_routable::path_set &paths) const
virtual int num_hops_to_node (node_id src, node_id dst) const
virtual coordinates neighbor_at_port (switch_id sid, int port) const
virtual node_id node_addr (const coordinates &coords) const
virtual node_id node_addr (const coordinates &sw_coords, int port) const
virtual void send_partners (traffic_pattern::type_t ty, node_id src_node, std::vector< node_id > &partners) const
virtual void recv_partners (traffic_pattern::type_t ty, node_id src_node, std::vector< node_id > &partners) const
Private Member Functions
virtual void compute_switch_coords (switch_id uid, coordinates &coords) const
Compute coordinates (e.g.
int last_col_index_start () const
Private Attributes
long last_col_index_start_
Additional Inherited Members
Public Types inherited from sstmac::hw::abstract_butterfly
enum dimension_t { up_dimension = 0, down_dimension = 1 }
Protected Member Functions inherited from sstmac::hw::structured_topology
void configure_injection_geometry (std::vector< int > &redundancies)
virtual std::vector< node_id > nodes_connected_to_switch (switch_id swaddr) const
structured_topology ()
void partners (bool get_send_partner, traffic_pattern::type_t ty, node_id src, std::vector< node_id > &partner_list) const
virtual void nearest_neighbor_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
virtual void tornado_recv_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
virtual void tornado_send_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
virtual void bit_complement_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
Protected Attributes inherited from sstmac::hw::abstract_butterfly
int kary_
int nfly_
long nswitches_per_col_
Protected Attributes inherited from sstmac::hw::structured_topology
int eject_geometric_id_
int injection_redundancy_
bool outputgraph_
Detailed Description
The butterfly class Encapsulates a butterfly topology as described in "High Performance Datacenter Networks" by Abts and Kim.
Definition at line 117 of file butterfly.h.
Constructor & Destructor Documentation
virtual sstmac::hw::butterfly::~butterfly () inline virtual
Definition at line 130 of file butterfly.h.
Member Function Documentation
virtual void sstmac::hw::butterfly::compute_switch_coords (switch_id swid, coordinates & coords) const private virtual
Compute coordinates (e.g.
X,Y,Z for 3D torus)
Parameters
swid The unique index defining a switch location
coords [inout] The unique coordinates of the switch
Reimplemented from sstmac::hw::abstract_butterfly.
virtual void sstmac::hw::butterfly::connect_objects (internal_connectable_map & objects) virtual
Given a set of connectables, connect them appropriately.
Parameters
objects The set of objects to connect
cloner If in parallel mode, not all objects may exist. The factory creates missing objects.
Exceptions
value_error If invalid switchid is passed to cloner
Implements sstmac::hw::structured_topology.
virtual int sstmac::hw::butterfly::convert_to_port (int dim, int dir) const virtual
switch_id sstmac::hw::butterfly::endpoint_to_ejection_switch (node_id nodeaddr, int & switch_port) const virtual
Reimplemented from sstmac::hw::structured_topology.
virtual void sstmac::hw::butterfly::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::hw::abstract_butterfly.
int sstmac::hw::butterfly::last_col_index_start () const inline private
Definition at line 187 of file butterfly.h.
int sstmac::hw::butterfly::minimal_distance (const coordinates & src_coords, const coordinates & dest_coords) const virtual
The function accepts either source or node coordinates.
This gives the minimal distance counting the number of hops between switches. If node coordinates are given, the last coordinate is just ignored.
Parameters
src_coords. The source coordinates. This can be either switch or node coordinates.
dest_coords. The destination coordinates. This can be either switch or node coordinates.
Returns
The number of hops to final destination
Implements sstmac::hw::structured_topology.
void sstmac::hw::butterfly::minimal_route_to_coords (const coordinates & src_coords, const coordinates & dest_coords, structured_routable::path & path) const virtual
Workhorse function for implementing minimal_route_to_switch and #minimal_route_to_node.
Given source/dest coordinates, find the minimal path.
Parameters
current_sw_addr The addr of the current switch
dest_sw_addr The addr of the destination switch
path [inout] A complete path descriptor to the destination switch
Implements sstmac::hw::structured_topology.
int sstmac::hw::butterfly::ndimensions () const inline virtual
Each level in a kary-nfly counts as a dimension.
Implements sstmac::hw::structured_topology.
Definition at line 166 of file butterfly.h.
References sstmac::hw::abstract_butterfly::compute_switch_coords(), sstmac::hw::abstract_butterfly::nfly_, sstmac::hw::structured_topology::nodes_connected_to_ejection_switch(), sstmac::hw::structured_topology::nodes_connected_to_injection_switch(), and sstmac::hw::structured_topology::productive_paths().
std::vector<node_id> sstmac::hw::butterfly::nodes_connected_to_ejection_switch (switch_id swaddr) const virtual
Reimplemented from sstmac::hw::structured_topology.
std::vector<node_id> sstmac::hw::butterfly::nodes_connected_to_injection_switch (switch_id swaddr) const virtual
Reimplemented from sstmac::hw::structured_topology.
virtual int sstmac::hw::butterfly::num_switches () const inline virtual
Definition at line 133 of file butterfly.h.
References sstmac::hw::structured_topology::connect_objects(), sstmac::hw::structured_topology::endpoint_to_ejection_switch(), sstmac::hw::structured_topology::minimal_distance(), sstmac::hw::structured_topology::minimal_route_to_coords(), sstmac::hw::abstract_butterfly::nfly_, sstmac::hw::abstract_butterfly::nswitches_per_col_, and sstmac::hw::abstract_butterfly::switch_number().
void sstmac::hw::butterfly::productive_paths (structured_routable::path_set & paths, const coordinates & current, const coordinates & dst) virtual
Reimplemented from sstmac::hw::structured_topology.
switch_id sstmac::hw::butterfly::switch_number (const coordinates & coords) const virtual
Reimplemented from sstmac::hw::abstract_butterfly.
virtual std::string sstmac::hw::butterfly::to_string () const inline virtual
Definition at line 123 of file butterfly.h.
References sstmac::hw::abstract_butterfly::init_factory_params().
Member Data Documentation
long sstmac::hw::butterfly::last_col_index_start_ private
Definition at line 192 of file butterfly.h.
The documentation for this class was generated from the following file:
sstmac/hardware/topology/butterfly.h