SST/macro: sstmac::hw::packet_flow_cut_through_arbitrator Class Reference
sstmac::hw::packet_flow_cut_through_arbitrator Class Reference
#include <packet_flow_arbitrator.h>
Classes
struct bandwidth_epoch
Public Member Functions
packet_flow_cut_through_arbitrator ()
~packet_flow_cut_through_arbitrator ()
virtual void arbitrate (packet_stats_st &st)
Assign bandwidth to payload.
virtual void set_outgoing_bw (double bw)
int bytes_sending (timestamp now) const
packet_flow_bandwidth_arbitrator * clone (double bw) const
std::string to_string () const
void partition (noise_model *model, int num_intervals)
partition Partition the arbitrator time windows into a series of randomly sized chunks
void init_noise_model (noise_model *noise)
Public Member Functions inherited from sstmac::hw::packet_flow_bandwidth_arbitrator
virtual ~packet_flow_bandwidth_arbitrator ()
double outgoing_bw () const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Private Member Functions
void clean_up (double now)
void do_arbitrate (packet_stats_st &st)
Private Attributes
bandwidth_epoch * head_
Additional Inherited Members
Static Public Member Functions inherited from sstmac::hw::packet_flow_bandwidth_arbitrator
static timestamp credit_delay (double max_in_bw, double out_bw, long bytes)
Protected Member Functions inherited from sstmac::hw::packet_flow_bandwidth_arbitrator
packet_flow_bandwidth_arbitrator ()
Protected Attributes inherited from sstmac::hw::packet_flow_bandwidth_arbitrator
double out_bw_
double inv_out_bw_
Detailed Description
Definition at line 131 of file packet_flow_arbitrator.h.
Constructor & Destructor Documentation
sstmac::hw::packet_flow_cut_through_arbitrator::packet_flow_cut_through_arbitrator ()
sstmac::hw::packet_flow_cut_through_arbitrator::~packet_flow_cut_through_arbitrator ()
Member Function Documentation
virtual void sstmac::hw::packet_flow_cut_through_arbitrator::arbitrate (packet_stats_st & st) virtual
Assign bandwidth to payload.
Returns
The time at which the packet can be forwarded to the next switch/node/etc.
Implements sstmac::hw::packet_flow_bandwidth_arbitrator.
int sstmac::hw::packet_flow_cut_through_arbitrator::bytes_sending (timestamp now) const virtual
Implements sstmac::hw::packet_flow_bandwidth_arbitrator.
void sstmac::hw::packet_flow_cut_through_arbitrator::clean_up (double now) private
packet_flow_bandwidth_arbitrator* sstmac::hw::packet_flow_cut_through_arbitrator::clone (double bw) const inline virtual
Implements sstmac::hw::packet_flow_bandwidth_arbitrator.
Definition at line 150 of file packet_flow_arbitrator.h.
References sstmac::hw::packet_flow_bandwidth_arbitrator::set_outgoing_bw().
void sstmac::hw::packet_flow_cut_through_arbitrator::do_arbitrate (packet_stats_st & st) private
void sstmac::hw::packet_flow_cut_through_arbitrator::init_noise_model (noise_model * noise) virtual
Reimplemented from sstmac::hw::packet_flow_bandwidth_arbitrator.
void sstmac::hw::packet_flow_cut_through_arbitrator::partition (noise_model * noise, int num_intervals) virtual
partition Partition the arbitrator time windows into a series of randomly sized chunks
Parameters
noise The noise model that randomly selects time values
num_intervals
Reimplemented from sstmac::hw::packet_flow_bandwidth_arbitrator.
virtual void sstmac::hw::packet_flow_cut_through_arbitrator::set_outgoing_bw (double bw) virtual
Reimplemented from sstmac::hw::packet_flow_bandwidth_arbitrator.
std::string sstmac::hw::packet_flow_cut_through_arbitrator::to_string () const inline virtual
Implements sstmac::hw::packet_flow_bandwidth_arbitrator.
Definition at line 158 of file packet_flow_arbitrator.h.
References sstmac::hw::packet_flow_bandwidth_arbitrator::init_noise_model(), and sstmac::hw::packet_flow_bandwidth_arbitrator::partition().
Member Data Documentation
bandwidth_epoch* sstmac::hw::packet_flow_cut_through_arbitrator::head_ private
Definition at line 200 of file packet_flow_arbitrator.h.
The documentation for this class was generated from the following file:
sstmac/hardware/packet_flow/packet_flow_arbitrator.h