SST/macro: sstmac::event_callback Class Reference
sstmac::event_callback Class Reference abstract
The main interface for something that can respond to an event (sst_message).
#include <event_callback.h>
Public Member Functions
virtual ~event_callback ()
virtual void handle (event *ev)=0
virtual std::string to_string () const
Public Member Functions inherited from sstmac::event_handler
virtual ~event_handler ()
event_loc_id event_location () const
virtual bool ipc_handler () const
Whether an event handler is a "fake" handler that represents logical process boundary.
int thread_id () const
virtual void deadlock_check (event *ev)
virtual void deadlock_check ()
Protected Member Functions
event_callback (event_loc_id id)
Protected Member Functions inherited from sstmac::event_handler
event_handler ()
void init_loc_id (event_loc_id id)
void init_thread_id (int id)
Additional Inherited Members
Static Public Attributes inherited from sstmac::event_handler
static const int null_lpid = -1
static const int null_threadid = -1
Detailed Description
The main interface for something that can respond to an event (sst_message).
Definition at line 23 of file event_callback.h.
Constructor & Destructor Documentation
virtual sstmac::event_callback::~event_callback () inline virtual
Definition at line 28 of file event_callback.h.
References handle().
sstmac::event_callback::event_callback (event_loc_id id) inline protected
Definition at line 39 of file event_callback.h.
References sstmac::event_handler::init_loc_id().
Member Function Documentation
virtual void sstmac::event_callback::handle (event * ev) pure virtual
Implements sstmac::event_handler.
Implemented in sstmac::event_callback_2_args< Cls, Fxn, Arg1, Arg2 >, sstmac::event_callback_1_args< Cls, Fxn, Arg1 >, and sstmac::event_callback_instance< Cls, Fxn >.
Referenced by ~event_callback().
virtual std::string sstmac::event_callback::to_string () const inline virtual
Implements sstmac::event_handler.
Definition at line 34 of file event_callback.h.
The documentation for this class was generated from the following file:
sstmac/common/event_callback.h