SST/macro: sstmac::hw::tiled_torus Class Reference
sstmac::hw::tiled_torus Class Reference
#include <tiled_torus.h>
Public Member Functions
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual void minimal_routes_to_coords (const coordinates &src_coords, const coordinates &dest_coords, geometry_routable::path &current, geometry_routable::path_set &paths)
std::string default_router () const
switch_id endpoint_to_injection_switch (node_id nodeaddr, int ports[], int &num_ports) const
switch_id endpoint_to_ejection_switch (node_id nodeaddr, int ports[], int &num_ports) const
void eject_paths_on_switch (node_id dest_addr, switch_id sw_addr, geometry_routable::path_set &paths) const
Public Member Functions inherited from sstmac::hw::hdtorus
virtual std::string to_string () const
virtual ~hdtorus ()
int shortest_distance (int dim, int src, int dst) const
int distance (int dim, int dir, int src, int dst) const
void down_path (int dim, const coordinates &src, const coordinates &dst, geometry_routable::path &path) const
void up_path (int dim, const coordinates &src, const coordinates &dst, geometry_routable::path &path) const
bool shortest_path_positive (int dim, const coordinates &src, const coordinates &dst) const
virtual void productive_path (int dim, const coordinates &src, const coordinates &dst, geometry_routable::path &path) const
void pick_vc (geometry_routable::path &path) const
switch_id switch_number (const coordinates &v) const
int diameter () const
std::string name () const
const std::vector< int > & dimensions () const
Returns the vector giving each dimension of the torus.
coordinates neighbor_at_port (switch_id sid, int port) const
virtual int num_switches () const
virtual int num_leaf_switches () const
Structured topologies can be direct (torus) or indirect (fat tree).
void configure_geometric_paths (std::vector< int > &redundancies)
virtual int ndimensions () const
The number of distinct 'dimensions' in the topology.
void minimal_route_to_coords (const coordinates &src_coords, const coordinates &dest_coords, geometry_routable::path &path)
Workhorse function for implementing minimal_route_to_switch and #minimal_route_to_node.
virtual void connect_objects (internal_connectable_map &switches)
Given a set of connectables, connect them appropriately.
virtual int convert_to_port (int dim, int dir) const
int minimal_distance (const coordinates &src_coords, const coordinates &dest_coords) const
The function accepts either source or node coordinates.
void partners (traffic_pattern::type_t ty, const coordinates &src_sw_coords, std::list< node_id > &partners) const
void configure_vc_routing (std::map< routing::algorithm_t, int > &m) const
Public Member Functions inherited from sstmac::hw::cartesian_topology
const std::vector< int > & red () const
virtual void minimal_routes_to_switch (switch_id current_sw_addr, switch_id dest_sw_addr, geometry_routable::path &current_path, geometry_routable::path_set &paths)
Public Member Functions inherited from sstmac::hw::structured_topology
virtual ~structured_topology ()
virtual void build_internal_connectables (internal_connectable_map &connectables, sprockit::factory< connectable > *factory, partition *part, int my_rank, sprockit::sim_parameters *params, connectable *dummy)
virtual void build_endpoint_connectables (end_point_connectable_map &connectables, sprockit::factory< connectable > *factory, partition *part, int my_rank, sprockit::sim_parameters *params)
virtual void build_interface_connectables (int conc, end_point_connectable_map &connectables, sprockit::factory2< connectable > *nic_factory, partition *part, int my_rank, sprockit::sim_parameters *params, sprockit::factory_type *interconnect)
virtual int endpoints_per_switch (switch_id addr) const
Given a switch address, return number of nodes connected to it.
virtual int num_nodes () const
virtual int num_endpoints () const
coordinates switch_coords (switch_id swid) const
Compute coordinates (e.g.
virtual coordinates node_coords (node_id nid) const
Compute coordinates (e.g.
coordinates endpoint_coords (node_id nid) const
virtual switch_id endpoint_to_ejection_switch (node_id nodeaddr, int &switch_port) const
virtual switch_id endpoint_to_injection_switch (node_id nodeaddr, int &switch_port) const
virtual int endpoint_to_ejection_port (node_id addr) const
virtual int endpoint_to_injection_port (node_id addr) const
virtual int endpoint_to_switch_port (node_id nid) const
void finalize_init ()
virtual void productive_paths (geometry_routable::path_set &paths, const coordinates &current, const coordinates &dst)
std::string label (node_id nid) const
std::string label (switch_id sid) const
virtual void minimal_route_to_switch (switch_id current_sw_addr, switch_id dest_sw_addr, geometry_routable::path &path)
Implementation of topology::minimal_route_to_switch.
virtual int num_hops_to_node (node_id src, node_id dst) const
virtual std::vector< node_id > nodes_connected_to_injection_switch (switch_id swaddr) const
virtual std::vector< node_id > nodes_connected_to_ejection_switch (switch_id swid) const
virtual node_id node_addr (const coordinates &coords) const
virtual node_id node_addr (const coordinates &sw_coords, int port) const
virtual void send_partners (traffic_pattern::type_t ty, node_id src_node, std::vector< node_id > &partners) const
virtual void recv_partners (traffic_pattern::type_t ty, node_id src_node, std::vector< node_id > &partners) const
Protected Member Functions
virtual void connect_dim (int dim, connectable *center, connectable *plus, connectable *minus)
Protected Member Functions inherited from sstmac::hw::hdtorus
virtual void compute_switch_coords (switch_id uid, coordinates &coords) const
Compute coordinates (e.g.
void nearest_neighbor_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
void bit_complement_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
void tornado_send_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
void tornado_recv_partners (const coordinates &src_sw_coords, int port, std::vector< node_id > &partners) const
Protected Member Functions inherited from sstmac::hw::structured_topology
void configure_injection_geometry (std::vector< int > &redundancies)
virtual std::vector< node_id > nodes_connected_to_switch (switch_id swaddr) const
structured_topology ()
void partners (bool get_send_partner, traffic_pattern::type_t ty, node_id src, std::vector< node_id > &partner_list) const
Private Member Functions
int port (int replica, int dim, int dir)
Private Attributes
int ntiles_row_
int ntiles_col_
std::vector< int > tile_offsets_
std::vector< int > rotater_
Additional Inherited Members
Public Types inherited from sstmac::hw::hdtorus
enum direction_t { pos = 0, neg = 1 }
Protected Attributes inherited from sstmac::hw::hdtorus
int diameter_
long num_switches_
std::vector< int > dimensions_
Protected Attributes inherited from sstmac::hw::cartesian_topology
std::vector< int > red_
Protected Attributes inherited from sstmac::hw::structured_topology
int eject_geometric_id_
int injection_redundancy_
bool outputgraph_
Detailed Description
Definition at line 10 of file tiled_torus.h.
Member Function Documentation
virtual void sstmac::hw::tiled_torus::connect_dim (int dim, connectable * center, connectable * plus, connectable * minus) protected virtual
Reimplemented from sstmac::hw::hdtorus.
Referenced by default_router().
std::string sstmac::hw::tiled_torus::default_router () const inline virtual
Reimplemented from sstmac::hw::structured_topology.
Definition at line 25 of file tiled_torus.h.
References connect_dim(), eject_paths_on_switch(), endpoint_to_ejection_switch(), endpoint_to_injection_switch(), and port().
void sstmac::hw::tiled_torus::eject_paths_on_switch (node_id dest_addr, switch_id sw_addr, geometry_routable::path_set & paths) const virtual
Reimplemented from sstmac::hw::structured_topology.
Referenced by default_router().
switch_id sstmac::hw::tiled_torus::endpoint_to_ejection_switch (node_id nodeaddr, int ports[], int & num_ports) const
Referenced by default_router().
switch_id sstmac::hw::tiled_torus::endpoint_to_injection_switch (node_id nodeaddr, int ports[], int & num_ports) const
Referenced by default_router().
virtual void sstmac::hw::tiled_torus::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::hw::hdtorus.
virtual void sstmac::hw::tiled_torus::minimal_routes_to_coords (const coordinates & src_coords, const coordinates & dest_coords, geometry_routable::path & current, geometry_routable::path_set & paths) virtual
Reimplemented from sstmac::hw::structured_topology.
int sstmac::hw::tiled_torus::port (int replica, int dim, int dir) private
Referenced by default_router().
Member Data Documentation
int sstmac::hw::tiled_torus::ntiles_col_ private
Definition at line 54 of file tiled_torus.h.
int sstmac::hw::tiled_torus::ntiles_row_ private
Definition at line 53 of file tiled_torus.h.
std::vector<int> sstmac::hw::tiled_torus::rotater_ private
Definition at line 56 of file tiled_torus.h.
std::vector<int> sstmac::hw::tiled_torus::tile_offsets_ private
Definition at line 55 of file tiled_torus.h.
The documentation for this class was generated from the following file:
sstmac/hardware/topology/tiled_torus.h