SST/macro: sstmac::sw::library Class Reference
sstmac::sw::library Class Reference abstract
#include <library.h>
Public Member Functions
virtual void unregister_all_libs ()
virtual std::string to_string () const
virtual std::string lib_name () const
virtual void init_os (operating_system *os)
virtual void consume_params (sprockit::sim_parameters *params)
virtual void incoming_event (event *ev)=0
operating_system * os () const
virtual ~library ()
Static Public Member Functions
static library * construct_lib (const std::string &libname)
static library * construct_lib (const std::string &libname, const software_id &sid)
static void register_builder (const std::string &libname, library_builder *builder)
Protected Member Functions
library ()
void register_lib (library *lib)
This function is provided so that libraries can instantiate, register, and use other libraries.
virtual bool supported () const
This is usually convenient to define to check if the node was set up correctly to support what this library wants to do.
Static Protected Member Functions
static library_builder * builder (const std::string &name)
Protected Attributes
operating_system * os_
std::string libname_
key::category key_cat_
Detailed Description
Definition at line 27 of file library.h.
Constructor & Destructor Documentation
virtual sstmac::sw::library::~library () virtual
Referenced by os().
sstmac::sw::library::library () protected
Referenced by os().
Member Function Documentation
static library_builder* sstmac::sw::library::builder (const std::string & name) static protected
Referenced by supported().
static library* sstmac::sw::library::construct_lib (const std::string & libname) static
static library* sstmac::sw::library::construct_lib (const std::string & libname, const software_id & sid) static
virtual void sstmac::sw::library::consume_params (sprockit::sim_parameters * params) virtual
Referenced by lib_name().
virtual void sstmac::sw::library::incoming_event (event * ev) pure virtual
Implemented in sstmac::sumi_server, sstmac::sw::blas_api, sumi::sumi_transport, sstmac::sw::launcher, sstmac::sw::service, and sstmac::sw::lib_sleep.
Referenced by sstmac::sw::lib_sleep::incoming_event(), sstmac::sw::lib_compute_time::incoming_event(), sstmac::sw::lib_compute_memmove::incoming_event(), sstmac::sw::lib_compute_inst::incoming_event(), sstmac::sw::blas_api::incoming_event(), and lib_name().
virtual void sstmac::sw::library::init_os (operating_system * os) virtual
Reimplemented in sstmac::sw::api, sstmac::sumi_api, and sstmac::sw::blas_api.
Referenced by lib_name().
virtual std::string sstmac::sw::library::lib_name () const inline virtual
Definition at line 48 of file library.h.
References consume_params(), incoming_event(), init_os(), libname_, and os().
operating_system* sstmac::sw::library::os () const inline
Definition at line 62 of file library.h.
References library(), os_, register_lib(), and ~library().
Referenced by lib_name().
static void sstmac::sw::library::register_builder (const std::string & libname, library_builder * builder) static
Referenced by sstmac::sw::library_builder_tmpl< T >::library_builder_tmpl().
void sstmac::sw::library::register_lib (library * lib) protected
This function is provided so that libraries can instantiate, register, and use other libraries.
Parameters
lib the library to register
Referenced by os().
virtual bool sstmac::sw::library::supported () const inline protected virtual
This is usually convenient to define to check if the node was set up correctly to support what this library wants to do.
This function is not currently a strict part of an interface.
Returns
true if the hardware supports this libraries functions
Reimplemented in sstmac::sw::lib_sleep.
Definition at line 84 of file library.h.
References builder().
virtual std::string sstmac::sw::library::to_string () const inline virtual
Reimplemented in sstmac::sw::launcher, and sstmac::sw::service.
Definition at line 43 of file library.h.
References libname_.
virtual void sstmac::sw::library::unregister_all_libs () virtual
Member Data Documentation
key::category sstmac::sw::library::key_cat_ protected
Definition at line 95 of file library.h.
std::string sstmac::sw::library::libname_ protected
Definition at line 94 of file library.h.
Referenced by lib_name(), and to_string().
operating_system* sstmac::sw::library::os_ protected
Definition at line 93 of file library.h.
Referenced by os().
The documentation for this class was generated from the following file:
sstmac/software/libraries/library.h