SST/macro: sstmac::native::clock_cycle_event_map Class Reference
sstmac::native::clock_cycle_event_map Class Reference
#include <clock_cycle_event_container.h>
Public Types
enum vote_type_t { vote_max, vote_min }
Public Member Functions
virtual ~clock_cycle_event_map () throw ()
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual void finalize_init ()
virtual void run ()
Run the eventmanager.
bool vote_to_terminate ()
virtual void set_interconnect (hw::interconnect *interconn)
virtual void ipc_schedule (timestamp t, event_loc_id dst, event_loc_id src, uint32_t seqnum, event *ev)
Public Member Functions inherited from sstmac::native::event_map
~event_map () throw ()
void clear (timestamp zero_time=timestamp(0))
Clear all events and set time back to a zero of your choice.
void cancel_all_messages (event_loc_id mod)
bool empty () const
Public Member Functions inherited from sstmac::native::event_container
virtual ~event_container () throw ()
Goodbye.
Public Member Functions inherited from sstmac::event_manager
virtual std::string to_string () const
bool is_complete ()
virtual ~event_manager ()
Goodbye.
timestamp now () const
void register_stat (stat_collector *stat, bool reduce_all=true, bool dump_all=false, bool dump_main=true)
stat_collector * register_thread_unique_stat (stat_collector *stat, bool reduce_all=true, bool dump_all=false, bool dump_main=true)
partition * topology_partition () const
parallel_runtime * runtime () const
void finish_stats ()
virtual void finish_stats (stat_collector *main, const std::string &name, timestamp end)
void stop ()
int me () const
int worker_id () const
int nproc () const
int nworker () const
virtual void multithread_schedule (int srcthread, int dstthread, uint32_t seqnum, event_queue_entry *ev)
virtual int lpid () const
int thread_id () const
int nthread () const
virtual event_manager * ev_man_for_thread (int thread_id) const
void init_param1 (parallel_runtime *rt)
virtual void schedule_stop (timestamp until)
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Protected Member Functions
virtual void schedule_incoming (const std::vector< void * > &mpi_buffers)
void do_next_event ()
timestamp next_event_time () const
virtual timestamp vote_next_round (timestamp my_time, vote_type_t ty)
int64_t do_vote (int64_t time, vote_type_t ty=vote_min)
virtual void receive_incoming_events ()
Protected Member Functions inherited from sstmac::native::event_map
event_queue_entry * pop_next_event ()
void add_event (event_queue_entry *ev)
Called by schedule. Child class must implement.
Protected Member Functions inherited from sstmac::native::event_container
event_container ()
void schedule (timestamp start_time, uint32_t seqnum, event_queue_entry *ev)
Set off the given eventhandler at the given time.
void finish ()
Called at end of run().
Protected Member Functions inherited from sstmac::event_manager
event_manager ()
void set_now (const timestamp &ts)
Protected Attributes
timestamp next_time_horizon_
timestamp lookahead_
timestamp no_events_left_time_
std::vector< void * > all_incoming_
std::vector< std::vector< void * > > thread_incoming_
hw::switch_interconnect * interconn_
int epoch_
Protected Attributes inherited from sstmac::native::event_map
queue_t queue_
Protected Attributes inherited from sstmac::native::event_container
bool running_
Sentinel to track whether the event handler is running or not.
timestamp last_update_sim_
Time of last event executed.
Protected Attributes inherited from sstmac::event_manager
bool complete_
bool stopped_
bool finish_on_stop_
parallel_runtime * rt_
int thread_id_
int me_
int nproc_
int nthread_
Friends
class multithreaded_event_container
Additional Inherited Members
Static Public Member Functions inherited from sstmac::event_manager
static int current_thread_id ()
Static Public Attributes inherited from sstmac::event_manager
static event_manager * global
Protected Types inherited from sstmac::native::event_map
typedef std::set< event_queue_entry *, event_compare > queue_t
Static Protected Attributes inherited from sstmac::event_manager
static std::vector< pthread_t > pthreads_
static std::vector< pthread_attr_t > pthread_attrs_
Detailed Description
Definition at line 16 of file clock_cycle_event_container.h.
Member Enumeration Documentation
enum sstmac::native::clock_cycle_event_map::vote_type_t
Enumerator
vote_max
vote_min
Definition at line 20 of file clock_cycle_event_container.h.
Constructor & Destructor Documentation
virtual sstmac::native::clock_cycle_event_map::~clock_cycle_event_map () throw () inline virtual
Definition at line 25 of file clock_cycle_event_container.h.
References finalize_init(), init_factory_params(), ipc_schedule(), run(), set_interconnect(), and vote_to_terminate().
Member Function Documentation
void sstmac::native::clock_cycle_event_map::do_next_event () protected virtual
Reimplemented from sstmac::native::event_container.
int64_t sstmac::native::clock_cycle_event_map::do_vote (int64_t time, vote_type_t ty = vote_min) protected
virtual void sstmac::native::clock_cycle_event_map::finalize_init () virtual
Reimplemented from sprockit::factory_type.
Reimplemented in sstmac::native::multithreaded_event_container.
Referenced by ~clock_cycle_event_map().
virtual void sstmac::native::clock_cycle_event_map::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::native::event_container.
Reimplemented in sstmac::native::multithreaded_event_container.
Referenced by ~clock_cycle_event_map().
virtual void sstmac::native::clock_cycle_event_map::ipc_schedule (timestamp t, event_loc_id dst, event_loc_id src, uint32_t seqnum, event * ev) virtual
Reimplemented from sstmac::event_manager.
Referenced by ~clock_cycle_event_map().
timestamp sstmac::native::clock_cycle_event_map::next_event_time () const protected
virtual void sstmac::native::clock_cycle_event_map::receive_incoming_events () protected virtual
Reimplemented in sstmac::native::multithreaded_event_container, and sstmac::native::multithreaded_subcontainer.
virtual void sstmac::native::clock_cycle_event_map::run () virtual
Run the eventmanager.
The eventmanager shall return control when no more messages remain.
Reimplemented from sstmac::native::event_container.
Reimplemented in sstmac::native::multithreaded_event_container, and sstmac::native::multithreaded_subcontainer.
Referenced by ~clock_cycle_event_map().
virtual void sstmac::native::clock_cycle_event_map::schedule_incoming (const std::vector< void * > & mpi_buffers) protected virtual
virtual void sstmac::native::clock_cycle_event_map::set_interconnect (hw::interconnect * interconn) virtual
Reimplemented from sstmac::event_manager.
Reimplemented in sstmac::native::multithreaded_event_container.
Referenced by ~clock_cycle_event_map().
virtual timestamp sstmac::native::clock_cycle_event_map::vote_next_round (timestamp my_time, vote_type_t ty) protected virtual
bool sstmac::native::clock_cycle_event_map::vote_to_terminate () virtual
Reimplemented from sstmac::native::event_container.
Referenced by ~clock_cycle_event_map().
Friends And Related Function Documentation
friend class multithreaded_event_container friend
Definition at line 50 of file clock_cycle_event_container.h.
Member Data Documentation
std::vector<void*> sstmac::native::clock_cycle_event_map::all_incoming_ protected
Definition at line 74 of file clock_cycle_event_container.h.
int sstmac::native::clock_cycle_event_map::epoch_ protected
Definition at line 77 of file clock_cycle_event_container.h.
hw::switch_interconnect* sstmac::native::clock_cycle_event_map::interconn_ protected
Definition at line 76 of file clock_cycle_event_container.h.
timestamp sstmac::native::clock_cycle_event_map::lookahead_ protected
Definition at line 72 of file clock_cycle_event_container.h.
timestamp sstmac::native::clock_cycle_event_map::next_time_horizon_ protected
Definition at line 71 of file clock_cycle_event_container.h.
timestamp sstmac::native::clock_cycle_event_map::no_events_left_time_ protected
Definition at line 73 of file clock_cycle_event_container.h.
std::vector<std::vector<void*> > sstmac::native::clock_cycle_event_map::thread_incoming_ protected
Definition at line 75 of file clock_cycle_event_container.h.
The documentation for this class was generated from the following file:
sstmac/backends/native/clock_cycle_parallel/clock_cycle_event_container.h