SST/macro: sstmac::payload Class Reference
sstmac::payload Class Reference abstract
Pure abstract base for payload that can be associated with a network send.
#include <payload.h>
Public Types
typedef sprockit::refcount_ptr< payload > ptr
typedef sprockit::refcount_ptr< const payload > const_ptr
Public Member Functions
virtual ~payload ()
Goodbye.
virtual void recover (sw::api *api)
virtual payload::const_ptr clone () const =0
Create a copy of this payload.
virtual std::string to_string () const
Stringify.
virtual void assign (void *data)
virtual void * data () const =0
virtual long byte_length () const =0
virtual payload::const_ptr add (const payload::const_ptr &other) const =0
Pure virtual add operator.
virtual payload::const_ptr prod (const payload::const_ptr &other) const =0
virtual payload::const_ptr min (const payload::const_ptr &other) const =0
Pure virtual less than (<) operator.
virtual payload::const_ptr max (const payload::const_ptr &other) const =0
Pure virtual greater than (>) operator.
virtual bool equals (const payload::const_ptr &other) const =0
Pure virtual equals operator.
virtual payload::const_ptr logical_or (const payload::const_ptr &other) const =0
Pure virtual logical or operator.
virtual payload::const_ptr logical_xor (const payload::const_ptr &other) const =0
Pure virtual logical xor operator.
virtual payload::const_ptr logical_and (const payload::const_ptr &other) const =0
Pure virtual logical and operator.
virtual payload::const_ptr bitwise_or (const payload::const_ptr &other) const =0
virtual payload::const_ptr bitwise_xor (const payload::const_ptr &other) const =0
Pure virtual logical xor operator.
virtual payload::const_ptr bitwise_and (const payload::const_ptr &other) const =0
Pure virtual logical and operator.
Public Member Functions inherited from sprockit::ptr_type
ptr_type ()
int nreferences () const
virtual ~ptr_type ()
Public Member Functions inherited from sprockit::serializable
virtual const char * cls_name () const =0
virtual void serialize_order (sprockit::serializer &ser)=0
virtual uint32_t cls_id () const =0
virtual ~serializable ()
Static Public Member Functions
static ptr null ()
Convenience function to get a null payload pointer.
Protected Member Functions
payload ()
Empty protected constructor to enforce using construct()
Protected Member Functions inherited from sprockit::ptr_type
void incref ()
int decref ()
Additional Inherited Members
Protected Types inherited from sprockit::serializable
enum cxn_flag_t { ConstructorFlag }
Detailed Description
Pure abstract base for payload that can be associated with a network send.
Definition at line 25 of file payload.h.
Member Typedef Documentation
typedef sprockit::refcount_ptr<const payload> sstmac::payload::const_ptr
Definition at line 38 of file payload.h.
typedef sprockit::refcount_ptr<payload> sstmac::payload::ptr
Definition at line 37 of file payload.h.
Constructor & Destructor Documentation
sstmac::payload::payload () inline protected
Empty protected constructor to enforce using construct()
Definition at line 33 of file payload.h.
virtual sstmac::payload::~payload () inline virtual
Goodbye.
Definition at line 42 of file payload.h.
References clone(), and recover().
Member Function Documentation
virtual payload::const_ptr sstmac::payload::add (const payload::const_ptr & other) const pure virtual
Pure virtual add operator.
Parameters
other Payload object to add to this one
Returns
A smart pointer to a new object which is the sum of this and other
Implemented in sstmac::pairpayloadvector< T1, T2 >, sstmac::value_payload< T >, sstmac::vector1_payload< Type, VectorType >, sstmac::pair_payload< T1, T2 >, and sstmac::wrapper_payload.
Referenced by assign().
virtual void sstmac::payload::assign (void * data) inline virtual
Reimplemented in sstmac::vector1_payload< Type, VectorType >.
Definition at line 74 of file payload.h.
References add(), bitwise_and(), bitwise_or(), bitwise_xor(), byte_length(), data(), equals(), logical_and(), logical_or(), logical_xor(), max(), min(), prod(), and spkt_throw_printf.
virtual payload::const_ptr sstmac::payload::bitwise_and (const payload::const_ptr & other) const pure virtual
Pure virtual logical and operator.
Parameters
other Payload to compare to
Returns
true if both payloads are considered true
Implemented in sstmac::bitwisevaluepayload< T >, sstmac::vector1_payload< Type, VectorType >, sstmac::value_payload< T >, and sstmac::wrapper_payload.
Referenced by assign().
virtual payload::const_ptr sstmac::payload::bitwise_or (const payload::const_ptr & other) const pure virtual
Implemented in sstmac::bitwisevaluepayload< T >, sstmac::vector1_payload< Type, VectorType >, sstmac::value_payload< T >, and sstmac::wrapper_payload.
Referenced by assign().
virtual payload::const_ptr sstmac::payload::bitwise_xor (const payload::const_ptr & other) const pure virtual
Pure virtual logical xor operator.
Parameters
other Payload to compare to
Returns
true if exactly one payload is considered true
Implemented in sstmac::bitwisevaluepayload< T >, sstmac::vector1_payload< Type, VectorType >, sstmac::value_payload< T >, and sstmac::wrapper_payload.
Referenced by assign().
virtual long sstmac::payload::byte_length () const pure virtual
Implemented in sstmac::pairpayloadvector< T1, T2 >, sstmac::value_payload< T >, sstmac::vector1_payload< Type, VectorType >, sstmac::pair_payload< T1, T2 >, and sstmac::wrapper_payload.
Referenced by assign().
virtual payload::const_ptr sstmac::payload::clone () const pure virtual
Create a copy of this payload.
Returns
A smart pointer to a new payload object
Implemented in sstmac::bitwisevaluepayload< T >, sstmac::pairpayloadvector< T1, T2 >, sstmac::value_payload< T >, sstmac::vector1_payload< Type, VectorType >, sstmac::pair_payload< T1, T2 >, and sstmac::wrapper_payload.
Referenced by ~payload().
virtual void* sstmac::payload::data () const pure virtual
Implemented in sstmac::pairpayloadvector< T1, T2 >, sstmac::value_payload< T >, sstmac::pair_payload< T1, T2 >, sstmac::vector1_payload< Type, VectorType >, and sstmac::wrapper_payload.
Referenced by assign().
virtual bool sstmac::payload::equals (const payload::const_ptr & other) const pure virtual
Pure virtual equals operator.
Parameters
other Payload to compare to
Returns
true if this payload is considered equal to the other
Implemented in sstmac::pairpayloadvector< T1, T2 >, sstmac::vector1_payload< Type, VectorType >, sstmac::value_payload< T >, sstmac::pair_payload< T1, T2 >, and sstmac::wrapper_payload.
Referenced by assign().
virtual payload::const_ptr sstmac::payload::logical_and (const payload::const_ptr & other) const pure virtual
Pure virtual logical and operator.
Parameters
other Payload to compare to
Returns
true if both payloads are considered true
Implemented in sstmac::pairpayloadvector< T1, T2 >, sstmac::vector1_payload< Type, VectorType >, sstmac::value_payload< T >, sstmac::pair_payload< T1, T2 >, and sstmac::wrapper_payload.
Referenced by assign().
virtual payload::const_ptr sstmac::payload::logical_or (const payload::const_ptr & other) const pure virtual
Pure virtual logical or operator.
Parameters
other Payload to compare to
Returns
true if this either payload is considered true
Implemented in sstmac::pairpayloadvector< T1, T2 >, sstmac::vector1_payload< Type, VectorType >, sstmac::value_payload< T >, sstmac::pair_payload< T1, T2 >, and sstmac::wrapper_payload.
Referenced by assign().
virtual payload::const_ptr sstmac::payload::logical_xor (const payload::const_ptr & other) const pure virtual
Pure virtual logical xor operator.
Parameters
other Payload to compare to
Returns
true if exactly one payload is considered true
Implemented in sstmac::pairpayloadvector< T1, T2 >, sstmac::vector1_payload< Type, VectorType >, sstmac::value_payload< T >, sstmac::pair_payload< T1, T2 >, and sstmac::wrapper_payload.
Referenced by assign().
virtual payload::const_ptr sstmac::payload::max (const payload::const_ptr & other) const pure virtual
Pure virtual greater than (>) operator.
Parameters
other Payload to compare to
Returns
true if this payload is considered greather than other
Implemented in sstmac::pairpayloadvector< T1, T2 >, sstmac::vector1_payload< Type, VectorType >, sstmac::value_payload< T >, sstmac::pair_payload< T1, T2 >, and sstmac::wrapper_payload.
Referenced by assign().
virtual payload::const_ptr sstmac::payload::min (const payload::const_ptr & other) const pure virtual
Pure virtual less than (<) operator.
Parameters
other Payload to compare to
Returns
true if this payload is considered less than other
Implemented in sstmac::pairpayloadvector< T1, T2 >, sstmac::value_payload< T >, sstmac::vector1_payload< Type, VectorType >, sstmac::pair_payload< T1, T2 >, and sstmac::wrapper_payload.
Referenced by assign().
static ptr sstmac::payload::null () inline static
Convenience function to get a null payload pointer.
Returns
null smart pointer
Definition at line 69 of file payload.h.
virtual payload::const_ptr sstmac::payload::prod (const payload::const_ptr & other) const pure virtual
Implemented in sstmac::value_payload< T >, sstmac::vector1_payload< Type, VectorType >, and sstmac::wrapper_payload.
Referenced by assign().
virtual void sstmac::payload::recover (sw::api * api) virtual
Referenced by ~payload().
virtual std::string sstmac::payload::to_string () const inline virtual
Stringify.
Returns
String description
Implements sprockit::printable_ptr_type.
Reimplemented in sstmac::bitwisevaluepayload< T >, sstmac::pairpayloadvector< T1, T2 >, sstmac::vector1_payload< Type, VectorType >, sstmac::value_payload< T >, sstmac::pair_payload< T1, T2 >, and sstmac::wrapper_payload.
Definition at line 60 of file payload.h.
The documentation for this class was generated from the following file:
sstmac/common/messages/payload.h