SST/macro: sstmac::hw::simple_memory_model::link Class Reference
sstmac::hw::simple_memory_model::link Class Reference
#include <simple_memory_model.h>
Public Member Functions
link (double bw, timestamp lat)
virtual ~link ()
virtual std::string to_string () const
virtual timestamp new_access (timestamp now, long size, double max_bw)
virtual void access_done ()
Protected Attributes
double bw_
timestamp lat_
timestamp last_access_
Detailed Description
Definition at line 40 of file simple_memory_model.h.
Constructor & Destructor Documentation
sstmac::hw::simple_memory_model::link::link (double bw, timestamp lat) inline
Definition at line 42 of file simple_memory_model.h.
virtual sstmac::hw::simple_memory_model::link::~link () inline virtual
Definition at line 46 of file simple_memory_model.h.
Member Function Documentation
virtual void sstmac::hw::simple_memory_model::link::access_done () virtual
Referenced by to_string().
virtual timestamp sstmac::hw::simple_memory_model::link::new_access (timestamp now, long size, double max_bw) virtual
Referenced by to_string().
virtual std::string sstmac::hw::simple_memory_model::link::to_string () const inline virtual
Definition at line 49 of file simple_memory_model.h.
References access_done(), and new_access().
Member Data Documentation
double sstmac::hw::simple_memory_model::link::bw_ protected
Definition at line 60 of file simple_memory_model.h.
timestamp sstmac::hw::simple_memory_model::link::last_access_ protected
Definition at line 62 of file simple_memory_model.h.
timestamp sstmac::hw::simple_memory_model::link::lat_ protected
Definition at line 61 of file simple_memory_model.h.
The documentation for this class was generated from the following file:
sstmac/hardware/memory/simple_memory_model.h