SST/macro: sstmac::hw::noise_model Class Reference
sstmac::hw::noise_model Class Reference abstract
#include <noise.h>
Public Member Functions
virtual ~noise_model ()
virtual double value ()=0
virtual void init_factory_params (sprockit::sim_parameters *params)
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Detailed Description
Definition at line 10 of file noise.h.
Constructor & Destructor Documentation
virtual sstmac::hw::noise_model::~noise_model () inline virtual
Definition at line 15 of file noise.h.
References sstmac::hw::DeclareFactory(), init_factory_params(), and value().
Member Function Documentation
virtual void sstmac::hw::noise_model::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented in sstmac::hw::gaussian_noise_model.
Referenced by sstmac::hw::gaussian_noise_model::to_string(), and ~noise_model().
virtual double sstmac::hw::noise_model::value () pure virtual
Implemented in sstmac::hw::gaussian_noise_model.
Referenced by sstmac::hw::gaussian_noise_model::to_string(), and ~noise_model().
The documentation for this class was generated from the following file:
sstmac/hardware/noise/noise.h