SST/macro: sstmac::sw::dumpi_task_mapper Class Reference
sstmac::sw::dumpi_task_mapper Class Reference
#include <dumpi_task_mapper.h>
Public Member Functions
void set_topology (hw::topology *top)
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual ~dumpi_task_mapper () throw ()
void map_ranks (const app_id &aid, const ordered_node_set &nodes, int ppn, std::vector< node_id > &result, int nproc)
Assign processes to nodes.
Public Member Functions inherited from sstmac::sw::task_mapper
virtual std::string to_string () const
virtual void init_param1 (parallel_runtime *rt)
virtual ~task_mapper () throw ()
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Member Functions
node_id node_id_from_hostname (const std::string &hostname)
node_id node_id_from_coordinates (int ncoord, int *coordinates)
Protected Member Functions inherited from sstmac::sw::task_mapper
task_mapper ()
int validate_nproc (int ppn, int num_nodes, int nproc, const char *name) const
Protected Attributes
std::string metaname_
hw::structured_topology * regtop_
Protected Attributes inherited from sstmac::sw::task_mapper
hw::topology * topology_
parallel_runtime * rt_
Detailed Description
Definition at line 22 of file dumpi_task_mapper.h.
Constructor & Destructor Documentation
virtual sstmac::sw::dumpi_task_mapper::~dumpi_task_mapper () throw () inline virtual
Definition at line 32 of file dumpi_task_mapper.h.
References map_ranks(), node_id_from_coordinates(), and node_id_from_hostname().
Member Function Documentation
virtual void sstmac::sw::dumpi_task_mapper::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::sw::task_mapper.
void sstmac::sw::dumpi_task_mapper::map_ranks (const app_id & aid, const ordered_node_set & allocation, int ppn, std::vector< node_id > & result, int nproc) virtual
Assign processes to nodes.
Parameters
aid The application ID for the application whose processes are being indexed
nodes is the set of unique nodes to be used for the allocation
ppn is the nominal number of processes allocated on each node.
result is the resulting vector of length nodes (size nproc)
nproc the total number of processes to allocate
Exceptions
value_error if nodes.empty()
value_error if ppn <= 0
value_error if nodes.size()*ppn < nproc
Implements sstmac::sw::task_mapper.
Referenced by ~dumpi_task_mapper().
node_id sstmac::sw::dumpi_task_mapper::node_id_from_coordinates (int ncoord, int * coordinates) protected
Referenced by ~dumpi_task_mapper().
node_id sstmac::sw::dumpi_task_mapper::node_id_from_hostname (const std::string & hostname) protected
Referenced by ~dumpi_task_mapper().
void sstmac::sw::dumpi_task_mapper::set_topology (hw::topology * top) virtual
Reimplemented from sstmac::sw::task_mapper.
Member Data Documentation
std::string sstmac::sw::dumpi_task_mapper::metaname_ protected
Definition at line 47 of file dumpi_task_mapper.h.
hw::structured_topology* sstmac::sw::dumpi_task_mapper::regtop_ protected
Definition at line 49 of file dumpi_task_mapper.h.
The documentation for this class was generated from the following file:
sstmac/software/launch/dumpi_task_mapper.h