SST/macro: UnitTest Class Reference
UnitTest Class Reference
#include <test.h>
Public Member Functions
void append (TestCase *test_case)
int validate (std::ostream &os=std::cout)
Static Public Member Functions
static int exit_status (int nfailed)
Private Attributes
std::vector< TestCase * > tests_
Detailed Description
Definition at line 85 of file test.h.
Member Function Documentation
void UnitTest::append (TestCase * test_case) inline
Definition at line 92 of file test.h.
References tests_.
Referenced by AssertEqual< T, A >::add_test(), AssertEqual< T, T >::add_test(), AssertEqual< std::vector< T >, A >::add_test(), AssertEqual< std::vector< T >, std::vector< T > >::add_test(), and assertThrows_impl().
static int UnitTest::exit_status (int nfailed) inline static
Definition at line 102 of file test.h.
int UnitTest::validate (std::ostream & os = std::cout)
Returns
The number of failed tests
Member Data Documentation
std::vector<TestCase*> UnitTest::tests_ private
Definition at line 89 of file test.h.
Referenced by append().
The documentation for this class was generated from the following file:
sprockit/sprockit/test/test.h