SST/macro: sstmac::event_queue_entry Class Reference
sstmac::event_queue_entry Class Reference abstract
#include <sst_event.h>
Protected Attributes
timestamp time_
event_loc_id dst_loc_
event_loc_id src_loc_
uint32_t seqnum_
A unique sequence number from the source.
Private Member Functions
NotSerializable (event_queue_entry) public
virtual void execute ()=0
virtual std::string to_string () const =0
event_queue_entry (event_loc_id dst, event_loc_id src)
timestamp time () const
void set_time (const timestamp &t)
void set_seqnum (uint32_t seqnum)
uint32_t seqnum () const
event_loc_id event_location () const
event_loc_id src_location () const
Detailed Description
Definition at line 67 of file sst_event.h.
Constructor & Destructor Documentation
sstmac::event_queue_entry::event_queue_entry (event_loc_id dst, event_loc_id src) inline private
Definition at line 89 of file sst_event.h.
Member Function Documentation
event_loc_id sstmac::event_queue_entry::event_location () const inline private
Definition at line 118 of file sst_event.h.
virtual void sstmac::event_queue_entry::execute () private pure virtual
Implemented in sstmac::generic_event_2_args< Cls, Fxn, Arg1, Arg2 >, sstmac::generic_event_1_args< Cls, Fxn, Arg1 >, sstmac::generic_event, sstmac::generic_event_0_args< Cls, Fxn >, sstmac::handler_event_queue_entry, sstmac::sw::timeout_event, and sstmac::sw::unblock_event.
sstmac::event_queue_entry::NotSerializable (event_queue_entry) inline private
Definition at line 72 of file sst_event.h.
References sstmac::event::to_string().
uint32_t sstmac::event_queue_entry::seqnum () const inline private
Definition at line 113 of file sst_event.h.
Referenced by sstmac::native::event_map::event_compare::operator()().
void sstmac::event_queue_entry::set_seqnum (uint32_t seqnum) inline private
Definition at line 108 of file sst_event.h.
void sstmac::event_queue_entry::set_time (const timestamp & t) inline private
Definition at line 103 of file sst_event.h.
event_loc_id sstmac::event_queue_entry::src_location () const inline private
Definition at line 123 of file sst_event.h.
Referenced by sstmac::native::event_map::event_compare::operator()().
timestamp sstmac::event_queue_entry::time () const inline private
Definition at line 98 of file sst_event.h.
Referenced by sstmac::native::event_map::event_compare::operator()().
virtual std::string sstmac::event_queue_entry::to_string () const private pure virtual
Implemented in sstmac::generic_event_2_args< Cls, Fxn, Arg1, Arg2 >, sstmac::generic_event_1_args< Cls, Fxn, Arg1 >, sstmac::generic_event_0_args< Cls, Fxn >, sstmac::generic_event, sstmac::handler_event_queue_entry, sstmac::sw::timeout_event, and sstmac::sw::unblock_event.
Member Data Documentation
event_loc_id sstmac::event_queue_entry::dst_loc_ protected
Definition at line 133 of file sst_event.h.
uint32_t sstmac::event_queue_entry::seqnum_ protected
A unique sequence number from the source.
Definition at line 136 of file sst_event.h.
event_loc_id sstmac::event_queue_entry::src_loc_ protected
Definition at line 134 of file sst_event.h.
timestamp sstmac::event_queue_entry::time_ protected
Definition at line 132 of file sst_event.h.
The documentation for this class was generated from the following file:
sstmac/common/sst_event.h