SST/macro: sstmac::event_trace Class Reference
sstmac::event_trace Class Reference
#include <event_trace.h>
Public Member Functions
event_trace ()
virtual void simulation_finished (timestamp end)
This is to notify that the statistics collector is done.
void collect (int key_typeid, const std::string &name, node_id addr, long threadid, int aid, int tid, long ticks_begin, long num_ticks)
void reduce (stat_collector *coll)
void dump_local_data ()
After post-processing, this notifies the collector to dump data to a file.
void dump_global_data ()
After post-processing, this notifies the collector to dump data to a file.
void global_reduce (parallel_runtime *rt)
void init_factory_params (sprockit::sim_parameters *params)
void clear ()
virtual ~event_trace ()
stat_collector * clone () const
event_trace * clone_me (int id) const
Public Member Functions inherited from sstmac::stat_collector
virtual ~stat_collector ()
virtual std::string to_string () const
bool registered () const
virtual void set_id (int id)
int id () const
void set_registered (bool reg)
void add_suffix (const std::string &suffix)
std::string fileroot () const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Member Functions
void clone_into (event_trace *cln) const
Protected Member Functions inherited from sstmac::stat_collector
stat_collector ()
void clone_into (stat_collector *cln) const
Protected Attributes
long start_
long stop_
Protected Attributes inherited from sstmac::stat_collector
bool registered_
int id_
std::string fileroot_
Additional Inherited Members
Static Protected Member Functions inherited from sstmac::stat_collector
static bool check_open (std::fstream &myfile, const std::string &fname, std::ios::openmode flags=std::ios::out)
Check to see if the file is open.
Detailed Description
Definition at line 20 of file event_trace.h.
Constructor & Destructor Documentation
sstmac::event_trace::event_trace () inline
Definition at line 25 of file event_trace.h.
References clear(), collect(), dump_global_data(), dump_local_data(), global_reduce(), init_factory_params(), reduce(), and simulation_finished().
Referenced by clone_me().
virtual sstmac::event_trace::~event_trace () inline virtual
Definition at line 60 of file event_trace.h.
Member Function Documentation
void sstmac::event_trace::clear () virtual
Implements sstmac::stat_collector.
Referenced by event_trace().
stat_collector* sstmac::event_trace::clone () const inline virtual
Implements sstmac::stat_collector.
Definition at line 64 of file event_trace.h.
References clone_me().
void sstmac::event_trace::clone_into (event_trace * cln) const protected
Referenced by clone_me().
event_trace* sstmac::event_trace::clone_me (int id) const inline
Definition at line 69 of file event_trace.h.
References clone_into(), event_trace(), and sstmac::stat_collector::set_id().
Referenced by clone().
void sstmac::event_trace::collect (int key_typeid, const std::string & name, node_id addr, long threadid, int aid, int tid, long ticks_begin, long num_ticks)
Referenced by event_trace().
void sstmac::event_trace::dump_global_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
Referenced by event_trace().
void sstmac::event_trace::dump_local_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
Referenced by event_trace().
void sstmac::event_trace::global_reduce (parallel_runtime * rt) virtual
Implements sstmac::stat_collector.
Referenced by event_trace().
void sstmac::event_trace::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::stat_collector.
Referenced by event_trace().
void sstmac::event_trace::reduce (stat_collector * coll) virtual
Implements sstmac::stat_collector.
Referenced by event_trace().
virtual void sstmac::event_trace::simulation_finished (timestamp end) virtual
This is to notify that the statistics collector is done.
Do any necessary data post-processing, but do NOT dump to file
Implements sstmac::stat_collector.
Referenced by event_trace().
Member Data Documentation
long sstmac::event_trace::start_ protected
Definition at line 81 of file event_trace.h.
long sstmac::event_trace::stop_ protected
Definition at line 82 of file event_trace.h.
The documentation for this class was generated from the following file:
sstmac/common/stats/event_trace.h