SST/macro: sstmac::hw::dist_dummy_switch Class Reference
sstmac::hw::dist_dummy_switch Class Reference
The dist_dummy_switch class Encapsulates a switch that is a placeholder used in parallel simulation.
#include <dist_dummyswitch.h>
Public Member Functions
dist_dummy_switch (switch_id sid)
std::string to_string () const
bool ipc_handler () const
virtual ~dist_dummy_switch ()
virtual void handle (event *ev)
virtual void connect (int src_outport, int dst_inport, connection_type_t ty, connectable *mod)
virtual void connect_input (int src_outport, int dst_inport, connectable *comp, config *cfg)
virtual void connect_output (int src_outport, int dst_inport, connectable *comp, config *cfg)
std::vector< switch_id > connected_switches () const
double hop_bandwidth () const
timestamp hop_latency () const
timestamp lookahead () const
int queue_length (int port) const
Protected Member Functions
virtual void connect_ejector (int src_outport, int dst_inport, event_handler *nic)
virtual void connect_injector (int src_outport, int dst_inport, event_handler *nic)
Detailed Description
The dist_dummy_switch class Encapsulates a switch that is a placeholder used in parallel simulation.
A link between a real switch and a dummy switch represents a link between switches on different MPI ranks.
Definition at line 30 of file dist_dummyswitch.h.
Constructor & Destructor Documentation
sstmac::hw::dist_dummy_switch::dist_dummy_switch (switch_id sid) inline
Definition at line 33 of file dist_dummyswitch.h.
References to_string().
virtual sstmac::hw::dist_dummy_switch::~dist_dummy_switch () inline virtual
Definition at line 48 of file dist_dummyswitch.h.
References handle().
Member Function Documentation
virtual void sstmac::hw::dist_dummy_switch::connect (int src_outport, int dst_inport, connection_type_t ty, connectable * mod) inline virtual
Definition at line 55 of file dist_dummyswitch.h.
References connect_input(), and connect_output().
virtual void sstmac::hw::dist_dummy_switch::connect_ejector (int src_outport, int dst_inport, event_handler * nic) protected virtual
Referenced by queue_length().
virtual void sstmac::hw::dist_dummy_switch::connect_injector (int src_outport, int dst_inport, event_handler * nic) protected virtual
Referenced by queue_length().
virtual void sstmac::hw::dist_dummy_switch::connect_input (int src_outport, int dst_inport, connectable * comp, config * cfg) virtual
Referenced by connect().
virtual void sstmac::hw::dist_dummy_switch::connect_output (int src_outport, int dst_inport, connectable * comp, config * cfg) virtual
Referenced by connect().
std::vector<switch_id> sstmac::hw::dist_dummy_switch::connected_switches () const inline
Definition at line 78 of file dist_dummyswitch.h.
References hop_bandwidth(), hop_latency(), lookahead(), and spkt_throw.
virtual void sstmac::hw::dist_dummy_switch::handle (event * ev) virtual
Referenced by ~dist_dummy_switch().
double sstmac::hw::dist_dummy_switch::hop_bandwidth () const
Referenced by connected_switches().
timestamp sstmac::hw::dist_dummy_switch::hop_latency () const
Referenced by connected_switches().
bool sstmac::hw::dist_dummy_switch::ipc_handler () const inline
Definition at line 43 of file dist_dummyswitch.h.
timestamp sstmac::hw::dist_dummy_switch::lookahead () const
Referenced by connected_switches().
int sstmac::hw::dist_dummy_switch::queue_length (int port) const inline
Definition at line 93 of file dist_dummyswitch.h.
References connect_ejector(), and connect_injector().
std::string sstmac::hw::dist_dummy_switch::to_string () const
Referenced by dist_dummy_switch().
The documentation for this class was generated from the following file:
sstmac/hardware/switch/dist_dummyswitch.h