SST/macro: sstmac::sw::lib_compute_inst Class Reference
sstmac::sw::lib_compute_inst Class Reference
#include <lib_compute_inst.h>
Public Member Functions
lib_compute_inst (software_id id)
lib_compute_inst (const std::string &id)
virtual ~lib_compute_inst ()
void compute_inst (compute_event *msg)
void compute_detailed (uint64_t flops, uint64_t nintops, uint64_t bytes)
void compute_loop (uint64_t nloops, uint32_t flops_per_loop, uint32_t intops_per_loop, uint32_t bytes_per_loop)
virtual bool supported () const
virtual void consume_params (sprockit::sim_parameters *params)
void incoming_event (event *ev)
Protected Attributes
double loop_overhead_
Detailed Description
Definition at line 27 of file lib_compute_inst.h.
Constructor & Destructor Documentation
sstmac::sw::lib_compute_inst::lib_compute_inst (software_id id)
sstmac::sw::lib_compute_inst::lib_compute_inst (const std::string & id)
virtual sstmac::sw::lib_compute_inst::~lib_compute_inst () inline virtual
Definition at line 36 of file lib_compute_inst.h.
References compute_detailed(), compute_inst(), compute_loop(), consume_params(), and supported().
Member Function Documentation
void sstmac::sw::lib_compute_inst::compute_detailed (uint64_t flops, uint64_t nintops, uint64_t bytes)
Referenced by ~lib_compute_inst().
void sstmac::sw::lib_compute_inst::compute_inst (compute_event * msg)
Referenced by ~lib_compute_inst().
void sstmac::sw::lib_compute_inst::compute_loop (uint64_t nloops, uint32_t flops_per_loop, uint32_t intops_per_loop, uint32_t bytes_per_loop)
Referenced by ~lib_compute_inst().
virtual void sstmac::sw::lib_compute_inst::consume_params (sprockit::sim_parameters * params) virtual
Reimplemented in sstmac::sw::lib_compute_loops, and sstmac::sw::lib_compute_memmove.
Referenced by ~lib_compute_inst().
void sstmac::sw::lib_compute_inst::incoming_event (event * ev) inline
Definition at line 59 of file lib_compute_inst.h.
References sstmac::sw::library::incoming_event().
virtual bool sstmac::sw::lib_compute_inst::supported () const virtual
Reimplemented in sstmac::sw::lib_compute_loops, sstmac::sw::lib_compute_matrix, and sstmac::sw::lib_compute_memmove.
Referenced by sstmac::sw::lib_compute_matrix::supported(), sstmac::sw::lib_compute_loops::supported(), and ~lib_compute_inst().
Member Data Documentation
double sstmac::sw::lib_compute_inst::loop_overhead_ protected
Definition at line 64 of file lib_compute_inst.h.
The documentation for this class was generated from the following file:
sstmac/software/libraries/compute/lib_compute_inst.h