SST/macro: TestCase_impl< T > Class Template Reference
TestCase_impl< T > Class Template Reference
#include <test.h>
Public Member Functions
TestCase_impl (const std::string &descr, bool should_be_equal, const T &test, const T &asserted)
bool is_correct () const
void print_error (std::ostream &os) const
void print_descr (std::ostream &os) const
void print_test_value (std::ostream &os) const
void print_asserted_value (std::ostream &os) const
Private Attributes
std::string descr_
bool should_be_equal_
bool equal_
T test_
T asserted_
Detailed Description
template<class T>
class TestCase_impl< T >
Definition at line 32 of file test.h.
Constructor & Destructor Documentation
template<class T > TestCase_impl< T >::TestCase_impl (const std::string & descr, bool should_be_equal, const T & test, const T & asserted) inline
Definition at line 43 of file test.h.
References TestEquals< T >::equals().
Member Function Documentation
template<class T > bool TestCase_impl< T >::is_correct () const inline virtual
Implements TestCase.
Definition at line 55 of file test.h.
template<class T > void TestCase_impl< T >::print_asserted_value (std::ostream & os) const inline virtual
Implements TestCase.
Definition at line 79 of file test.h.
References ClassOutput< T >::print().
template<class T > void TestCase_impl< T >::print_descr (std::ostream & os) const inline virtual
Implements TestCase.
Definition at line 69 of file test.h.
template<class T > void TestCase_impl< T >::print_error (std::ostream & os) const inline virtual
Implements TestCase.
Definition at line 59 of file test.h.
template<class T > void TestCase_impl< T >::print_test_value (std::ostream & os) const inline virtual
Implements TestCase.
Definition at line 74 of file test.h.
References ClassOutput< T >::print().
Member Data Documentation
template<class T > T TestCase_impl< T >::asserted_ private
Definition at line 40 of file test.h.
template<class T > std::string TestCase_impl< T >::descr_ private
Definition at line 36 of file test.h.
template<class T > bool TestCase_impl< T >::equal_ private
Definition at line 38 of file test.h.
template<class T > bool TestCase_impl< T >::should_be_equal_ private
Definition at line 37 of file test.h.
template<class T > T TestCase_impl< T >::test_ private
Definition at line 39 of file test.h.
The documentation for this class was generated from the following file:
sprockit/sprockit/test/test.h