SST/macro: sstmac::stat_local_double Class Reference
sstmac::stat_local_double Class Reference
#include <stat_local_double.h>
Public Member Functions
stat_local_double ()
void collect (double value)
void simulation_finished (timestamp end)
This is to notify that the statistics collector is done.
void dump_local_data ()
After post-processing, this notifies the collector to dump data to a file.
void dump_global_data ()
After post-processing, this notifies the collector to dump data to a file.
void global_reduce (parallel_runtime *rt)
void clear ()
void reduce (stat_collector *coll)
void init_factory_params (sprockit::sim_parameters *params)
stat_local_double * clone_me (int id) const
stat_collector * clone () const
Public Member Functions inherited from sstmac::stat_collector
virtual ~stat_collector ()
virtual std::string to_string () const
void init_factory_params (sprockit::sim_parameters *params)
bool registered () const
virtual void set_id (int id)
int id () const
void set_registered (bool reg)
void add_suffix (const std::string &suffix)
std::string fileroot () const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Member Functions
void dump (const std::string &froot)
void clone_into (stat_local_double *cln) const
Protected Member Functions inherited from sstmac::stat_collector
stat_collector ()
void clone_into (stat_collector *cln) const
Protected Attributes
int size_
double value_
std::vector< double > values_
Protected Attributes inherited from sstmac::stat_collector
bool registered_
int id_
std::string fileroot_
Additional Inherited Members
Static Protected Member Functions inherited from sstmac::stat_collector
static bool check_open (std::fstream &myfile, const std::string &fname, std::ios::openmode flags=std::ios::out)
Check to see if the file is open.
Detailed Description
Definition at line 10 of file stat_local_double.h.
Constructor & Destructor Documentation
sstmac::stat_local_double::stat_local_double ()
Referenced by clone_me().
Member Function Documentation
void sstmac::stat_local_double::clear () virtual
Implements sstmac::stat_collector.
stat_collector* sstmac::stat_local_double::clone () const inline virtual
Implements sstmac::stat_collector.
Definition at line 49 of file stat_local_double.h.
References clone_into(), clone_me(), and dump().
void sstmac::stat_local_double::clone_into (stat_local_double * cln) const protected
Referenced by clone(), and clone_me().
stat_local_double* sstmac::stat_local_double::clone_me (int id) const inline
Definition at line 41 of file stat_local_double.h.
References clone_into(), sstmac::stat_collector::set_id(), and stat_local_double().
Referenced by clone().
void sstmac::stat_local_double::collect (double value)
void sstmac::stat_local_double::dump (const std::string & froot) protected
Referenced by clone().
void sstmac::stat_local_double::dump_global_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
void sstmac::stat_local_double::dump_local_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
void sstmac::stat_local_double::global_reduce (parallel_runtime * rt) virtual
Implements sstmac::stat_collector.
void sstmac::stat_local_double::init_factory_params (sprockit::sim_parameters * params)
void sstmac::stat_local_double::reduce (stat_collector * coll) virtual
Implements sstmac::stat_collector.
void sstmac::stat_local_double::simulation_finished (timestamp end) virtual
This is to notify that the statistics collector is done.
Do any necessary data post-processing, but do NOT dump to file
Implements sstmac::stat_collector.
Member Data Documentation
int sstmac::stat_local_double::size_ protected
Definition at line 61 of file stat_local_double.h.
double sstmac::stat_local_double::value_ protected
Definition at line 62 of file stat_local_double.h.
std::vector<double> sstmac::stat_local_double::values_ protected
Definition at line 63 of file stat_local_double.h.
The documentation for this class was generated from the following file:
sstmac/common/stats/stat_local_double.h