SST/macro: sstmac::param_expander Class Reference
sstmac::param_expander Class Reference abstract
#include <param_expander.h>
Public Member Functions
virtual ~param_expander ()
virtual void expand (sprockit::sim_parameters *params)=0
virtual void finalize_init ()
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Detailed Description
Definition at line 9 of file param_expander.h.
Constructor & Destructor Documentation
virtual sstmac::param_expander::~param_expander () inline virtual
Definition at line 13 of file param_expander.h.
References sstmac::DeclareFactory(), expand(), and finalize_init().
Member Function Documentation
virtual void sstmac::param_expander::expand (sprockit::sim_parameters * params) pure virtual
Implemented in sstmac::hw::simple_param_expander, and sstmac::hw::packet_flow_param_expander.
Referenced by ~param_expander().
virtual void sstmac::param_expander::finalize_init () virtual
Reimplemented from sprockit::factory_type.
Referenced by ~param_expander().
The documentation for this class was generated from the following file:
sstmac/common/param_expander.h