SST/macro: sstmac::stat_spyplot_png Class Reference
sstmac::stat_spyplot_png Class Reference
this stat_collector class keeps a spy plot, and outputs it as a png
#include <stat_spyplot.h>
Public Member Functions
stat_spyplot_png ()
virtual std::string to_string () const
virtual void add (int source, int dest, long num)
virtual void dump_to_file (const std::string &froot)
void set_normalization (long max)
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual ~stat_spyplot_png ()
stat_spyplot * clone_me (int id) const
stat_collector * clone () const
Public Member Functions inherited from sstmac::stat_spyplot
virtual void simulation_finished (timestamp end)
This is to notify that the statistics collector is done.
virtual void dump_local_data ()
After post-processing, this notifies the collector to dump data to a file.
virtual void dump_global_data ()
After post-processing, this notifies the collector to dump data to a file.
virtual void reduce (stat_collector *coll)
virtual void global_reduce (parallel_runtime *rt)
virtual void clear ()
virtual ~stat_spyplot ()
virtual void add_one (int source, int dest)
stat_spyplot ()
Public Member Functions inherited from sstmac::stat_collector
virtual ~stat_collector ()
void init_factory_params (sprockit::sim_parameters *params)
bool registered () const
virtual void set_id (int id)
int id () const
void set_registered (bool reg)
void add_suffix (const std::string &suffix)
std::string fileroot () const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Member Functions
void clone_into (stat_spyplot_png *cln) const
Protected Member Functions inherited from sstmac::stat_spyplot
void clone_into (stat_spyplot *cln) const
Protected Member Functions inherited from sstmac::stat_collector
stat_collector ()
void clone_into (stat_collector *cln) const
Protected Attributes
long normalization_
bool fill_
Protected Attributes inherited from sstmac::stat_spyplot
spyplot_map vals_
int max_dest_
Protected Attributes inherited from sstmac::stat_collector
bool registered_
int id_
std::string fileroot_
Additional Inherited Members
Protected Types inherited from sstmac::stat_spyplot
typedef spkt_unordered_map< int, long > long_map
typedef spkt_unordered_map< int, long_map > spyplot_map
Static Protected Member Functions inherited from sstmac::stat_collector
static bool check_open (std::fstream &myfile, const std::string &fname, std::ios::openmode flags=std::ios::out)
Check to see if the file is open.
Detailed Description
this stat_collector class keeps a spy plot, and outputs it as a png
Definition at line 98 of file stat_spyplot.h.
Constructor & Destructor Documentation
sstmac::stat_spyplot_png::stat_spyplot_png () inline
Definition at line 101 of file stat_spyplot.h.
virtual sstmac::stat_spyplot_png::~stat_spyplot_png () inline virtual
Definition at line 126 of file stat_spyplot.h.
Member Function Documentation
virtual void sstmac::stat_spyplot_png::add (int source, int dest, long num) virtual
Reimplemented from sstmac::stat_spyplot.
stat_collector* sstmac::stat_spyplot_png::clone () const inline virtual
Reimplemented from sstmac::stat_spyplot.
Definition at line 138 of file stat_spyplot.h.
References sstmac::stat_spyplot::clone_into(), and sstmac::stat_spyplot::clone_me().
void sstmac::stat_spyplot_png::clone_into (stat_spyplot_png * cln) const protected
stat_spyplot* sstmac::stat_spyplot_png::clone_me (int id) const inline virtual
Reimplemented from sstmac::stat_spyplot.
Definition at line 130 of file stat_spyplot.h.
References sstmac::stat_spyplot::clone_into(), and sstmac::stat_collector::set_id().
virtual void sstmac::stat_spyplot_png::dump_to_file (const std::string & froot) virtual
Reimplemented from sstmac::stat_spyplot.
virtual void sstmac::stat_spyplot_png::init_factory_params (sprockit::sim_parameters * params) virtual
void sstmac::stat_spyplot_png::set_normalization (long max) inline
Definition at line 118 of file stat_spyplot.h.
References sstmac::stat_collector::init_factory_params().
virtual std::string sstmac::stat_spyplot_png::to_string () const inline virtual
Reimplemented from sstmac::stat_spyplot.
Definition at line 107 of file stat_spyplot.h.
References sstmac::stat_spyplot::add(), and sstmac::stat_spyplot::dump_to_file().
Member Data Documentation
bool sstmac::stat_spyplot_png::fill_ protected
Definition at line 148 of file stat_spyplot.h.
long sstmac::stat_spyplot_png::normalization_ protected
Definition at line 147 of file stat_spyplot.h.
The documentation for this class was generated from the following file:
sstmac/common/stats/stat_spyplot.h