SST/macro: sstmac::hw::stat_bytes_sent Class Reference
sstmac::hw::stat_bytes_sent Class Reference
#include <packet_flow_stats.h>
Classes
class aggregation
struct global_gather_stats_t
Public Member Functions
stat_bytes_sent ()
void record (int port, long bytes)
void set_topology (topology *top)
void simulation_finished (timestamp end)
This is to notify that the statistics collector is done.
void dump_local_data ()
After post-processing, this notifies the collector to dump data to a file.
void dump_global_data ()
After post-processing, this notifies the collector to dump data to a file.
void global_reduce (parallel_runtime *rt)
void reduce (stat_collector *coll)
stat_collector * clone () const
void clear ()
Public Member Functions inherited from sstmac::stat_collector
virtual ~stat_collector ()
virtual std::string to_string () const
void init_factory_params (sprockit::sim_parameters *params)
bool registered () const
virtual void set_id (int id)
int id () const
void set_registered (bool reg)
void add_suffix (const std::string &suffix)
std::string fileroot () const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Member Functions
void clone_into (stat_bytes_sent *cln) const
Protected Member Functions inherited from sstmac::stat_collector
stat_collector ()
void clone_into (stat_collector *cln) const
Private Types
typedef std::map< int, long > port_map
Private Member Functions
void global_reduce_non_root (parallel_runtime *rt, int root, char *buffer, int buffer_size)
void collect_buffer_at_root (char *buffer, int buffer_size)
void output_switch (int sid, std::fstream &data_str, structured_topology *top)
void collect_counts_at_root (parallel_runtime *rt, int src, global_gather_stats_t stats)
void global_reduce_root (parallel_runtime *rt, global_gather_stats_t *stats, char *my_buffer, int my_buffer_size)
Private Attributes
FRIEND_SERIALIZATION
topology * top_
port_map port_map_
aggregation * local_aggregation_
std::vector< port_map > global_aggregation_
Additional Inherited Members
Static Protected Member Functions inherited from sstmac::stat_collector
static bool check_open (std::fstream &myfile, const std::string &fname, std::ios::openmode flags=std::ios::out)
Check to see if the file is open.
Protected Attributes inherited from sstmac::stat_collector
bool registered_
int id_
std::string fileroot_
Detailed Description
Definition at line 13 of file packet_flow_stats.h.
Member Typedef Documentation
typedef std::map<int, long> sstmac::hw::stat_bytes_sent::port_map private
Definition at line 83 of file packet_flow_stats.h.
Constructor & Destructor Documentation
sstmac::hw::stat_bytes_sent::stat_bytes_sent () inline
Definition at line 19 of file packet_flow_stats.h.
Referenced by clone().
Member Function Documentation
void sstmac::hw::stat_bytes_sent::clear () inline virtual
Implements sstmac::stat_collector.
Definition at line 54 of file packet_flow_stats.h.
References collect_buffer_at_root(), global_reduce_non_root(), and output_switch().
stat_collector* sstmac::hw::stat_bytes_sent::clone () const inline virtual
Implements sstmac::stat_collector.
Definition at line 47 of file packet_flow_stats.h.
References clone_into(), and stat_bytes_sent().
void sstmac::hw::stat_bytes_sent::clone_into (stat_bytes_sent * cln) const protected
Referenced by clone().
void sstmac::hw::stat_bytes_sent::collect_buffer_at_root (char * buffer, int buffer_size) private
Referenced by clear().
void sstmac::hw::stat_bytes_sent::collect_counts_at_root (parallel_runtime * rt, int src, global_gather_stats_t stats) private
void sstmac::hw::stat_bytes_sent::dump_global_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
Referenced by set_topology().
void sstmac::hw::stat_bytes_sent::dump_local_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
Referenced by set_topology().
void sstmac::hw::stat_bytes_sent::global_reduce (parallel_runtime * rt) virtual
Implements sstmac::stat_collector.
Referenced by set_topology().
void sstmac::hw::stat_bytes_sent::global_reduce_non_root (parallel_runtime * rt, int root, char * buffer, int buffer_size) private
Referenced by clear().
void sstmac::hw::stat_bytes_sent::global_reduce_root (parallel_runtime * rt, global_gather_stats_t * stats, char * my_buffer, int my_buffer_size) private
void sstmac::hw::stat_bytes_sent::output_switch (int sid, std::fstream & data_str, structured_topology * top) private
Referenced by clear().
void sstmac::hw::stat_bytes_sent::record (int port, long bytes) inline
Definition at line 22 of file packet_flow_stats.h.
References port_map_.
void sstmac::hw::stat_bytes_sent::reduce (stat_collector * coll) virtual
Implements sstmac::stat_collector.
Referenced by set_topology().
void sstmac::hw::stat_bytes_sent::set_topology (topology * top) inline
Definition at line 27 of file packet_flow_stats.h.
References dump_global_data(), dump_local_data(), global_reduce(), reduce(), simulation_finished(), and top_.
void sstmac::hw::stat_bytes_sent::simulation_finished (timestamp end) virtual
This is to notify that the statistics collector is done.
Do any necessary data post-processing, but do NOT dump to file
Implements sstmac::stat_collector.
Referenced by set_topology().
Member Data Documentation
sstmac::hw::stat_bytes_sent::FRIEND_SERIALIZATION private
Definition at line 16 of file packet_flow_stats.h.
std::vector<port_map> sstmac::hw::stat_bytes_sent::global_aggregation_ private
Definition at line 147 of file packet_flow_stats.h.
aggregation* sstmac::hw::stat_bytes_sent::local_aggregation_ private
Definition at line 146 of file packet_flow_stats.h.
port_map sstmac::hw::stat_bytes_sent::port_map_ private
Definition at line 84 of file packet_flow_stats.h.
Referenced by record().
topology* sstmac::hw::stat_bytes_sent::top_ private
Definition at line 81 of file packet_flow_stats.h.
Referenced by set_topology().
The documentation for this class was generated from the following file:
sstmac/hardware/packet_flow/packet_flow_stats.h