SST/macro: sprockit::pvt::ser_sizer Class Reference
sprockit::pvt::ser_sizer Class Reference
#include <serialize_sizer.h>
Public Member Functions
ser_sizer ()
template<class T >
void size (T &t)
void size_string (std::string &str)
void add (size_t s)
size_t size () const
void reset ()
Protected Attributes
size_t size_
Detailed Description
Definition at line 7 of file serialize_sizer.h.
Constructor & Destructor Documentation
sprockit::pvt::ser_sizer::ser_sizer () inline
Definition at line 10 of file serialize_sizer.h.
Member Function Documentation
void sprockit::pvt::ser_sizer::add (size_t s) inline
Definition at line 25 of file serialize_sizer.h.
References size_.
Referenced by sprockit::serializer::array(), and sprockit::serializer::binary().
void sprockit::pvt::ser_sizer::reset () inline
Definition at line 35 of file serialize_sizer.h.
References size_.
Referenced by sprockit::serializer::reset(), and sprockit::serializer::start_sizing().
template<class T > void sprockit::pvt::ser_sizer::size (T & t) inline
Definition at line 17 of file serialize_sizer.h.
References size_, and size_string().
Referenced by sprockit::serializer::primitive(), and sprockit::serializer::size().
size_t sprockit::pvt::ser_sizer::size () const inline
Definition at line 30 of file serialize_sizer.h.
References size_.
void sprockit::pvt::ser_sizer::size_string (std::string & str)
Referenced by size().
Member Data Documentation
size_t sprockit::pvt::ser_sizer::size_ protected
Definition at line 40 of file serialize_sizer.h.
Referenced by add(), reset(), and size().
The documentation for this class was generated from the following file:
sprockit/sprockit/serialize_sizer.h