SST/macro: sstmac::native::multithreaded_subcontainer Class Reference
sstmac::native::multithreaded_subcontainer Class Reference
#include <multithreaded_subcontainer.h>
Public Member Functions
~multithreaded_subcontainer () throw ()
void multithread_schedule (int srcthread, int dstthread, uint32_t seqnum, event_queue_entry *ev)
void receive_incoming_events ()
timestamp vote_next_round (timestamp my_time)
void run ()
Run the eventmanager.
multithreaded_subcontainer (int thread_id, multithreaded_event_container *parent)
Public Member Functions inherited from sstmac::native::clock_cycle_event_map
virtual ~clock_cycle_event_map () throw ()
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual void finalize_init ()
bool vote_to_terminate ()
virtual void set_interconnect (hw::interconnect *interconn)
virtual void ipc_schedule (timestamp t, event_loc_id dst, event_loc_id src, uint32_t seqnum, event *ev)
Public Member Functions inherited from sstmac::native::event_map
~event_map () throw ()
void clear (timestamp zero_time=timestamp(0))
Clear all events and set time back to a zero of your choice.
void cancel_all_messages (event_loc_id mod)
bool empty () const
Public Member Functions inherited from sstmac::native::event_container
virtual ~event_container () throw ()
Goodbye.
Public Member Functions inherited from sstmac::event_manager
virtual std::string to_string () const
bool is_complete ()
virtual ~event_manager ()
Goodbye.
timestamp now () const
void register_stat (stat_collector *stat, bool reduce_all=true, bool dump_all=false, bool dump_main=true)
stat_collector * register_thread_unique_stat (stat_collector *stat, bool reduce_all=true, bool dump_all=false, bool dump_main=true)
partition * topology_partition () const
parallel_runtime * runtime () const
void finish_stats ()
virtual void finish_stats (stat_collector *main, const std::string &name, timestamp end)
void stop ()
int me () const
int worker_id () const
int nproc () const
int nworker () const
virtual int lpid () const
int thread_id () const
int nthread () const
virtual event_manager * ev_man_for_thread (int thread_id) const
void init_param1 (parallel_runtime *rt)
virtual void schedule_stop (timestamp until)
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Protected Attributes
multithreaded_event_container * parent_
Protected Attributes inherited from sstmac::native::clock_cycle_event_map
timestamp next_time_horizon_
timestamp lookahead_
timestamp no_events_left_time_
std::vector< void * > all_incoming_
std::vector< std::vector< void * > > thread_incoming_
hw::switch_interconnect * interconn_
int epoch_
Protected Attributes inherited from sstmac::native::event_map
queue_t queue_
Protected Attributes inherited from sstmac::native::event_container
bool running_
Sentinel to track whether the event handler is running or not.
timestamp last_update_sim_
Time of last event executed.
Protected Attributes inherited from sstmac::event_manager
bool complete_
bool stopped_
bool finish_on_stop_
parallel_runtime * rt_
int thread_id_
int me_
int nproc_
int nthread_
Additional Inherited Members
Public Types inherited from sstmac::native::clock_cycle_event_map
enum vote_type_t { vote_max, vote_min }
Static Public Member Functions inherited from sstmac::event_manager
static int current_thread_id ()
Static Public Attributes inherited from sstmac::event_manager
static event_manager * global
Protected Types inherited from sstmac::native::event_map
typedef std::set< event_queue_entry *, event_compare > queue_t
Protected Member Functions inherited from sstmac::native::clock_cycle_event_map
virtual void schedule_incoming (const std::vector< void * > &mpi_buffers)
void do_next_event ()
timestamp next_event_time () const
virtual timestamp vote_next_round (timestamp my_time, vote_type_t ty)
int64_t do_vote (int64_t time, vote_type_t ty=vote_min)
Protected Member Functions inherited from sstmac::native::event_map
event_queue_entry * pop_next_event ()
void add_event (event_queue_entry *ev)
Called by schedule. Child class must implement.
Protected Member Functions inherited from sstmac::native::event_container
event_container ()
void schedule (timestamp start_time, uint32_t seqnum, event_queue_entry *ev)
Set off the given eventhandler at the given time.
void finish ()
Called at end of run().
Protected Member Functions inherited from sstmac::event_manager
event_manager ()
void set_now (const timestamp &ts)
Static Protected Attributes inherited from sstmac::event_manager
static std::vector< pthread_t > pthreads_
static std::vector< pthread_attr_t > pthread_attrs_
Detailed Description
Definition at line 13 of file multithreaded_subcontainer.h.
Constructor & Destructor Documentation
sstmac::native::multithreaded_subcontainer::~multithreaded_subcontainer () throw () inline
Definition at line 17 of file multithreaded_subcontainer.h.
References multithread_schedule(), multithreaded_subcontainer(), receive_incoming_events(), run(), sstmac::event_manager::thread_id(), and vote_next_round().
sstmac::native::multithreaded_subcontainer::multithreaded_subcontainer (int thread_id, multithreaded_event_container * parent)
Referenced by ~multithreaded_subcontainer().
Member Function Documentation
void sstmac::native::multithreaded_subcontainer::multithread_schedule (int srcthread, int dstthread, uint32_t seqnum, event_queue_entry * ev) virtual
Reimplemented from sstmac::event_manager.
Referenced by ~multithreaded_subcontainer().
void sstmac::native::multithreaded_subcontainer::receive_incoming_events () virtual
Reimplemented from sstmac::native::clock_cycle_event_map.
Referenced by ~multithreaded_subcontainer().
void sstmac::native::multithreaded_subcontainer::run () virtual
Run the eventmanager.
The eventmanager shall return control when no more messages remain.
Reimplemented from sstmac::native::clock_cycle_event_map.
Referenced by ~multithreaded_subcontainer().
timestamp sstmac::native::multithreaded_subcontainer::vote_next_round (timestamp my_time)
Referenced by ~multithreaded_subcontainer().
Member Data Documentation
multithreaded_event_container* sstmac::native::multithreaded_subcontainer::parent_ protected
Definition at line 38 of file multithreaded_subcontainer.h.
The documentation for this class was generated from the following file:
sstmac/backends/native/clock_cycle_parallel/multithreaded_subcontainer.h