SST/macro: sstmac::hw::routable Class Reference
sstmac::hw::routable Class Reference
#include <routable_message.h>
Public Member Functions
node_id toaddr () const
node_id fromaddr () const
void set_toaddr (node_id to)
void set_fromaddr (node_id from)
const routing_info & rinfo () const
routing_info & rinfo ()
int port () const
int vc () const
routing::algorithm_t algo () const
void set_algo (routing::algorithm_t algo)
void serialize_order (serializer &ser)
void add_hop ()
int n_hops ()
Protected Member Functions
routable ()
routable (node_id toaddr, node_id fromaddr)
Protected Attributes
routing_info rinfo_
node_id toaddr_
node_id fromaddr_
int n_hops_
Detailed Description
Definition at line 10 of file routable_message.h.
Constructor & Destructor Documentation
sstmac::hw::routable::routable () inline protected
Definition at line 78 of file routable_message.h.
References fromaddr(), and toaddr().
sstmac::hw::routable::routable (node_id toaddr, node_id fromaddr) protected
Member Function Documentation
void sstmac::hw::routable::add_hop () inline
Definition at line 68 of file routable_message.h.
References n_hops_.
routing::algorithm_t sstmac::hw::routable::algo () const inline
Definition at line 55 of file routable_message.h.
References rinfo_, and sstmac::hw::routing_info::route_algo().
node_id sstmac::hw::routable::fromaddr () const inline
Definition at line 20 of file routable_message.h.
References fromaddr_.
Referenced by routable().
int sstmac::hw::routable::n_hops () inline
Definition at line 73 of file routable_message.h.
References n_hops_.
int sstmac::hw::routable::port () const inline
Definition at line 45 of file routable_message.h.
References sstmac::hw::routing_info::port(), and rinfo_.
const routing_info& sstmac::hw::routable::rinfo () const inline
Definition at line 35 of file routable_message.h.
References rinfo_.
routing_info& sstmac::hw::routable::rinfo () inline
Definition at line 40 of file routable_message.h.
References rinfo_.
void sstmac::hw::routable::serialize_order (serializer & ser)
Referenced by set_algo().
void sstmac::hw::routable::set_algo (routing::algorithm_t algo) inline
Definition at line 60 of file routable_message.h.
References rinfo_, serialize_order(), and sstmac::hw::routing_info::set_route_algo().
void sstmac::hw::routable::set_fromaddr (node_id from) inline
Definition at line 30 of file routable_message.h.
References fromaddr_.
void sstmac::hw::routable::set_toaddr (node_id to) inline
Definition at line 25 of file routable_message.h.
References toaddr_.
node_id sstmac::hw::routable::toaddr () const inline
Definition at line 15 of file routable_message.h.
References toaddr_.
Referenced by routable().
int sstmac::hw::routable::vc () const inline
Definition at line 50 of file routable_message.h.
References rinfo_, and sstmac::hw::routing_info::vc().
Member Data Documentation
node_id sstmac::hw::routable::fromaddr_ protected
Definition at line 87 of file routable_message.h.
Referenced by fromaddr(), and set_fromaddr().
int sstmac::hw::routable::n_hops_ protected
Definition at line 89 of file routable_message.h.
Referenced by add_hop(), and n_hops().
routing_info sstmac::hw::routable::rinfo_ protected
Definition at line 83 of file routable_message.h.
Referenced by algo(), port(), rinfo(), set_algo(), and vc().
node_id sstmac::hw::routable::toaddr_ protected
Definition at line 85 of file routable_message.h.
Referenced by set_toaddr(), and toaddr().
The documentation for this class was generated from the following file:
sstmac/hardware/router/routable_message.h