SST/macro: sprockit::SpktFactory3InitParams< T, U, V, W > Class Template Reference
sprockit::SpktFactory3InitParams< T, U, V, W > Class Template Reference
#include <factory.h>
Public Types
typedef SpktFactory< T > parent
Public Types inherited from sprockit::SpktFactory< T >
typedef SpktFactoryTemplateBase< T > parent
typedef T element_type
Static Public Member Functions
static T * get_value (const std::string &valname, sim_parameters *params, const U &param1, const V &param2, const W &param3)
static T * get_param (const std::string &param_name, sim_parameters *params, const U &param1, const V &param2, const W &param3)
static T * get_optional_param (const std::string &param_name, const std::string &defval, sim_parameters *params, const U &param1, const V &param2, const W &param3)
static T * get_extra_param (const std::string &param_name, sim_parameters *params, const U &param1, const V &param2, const W &param3)
Static Public Member Functions inherited from sprockit::SpktFactory< T >
static void register_alias (const std::string &oldname, const std::string &newname)
static T * get_value (const std::string &valname, sim_parameters *params)
static T * get_extra_param (const std::string &param_name, sim_parameters *params)
static T * get_param (const std::string &param_name, sim_parameters *params)
static T * get_optional_param (const std::string &param_name, const std::string &defval, sim_parameters *params)
Static Public Member Functions inherited from sprockit::SpktFactoryTemplateBase< T >
static void register_name (const std::string &name, SpktDesc_base *descr)
static void delete_statics ()
static void validate_map (const std::string &valname)
Static Public Member Functions inherited from sprockit::SpktFactory_base
static void add_to_map (const std::string &namestr, SpktDesc_base *desc, std::map< std::string, SpktDesc_base * > *descr_map, std::map< std::string, std::list< std::string > > *alias_map)
static std::string value (const std::string &key, sim_parameters *params)
static std::string value (const std::string &key, const std::string &defval, sim_parameters *params)
static bool exists (const std::string &key, sim_parameters *params)
Additional Inherited Members
Protected Types inherited from sprockit::SpktFactoryTemplateBase< T >
typedef std::map< std::string, SpktDesc_base * > descr_map
typedef std::map< std::string, std::list< std::string > > alias_map
Static Protected Member Functions inherited from sprockit::SpktFactory< T >
static T * _get_value (const std::string &valname)
static T * _get_param (const std::string &param_name, sim_parameters *params)
static T * _get_optional_param (const std::string &param_name, const std::string &defval, sim_parameters *params)
Static Protected Attributes inherited from sprockit::SpktFactoryTemplateBase< T >
static descr_map * object_map_
static alias_map * alias_map_
static const char * name_
Detailed Description
template<class T, class U, class V, class W>
class sprockit::SpktFactory3InitParams< T, U, V, W >
Definition at line 361 of file factory.h.
Member Typedef Documentation
template<class T , class U , class V , class W > typedef SpktFactory<T> sprockit::SpktFactory3InitParams< T, U, V, W >::parent
Definition at line 364 of file factory.h.
Member Function Documentation
template<class T , class U , class V , class W > static T* sprockit::SpktFactory3InitParams< T, U, V, W >::get_extra_param (const std::string & param_name, sim_parameters * params, const U & param1, const V & param2, const W & param3) inline static
Definition at line 396 of file factory.h.
References get_param().
template<class T , class U , class V , class W > static T* sprockit::SpktFactory3InitParams< T, U, V, W >::get_optional_param (const std::string & param_name, const std::string & defval, sim_parameters * params, const U & param1, const V & param2, const W & param3) inline static
Definition at line 387 of file factory.h.
References sprockit::factory_init().
template<class T , class U , class V , class W > static T* sprockit::SpktFactory3InitParams< T, U, V, W >::get_param (const std::string & param_name, sim_parameters * params, const U & param1, const V & param2, const W & param3) inline static
Definition at line 378 of file factory.h.
References sprockit::factory_init().
template<class T , class U , class V , class W > static T* sprockit::SpktFactory3InitParams< T, U, V, W >::get_value (const std::string & valname, sim_parameters * params, const U & param1, const V & param2, const W & param3) inline static
Definition at line 370 of file factory.h.
References sprockit::factory_init().
The documentation for this class was generated from the following file:
sprockit/sprockit/factories/factory.h