SST/macro: sstmac::native::indexing_app_manager Class Reference
sstmac::native::indexing_app_manager Class Reference abstract
#include <indexing_app_manager.h>
Public Member Functions
void init_factory_params (sprockit::sim_parameters *params)
virtual ~indexing_app_manager ()
virtual int nproc () const
node_id node_assignment (int rank) const
const std::list< int > & rank_assignment (node_id nid) const
sw::launch_info * launch_info () const
void allocate_and_index_jobs ()
void set_interconnect (hw::interconnect *interconn)
Public Member Functions inherited from sstmac::sw::app_manager
virtual ~app_manager ()
virtual void init_param1 (sw::app_id aid)
virtual void init_param2 (parallel_runtime *rt)
hw::topology * topol () const
hw::interconnect * interconn () const
hw::node * node_at (node_id nid) const
void add_hostname (sw::task_id tid, const std::string &name, node_id addr)
void setenv (const std::string &name, const std::string &value)
std::string getenv (const std::string &name) const
std::string hostname (sw::task_id tid) const
node_id node_address (const std::string &hostname) const
node_id node_for_task (sw::task_id tid) const
void set_node_address (sw::task_id tid, node_id n)
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Member Functions
void init_launch_info ()
virtual void do_allocate_and_index_jobs ()=0
Protected Member Functions inherited from sstmac::sw::app_manager
app_manager ()
Protected Attributes
sw::allocation_strategy * allocator_
sw::index_strategy * indexer_
std::vector< node_id > rank_to_node_indexing_
std::vector< std::list< int > > node_to_rank_indexing_
sw::launch_info * linfo_
int nproc_
Protected Attributes inherited from sstmac::sw::app_manager
parallel_runtime * rt_
hw::topology * top_
hw::interconnect * interconn_
sw::app * app_template_
sw::app_id aid_
std::string appname_
std::vector< int > core_affinities_
task_to_node_map nodeids_
task_to_hostname_map hostnames_
hostname_to_addr_map inet_addrs_
shell_var_map shell_env_
Additional Inherited Members
Static Public Member Functions inherited from sstmac::sw::app_manager
static app_manager * static_app_manager (int aid, sprockit::sim_parameters *params)
Protected Types inherited from sstmac::sw::app_manager
typedef spkt_unordered_map< sw::task_id, node_id > task_to_node_map
typedef spkt_unordered_map< sw::task_id, std::string > task_to_hostname_map
typedef spkt_unordered_map< std::string, std::string > shell_var_map
typedef spkt_unordered_map< std::string, node_id > hostname_to_addr_map
Detailed Description
Definition at line 13 of file indexing_app_manager.h.
Constructor & Destructor Documentation
virtual sstmac::native::indexing_app_manager::~indexing_app_manager () virtual
Member Function Documentation
void sstmac::native::indexing_app_manager::allocate_and_index_jobs () virtual
Implements sstmac::sw::app_manager.
Referenced by launch_info().
virtual void sstmac::native::indexing_app_manager::do_allocate_and_index_jobs () protected pure virtual
Implemented in sstmac::native::skeleton_app_manager, and sstmac::native::dumpi_app_manager.
Referenced by launch_info().
void sstmac::native::indexing_app_manager::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::sw::app_manager.
Reimplemented in sstmac::native::skeleton_app_manager.
void sstmac::native::indexing_app_manager::init_launch_info () protected
Referenced by launch_info().
sw::launch_info* sstmac::native::indexing_app_manager::launch_info () const inline virtual
Implements sstmac::sw::app_manager.
Definition at line 39 of file indexing_app_manager.h.
References allocate_and_index_jobs(), do_allocate_and_index_jobs(), init_launch_info(), sstmac::sw::app_manager::interconn(), linfo_, and set_interconnect().
node_id sstmac::native::indexing_app_manager::node_assignment (int rank) const inline virtual
Implements sstmac::sw::app_manager.
Definition at line 29 of file indexing_app_manager.h.
References rank_to_node_indexing_.
virtual int sstmac::native::indexing_app_manager::nproc () const inline virtual
Implements sstmac::sw::app_manager.
Definition at line 24 of file indexing_app_manager.h.
References nproc_.
Referenced by sstmac::native::skeleton_app_manager::to_string().
const std::list<int>& sstmac::native::indexing_app_manager::rank_assignment (node_id nid) const inline virtual
Implements sstmac::sw::app_manager.
Definition at line 34 of file indexing_app_manager.h.
References node_to_rank_indexing_.
void sstmac::native::indexing_app_manager::set_interconnect (hw::interconnect * interconn) virtual
Reimplemented from sstmac::sw::app_manager.
Referenced by launch_info().
Member Data Documentation
sw::allocation_strategy* sstmac::native::indexing_app_manager::allocator_ protected
Definition at line 56 of file indexing_app_manager.h.
sw::index_strategy* sstmac::native::indexing_app_manager::indexer_ protected
Definition at line 57 of file indexing_app_manager.h.
sw::launch_info* sstmac::native::indexing_app_manager::linfo_ protected
Definition at line 60 of file indexing_app_manager.h.
Referenced by launch_info().
std::vector<std::list<int> > sstmac::native::indexing_app_manager::node_to_rank_indexing_ protected
Definition at line 59 of file indexing_app_manager.h.
Referenced by rank_assignment().
int sstmac::native::indexing_app_manager::nproc_ protected
Definition at line 62 of file indexing_app_manager.h.
Referenced by nproc().
std::vector<node_id> sstmac::native::indexing_app_manager::rank_to_node_indexing_ protected
Definition at line 58 of file indexing_app_manager.h.
Referenced by node_assignment().
The documentation for this class was generated from the following file:
sstmac/backends/native/indexing_app_manager.h