SST/macro: sstmac::sw::compute_event Class Reference
sstmac::sw::compute_event Class Reference
Input for processor models that use performance counter data.
#include <compute_event.h>
Private Types
enum event_type_t {
mem_random = 0, mem_sequential = 1, flop = 2, intop = 3,
time = 4
}
Private Member Functions
ImplementSerializableDefaultConstructor (compute_event) public
compute_event ()
virtual ~compute_event ()
std::string to_string () const
void set_event_value (event_type_t ty, uint64_t val)
uint64_t event_value (event_type_t ty) const
Get event data.
void set_event_time (const timestamp &t)
std::string debug_string () const
timestamp event_time () const
bool timed_computed () const
void set_core (int core)
int core () const
hw::memory_access_id access_id () const
void set_access_id (hw::memory_access_id id)
uint64_t unique_id () const
long byte_length () const
Private Attributes
int core_
uint64_t event_data_ [MAX_EVENTS]
hw::memory_access_id unique_id_
Additional Inherited Members
Public Member Functions inherited from sstmac::event
void serialize_order (serializer &ser)
virtual bool is_packet () const
convenience methods
virtual bool is_credit () const
virtual bool is_failure () const
template<class T >
T * interface ()
Public Member Functions inherited from sprockit::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
virtual ~serializable ()
Protected Types inherited from sprockit::serializable
enum cxn_flag_t { ConstructorFlag }
Detailed Description
Input for processor models that use performance counter data.
Is basically just a map that maps std::string keys to integer values. Keys are defined in the libraries that use them.
Definition at line 33 of file compute_event.h.
Member Enumeration Documentation
enum sstmac::sw::compute_event::event_type_t private
Enumerator
mem_random
mem_sequential
flop
intop
time
Definition at line 44 of file compute_event.h.
Constructor & Destructor Documentation
sstmac::sw::compute_event::compute_event () private
virtual sstmac::sw::compute_event::~compute_event () inline private virtual
Definition at line 54 of file compute_event.h.
Member Function Documentation
hw::memory_access_id sstmac::sw::compute_event::access_id () const inline private
Definition at line 109 of file compute_event.h.
References unique_id_.
long sstmac::sw::compute_event::byte_length () const private
Referenced by unique_id().
int sstmac::sw::compute_event::core () const inline private
Definition at line 104 of file compute_event.h.
References core_.
Referenced by set_core().
std::string sstmac::sw::compute_event::debug_string () const private
Referenced by set_event_time().
timestamp sstmac::sw::compute_event::event_time () const inline private
Definition at line 89 of file compute_event.h.
References event_data_, sstmac::timestamp::exact, and time.
uint64_t sstmac::sw::compute_event::event_value (event_type_t ty) const inline private
Get event data.
Parameters
key the key
Returns
value associated with given key
Definition at line 76 of file compute_event.h.
References event_data_.
sstmac::sw::compute_event::ImplementSerializableDefaultConstructor (compute_event) inline private
Definition at line 38 of file compute_event.h.
void sstmac::sw::compute_event::set_access_id (hw::memory_access_id id) inline private
Definition at line 114 of file compute_event.h.
References unique_id_.
void sstmac::sw::compute_event::set_core (int core) inline private
Definition at line 99 of file compute_event.h.
References core(), and core_.
void sstmac::sw::compute_event::set_event_time (const timestamp & t) inline private
Definition at line 81 of file compute_event.h.
References debug_string(), event_data_, sstmac::timestamp::ticks_int64(), and time.
void sstmac::sw::compute_event::set_event_value (event_type_t ty, uint64_t val) inline private
Parameters
key the key
val value to associate with the given key
Definition at line 66 of file compute_event.h.
References event_data_.
bool sstmac::sw::compute_event::timed_computed () const inline private
Definition at line 94 of file compute_event.h.
References event_data_, and time.
std::string sstmac::sw::compute_event::to_string () const inline private virtual
Implements sstmac::event.
Definition at line 57 of file compute_event.h.
uint64_t sstmac::sw::compute_event::unique_id () const inline private
Definition at line 119 of file compute_event.h.
References byte_length(), and unique_id_.
Member Data Documentation
int sstmac::sw::compute_event::core_ private
Definition at line 127 of file compute_event.h.
Referenced by core(), and set_core().
uint64_t sstmac::sw::compute_event::event_data_[MAX_EVENTS] private
Definition at line 130 of file compute_event.h.
Referenced by event_time(), event_value(), set_event_time(), set_event_value(), and timed_computed().
hw::memory_access_id sstmac::sw::compute_event::unique_id_ private
Definition at line 132 of file compute_event.h.
Referenced by access_id(), set_access_id(), and unique_id().
The documentation for this class was generated from the following file:
sstmac/software/libraries/compute/compute_event.h