SST/macro: sstmac::hw::packet_flow_netlink Class Reference
sstmac::hw::packet_flow_netlink Class Reference
#include <packet_flow_nic.h>
Public Member Functions
packet_flow_netlink ()
std::string to_string () const
void init_factory_params (sprockit::sim_parameters *params)
void connect (int src_outport, int dst_inport, connection_type_t ty, connectable *mod, config *cfg)
connect
void set_event_parent (event_scheduler *m)
Set the eventmanager for this scheduler.
void handle (event *ev)
event_handler * ejector ()
int initial_credits () const
event_handler * injector ()
Public Member Functions inherited from sstmac::hw::netlink
int node_port (int node_offset) const
int switch_port (int tile_offset) const
void init_param1 (sprockit::factory_type *)
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Public Member Functions inherited from sstmac::event_subscheduler
event_subscheduler ()
timestamp now () const
get the current time
void schedule (timestamp t, event_handler *handler, event *ev)
Add an event to the event queue, where msg will get delivered to handler at time t.
void schedule (timestamp t, event_queue_entry *ev)
void schedule_now (event_queue_entry *ev)
void schedule_now (event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_queue_entry *ev)
void send_self_event (timestamp arrival, event *ev)
void send_delayed_self_event (timestamp delay, event *ev)
void send_now_self_event (event *ev)
void send_self_event_queue (timestamp arrival, event_queue_entry *ev)
void send_delayed_self_event_queue (timestamp delay, event_queue_entry *ev)
void send_now_self_event_queue (event_queue_entry *ev)
event_scheduler * parent () const
Public Member Functions inherited from sstmac::event_handler
virtual ~event_handler ()
event_loc_id event_location () const
virtual bool ipc_handler () const
Whether an event handler is a "fake" handler that represents logical process boundary.
int thread_id () const
virtual void deadlock_check (event *ev)
virtual void deadlock_check ()
Private Member Functions
void init ()
Private Attributes
packet_flow_crossbar * block_
int tile_rotater_
bool inited_
Static Private Attributes
static const int really_big_buffer
Additional Inherited Members
Public Types inherited from sstmac::hw::connectable
enum config_type_t {
RedundantConnection =0, WeightedConnection =1, FixedBandwidthConnection =2, FixedConnection =3,
BasicConnection =4
}
enum connection_type_t { output, input }
Static Public Member Functions inherited from sstmac::hw::connectable
static const char * str (connection_type_t ty)
Static Public Attributes inherited from sstmac::hw::connectable
static const int any_port = -1
Static Public Attributes inherited from sstmac::event_handler
static const int null_lpid = -1
static const int null_threadid = -1
Protected Member Functions inherited from sstmac::event_handler
event_handler ()
void init_loc_id (event_loc_id id)
void init_thread_id (int id)
Protected Attributes inherited from sstmac::hw::netlink
int num_eject_
int num_inject_
netlink_id id_
Protected Attributes inherited from sstmac::event_subscheduler
event_scheduler * parent_
Detailed Description
Definition at line 83 of file packet_flow_nic.h.
Constructor & Destructor Documentation
sstmac::hw::packet_flow_netlink::packet_flow_netlink () inline
Definition at line 88 of file packet_flow_nic.h.
Member Function Documentation
void sstmac::hw::packet_flow_netlink::connect (int src_outport, int dst_inport, connection_type_t ty, connectable * mod, config * cfg) virtual
connect
Parameters
src_outport The outgoing port at the source
dst_inport The incoming port at the destination
ty Whether we are configuring the input or output direction
mod The device currently being connected
cfg A struct with various special configuration options
Implements sstmac::hw::connectable.
event_handler* sstmac::hw::packet_flow_netlink::ejector () inline
Definition at line 118 of file packet_flow_nic.h.
References sstmac::init().
void sstmac::hw::packet_flow_netlink::handle (event * ev) virtual
Reimplemented from sstmac::event_subscheduler.
void sstmac::hw::packet_flow_netlink::init () private
void sstmac::hw::packet_flow_netlink::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::hw::netlink.
int sstmac::hw::packet_flow_netlink::initial_credits () const inline
Definition at line 124 of file packet_flow_nic.h.
event_handler* sstmac::hw::packet_flow_netlink::injector () inline
Definition at line 129 of file packet_flow_nic.h.
References sstmac::init().
void sstmac::hw::packet_flow_netlink::set_event_parent (event_scheduler * m) virtual
Set the eventmanager for this scheduler.
Unfortunately, this always has to be called after an event_scheduler is constructed.
Parameters
m the simulation eventmanager
Reimplemented from sstmac::event_subscheduler.
std::string sstmac::hw::packet_flow_netlink::to_string () const inline virtual
Reimplemented from sstmac::event_subscheduler.
Definition at line 96 of file packet_flow_nic.h.
References sstmac::hw::packet_flow_nic::connect(), sstmac::hw::packet_flow_nic::handle(), sstmac::hw::packet_flow_nic::init_factory_params(), and sstmac::hw::packet_flow_nic::set_event_parent().
Member Data Documentation
packet_flow_crossbar* sstmac::hw::packet_flow_netlink::block_ private
Definition at line 139 of file packet_flow_nic.h.
bool sstmac::hw::packet_flow_netlink::inited_ private
Definition at line 141 of file packet_flow_nic.h.
const int sstmac::hw::packet_flow_netlink::really_big_buffer static private
Definition at line 138 of file packet_flow_nic.h.
int sstmac::hw::packet_flow_netlink::tile_rotater_ private
Definition at line 140 of file packet_flow_nic.h.
The documentation for this class was generated from the following file:
sstmac/hardware/packet_flow/packet_flow_nic.h