SST/macro: sstmac::hw::packet_flow_bandwidth_arbitrator Class Reference
sstmac::hw::packet_flow_bandwidth_arbitrator Class Reference abstract
#include <packet_flow_arbitrator.h>
Public Member Functions
virtual void arbitrate (timestamp now, packet_flow_payload *payload, timestamp &packet_head_leaves, timestamp &packet_tail_leaves, timestamp &credit_leaves)=0
Assign bandwidth to payload.
virtual std::string to_string () const =0
virtual ~packet_flow_bandwidth_arbitrator ()
virtual void set_outgoing_bw (double out_bw)
double outgoing_bw () const
virtual void init_noise_model (noise_model *noise)
virtual void partition (noise_model *noise, int num_intervals)
partition Partition the arbitrator time windows into a series of randomly sized chunks
virtual packet_flow_bandwidth_arbitrator * clone (double bw) const =0
virtual int bytes_sending (const timestamp &now) const =0
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Static Public Member Functions
static timestamp credit_delay (double max_in_bw, double out_bw, long bytes)
Protected Member Functions
packet_flow_bandwidth_arbitrator ()
Protected Attributes
double out_bw_
double inv_out_bw_
Static Protected Attributes
static const int min_trans_
Detailed Description
Definition at line 13 of file packet_flow_arbitrator.h.
Constructor & Destructor Documentation
virtual sstmac::hw::packet_flow_bandwidth_arbitrator::~packet_flow_bandwidth_arbitrator () inline virtual
Definition at line 33 of file packet_flow_arbitrator.h.
sstmac::hw::packet_flow_bandwidth_arbitrator::packet_flow_bandwidth_arbitrator () protected
Referenced by credit_delay().
Member Function Documentation
virtual void sstmac::hw::packet_flow_bandwidth_arbitrator::arbitrate (timestamp now, packet_flow_payload * payload, timestamp & packet_head_leaves, timestamp & packet_tail_leaves, timestamp & credit_leaves) pure virtual
Assign bandwidth to payload.
Returns
The time at which the packet can be forwarded to the next switch/node/etc.
Implemented in sstmac::hw::packet_flow_cut_through_arbitrator, sstmac::hw::packet_flow_simple_arbitrator, and sstmac::hw::packet_flow_null_arbitrator.
virtual int sstmac::hw::packet_flow_bandwidth_arbitrator::bytes_sending (const timestamp & now) const pure virtual
Implemented in sstmac::hw::packet_flow_cut_through_arbitrator, sstmac::hw::packet_flow_simple_arbitrator, and sstmac::hw::packet_flow_null_arbitrator.
Referenced by credit_delay(), sstmac::hw::packet_flow_null_arbitrator::to_string(), and sstmac::hw::packet_flow_simple_arbitrator::to_string().
virtual packet_flow_bandwidth_arbitrator* sstmac::hw::packet_flow_bandwidth_arbitrator::clone (double bw) const pure virtual
Implemented in sstmac::hw::packet_flow_cut_through_arbitrator, sstmac::hw::packet_flow_simple_arbitrator, and sstmac::hw::packet_flow_null_arbitrator.
Referenced by credit_delay().
static timestamp sstmac::hw::packet_flow_bandwidth_arbitrator::credit_delay (double max_in_bw, double out_bw, long bytes) inline static
Definition at line 46 of file packet_flow_arbitrator.h.
References bytes_sending(), clone(), init_noise_model(), packet_flow_bandwidth_arbitrator(), and partition().
virtual void sstmac::hw::packet_flow_bandwidth_arbitrator::init_noise_model (noise_model * noise) virtual
Reimplemented in sstmac::hw::packet_flow_cut_through_arbitrator.
Referenced by credit_delay(), and sstmac::hw::packet_flow_cut_through_arbitrator::to_string().
double sstmac::hw::packet_flow_bandwidth_arbitrator::outgoing_bw () const inline
Definition at line 41 of file packet_flow_arbitrator.h.
References out_bw_.
virtual void sstmac::hw::packet_flow_bandwidth_arbitrator::partition (noise_model * noise, int num_intervals) virtual
partition Partition the arbitrator time windows into a series of randomly sized chunks
Parameters
noise The noise model that randomly selects time values
num_intervals
Reimplemented in sstmac::hw::packet_flow_cut_through_arbitrator.
Referenced by credit_delay(), and sstmac::hw::packet_flow_cut_through_arbitrator::to_string().
virtual void sstmac::hw::packet_flow_bandwidth_arbitrator::set_outgoing_bw (double out_bw) inline virtual
Reimplemented in sstmac::hw::packet_flow_cut_through_arbitrator.
Definition at line 36 of file packet_flow_arbitrator.h.
References inv_out_bw_, and out_bw_.
Referenced by sstmac::hw::packet_flow_null_arbitrator::clone(), sstmac::hw::packet_flow_simple_arbitrator::clone(), and sstmac::hw::packet_flow_cut_through_arbitrator::clone().
virtual std::string sstmac::hw::packet_flow_bandwidth_arbitrator::to_string () const pure virtual
Implemented in sstmac::hw::packet_flow_cut_through_arbitrator, sstmac::hw::packet_flow_simple_arbitrator, and sstmac::hw::packet_flow_null_arbitrator.
Member Data Documentation
double sstmac::hw::packet_flow_bandwidth_arbitrator::inv_out_bw_ protected
Definition at line 75 of file packet_flow_arbitrator.h.
Referenced by set_outgoing_bw().
const int sstmac::hw::packet_flow_bandwidth_arbitrator::min_trans_ static protected
Definition at line 76 of file packet_flow_arbitrator.h.
double sstmac::hw::packet_flow_bandwidth_arbitrator::out_bw_ protected
Definition at line 74 of file packet_flow_arbitrator.h.
Referenced by outgoing_bw(), and set_outgoing_bw().
The documentation for this class was generated from the following file:
sstmac/hardware/packet_flow/packet_flow_arbitrator.h