SST/macro: sstmac::location_trace Class Reference
sstmac::location_trace Class Reference
#include <location_trace.h>
Classes
struct event
Public Member Functions
std::string to_string () const
void collect (timestamp created, event_loc_id creator, timestamp scheduled, event_loc_id runner)
bool read (std::istream &myfile, timestamp &created, event_loc_id &creator, timestamp &scheduled, event_loc_id &runner)
void dump_local_data ()
After post-processing, this notifies the collector to dump data to a file.
void dump_global_data ()
After post-processing, this notifies the collector to dump data to a file.
void global_reduce (parallel_runtime *rt)
void simulation_finished (timestamp end)
This is to notify that the statistics collector is done.
location_trace * clone_me (int id) const
stat_collector * clone () const
void reduce (stat_collector *coll)
void clear ()
virtual ~location_trace ()
Public Member Functions inherited from sstmac::stat_collector
virtual ~stat_collector ()
virtual void init_factory_params (sprockit::sim_parameters *params)
bool registered () const
virtual void set_id (int id)
int id () const
void set_registered (bool reg)
void add_suffix (const std::string &suffix)
std::string fileroot () const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Private Attributes
std::list< event > local_events_
std::map< timestamp, event > global_events_
Additional Inherited Members
Protected Member Functions inherited from sstmac::stat_collector
stat_collector ()
void clone_into (stat_collector *cln) const
Static Protected Member Functions inherited from sstmac::stat_collector
static bool check_open (std::fstream &myfile, const std::string &fname, std::ios::openmode flags=std::ios::out)
Check to see if the file is open.
Protected Attributes inherited from sstmac::stat_collector
bool registered_
int id_
std::string fileroot_
Detailed Description
Definition at line 9 of file location_trace.h.
Constructor & Destructor Documentation
virtual sstmac::location_trace::~location_trace () inline virtual
Definition at line 61 of file location_trace.h.
Member Function Documentation
void sstmac::location_trace::clear () virtual
Implements sstmac::stat_collector.
Referenced by clone().
stat_collector* sstmac::location_trace::clone () const inline virtual
Implements sstmac::stat_collector.
Definition at line 52 of file location_trace.h.
References clear(), clone_me(), and reduce().
location_trace* sstmac::location_trace::clone_me (int id) const inline
Definition at line 45 of file location_trace.h.
References sstmac::stat_collector::set_id().
Referenced by clone().
void sstmac::location_trace::collect (timestamp created, event_loc_id creator, timestamp scheduled, event_loc_id runner)
Referenced by to_string().
void sstmac::location_trace::dump_global_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
Referenced by to_string().
void sstmac::location_trace::dump_local_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
Referenced by to_string().
void sstmac::location_trace::global_reduce (parallel_runtime * rt) virtual
Implements sstmac::stat_collector.
Referenced by to_string().
bool sstmac::location_trace::read (std::istream & myfile, timestamp & created, event_loc_id & creator, timestamp & scheduled, event_loc_id & runner)
Referenced by to_string().
void sstmac::location_trace::reduce (stat_collector * coll) virtual
Implements sstmac::stat_collector.
Referenced by clone().
void sstmac::location_trace::simulation_finished (timestamp end) inline virtual
This is to notify that the statistics collector is done.
Do any necessary data post-processing, but do NOT dump to file
Implements sstmac::stat_collector.
Definition at line 42 of file location_trace.h.
std::string sstmac::location_trace::to_string () const inline virtual
Reimplemented from sstmac::stat_collector.
Definition at line 15 of file location_trace.h.
References collect(), dump_global_data(), dump_local_data(), global_reduce(), and read().
Member Data Documentation
std::map<timestamp, event> sstmac::location_trace::global_events_ private
Definition at line 74 of file location_trace.h.
std::list<event> sstmac::location_trace::local_events_ private
Definition at line 72 of file location_trace.h.
The documentation for this class was generated from the following file:
sstmac/common/stats/location_trace.h