SST/macro: sstmac::sw::index_strategy Class Reference
sstmac::sw::index_strategy Class Reference abstract
Base class for strategies regarding how to sequentially number nodes in a parallel simulation.
#include <index_strategy.h>
Public Types
typedef std::set< node_id > node_set
Public Member Functions
virtual std::string to_string () const
virtual void set_topology (hw::topology *top)
virtual void init_param1 (parallel_runtime *rt)
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual ~index_strategy () throw ()
virtual void allocate (const app_id &aid, const node_set &allocation, int ppn, std::vector< node_id > &result, int nproc)=0
Assign processes to nodes.
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Member Functions
index_strategy ()
int validate_nproc (int ppn, int num_nodes, int nproc, const char *name) const
Protected Attributes
hw::topology * topology_
parallel_runtime * rt_
Detailed Description
Base class for strategies regarding how to sequentially number nodes in a parallel simulation.
Definition at line 34 of file index_strategy.h.
Member Typedef Documentation
typedef std::set<node_id> sstmac::sw::index_strategy::node_set
Definition at line 38 of file index_strategy.h.
Constructor & Destructor Documentation
virtual sstmac::sw::index_strategy::~index_strategy () throw () virtual
Referenced by init_param1().
sstmac::sw::index_strategy::index_strategy () inline protected
Definition at line 81 of file index_strategy.h.
References validate_nproc().
Member Function Documentation
virtual void sstmac::sw::index_strategy::allocate (const app_id & aid, const node_set & allocation, int ppn, std::vector< node_id > & result, int nproc) pure virtual
Assign processes to nodes.
Parameters
aid The application ID for the application whose processes are being indexed
nodes is the list of unique nodes to be used for the allocation
ppn is the nominal number of processes allocated on each node.
result is the resulting vector of length nodes (size nproc)
nproc the total number of processes to allocate
Exceptions
value_error if nodes.empty()
value_error if ppn <= 0
value_error if nodes.size()*ppn < nproc
Implemented in sstmac::sw::random_indexing, sstmac::sw::dumpi_indexer, sstmac::sw::block_indexing, sstmac::sw::round_robin_indexing, sstmac::sw::coordinate_indexing, sstmac::sw::hostname_indexer, and sstmac::sw::node_id_indexing.
Referenced by init_param1().
virtual void sstmac::sw::index_strategy::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented in sstmac::sw::coordinate_indexing, sstmac::sw::dumpi_indexer, sstmac::sw::random_indexing, sstmac::sw::node_id_indexing, and sstmac::sw::hostname_indexer.
Referenced by init_param1().
virtual void sstmac::sw::index_strategy::init_param1 (parallel_runtime * rt) inline virtual
Definition at line 52 of file index_strategy.h.
References allocate(), init_factory_params(), rt_, and ~index_strategy().
virtual void sstmac::sw::index_strategy::set_topology (hw::topology * top) inline virtual
Reimplemented in sstmac::sw::dumpi_indexer.
Definition at line 47 of file index_strategy.h.
References topology_.
virtual std::string sstmac::sw::index_strategy::to_string () const inline virtual
Definition at line 42 of file index_strategy.h.
int sstmac::sw::index_strategy::validate_nproc (int ppn, int num_nodes, int nproc, const char * name) const protected
Referenced by index_strategy().
Member Data Documentation
parallel_runtime* sstmac::sw::index_strategy::rt_ protected
Definition at line 89 of file index_strategy.h.
Referenced by init_param1().
hw::topology* sstmac::sw::index_strategy::topology_ protected
Definition at line 88 of file index_strategy.h.
Referenced by set_topology().
The documentation for this class was generated from the following file:
sstmac/software/launch/index_strategy.h