SST/macro: sstmac::sw::lib_compute_time Class Reference
sstmac::sw::lib_compute_time Class Reference
#include <lib_compute_time.h>
Public Member Functions
lib_compute_time (software_id id)
lib_compute_time (const char *prefix, software_id id)
lib_compute_time (const std::string &name, software_id id)
virtual ~lib_compute_time ()
void incoming_event (event *ev)
void compute (timestamp time)
Detailed Description
Definition at line 22 of file lib_compute_time.h.
Constructor & Destructor Documentation
sstmac::sw::lib_compute_time::lib_compute_time (software_id id)
sstmac::sw::lib_compute_time::lib_compute_time (const char * prefix, software_id id)
sstmac::sw::lib_compute_time::lib_compute_time (const std::string & name, software_id id)
virtual sstmac::sw::lib_compute_time::~lib_compute_time () virtual
Member Function Documentation
void sstmac::sw::lib_compute_time::compute (timestamp time)
Referenced by incoming_event().
void sstmac::sw::lib_compute_time::incoming_event (event * ev) inline
Definition at line 36 of file lib_compute_time.h.
References compute(), and sstmac::sw::library::incoming_event().
The documentation for this class was generated from the following file:
sstmac/software/libraries/compute/lib_compute_time.h