SST/macro: sstmac::event Class Reference
sstmac::event Class Reference abstract
#include <sst_event.h>
Public Member Functions
virtual std::string to_string () const =0
void serialize_order (serializer &ser)
virtual bool is_packet () const
convenience methods
virtual bool is_credit () const
virtual bool is_failure () const
template<class T >
T * interface ()
Public Member Functions inherited from sprockit::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
virtual ~serializable ()
Additional Inherited Members
Protected Types inherited from sprockit::serializable
enum cxn_flag_t { ConstructorFlag }
Detailed Description
Definition at line 28 of file sst_event.h.
Member Function Documentation
template<class T > T* sstmac::event::interface () inline
Definition at line 60 of file sst_event.h.
Referenced by sstmac::hw::multipath_router< ParentRouter >::route().
virtual bool sstmac::event::is_credit () const inline virtual
Definition at line 49 of file sst_event.h.
virtual bool sstmac::event::is_failure () const inline virtual
Definition at line 54 of file sst_event.h.
virtual bool sstmac::event::is_packet () const inline virtual
convenience methods
Reimplemented in sstmac::hw::packet.
Definition at line 44 of file sst_event.h.
void sstmac::event::serialize_order (serializer & ser) inline virtual
Implements sprockit::serializable.
Reimplemented in sstmac::hw::network_message, sstmac::hw::packet, and sstmac::transport_message.
Definition at line 40 of file sst_event.h.
Referenced by sstmac::hw::fail_event::ImplementSerializable().
virtual std::string sstmac::event::to_string () const pure virtual
Implemented in sstmac::hw::network_message, sstmac::sw::launch_event, sstmac::sw::compute_event, sstmac::transport_message, sstmac::hw::memory_message, sstmac::sw::arrive_message, sstmac::sw::job_launch_event, sstmac::hw::fail_event, sstmac::hw::packet, and sstmac::sleep_event.
Referenced by sstmac::event_queue_entry::NotSerializable(), and sstmac::handler_event_queue_entry::~handler_event_queue_entry().
The documentation for this class was generated from the following file:
sstmac/common/sst_event.h