SST/macro: ClassOutput< T > Class Template Reference
ClassOutput< T > Class Template Reference
#include <output.h>
Static Public Member Functions
static void print (const T &t, std::ostream &os)
Detailed Description
template<class T>
class ClassOutput< T >
Definition at line 9 of file output.h.
Member Function Documentation
template<class T > static void ClassOutput< T >::print (const T & t, std::ostream & os) inline static
Definition at line 14 of file output.h.
Referenced by ClassOutput< std::vector< T > >::print(), ClassOutput< std::map< T, U > >::print(), TestCase_impl< T >::print_asserted_value(), and TestCase_impl< T >::print_test_value().
The documentation for this class was generated from the following file:
sprockit/sprockit/test/output.h