SST/macro: sstmac::stat_histogram Class Reference
sstmac::stat_histogram Class Reference
#include <stat_histogram.h>
Public Member Functions
stat_histogram ()
void collect (double value)
void collect (double value, int num)
void simulation_finished (timestamp end)
This is to notify that the statistics collector is done.
void dump_local_data ()
After post-processing, this notifies the collector to dump data to a file.
void dump_global_data ()
After post-processing, this notifies the collector to dump data to a file.
void global_reduce (parallel_runtime *rt)
void clear ()
void reduce (stat_collector *coll)
void init_factory_params (sprockit::sim_parameters *params)
stat_histogram * clone_me (int id) const
stat_collector * clone () const
Public Member Functions inherited from sstmac::stat_collector
virtual ~stat_collector ()
virtual std::string to_string () const
bool registered () const
virtual void set_id (int id)
int id () const
void set_registered (bool reg)
void add_suffix (const std::string &suffix)
std::string fileroot () const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Member Functions
void dump (const std::string &froot)
void clone_into (stat_histogram *cln) const
Protected Member Functions inherited from sstmac::stat_collector
stat_collector ()
void clone_into (stat_collector *cln) const
Protected Attributes
std::vector< long > counts_
double bin_size_
long max_bin_
bool is_log_
Protected Attributes inherited from sstmac::stat_collector
bool registered_
int id_
std::string fileroot_
Additional Inherited Members
Static Protected Member Functions inherited from sstmac::stat_collector
static bool check_open (std::fstream &myfile, const std::string &fname, std::ios::openmode flags=std::ios::out)
Check to see if the file is open.
Detailed Description
Definition at line 10 of file stat_histogram.h.
Constructor & Destructor Documentation
sstmac::stat_histogram::stat_histogram ()
Referenced by clone_me().
Member Function Documentation
void sstmac::stat_histogram::clear () virtual
Implements sstmac::stat_collector.
stat_collector* sstmac::stat_histogram::clone () const inline virtual
Implements sstmac::stat_collector.
Definition at line 52 of file stat_histogram.h.
References clone_into(), clone_me(), and dump().
void sstmac::stat_histogram::clone_into (stat_histogram * cln) const protected
Referenced by clone(), and clone_me().
stat_histogram* sstmac::stat_histogram::clone_me (int id) const inline
Definition at line 44 of file stat_histogram.h.
References clone_into(), sstmac::stat_collector::set_id(), and stat_histogram().
Referenced by clone().
void sstmac::stat_histogram::collect (double value)
void sstmac::stat_histogram::collect (double value, int num)
void sstmac::stat_histogram::dump (const std::string & froot) protected
Referenced by clone().
void sstmac::stat_histogram::dump_global_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
void sstmac::stat_histogram::dump_local_data () virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implements sstmac::stat_collector.
void sstmac::stat_histogram::global_reduce (parallel_runtime * rt) virtual
Implements sstmac::stat_collector.
void sstmac::stat_histogram::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::stat_collector.
void sstmac::stat_histogram::reduce (stat_collector * coll) virtual
Implements sstmac::stat_collector.
void sstmac::stat_histogram::simulation_finished (timestamp end) virtual
This is to notify that the statistics collector is done.
Do any necessary data post-processing, but do NOT dump to file
Implements sstmac::stat_collector.
Member Data Documentation
double sstmac::stat_histogram::bin_size_ protected
Definition at line 66 of file stat_histogram.h.
std::vector<long> sstmac::stat_histogram::counts_ protected
Definition at line 64 of file stat_histogram.h.
bool sstmac::stat_histogram::is_log_ protected
Definition at line 70 of file stat_histogram.h.
long sstmac::stat_histogram::max_bin_ protected
Definition at line 68 of file stat_histogram.h.
The documentation for this class was generated from the following file:
sstmac/common/stats/stat_histogram.h