SST/macro: sprockit::pvt::ser_buffer_accessor Class Reference
sprockit::pvt::ser_buffer_accessor Class Reference
#include <serialize_buffer_accessor.h>
Public Member Functions
template<class T >
T * next ()
char * next_str (size_t size)
size_t size () const
size_t max_size () const
void init (void *buffer, size_t size)
void clear ()
void reset ()
Protected Member Functions
ser_buffer_accessor ()
Protected Attributes
char * bufstart_
char * bufptr_
size_t size_
size_t max_size_
Detailed Description
Definition at line 18 of file serialize_buffer_accessor.h.
Constructor & Destructor Documentation
sprockit::pvt::ser_buffer_accessor::ser_buffer_accessor () inline protected
Definition at line 69 of file serialize_buffer_accessor.h.
Member Function Documentation
void sprockit::pvt::ser_buffer_accessor::clear () inline
Definition at line 57 of file serialize_buffer_accessor.h.
References bufptr_, bufstart_, max_size_, and size_.
void sprockit::pvt::ser_buffer_accessor::init (void * buffer, size_t size) inline
Definition at line 50 of file serialize_buffer_accessor.h.
References bufstart_, max_size_, reset(), and size().
Referenced by sprockit::serializer::start_packing(), and sprockit::serializer::start_unpacking().
size_t sprockit::pvt::ser_buffer_accessor::max_size () const inline
Definition at line 45 of file serialize_buffer_accessor.h.
References max_size_.
template<class T > T* sprockit::pvt::ser_buffer_accessor::next () inline
Definition at line 22 of file serialize_buffer_accessor.h.
References bufptr_, max_size_, and size_.
char* sprockit::pvt::ser_buffer_accessor::next_str (size_t size) inline
Definition at line 31 of file serialize_buffer_accessor.h.
References bufptr_, max_size_, size(), and size_.
Referenced by sprockit::serializer::array().
void sprockit::pvt::ser_buffer_accessor::reset () inline
Definition at line 63 of file serialize_buffer_accessor.h.
References bufptr_, bufstart_, and size_.
Referenced by init(), and sprockit::serializer::reset().
size_t sprockit::pvt::ser_buffer_accessor::size () const inline
Definition at line 40 of file serialize_buffer_accessor.h.
References size_.
Referenced by init(), next_str(), and sprockit::serializer::size().
Member Data Documentation
char* sprockit::pvt::ser_buffer_accessor::bufptr_ protected
Definition at line 78 of file serialize_buffer_accessor.h.
Referenced by clear(), next(), next_str(), and reset().
char* sprockit::pvt::ser_buffer_accessor::bufstart_ protected
Definition at line 77 of file serialize_buffer_accessor.h.
Referenced by clear(), init(), and reset().
size_t sprockit::pvt::ser_buffer_accessor::max_size_ protected
Definition at line 80 of file serialize_buffer_accessor.h.
Referenced by clear(), init(), max_size(), next(), and next_str().
size_t sprockit::pvt::ser_buffer_accessor::size_ protected
Definition at line 79 of file serialize_buffer_accessor.h.
Referenced by clear(), next(), next_str(), reset(), and size().
The documentation for this class was generated from the following file:
sprockit/sprockit/serialize_buffer_accessor.h