SST/macro: sstmac::sw::sstmac_global_builtin< T > Class Template Reference
sstmac::sw::sstmac_global_builtin< T > Class Template Reference
#include <global_builtin.h>
Public Types
typedef val_map::const_iterator const_iterator
Public Member Functions
sstmac_global_builtin ()
sstmac_global_builtin (T init)
sstmac_global_builtin (const sstmac_global_builtin< T > &other)
virtual ~sstmac_global_builtin ()
void print_all () const
virtual T & get_val () const
virtual std::string to_string () const
template<typename U >
T & operator= (const U &b)
template<typename U >
T & operator+= (const U &b)
template<typename U >
T & operator-= (const U &b)
template<typename U >
T & operator*= (const U &b)
template<typename U >
T & operator/= (const U &b)
template<typename U >
bool operator== (const U &b) const
template<typename U >
bool operator!= (const U &b) const
operator T & ()
T operator++ (int dummy)
T operator-- (int dummy)
T operator++ ()
T operator-- ()
operator double () const
operator int () const
operator bool () const
operator size_t () const
operator long () const
operator long long () const
template<typename U >
T operator+ (const U &b) const
template<typename U >
T operator- (const U &b) const
template<typename U >
T operator/ (const U &b) const
template<typename U >
T operator<< (const U &b) const
template<typename U >
T operator>> (const U &b) const
template<typename U >
T operator% (const U &b) const
template<typename U >
T operator* (const U &b) const
T * operator& () const
template<typename U >
bool operator> (const U &b)
template<typename U >
bool operator< (const U &b)
void delete_vals ()
const_iterator begin () const
const_iterator end () const
Private Types
typedef spkt_unordered_map
< long, T > val_map
Private Member Functions
bool check_init (process_context ptxt) const
Private Attributes
val_map vals_
T init_
bool isinit_
Additional Inherited Members
Protected Member Functions inherited from sstmac::sw::sstmac_global
process_context current_context () const
Detailed Description
template<typename T>
class sstmac::sw::sstmac_global_builtin< T >
Definition at line 22 of file global_builtin.h.
Member Typedef Documentation
template<typename T> typedef val_map::const_iterator sstmac::sw::sstmac_global_builtin< T >::const_iterator
Definition at line 48 of file global_builtin.h.
template<typename T> typedef spkt_unordered_map<long, T> sstmac::sw::sstmac_global_builtin< T >::val_map private
Definition at line 26 of file global_builtin.h.
Constructor & Destructor Documentation
template<typename T> sstmac::sw::sstmac_global_builtin< T >::sstmac_global_builtin () inline explicit
Definition at line 51 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::isinit_.
template<typename T> sstmac::sw::sstmac_global_builtin< T >::sstmac_global_builtin (T init) inline explicit
Definition at line 56 of file global_builtin.h.
template<typename T> sstmac::sw::sstmac_global_builtin< T >::sstmac_global_builtin (const sstmac_global_builtin< T > & other) inline explicit
Definition at line 61 of file global_builtin.h.
References spkt_throw_printf.
template<typename T> virtual sstmac::sw::sstmac_global_builtin< T >::~sstmac_global_builtin () inline virtual
Definition at line 67 of file global_builtin.h.
Member Function Documentation
template<typename T> const_iterator sstmac::sw::sstmac_global_builtin< T >::begin () const inline
Definition at line 301 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::vals_.
template<typename T> bool sstmac::sw::sstmac_global_builtin< T >::check_init (process_context ptxt) const inline private
Definition at line 32 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::init_, sstmac::sw::process_context::none, and sstmac::sw::sstmac_global_builtin< T >::vals_.
template<typename T> void sstmac::sw::sstmac_global_builtin< T >::delete_vals () inline
Definition at line 286 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::init_, and sstmac::sw::sstmac_global_builtin< T >::vals_.
template<typename T> const_iterator sstmac::sw::sstmac_global_builtin< T >::end () const inline
Definition at line 305 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::vals_.
template<typename T> virtual T& sstmac::sw::sstmac_global_builtin< T >::get_val () const inline virtual
Definition at line 80 of file global_builtin.h.
References sstmac::sw::sstmac_global::current_context(), sstmac::sw::sstmac_global_builtin< T >::init_, sstmac::sw::sstmac_global_builtin< T >::isinit_, sstmac::sw::process_context::none, and sstmac::sw::sstmac_global_builtin< T >::vals_.
Referenced by sstmac::sw::sstmac_global_builtin< T >::operator bool(), sstmac::sw::sstmac_global_struct< T >::operator const T *(), sstmac::sw::sstmac_global_builtin< T >::operator double(), sstmac::sw::sstmac_global_builtin< T >::operator int(), sstmac::sw::sstmac_global_builtin< T >::operator long(), sstmac::sw::sstmac_global_builtin< T >::operator long long(), sstmac::sw::sstmac_global_builtin< T >::operator size_t(), sstmac::sw::sstmac_global_struct< T >::operator T(), sstmac::sw::sstmac_global_builtin< T >::operator T &(), sstmac::sw::sstmac_global_struct< T >::operator T *(), sstmac::sw::sstmac_global_builtin< T >::operator!=(), sstmac::sw::sstmac_global_builtin< T >::operator%(), sstmac::sw::sstmac_global_builtin< T >::operator&(), sstmac::sw::sstmac_global_struct< T >::operator*(), sstmac::sw::sstmac_global_builtin< T >::operator*(), sstmac::sw::sstmac_global_builtin< T >::operator*=(), sstmac::sw::sstmac_global_builtin< T >::operator+(), sstmac::sw::sstmac_global_builtin< T >::operator++(), sstmac::sw::sstmac_global_builtin< T >::operator+=(), sstmac::sw::sstmac_global_builtin< T >::operator-(), sstmac::sw::sstmac_global_builtin< T >::operator--(), sstmac::sw::sstmac_global_builtin< T >::operator-=(), sstmac::sw::sstmac_global_struct< T >::operator->(), sstmac::sw::sstmac_global_builtin< T >::operator/(), sstmac::sw::sstmac_global_builtin< T >::operator/=(), sstmac::sw::sstmac_global_builtin< T >::operator<(), sstmac::sw::sstmac_global_builtin< T >::operator<<(), sstmac::sw::sstmac_global_struct< T >::operator=(), sstmac::sw::sstmac_global_builtin< T >::operator=(), sstmac::sw::sstmac_global_builtin< T >::operator==(), sstmac::sw::sstmac_global_builtin< T >::operator>(), sstmac::sw::sstmac_global_builtin< T >::operator>>(), and sstmac::sw::sstmac_global_builtin< T >::to_string().
template<typename T> sstmac::sw::sstmac_global_builtin< T >::operator bool () const inline
Definition at line 206 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> sstmac::sw::sstmac_global_builtin< T >::operator double () const inline
Definition at line 198 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> sstmac::sw::sstmac_global_builtin< T >::operator int () const inline
Definition at line 202 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> sstmac::sw::sstmac_global_builtin< T >::operator long () const inline
Definition at line 214 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> sstmac::sw::sstmac_global_builtin< T >::operator long long () const inline
Definition at line 218 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> sstmac::sw::sstmac_global_builtin< T >::operator size_t () const inline
Definition at line 210 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> sstmac::sw::sstmac_global_builtin< T >::operator T & () inline
Definition at line 169 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > bool sstmac::sw::sstmac_global_builtin< T >::operator!= (const U & b) const inline
Definition at line 158 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T sstmac::sw::sstmac_global_builtin< T >::operator% (const U & b) const inline
Definition at line 254 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> T* sstmac::sw::sstmac_global_builtin< T >::operator& () const inline
Definition at line 265 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T sstmac::sw::sstmac_global_builtin< T >::operator* (const U & b) const inline
Definition at line 260 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T& sstmac::sw::sstmac_global_builtin< T >::operator*= (const U & b) inline
Definition at line 134 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T sstmac::sw::sstmac_global_builtin< T >::operator+ (const U & b) const inline
Definition at line 224 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> T sstmac::sw::sstmac_global_builtin< T >::operator++ (int dummy) inline
Definition at line 175 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> T sstmac::sw::sstmac_global_builtin< T >::operator++ () inline
Definition at line 187 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T& sstmac::sw::sstmac_global_builtin< T >::operator+= (const U & b) inline
Definition at line 118 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T sstmac::sw::sstmac_global_builtin< T >::operator- (const U & b) const inline
Definition at line 230 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> T sstmac::sw::sstmac_global_builtin< T >::operator-- (int dummy) inline
Definition at line 181 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> T sstmac::sw::sstmac_global_builtin< T >::operator-- () inline
Definition at line 193 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T& sstmac::sw::sstmac_global_builtin< T >::operator-= (const U & b) inline
Definition at line 126 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T sstmac::sw::sstmac_global_builtin< T >::operator/ (const U & b) const inline
Definition at line 236 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T& sstmac::sw::sstmac_global_builtin< T >::operator/= (const U & b) inline
Definition at line 142 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > bool sstmac::sw::sstmac_global_builtin< T >::operator< (const U & b) inline
Definition at line 279 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T sstmac::sw::sstmac_global_builtin< T >::operator<< (const U & b) const inline
Definition at line 242 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T& sstmac::sw::sstmac_global_builtin< T >::operator= (const U & b) inline
Definition at line 110 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > bool sstmac::sw::sstmac_global_builtin< T >::operator== (const U & b) const inline
Definition at line 150 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > bool sstmac::sw::sstmac_global_builtin< T >::operator> (const U & b) inline
Definition at line 271 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> template<typename U > T sstmac::sw::sstmac_global_builtin< T >::operator>> (const U & b) const inline
Definition at line 248 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> void sstmac::sw::sstmac_global_builtin< T >::print_all () const inline
Definition at line 72 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::vals_.
template<typename T> virtual std::string sstmac::sw::sstmac_global_builtin< T >::to_string () const inline virtual
Definition at line 102 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::get_val().
Member Data Documentation
template<typename T> T sstmac::sw::sstmac_global_builtin< T >::init_ mutable private
Definition at line 28 of file global_builtin.h.
Referenced by sstmac::sw::sstmac_global_builtin< T >::check_init(), sstmac::sw::sstmac_global_builtin< T >::delete_vals(), and sstmac::sw::sstmac_global_builtin< T >::get_val().
template<typename T> bool sstmac::sw::sstmac_global_builtin< T >::isinit_ mutable private
Definition at line 29 of file global_builtin.h.
Referenced by sstmac::sw::sstmac_global_builtin< T >::get_val(), and sstmac::sw::sstmac_global_builtin< T >::sstmac_global_builtin().
template<typename T> val_map sstmac::sw::sstmac_global_builtin< T >::vals_ private
Definition at line 27 of file global_builtin.h.
Referenced by sstmac::sw::sstmac_global_builtin< T >::begin(), sstmac::sw::sstmac_global_builtin< T >::check_init(), sstmac::sw::sstmac_global_builtin< T >::delete_vals(), sstmac::sw::sstmac_global_builtin< T >::end(), sstmac::sw::sstmac_global_builtin< T >::get_val(), and sstmac::sw::sstmac_global_builtin< T >::print_all().
The documentation for this class was generated from the following file:
sstmac/software/process/global_builtin.h