SST/macro: sstmac::hw::structured_routable Class Reference
sstmac::hw::structured_routable Class Reference
#include <routable.h>
Classes
struct path
class path_set
Public Types
enum metadata_slot { valiant_stage, final_stage, crossed_timeline }
Public Member Functions
node_id toaddr () const
node_id fromaddr () const
void set_toaddr (node_id to)
void set_fromaddr (node_id from)
path & current_path ()
void assign_path (const path &pth)
void check_vc ()
virtual int vc () const
int port () const
void serialize_order (serializer &ser)
void set_dest_switch (switch_id sid)
switch_id dest_switch () const
Protected Member Functions
structured_routable ()
structured_routable (node_id toaddr, node_id fromaddr)
Private Attributes
node_id toaddr_
node_id fromaddr_
path path_
switch_id dest_switch_
Detailed Description
Definition at line 11 of file routable.h.
Member Enumeration Documentation
enum sstmac::hw::structured_routable::metadata_slot
Enumerator
valiant_stage
final_stage
crossed_timeline
Definition at line 14 of file routable.h.
Constructor & Destructor Documentation
sstmac::hw::structured_routable::structured_routable () inline protected
Definition at line 142 of file routable.h.
References fromaddr(), and toaddr().
sstmac::hw::structured_routable::structured_routable (node_id toaddr, node_id fromaddr) protected
Member Function Documentation
void sstmac::hw::structured_routable::assign_path (const path & pth) inline
Definition at line 108 of file routable.h.
References path_.
void sstmac::hw::structured_routable::check_vc () inline
Definition at line 113 of file routable.h.
References path_, sstmac::hw::routing::uninitialized, and sstmac::hw::structured_routable::path::vc.
path& sstmac::hw::structured_routable::current_path () inline
Definition at line 103 of file routable.h.
References path_.
switch_id sstmac::hw::structured_routable::dest_switch () const inline
Definition at line 137 of file routable.h.
References dest_switch_.
node_id sstmac::hw::structured_routable::fromaddr () const inline
Definition at line 88 of file routable.h.
References fromaddr_.
Referenced by structured_routable().
int sstmac::hw::structured_routable::port () const inline
Definition at line 124 of file routable.h.
References sstmac::hw::structured_routable::path::outport, path_, and serialize_order().
void sstmac::hw::structured_routable::serialize_order (serializer & ser)
Referenced by port().
void sstmac::hw::structured_routable::set_dest_switch (switch_id sid) inline
Definition at line 132 of file routable.h.
References dest_switch_.
void sstmac::hw::structured_routable::set_fromaddr (node_id from) inline
Definition at line 98 of file routable.h.
References fromaddr_.
void sstmac::hw::structured_routable::set_toaddr (node_id to) inline
Definition at line 93 of file routable.h.
References toaddr_.
node_id sstmac::hw::structured_routable::toaddr () const inline
Definition at line 83 of file routable.h.
References toaddr_.
Referenced by structured_routable().
virtual int sstmac::hw::structured_routable::vc () const inline virtual
Definition at line 119 of file routable.h.
References path_, and sstmac::hw::structured_routable::path::vc.
Member Data Documentation
switch_id sstmac::hw::structured_routable::dest_switch_ private
Definition at line 153 of file routable.h.
Referenced by dest_switch(), and set_dest_switch().
node_id sstmac::hw::structured_routable::fromaddr_ private
Definition at line 149 of file routable.h.
Referenced by fromaddr(), and set_fromaddr().
path sstmac::hw::structured_routable::path_ private
Definition at line 151 of file routable.h.
Referenced by assign_path(), check_vc(), current_path(), port(), and vc().
node_id sstmac::hw::structured_routable::toaddr_ private
Definition at line 147 of file routable.h.
Referenced by set_toaddr(), and toaddr().
The documentation for this class was generated from the following file:
sstmac/hardware/router/routable.h