SST/macro: sstmac::hw::packet_flow_handler Class Reference
sstmac::hw::packet_flow_handler Class Reference abstract
#include <packet_flow_handler.h>
Public Member Functions
packet_flow_handler ()
virtual std::string to_string () const
virtual ~packet_flow_handler ()
virtual void handle (event *ev)
virtual void handle_credit (packet_flow_credit *msg)=0
virtual void handle_payload (packet_flow_payload *pkt)=0
int thread_id () const
Public Member Functions inherited from sstmac::event_subscheduler
event_subscheduler ()
timestamp now () const
get the current time
void schedule (timestamp t, event_handler *handler, event *ev)
Add an event to the event queue, where msg will get delivered to handler at time t.
void schedule (timestamp t, event_queue_entry *ev)
void schedule_now (event_queue_entry *ev)
void schedule_now (event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_queue_entry *ev)
void send_self_event (timestamp arrival, event *ev)
void send_delayed_self_event (timestamp delay, event *ev)
void send_now_self_event (event *ev)
void send_self_event_queue (timestamp arrival, event_queue_entry *ev)
void send_delayed_self_event_queue (timestamp delay, event_queue_entry *ev)
void send_now_self_event_queue (event_queue_entry *ev)
virtual void set_event_parent (event_scheduler *m)
Set the eventmanager for this scheduler.
event_scheduler * parent () const
Public Member Functions inherited from sstmac::event_handler
virtual ~event_handler ()
event_loc_id event_location () const
virtual bool ipc_handler () const
Whether an event handler is a "fake" handler that represents logical process boundary.
int thread_id () const
virtual void deadlock_check (event *ev)
virtual void deadlock_check ()
Additional Inherited Members
Static Public Attributes inherited from sstmac::event_handler
static const int null_lpid = -1
static const int null_threadid = -1
Protected Member Functions inherited from sstmac::event_handler
event_handler ()
void init_loc_id (event_loc_id id)
void init_thread_id (int id)
Protected Attributes inherited from sstmac::event_subscheduler
event_scheduler * parent_
Detailed Description
Definition at line 62 of file packet_flow_handler.h.
Constructor & Destructor Documentation
sstmac::hw::packet_flow_handler::packet_flow_handler ()
virtual sstmac::hw::packet_flow_handler::~packet_flow_handler () inline virtual
Definition at line 74 of file packet_flow_handler.h.
Member Function Documentation
virtual void sstmac::hw::packet_flow_handler::handle (event * ev) virtual
Reimplemented from sstmac::event_subscheduler.
virtual void sstmac::hw::packet_flow_handler::handle_credit (packet_flow_credit * msg) pure virtual
Implemented in sstmac::hw::packet_flow_injection_buffer, sstmac::hw::packet_flow_eject_buffer, sstmac::hw::packet_flow_network_buffer, and sstmac::hw::packet_flow_NtoM_queue.
Referenced by sstmac::hw::packet_flow_eject_buffer::packet_flow_eject_buffer(), sstmac::hw::packet_flow_injection_buffer::space_to_send(), and sstmac::hw::packet_flow_network_buffer::~packet_flow_network_buffer().
virtual void sstmac::hw::packet_flow_handler::handle_payload (packet_flow_payload * pkt) pure virtual
Implemented in sstmac::hw::packet_flow_sender.
int sstmac::hw::packet_flow_handler::thread_id () const inline
Definition at line 86 of file packet_flow_handler.h.
References sstmac::event_handler::thread_id().
virtual std::string sstmac::hw::packet_flow_handler::to_string () const inline virtual
Reimplemented from sstmac::event_subscheduler.
Reimplemented in sstmac::hw::packet_flow_demuxer, and sstmac::hw::packet_flow_sender.
Definition at line 70 of file packet_flow_handler.h.
The documentation for this class was generated from the following file:
sstmac/hardware/packet_flow/packet_flow_handler.h