SST/macro: sstmac::sw::threading_pth Class Reference
sstmac::sw::threading_pth Class Reference
#include <threading_pth.h>
Public Member Functions
virtual ~threading_pth ()
virtual threading_interface * copy ()
virtual void init_context ()
virtual void destroy_context ()
virtual void start_context (int physical_thread_id, void *stack, size_t stacksize, void(*func)(void *), void *args, threading_interface *yield_to)
Start a new context.
virtual void swap_context (threading_interface *to)
Swap context.
virtual void complete_context (threading_interface *to)
This is called when we have completed running the thread.
Public Member Functions inherited from sstmac::sw::threading_interface
virtual ~threading_interface ()
Private Types
typedef pth_uctx_t threadcontext_t
Private Attributes
threadcontext_t context_
Detailed Description
Definition at line 21 of file threading_pth.h.
Member Typedef Documentation
typedef pth_uctx_t sstmac::sw::threading_pth::threadcontext_t private
Definition at line 23 of file threading_pth.h.
Constructor & Destructor Documentation
virtual sstmac::sw::threading_pth::~threading_pth () inline virtual
Definition at line 29 of file threading_pth.h.
Member Function Documentation
virtual void sstmac::sw::threading_pth::complete_context (threading_interface * to) inline virtual
This is called when we have completed running the thread.
It is called in the from context.
Implements sstmac::sw::threading_interface.
Definition at line 55 of file threading_pth.h.
References swap_context().
virtual threading_interface* sstmac::sw::threading_pth::copy () inline virtual
Implements sstmac::sw::threading_interface.
Definition at line 32 of file threading_pth.h.
References destroy_context(), init_context(), start_context(), and swap_context().
virtual void sstmac::sw::threading_pth::destroy_context () virtual
Implements sstmac::sw::threading_interface.
Referenced by copy().
virtual void sstmac::sw::threading_pth::init_context () virtual
Implements sstmac::sw::threading_interface.
Referenced by copy().
virtual void sstmac::sw::threading_pth::start_context (int physical_thread_id, void * stack, size_t stacksize, void(*)(void *) func, void * args, threading_interface * yield_to) virtual
Start a new context.
Implements sstmac::sw::threading_interface.
Referenced by copy().
virtual void sstmac::sw::threading_pth::swap_context (threading_interface * to) virtual
Swap context.
Implements sstmac::sw::threading_interface.
Referenced by complete_context(), and copy().
Member Data Documentation
threadcontext_t sstmac::sw::threading_pth::context_ private
Definition at line 26 of file threading_pth.h.
The documentation for this class was generated from the following file:
sstmac/software/threading/threading_pth.h