SST/macro: sstmac::sw::allocation_strategy Class Reference
sstmac::sw::allocation_strategy Class Reference abstract
Strategy type for assigning processes to nodes in a parallel run.
#include <allocation_strategy.h>
Public Member Functions
virtual void init_param1 (parallel_runtime *rt)
hw::topology * topol () const
void set_interconnect (hw::interconnect *ic)
virtual void set_topology (hw::topology *top)
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual std::string to_string () const
virtual ~allocation_strategy () throw ()
virtual void allocate (int nnode, node_set &allocation)=0
Get nodes.
virtual void release (const node_set &alloc)
Release a set of nodes back into the allocation.
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Types
typedef std::set< node_id > node_set
Protected Member Functions
allocation_strategy ()
void validate_num_nodes (int num_nodes, const char *type)
Protected Attributes
hw::topology * topology_
hw::interconnect * interconn_
parallel_runtime * rt_
Detailed Description
Strategy type for assigning processes to nodes in a parallel run.
Definition at line 36 of file allocation_strategy.h.
Member Typedef Documentation
typedef std::set<node_id> sstmac::sw::allocation_strategy::node_set protected
Definition at line 39 of file allocation_strategy.h.
Constructor & Destructor Documentation
virtual sstmac::sw::allocation_strategy::~allocation_strategy () throw () virtual
Referenced by to_string().
sstmac::sw::allocation_strategy::allocation_strategy () inline protected
Definition at line 91 of file allocation_strategy.h.
References validate_num_nodes().
Member Function Documentation
virtual void sstmac::sw::allocation_strategy::allocate (int nnode, node_set & allocation) pure virtual
Get nodes.
Parameters
nnode number of nodes requested
allocation returns the nodes that have been allocated
Exceptions
value_error If not enough nodes are available, then this will throw. Nodes are removed from available and put into allocated.
Implemented in sstmac::sw::hostname_allocation, sstmac::sw::cart_allocation, sstmac::sw::dumpi_allocation, sstmac::sw::random_allocation, sstmac::sw::first_available_allocation, sstmac::sw::coordinate_allocation, and sstmac::sw::node_id_allocation.
Referenced by to_string().
virtual void sstmac::sw::allocation_strategy::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented in sstmac::sw::cart_allocation, sstmac::sw::hostname_allocation, sstmac::sw::dumpi_allocation, sstmac::sw::random_allocation, sstmac::sw::coordinate_allocation, and sstmac::sw::node_id_allocation.
Referenced by set_topology().
virtual void sstmac::sw::allocation_strategy::init_param1 (parallel_runtime * rt) inline virtual
Definition at line 43 of file allocation_strategy.h.
References rt_.
virtual void sstmac::sw::allocation_strategy::release (const node_set & alloc) virtual
Release a set of nodes back into the allocation.
Parameters
alloc The nodes to deallocate
Referenced by to_string().
void sstmac::sw::allocation_strategy::set_interconnect (hw::interconnect * ic)
Referenced by topol().
virtual void sstmac::sw::allocation_strategy::set_topology (hw::topology * top) inline virtual
Reimplemented in sstmac::sw::cart_allocation, sstmac::sw::hostname_allocation, sstmac::sw::dumpi_allocation, and sstmac::sw::coordinate_allocation.
Definition at line 59 of file allocation_strategy.h.
References init_factory_params(), and topology_.
virtual std::string sstmac::sw::allocation_strategy::to_string () const inline virtual
Definition at line 67 of file allocation_strategy.h.
References allocate(), release(), and ~allocation_strategy().
hw::topology* sstmac::sw::allocation_strategy::topol () const inline
Returns
The topology being allocated from
Definition at line 51 of file allocation_strategy.h.
References set_interconnect(), and topology_.
void sstmac::sw::allocation_strategy::validate_num_nodes (int num_nodes, const char * type) protected
Referenced by allocation_strategy().
Member Data Documentation
hw::interconnect* sstmac::sw::allocation_strategy::interconn_ protected
Definition at line 98 of file allocation_strategy.h.
parallel_runtime* sstmac::sw::allocation_strategy::rt_ protected
Definition at line 99 of file allocation_strategy.h.
Referenced by init_param1().
hw::topology* sstmac::sw::allocation_strategy::topology_ protected
Definition at line 97 of file allocation_strategy.h.
Referenced by set_topology(), and topol().
The documentation for this class was generated from the following file:
sstmac/software/launch/allocation_strategy.h