SST/macro: sstmac::hw::packet Class Reference
sstmac::hw::packet Class Reference abstract
#include <packet.h>
Public Member Functions
message * orig () const
virtual std::string to_string () const
bool is_tail () const
int byte_length () const
uint64_t unique_id () const
void add_delay_us (double delay_us)
double delay_us () const
virtual void serialize_order (serializer &ser)
virtual bool is_packet () const
convenience methods
virtual node_id toaddr () const =0
virtual node_id fromaddr () const =0
long byte_offset () const
Public Member Functions inherited from sstmac::event
virtual bool is_credit () const
virtual bool is_failure () const
template<class T >
T * interface ()
Public Member Functions inherited from sprockit::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
virtual ~serializable ()
Protected Member Functions
packet ()
packet (message *orig, long num_bytes, long byte_offset)
template<class T >
T & get_field (int name)
Protected Attributes
message * orig_
int num_bytes_
long byte_offset_
uint64_t unique_id_
double cumulative_delay_us_
Private Attributes
std::map< int, uint64_t > fields_
Additional Inherited Members
Protected Types inherited from sprockit::serializable
enum cxn_flag_t { ConstructorFlag }
Detailed Description
Definition at line 11 of file packet.h.
Constructor & Destructor Documentation
sstmac::hw::packet::packet () inline protected
Definition at line 71 of file packet.h.
References byte_offset(), and orig().
sstmac::hw::packet::packet (message * orig, long num_bytes, long byte_offset) protected
Member Function Documentation
void sstmac::hw::packet::add_delay_us (double delay_us) inline
Definition at line 42 of file packet.h.
References cumulative_delay_us_, and delay_us().
int sstmac::hw::packet::byte_length () const inline
Definition at line 32 of file packet.h.
References num_bytes_.
long sstmac::hw::packet::byte_offset () const inline
Definition at line 66 of file packet.h.
References byte_offset_.
Referenced by packet().
double sstmac::hw::packet::delay_us () const inline
Definition at line 47 of file packet.h.
References cumulative_delay_us_, and serialize_order().
Referenced by add_delay_us().
virtual node_id sstmac::hw::packet::fromaddr () const pure virtual
Referenced by is_packet().
template<class T > T& sstmac::hw::packet::get_field (int name) inline protected
Definition at line 91 of file packet.h.
References fields_.
virtual bool sstmac::hw::packet::is_packet () const inline virtual
convenience methods
Reimplemented from sstmac::event.
Definition at line 55 of file packet.h.
References fromaddr(), and toaddr().
bool sstmac::hw::packet::is_tail () const inline
Definition at line 27 of file packet.h.
References orig_.
message* sstmac::hw::packet::orig () const inline
Definition at line 17 of file packet.h.
References orig_.
Referenced by packet().
virtual void sstmac::hw::packet::serialize_order (serializer & ser) virtual
Reimplemented from sstmac::event.
Referenced by delay_us().
virtual std::string sstmac::hw::packet::to_string () const inline virtual
Implements sstmac::event.
Definition at line 22 of file packet.h.
virtual node_id sstmac::hw::packet::toaddr () const pure virtual
Referenced by is_packet().
uint64_t sstmac::hw::packet::unique_id () const inline
Definition at line 37 of file packet.h.
References unique_id_.
Member Data Documentation
long sstmac::hw::packet::byte_offset_ protected
Definition at line 83 of file packet.h.
Referenced by byte_offset().
double sstmac::hw::packet::cumulative_delay_us_ protected
Definition at line 87 of file packet.h.
Referenced by add_delay_us(), and delay_us().
std::map<int, uint64_t> sstmac::hw::packet::fields_ private
Definition at line 97 of file packet.h.
Referenced by get_field().
int sstmac::hw::packet::num_bytes_ protected
Definition at line 81 of file packet.h.
Referenced by byte_length().
message* sstmac::hw::packet::orig_ protected
Definition at line 79 of file packet.h.
Referenced by is_tail(), and orig().
uint64_t sstmac::hw::packet::unique_id_ protected
Definition at line 85 of file packet.h.
Referenced by unique_id().
The documentation for this class was generated from the following file:
sstmac/hardware/common/packet.h