SST/macro: sstmac::thread_info Class Reference
sstmac::thread_info Class Reference
#include <thread_info.h>
Static Public Member Functions
static void register_kernel_space_virtual_thread (int thread_id, pthread_t *thr, pthread_attr_t *attrs)
static void register_user_space_virtual_thread (int phys_thread_id, void *stack, size_t stacksize)
static int current_physical_thread_id ()
Static Protected Member Functions
static int kernel_space_thread_id ()
static int user_space_thread_id ()
Static Protected Attributes
static size_t stacksize_
Detailed Description
Definition at line 9 of file thread_info.h.
Member Function Documentation
static int sstmac::thread_info::current_physical_thread_id () inline static
Definition at line 18 of file thread_info.h.
References kernel_space_thread_id(), and user_space_thread_id().
Referenced by sstmac::sw::operating_system::static_os_thread_context().
static int sstmac::thread_info::kernel_space_thread_id () static protected
Referenced by current_physical_thread_id().
static void sstmac::thread_info::register_kernel_space_virtual_thread (int thread_id, pthread_t * thr, pthread_attr_t * attrs) static
static void sstmac::thread_info::register_user_space_virtual_thread (int phys_thread_id, void * stack, size_t stacksize) static
static int sstmac::thread_info::user_space_thread_id () inline static protected
Definition at line 30 of file thread_info.h.
References stacksize_.
Referenced by current_physical_thread_id().
Member Data Documentation
size_t sstmac::thread_info::stacksize_ static protected
Definition at line 39 of file thread_info.h.
Referenced by user_space_thread_id().
The documentation for this class was generated from the following file:
sstmac/common/thread_info.h