SST/macro: sstmac::hw::packet_flow_nic_packetizer Class Reference
sstmac::hw::packet_flow_nic_packetizer Class Reference
#include <packet_flow_packetizer.h>
Public Member Functions
packet_flow_nic_packetizer ()
std::string to_string () const
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual ~packet_flow_nic_packetizer () throw ()
void setNotify (event_handler *handler)
bool spaceToSend (int vn, int num_bits) const
We assume the injection buffer has infinite occupancy.
void inject (int vn, long bytes, long byte_offset, message *payload)
void set_output (int port, connectable *output, int credits)
Set up the injection/ejection links to the switch the NIC is connected to.
void set_input (int port, connectable *input)
virtual void set_event_parent (event_scheduler *m)
Set the eventmanager for this scheduler.
virtual void finalize_init ()
void set_acker (event_handler *handler)
double injection_bandwidth () const
Public Member Functions inherited from sstmac::hw::packet_flow_packetizer
void handle (event *ev)
Public Member Functions inherited from sstmac::hw::packetizer
void start (int vn, message *payload)
void packetArrived (int vn, packet *pkt)
void sendWhatYouCan (int vn)
void setNotify (packetizer_callback *handler)
int packetSize () const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Public Member Functions inherited from sstmac::event_subscheduler
event_subscheduler ()
timestamp now () const
get the current time
void schedule (timestamp t, event_handler *handler, event *ev)
Add an event to the event queue, where msg will get delivered to handler at time t.
void schedule (timestamp t, event_queue_entry *ev)
void schedule_now (event_queue_entry *ev)
void schedule_now (event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_handler *handler, event *ev)
void schedule_delay (timestamp delay, event_queue_entry *ev)
void send_self_event (timestamp arrival, event *ev)
void send_delayed_self_event (timestamp delay, event *ev)
void send_now_self_event (event *ev)
void send_self_event_queue (timestamp arrival, event_queue_entry *ev)
void send_delayed_self_event_queue (timestamp delay, event_queue_entry *ev)
void send_now_self_event_queue (event_queue_entry *ev)
event_scheduler * parent () const
Public Member Functions inherited from sstmac::event_handler
virtual ~event_handler ()
event_loc_id event_location () const
virtual bool ipc_handler () const
Whether an event handler is a "fake" handler that represents logical process boundary.
int thread_id () const
virtual void deadlock_check (event *ev)
virtual void deadlock_check ()
Protected Member Functions
void recv_packet_common (packet_flow_payload *pkt)
virtual void recv_credit (packet_flow_credit *credit)
Protected Member Functions inherited from sstmac::hw::packetizer
void bytesArrived (int vn, uint64_t unique_id, int bytes, message *parent)
Protected Member Functions inherited from sstmac::event_handler
event_handler ()
void init_loc_id (event_loc_id id)
void init_thread_id (int id)
Protected Attributes
stat_histogram * congestion_hist_
stat_spyplot * congestion_spyplot_
bool acc_delay_
double inj_bw_
double ej_bw_
int buffer_size_
packet_flow_injection_buffer * inj_buffer_
packet_flow_eject_buffer * ej_buffer_
recv_cq completion_queue_
node_id my_addr_
Protected Attributes inherited from sstmac::event_subscheduler
event_scheduler * parent_
Additional Inherited Members
Static Public Attributes inherited from sstmac::event_handler
static const int null_lpid = -1
static const int null_threadid = -1
Detailed Description
Definition at line 31 of file packet_flow_packetizer.h.
Constructor & Destructor Documentation
sstmac::hw::packet_flow_nic_packetizer::packet_flow_nic_packetizer ()
virtual sstmac::hw::packet_flow_nic_packetizer::~packet_flow_nic_packetizer () throw () virtual
Member Function Documentation
virtual void sstmac::hw::packet_flow_nic_packetizer::finalize_init () virtual
Reimplemented from sprockit::factory_type.
virtual void sstmac::hw::packet_flow_nic_packetizer::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::hw::packetizer.
void sstmac::hw::packet_flow_nic_packetizer::inject (int vn, long bytes, long byte_offset, message * payload) virtual
Implements sstmac::hw::packetizer.
double sstmac::hw::packet_flow_nic_packetizer::injection_bandwidth () const inline
Definition at line 78 of file packet_flow_packetizer.h.
References sstmac::hw::packet_flow_packetizer::recv_credit().
virtual void sstmac::hw::packet_flow_nic_packetizer::recv_credit (packet_flow_credit * credit) protected virtual
Implements sstmac::hw::packet_flow_packetizer.
void sstmac::hw::packet_flow_nic_packetizer::recv_packet_common (packet_flow_payload * pkt) protected
void sstmac::hw::packet_flow_nic_packetizer::set_acker (event_handler * handler)
virtual void sstmac::hw::packet_flow_nic_packetizer::set_event_parent (event_scheduler * m) virtual
Set the eventmanager for this scheduler.
Unfortunately, this always has to be called after an event_scheduler is constructed.
Parameters
m the simulation eventmanager
Reimplemented from sstmac::event_subscheduler.
void sstmac::hw::packet_flow_nic_packetizer::set_input (int port, connectable * input)
void sstmac::hw::packet_flow_nic_packetizer::set_output (int port, connectable * output, int credits)
Set up the injection/ejection links to the switch the NIC is connected to.
Parameters
sw The switch that injects/ejects
void sstmac::hw::packet_flow_nic_packetizer::setNotify (event_handler * handler)
bool sstmac::hw::packet_flow_nic_packetizer::spaceToSend (int vn, int num_bits) const virtual
We assume the injection buffer has infinite occupancy.
Implements sstmac::hw::packetizer.
std::string sstmac::hw::packet_flow_nic_packetizer::to_string () const inline virtual
Reimplemented from sstmac::event_subscheduler.
Definition at line 39 of file packet_flow_packetizer.h.
References sprockit::factory_type::finalize_init(), sstmac::hw::packetizer::init_factory_params(), sstmac::hw::packetizer::inject(), sprockit::printf(), sstmac::event_subscheduler::set_event_parent(), sstmac::hw::packetizer::setNotify(), and sstmac::hw::packetizer::spaceToSend().
Member Data Documentation
bool sstmac::hw::packet_flow_nic_packetizer::acc_delay_ protected
Definition at line 92 of file packet_flow_packetizer.h.
int sstmac::hw::packet_flow_nic_packetizer::buffer_size_ protected
Definition at line 96 of file packet_flow_packetizer.h.
recv_cq sstmac::hw::packet_flow_nic_packetizer::completion_queue_ protected
Definition at line 100 of file packet_flow_packetizer.h.
stat_histogram* sstmac::hw::packet_flow_nic_packetizer::congestion_hist_ protected
Definition at line 90 of file packet_flow_packetizer.h.
stat_spyplot* sstmac::hw::packet_flow_nic_packetizer::congestion_spyplot_ protected
Definition at line 91 of file packet_flow_packetizer.h.
packet_flow_eject_buffer* sstmac::hw::packet_flow_nic_packetizer::ej_buffer_ protected
Definition at line 98 of file packet_flow_packetizer.h.
double sstmac::hw::packet_flow_nic_packetizer::ej_bw_ protected
Definition at line 95 of file packet_flow_packetizer.h.
packet_flow_injection_buffer* sstmac::hw::packet_flow_nic_packetizer::inj_buffer_ protected
Definition at line 97 of file packet_flow_packetizer.h.
double sstmac::hw::packet_flow_nic_packetizer::inj_bw_ protected
Definition at line 94 of file packet_flow_packetizer.h.
node_id sstmac::hw::packet_flow_nic_packetizer::my_addr_ protected
Definition at line 102 of file packet_flow_packetizer.h.
The documentation for this class was generated from the following file:
sstmac/hardware/packet_flow/packet_flow_packetizer.h