SST/macro: sstmac::value_payload< T > Class Template Reference
sstmac::value_payload< T > Class Template Reference
Network payload consisting of a value with sensible copy semantics.
#include <value_payload.h>
Protected Member Functions
value_payload (const T &inval, size_t size=sizeof(T))
template<typename Other >
value_payload (const Other &inval, size_t size=sizeof(T))
Construction with type conversion.
value_payload (const value_payload< T > &other, size_t size=sizeof(T))
Private copy constructor.
Protected Member Functions inherited from sstmac::payload
payload ()
Empty protected constructor to enforce using construct()
Protected Member Functions inherited from sprockit::ptr_type
void incref ()
int decref ()
Protected Attributes
T data_
The data we keep.
size_t size_
Private Types
typedef sprockit::refcount_ptr< value_payload< T > > ptr
typedef sprockit::refcount_ptr< const value_payload< T > > const_ptr
Private Member Functions
ImplementSerializable (value_payload) public
virtual ~value_payload ()
payload::const_ptr clone () const
Clone this object.
T & typed_data () const
Access the underlying data in a const context.
void * data () const
virtual long byte_length () const
virtual payload::const_ptr add (const payload::const_ptr &other) const
Add operator.
virtual payload::const_ptr prod (const payload::const_ptr &other) const
virtual payload::const_ptr min (const payload::const_ptr &other) const
Less than comparator.
virtual payload::const_ptr max (const payload::const_ptr &other) const
Greater than comparator.
virtual bool equals (const payload::const_ptr &other) const
Equals comparator.
payload::const_ptr logical_or (const payload::const_ptr &other) const
Logical or comparator.
payload::const_ptr logical_xor (const payload::const_ptr &other) const
Logical xor comparator.
payload::const_ptr logical_and (const payload::const_ptr &other) const
Logical and comparator.
payload::const_ptr bitwise_or (const payload::const_ptr &other) const
Logical or comparator.
payload::const_ptr bitwise_xor (const payload::const_ptr &other) const
Logical xor comparator.
payload::const_ptr bitwise_and (const payload::const_ptr &other) const
Logical and comparator.
virtual void serialize_order (sstmac::serializer &ser)
virtual std::string to_string () const
Strinfier.
Static Private Member Functions
static value_payload::const_ptr construct (const T &inval)
Construct a new valuepayload.
static value_payload::const_ptr construct (const T &inval, size_t s)
template<typename Other >
static value_payload::const_ptr construct (const Other &inval)
Construct a new valuepayload with type conversion.
static value_payload::ptr construct ()
Additional Inherited Members
Public Types inherited from sstmac::payload
typedef sprockit::refcount_ptr< payload > ptr
typedef sprockit::refcount_ptr< const payload > const_ptr
Public Member Functions inherited from sstmac::payload
virtual ~payload ()
Goodbye.
virtual void recover (sw::api *api)
virtual void assign (void *data)
Public Member Functions inherited from sprockit::ptr_type
ptr_type ()
int nreferences () const
virtual ~ptr_type ()
Public Member Functions inherited from sprockit::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
virtual ~serializable ()
Static Public Member Functions inherited from sstmac::payload
static ptr null ()
Convenience function to get a null payload pointer.
Protected Types inherited from sprockit::serializable
enum cxn_flag_t { ConstructorFlag }
Detailed Description
template<typename T>
class sstmac::value_payload< T >
Network payload consisting of a value with sensible copy semantics.
Don't use this for pointer types, since you will break assumptions about const-ness or protection of underlying data.
Definition at line 59 of file value_payload.h.
Member Typedef Documentation
template<typename T> typedef sprockit::refcount_ptr<const value_payload<T> > sstmac::value_payload< T >::const_ptr private
Definition at line 69 of file value_payload.h.
template<typename T> typedef sprockit::refcount_ptr<value_payload<T> > sstmac::value_payload< T >::ptr private
Definition at line 68 of file value_payload.h.
Constructor & Destructor Documentation
template<typename T> virtual sstmac::value_payload< T >::~value_payload () inline private virtual
Definition at line 72 of file value_payload.h.
template<typename T> sstmac::value_payload< T >::value_payload (const T & inval, size_t size = sizeof(T)) inline protected
Definition at line 287 of file value_payload.h.
template<typename T> template<typename Other > sstmac::value_payload< T >::value_payload (const Other & inval, size_t size = sizeof(T)) inline protected
Construction with type conversion.
Definition at line 293 of file value_payload.h.
template<typename T> sstmac::value_payload< T >::value_payload (const value_payload< T > & other, size_t size = sizeof(T)) inline protected
Private copy constructor.
Definition at line 298 of file value_payload.h.
Member Function Documentation
template<typename T> virtual payload::const_ptr sstmac::value_payload< T >::add (const payload::const_ptr & other) const inline private virtual
Add operator.
Parameters
other
Returns
a smart pointer to a new valuepayload object
Implements sstmac::payload.
Definition at line 126 of file value_payload.h.
References ptr_safe_cast.
template<typename T> payload::const_ptr sstmac::value_payload< T >::bitwise_and (const payload::const_ptr & other) const inline private virtual
Logical and comparator.
Parameters
other
Returns
Implements sstmac::payload.
Reimplemented in sstmac::bitwisevaluepayload< T >.
Definition at line 264 of file value_payload.h.
References spkt_throw_printf.
template<typename T> payload::const_ptr sstmac::value_payload< T >::bitwise_or (const payload::const_ptr & other) const inline private virtual
Logical or comparator.
Parameters
other
Returns
Implements sstmac::payload.
Reimplemented in sstmac::bitwisevaluepayload< T >.
Definition at line 242 of file value_payload.h.
References spkt_throw_printf.
template<typename T> payload::const_ptr sstmac::value_payload< T >::bitwise_xor (const payload::const_ptr & other) const inline private virtual
Logical xor comparator.
Parameters
other
Returns
Implements sstmac::payload.
Reimplemented in sstmac::bitwisevaluepayload< T >.
Definition at line 253 of file value_payload.h.
References spkt_throw_printf.
template<typename T> virtual long sstmac::value_payload< T >::byte_length () const inline private virtual
Implements sstmac::payload.
Definition at line 116 of file value_payload.h.
template<typename T> payload::const_ptr sstmac::value_payload< T >::clone () const inline private virtual
Clone this object.
Implements sstmac::payload.
Reimplemented in sstmac::bitwisevaluepayload< T >.
Definition at line 100 of file value_payload.h.
template<typename T> static value_payload::const_ptr sstmac::value_payload< T >::construct (const T & inval) inline static private
Construct a new valuepayload.
Definition at line 77 of file value_payload.h.
template<typename T> static value_payload::const_ptr sstmac::value_payload< T >::construct (const T & inval, size_t s) inline static private
Definition at line 82 of file value_payload.h.
template<typename T> template<typename Other > static value_payload::const_ptr sstmac::value_payload< T >::construct (const Other & inval) inline static private
Construct a new valuepayload with type conversion.
Definition at line 89 of file value_payload.h.
template<typename T> static value_payload::ptr sstmac::value_payload< T >::construct () inline static private
Definition at line 94 of file value_payload.h.
Referenced by sstmac::bool_result< int >::get_false(), sstmac::bool_result< bool >::get_false(), sstmac::bool_result< int >::get_true(), and sstmac::bool_result< bool >::get_true().
template<typename T> void* sstmac::value_payload< T >::data () const inline private virtual
Implements sstmac::payload.
Definition at line 111 of file value_payload.h.
Referenced by sstmac::bitwisevaluepayload< T >::bitwise_and(), sstmac::bitwisevaluepayload< T >::bitwise_or(), sstmac::bitwisevaluepayload< T >::bitwise_xor(), and sstmac::bitwisevaluepayload< T >::to_string().
template<typename T> virtual bool sstmac::value_payload< T >::equals (const payload::const_ptr & other) const inline private virtual
Equals comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 189 of file value_payload.h.
References ptr_safe_cast.
template<typename T> sstmac::value_payload< T >::ImplementSerializable (value_payload< T >) inline private
Definition at line 63 of file value_payload.h.
template<typename T> payload::const_ptr sstmac::value_payload< T >::logical_and (const payload::const_ptr & other) const inline private virtual
Logical and comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 226 of file value_payload.h.
References sstmac::bool_result< T >::get_false(), sstmac::bool_result< T >::get_true(), and ptr_safe_cast.
template<typename T> payload::const_ptr sstmac::value_payload< T >::logical_or (const payload::const_ptr & other) const inline private virtual
Logical or comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 200 of file value_payload.h.
References sstmac::bool_result< T >::get_false(), and ptr_safe_cast.
template<typename T> payload::const_ptr sstmac::value_payload< T >::logical_xor (const payload::const_ptr & other) const inline private virtual
Logical xor comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 212 of file value_payload.h.
References sstmac::bool_result< T >::get_false(), sstmac::bool_result< T >::get_true(), and ptr_safe_cast.
template<typename T> virtual payload::const_ptr sstmac::value_payload< T >::max (const payload::const_ptr & other) const inline private virtual
Greater than comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 172 of file value_payload.h.
References ptr_safe_cast.
template<typename T> virtual payload::const_ptr sstmac::value_payload< T >::min (const payload::const_ptr & other) const inline private virtual
Less than comparator.
Parameters
other
Returns
Implements sstmac::payload.
Definition at line 159 of file value_payload.h.
References ptr_safe_cast.
template<typename T> virtual payload::const_ptr sstmac::value_payload< T >::prod (const payload::const_ptr & other) const inline private virtual
Implements sstmac::payload.
Definition at line 140 of file value_payload.h.
References ptr_safe_cast.
template<typename T> virtual void sstmac::value_payload< T >::serialize_order (sstmac::serializer & ser) inline private virtual
Implements sprockit::serializable.
Reimplemented in sstmac::bitwisevaluepayload< T >.
Definition at line 270 of file value_payload.h.
Referenced by sstmac::bitwisevaluepayload< T >::serialize_order().
template<typename T> virtual std::string sstmac::value_payload< T >::to_string () const inline private virtual
Strinfier.
Returns
a std::string description
Reimplemented from sstmac::payload.
Reimplemented in sstmac::bitwisevaluepayload< T >.
Definition at line 280 of file value_payload.h.
template<typename T> T& sstmac::value_payload< T >::typed_data () const inline private
Access the underlying data in a const context.
Definition at line 106 of file value_payload.h.
Member Data Documentation
template<typename T> T sstmac::value_payload< T >::data_ mutable protected
The data we keep.
Definition at line 304 of file value_payload.h.
template<typename T> size_t sstmac::value_payload< T >::size_ protected
Definition at line 305 of file value_payload.h.
The documentation for this class was generated from the following file:
sstmac/common/messages/value_payload.h