SST/macro: sstmac::stat_collector Class Reference
sstmac::stat_collector Class Reference abstract
A type of logger that collects some kind of statistic and outputs to a file during or at the end of a simulation.
#include <stat_collector.h>
Public Member Functions
virtual ~stat_collector ()
virtual void simulation_finished (timestamp end)=0
This is to notify that the statistics collector is done.
virtual void dump_local_data ()=0
After post-processing, this notifies the collector to dump data to a file.
virtual void dump_global_data ()=0
After post-processing, this notifies the collector to dump data to a file.
virtual void global_reduce (parallel_runtime *rt)=0
virtual void reduce (stat_collector *coll)=0
virtual void clear ()=0
virtual stat_collector * clone () const =0
virtual std::string to_string () const
virtual void init_factory_params (sprockit::sim_parameters *params)
bool registered () const
virtual void set_id (int id)
int id () const
void set_registered (bool reg)
void add_suffix (const std::string &suffix)
std::string fileroot () const
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
virtual void finalize_init ()
Protected Member Functions
stat_collector ()
void clone_into (stat_collector *cln) const
Static Protected Member Functions
static bool check_open (std::fstream &myfile, const std::string &fname, std::ios::openmode flags=std::ios::out)
Check to see if the file is open.
Protected Attributes
bool registered_
int id_
std::string fileroot_
Detailed Description
A type of logger that collects some kind of statistic and outputs to a file during or at the end of a simulation.
Usually, a static instance of this class should be used, because no merging of stat objects takes place, which means you'll get one file for each stat object.
Definition at line 30 of file stat_collector.h.
Constructor & Destructor Documentation
virtual sstmac::stat_collector::~stat_collector () virtual
sstmac::stat_collector::stat_collector () inline protected
Definition at line 101 of file stat_collector.h.
References check_open(), and clone_into().
Member Function Documentation
void sstmac::stat_collector::add_suffix (const std::string & suffix)
Referenced by set_registered().
static bool sstmac::stat_collector::check_open (std::fstream & myfile, const std::string & fname, std::ios::openmode flags = std::ios::out) static protected
Check to see if the file is open.
If not, try and open it and set the current output stream to it, and throw an sprockit::spkt_error if something goes wrong.
Returns
Referenced by stat_collector().
virtual void sstmac::stat_collector::clear () pure virtual
Implemented in sstmac::hw::stat_bytes_sent, sstmac::sw::ftq_calendar, sstmac::location_trace, sstmac::event_trace, sstmac::stat_spyplot, sstmac::sw::graph_viz, sstmac::stat_histogram, sstmac::stat_global_int, sstmac::stat_local_double, and sstmac::stat_local_int.
virtual stat_collector* sstmac::stat_collector::clone () const pure virtual
Implemented in sstmac::hw::stat_bytes_sent, sstmac::sw::ftq_calendar, sstmac::stat_spyplot_png, sstmac::stat_spyplot, sstmac::sw::graph_viz, sstmac::event_trace, sstmac::location_trace, sstmac::stat_histogram, sstmac::stat_global_int, sstmac::stat_local_double, and sstmac::stat_local_int.
void sstmac::stat_collector::clone_into (stat_collector * cln) const protected
Referenced by stat_collector().
virtual void sstmac::stat_collector::dump_global_data () pure virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implemented in sstmac::hw::stat_bytes_sent, sstmac::sw::ftq_calendar, sstmac::sw::graph_viz, sstmac::event_trace, sstmac::stat_spyplot, sstmac::location_trace, sstmac::stat_histogram, sstmac::stat_global_int, sstmac::stat_local_double, and sstmac::stat_local_int.
virtual void sstmac::stat_collector::dump_local_data () pure virtual
After post-processing, this notifies the collector to dump data to a file.
Parameters
name The root of the filename to dump to
Implemented in sstmac::hw::stat_bytes_sent, sstmac::sw::ftq_calendar, sstmac::sw::graph_viz, sstmac::event_trace, sstmac::stat_spyplot, sstmac::location_trace, sstmac::stat_histogram, sstmac::stat_global_int, sstmac::stat_local_double, and sstmac::stat_local_int.
std::string sstmac::stat_collector::fileroot () const inline
Definition at line 96 of file stat_collector.h.
References fileroot_.
virtual void sstmac::stat_collector::global_reduce (parallel_runtime * rt) pure virtual
Implemented in sstmac::hw::stat_bytes_sent, sstmac::sw::ftq_calendar, sstmac::sw::graph_viz, sstmac::stat_spyplot, sstmac::event_trace, sstmac::location_trace, sstmac::stat_histogram, sstmac::stat_global_int, sstmac::stat_local_double, and sstmac::stat_local_int.
int sstmac::stat_collector::id () const inline
Definition at line 83 of file stat_collector.h.
References id_.
Referenced by set_id().
virtual void sstmac::stat_collector::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented in sstmac::hw::stat_bytes_sent, sstmac::sw::ftq_calendar, sstmac::stat_spyplot_png, sstmac::event_trace, sstmac::stat_histogram, sstmac::stat_global_int, sstmac::stat_local_double, and sstmac::stat_local_int.
Referenced by sstmac::stat_spyplot_png::set_normalization(), and to_string().
virtual void sstmac::stat_collector::reduce (stat_collector * coll) pure virtual
Implemented in sstmac::hw::stat_bytes_sent, sstmac::sw::ftq_calendar, sstmac::location_trace, sstmac::stat_spyplot, sstmac::sw::graph_viz, sstmac::event_trace, sstmac::stat_histogram, sstmac::stat_global_int, sstmac::stat_local_double, and sstmac::stat_local_int.
bool sstmac::stat_collector::registered () const inline
Definition at line 73 of file stat_collector.h.
References registered_.
virtual void sstmac::stat_collector::set_id (int id) inline virtual
Definition at line 78 of file stat_collector.h.
References id(), and id_.
Referenced by sstmac::stat_global_int::clone_me(), sstmac::stat_local_double::clone_me(), sstmac::stat_local_int::clone_me(), sstmac::stat_histogram::clone_me(), sstmac::location_trace::clone_me(), sstmac::sw::graph_viz::clone_me(), sstmac::event_trace::clone_me(), sstmac::stat_spyplot::clone_me(), sstmac::stat_spyplot_png::clone_me(), and sstmac::sw::ftq_calendar::clone_me().
void sstmac::stat_collector::set_registered (bool reg) inline
Definition at line 88 of file stat_collector.h.
References add_suffix(), and registered_.
virtual void sstmac::stat_collector::simulation_finished (timestamp end) pure virtual
This is to notify that the statistics collector is done.
Do any necessary data post-processing, but do NOT dump to file
Implemented in sstmac::hw::stat_bytes_sent, sstmac::sw::ftq_calendar, sstmac::sw::graph_viz, sstmac::location_trace, sstmac::stat_spyplot, sstmac::event_trace, sstmac::stat_histogram, sstmac::stat_global_int, sstmac::stat_local_double, and sstmac::stat_local_int.
virtual std::string sstmac::stat_collector::to_string () const inline virtual
Reimplemented in sstmac::sw::ftq_calendar, sstmac::stat_spyplot_png, sstmac::sw::graph_viz, sstmac::stat_spyplot, and sstmac::location_trace.
Definition at line 65 of file stat_collector.h.
References init_factory_params().
Member Data Documentation
std::string sstmac::stat_collector::fileroot_ protected
Definition at line 122 of file stat_collector.h.
Referenced by fileroot().
int sstmac::stat_collector::id_ protected
Definition at line 121 of file stat_collector.h.
Referenced by id(), and set_id().
bool sstmac::stat_collector::registered_ protected
Definition at line 120 of file stat_collector.h.
Referenced by registered(), and set_registered().
The documentation for this class was generated from the following file:
sstmac/common/stats/stat_collector.h