SST/macro: RNG::UniformInteger Class Reference
RNG::UniformInteger Class Reference abstract
This is a base class for random number generators that return an integer uniformly distributed in a range.
#include <rng.h>
Public Member Functions
virtual ~UniformInteger ()
virtual rngint_t value ()=0
rngint_t value_in_range (rngint_t range)
virtual void vec_reseed (const std::vector< rngint_t > &seeds)=0
virtual int nseed ()=0
virtual double realvalue (bool include_zero=true, bool include_one=true)
Return a random value in the interval [0,1], (0,1], [0,1), or (0,1)
void reseed ()
void reseed (rngint_t)
void reseed (rngint_t, rngint_t)
void reseed (rngint_t, rngint_t, rngint_t)
void reseed (rngint_t, rngint_t, rngint_t, rngint_t)
Detailed Description
This is a base class for random number generators that return an integer uniformly distributed in a range.
Definition at line 26 of file rng.h.
Constructor & Destructor Documentation
virtual RNG::UniformInteger::~UniformInteger () virtual
Member Function Documentation
virtual int RNG::UniformInteger::nseed () pure virtual
Implemented in RNG::Combo, RNG::SWB, RNG::LFIB4, RNG::Table256, RNG::SimpleCombo, RNG::CONG, RNG::SHR3, RNG::MWC, and RNG::mersenne_twister.
virtual double RNG::UniformInteger::realvalue (bool include_zero = true, bool include_one = true) inline virtual
Return a random value in the interval [0,1], (0,1], [0,1), or (0,1)
Definition at line 48 of file rng.h.
References value().
void RNG::UniformInteger::reseed ()
void RNG::UniformInteger::reseed (rngint_t)
void RNG::UniformInteger::reseed (rngint_t , rngint_t)
void RNG::UniformInteger::reseed (rngint_t , rngint_t , rngint_t)
void RNG::UniformInteger::reseed (rngint_t , rngint_t , rngint_t , rngint_t)
virtual rngint_t RNG::UniformInteger::value () pure virtual
Implemented in RNG::Combo, RNG::SWB, RNG::LFIB4, RNG::SimpleCombo, RNG::CONG, RNG::SHR3, RNG::mersenne_twister, and RNG::MWC.
Referenced by RNG::UniformInteger_functor::operator()(), realvalue(), and value_in_range().
rngint_t RNG::UniformInteger::value_in_range (rngint_t range) inline
Definition at line 36 of file rng.h.
References value().
Referenced by RNG::UniformInteger_functor::operator()().
virtual void RNG::UniformInteger::vec_reseed (const std::vector< rngint_t > & seeds) pure virtual
Implemented in RNG::Combo, RNG::SWB, RNG::LFIB4, RNG::Table256, RNG::SimpleCombo, RNG::CONG, RNG::SHR3, RNG::MWC, and RNG::mersenne_twister.
The documentation for this class was generated from the following file:
sstmac/common/rng.h