SST/macro: sprockit::serializable_factory Class Reference
sprockit::serializable_factory Class Reference
#include <serializable.h>
Static Public Member Functions
static serializable * get_serializable (uint32_t cls_id)
static uint32_t add_builder (serializable_builder *builder, const char *name)
static bool sanity (serializable *ser, uint32_t cls_id)
static void delete_statics ()
Protected Types
typedef spkt_unordered_map< long, serializable_builder * > builder_map
Static Protected Attributes
static builder_map * builders_
Detailed Description
Definition at line 140 of file serializable.h.
Member Typedef Documentation
typedef spkt_unordered_map<long, serializable_builder*> sprockit::serializable_factory::builder_map protected
Definition at line 143 of file serializable.h.
Member Function Documentation
static uint32_t sprockit::serializable_factory::add_builder (serializable_builder * builder, const char * name) static
Returns
The cls id for the given builder
Referenced by sanity().
static void sprockit::serializable_factory::delete_statics () static
static serializable* sprockit::serializable_factory::get_serializable (uint32_t cls_id) static
static bool sprockit::serializable_factory::sanity (serializable * ser, uint32_t cls_id) inline static
Definition at line 157 of file serializable.h.
References add_builder(), sprockit::serializable_builder::cls_id(), and sprockit::serializable_builder::name().
Member Data Documentation
builder_map* sprockit::serializable_factory::builders_ static protected
Definition at line 144 of file serializable.h.
The documentation for this class was generated from the following file:
sprockit/sprockit/serializable.h