SST/macro: sstmac::hw::simple_processor Class Reference
sstmac::hw::simple_processor Class Reference
A very simple processor model.
#include <simple_processor.h>
Public Member Functions
virtual ~simple_processor ()
Goodbye.
virtual void finalize_init ()
void do_compute (sw::compute_event *ev)
virtual std::string to_string () const
Public Member Functions inherited from sstmac::hw::processor
virtual ~processor ()
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual void init_param1 (memory_model *mem)
virtual void init_param2 (node *nd)
void compute (event *ev)
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Protected Member Functions
void do_compute (timed_interface *msg, long thread_id)
Protected Member Functions inherited from sstmac::hw::processor
processor ()
Additional Inherited Members
Static Public Member Functions inherited from sstmac::hw::processor
static void delete_statics ()
Protected Attributes inherited from sstmac::hw::processor
double freq_
double mem_freq_
memory_model * mem_
node * node_
Detailed Description
A very simple processor model.
Definition at line 26 of file simple_processor.h.
Constructor & Destructor Documentation
virtual sstmac::hw::simple_processor::~simple_processor () inline virtual
Goodbye.
Definition at line 31 of file simple_processor.h.
References do_compute(), and finalize_init().
Member Function Documentation
void sstmac::hw::simple_processor::do_compute (sw::compute_event * ev) virtual
Implements sstmac::hw::processor.
Referenced by to_string(), and ~simple_processor().
void sstmac::hw::simple_processor::do_compute (timed_interface * msg, long thread_id) protected
virtual void sstmac::hw::simple_processor::finalize_init () virtual
Reimplemented from sstmac::hw::processor.
Reimplemented in sstmac::hw::instruction_processor.
Referenced by ~simple_processor().
virtual std::string sstmac::hw::simple_processor::to_string () const inline virtual
Reimplemented in sstmac::hw::instruction_processor.
Definition at line 40 of file simple_processor.h.
References do_compute().
The documentation for this class was generated from the following file:
sstmac/hardware/processor/simple_processor.h