SST/macro: sstmac::hw::instruction_processor Class Reference
sstmac::hw::instruction_processor Class Reference
#include <instruction_processor.h>
Public Member Functions
instruction_processor ()
virtual std::string to_string () const
virtual ~instruction_processor ()
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual void finalize_init ()
virtual void do_compute (sw::compute_event *cev)
Public Member Functions inherited from sstmac::hw::simple_processor
virtual ~simple_processor ()
Goodbye.
void do_compute (sw::compute_event *ev)
Public Member Functions inherited from sstmac::hw::processor
virtual ~processor ()
virtual void init_param1 (memory_model *mem)
virtual void init_param2 (node *nd)
void compute (event *ev)
Public Member Functions inherited from sprockit::factory_type
virtual void init_factory_params (sim_parameters *params)
Protected Member Functions
void set_memop_distribution (double stdev)
void set_flop_distribution (double stdev)
double instruction_time (sw::compute_event *msg)
Protected Member Functions inherited from sstmac::hw::simple_processor
void do_compute (timed_interface *msg, long thread_id)
Protected Member Functions inherited from sstmac::hw::processor
processor ()
Protected Attributes
double tflop_
double tintop_
double tmemseq_
double tmemrnd_
double max_single_mem_bw_
double negligible_time_sec_
double negligible_bytes_
double parallelism_
noise_model * noise_model_
Protected Attributes inherited from sstmac::hw::processor
double freq_
double mem_freq_
memory_model * mem_
node * node_
Additional Inherited Members
Static Public Member Functions inherited from sstmac::hw::processor
static void delete_statics ()
Detailed Description
Definition at line 24 of file instruction_processor.h.
Constructor & Destructor Documentation
sstmac::hw::instruction_processor::instruction_processor ()
virtual sstmac::hw::instruction_processor::~instruction_processor () inline virtual
Definition at line 35 of file instruction_processor.h.
References do_compute(), finalize_init(), init_factory_params(), instruction_time(), set_flop_distribution(), and set_memop_distribution().
Member Function Documentation
virtual void sstmac::hw::instruction_processor::do_compute (sw::compute_event * cev) virtual
Implements sstmac::hw::processor.
Referenced by ~instruction_processor().
virtual void sstmac::hw::instruction_processor::finalize_init () virtual
Reimplemented from sstmac::hw::simple_processor.
Referenced by ~instruction_processor().
virtual void sstmac::hw::instruction_processor::init_factory_params (sprockit::sim_parameters * params) virtual
Reimplemented from sstmac::hw::processor.
Referenced by ~instruction_processor().
double sstmac::hw::instruction_processor::instruction_time (sw::compute_event * msg) protected
Referenced by ~instruction_processor().
void sstmac::hw::instruction_processor::set_flop_distribution (double stdev) protected
Referenced by ~instruction_processor().
void sstmac::hw::instruction_processor::set_memop_distribution (double stdev) protected
Referenced by ~instruction_processor().
virtual std::string sstmac::hw::instruction_processor::to_string () const inline virtual
Reimplemented from sstmac::hw::simple_processor.
Definition at line 31 of file instruction_processor.h.
Member Data Documentation
double sstmac::hw::instruction_processor::max_single_mem_bw_ protected
Definition at line 62 of file instruction_processor.h.
double sstmac::hw::instruction_processor::negligible_bytes_ protected
Definition at line 65 of file instruction_processor.h.
double sstmac::hw::instruction_processor::negligible_time_sec_ protected
Definition at line 64 of file instruction_processor.h.
noise_model* sstmac::hw::instruction_processor::noise_model_ protected
Definition at line 69 of file instruction_processor.h.
double sstmac::hw::instruction_processor::parallelism_ protected
Definition at line 67 of file instruction_processor.h.
double sstmac::hw::instruction_processor::tflop_ protected
Definition at line 57 of file instruction_processor.h.
double sstmac::hw::instruction_processor::tintop_ protected
Definition at line 58 of file instruction_processor.h.
double sstmac::hw::instruction_processor::tmemrnd_ protected
Definition at line 60 of file instruction_processor.h.
double sstmac::hw::instruction_processor::tmemseq_ protected
Definition at line 59 of file instruction_processor.h.
The documentation for this class was generated from the following file:
sstmac/hardware/processor/instruction_processor.h