SST/macro: sprockit::serialize< std::vector< T > > Class Template Reference
sprockit::serialize< std::vector< T > > Class Template Reference
#include <serialize_vector.h>
Public Member Functions
void operator() (Vector &v, serializer &ser)
Private Types
typedef std::vector< T > Vector
Detailed Description
template<class T>
class sprockit::serialize< std::vector< T > >
Definition at line 10 of file serialize_vector.h.
Member Typedef Documentation
template<class T > typedef std::vector<T> sprockit::serialize< std::vector< T > >::Vector private
Definition at line 11 of file serialize_vector.h.
Member Function Documentation
template<class T > void sprockit::serialize< std::vector< T > >::operator() (Vector & v, serializer & ser) inline
Definition at line 14 of file serialize_vector.h.
References sprockit::serializer::mode(), sprockit::serializer::PACK, sprockit::serializer::pack(), sprockit::serializer::size(), sprockit::serializer::SIZER, sprockit::serializer::UNPACK, and sprockit::serializer::unpack().
The documentation for this class was generated from the following file:
sprockit/sprockit/serialize_vector.h