SST/macro: sprockit/sprockit/test/container.h File Reference
container.h File Reference
#include <map>
#include <vector>
#include <sprockit/test/assert.h>
Classes
class kv< K, V >
class ContainerAppend< C, A >
class ContainerAppend< std::vector< T >, A >
class ContainerAppend< std::map< K, V >, kv< K, V > >
Functions
template<class C , class A >
void fillContainer (C &t, A &a1)
template<class C , class A >
void fillContainer (C &t, const A &a1, const A &a2)
template<class C , class A >
void fillContainer (C &t, const A &a1, const A &a2, const A &a3)
template<class C , class A >
void fillContainer (C &t, const A &a1, const A &a2, const A &a3, const A &a4)
template<class C , class A >
void fillContainer (C &t, const A &a1, const A &a2, const A &a3, const A &a4, const A &a5)
template<class C , class A >
void fillContainer (C &t, A &a1, A &a2, A &a3, A &a4, A &a5, A &a6)
Function Documentation
template<class C , class A > void fillContainer (C & t, A & a1)
Definition at line 53 of file container.h.
References ContainerAppend< C, A >::append().
template<class C , class A > void fillContainer (C & t, const A & a1, const A & a2)
Definition at line 59 of file container.h.
References ContainerAppend< C, A >::append().
template<class C , class A > void fillContainer (C & t, const A & a1, const A & a2, const A & a3)
Definition at line 66 of file container.h.
References ContainerAppend< C, A >::append().
template<class C , class A > void fillContainer (C & t, const A & a1, const A & a2, const A & a3, const A & a4)
Definition at line 74 of file container.h.
References ContainerAppend< C, A >::append().
template<class C , class A > void fillContainer (C & t, const A & a1, const A & a2, const A & a3, const A & a4, const A & a5)
Definition at line 83 of file container.h.
References ContainerAppend< C, A >::append().
template<class C , class A > void fillContainer (C & t, A & a1, A & a2, A & a3, A & a4, A & a5, A & a6)
Definition at line 94 of file container.h.
References ContainerAppend< C, A >::append().