SST/macro: sstmac/hardware/interconnect/interconnect.h File Reference
interconnect.h File Reference
#include <sstmac/common/timestamp.h>
#include <sstmac/common/node_address.h>
#include <sstmac/hardware/common/connection.h>
#include <sstmac/hardware/node/node_fwd.h>
#include <sstmac/hardware/topology/topology_fwd.h>
#include <sstmac/hardware/nic/nic_fwd.h>
#include <sstmac/hardware/nic/netlink_fwd.h>
#include <sstmac/backends/common/sim_partition_fwd.h>
#include <sprockit/debug.h>
#include <sprockit/factories/factory.h>
#include <sprockit/unordered.h>
#include <set>
Macros
#define interconn_debug(...) debug_printf(sprockit::dbg::interconnect, __VA_ARGS__)
#define SSTMAC_SET_TOPOLOGY(obj, top) obj->set_topology(top);
#define STATIC_INIT_TOPOLOGY(params)
#define STATIC_INIT_INTERCONNECT(params)
Functions
DeclareDebugSlot (interconnect) namespace sstmac
Macro Definition Documentation
#define interconn_debug (...) debug_printf(sprockit::dbg::interconnect, __VA_ARGS__)
#define SSTMAC_SET_TOPOLOGY (obj, top) obj->set_topology(top);
#define STATIC_INIT_INTERCONNECT (params)
#define STATIC_INIT_TOPOLOGY (params)
Function Documentation
DeclareDebugSlot (interconnect)
Base class for network congestion models.
Do not actually inject the message into the network or do any congestion modeling. Just immediately schedule the message at its destination after some computed delay.
Parameters
msg The message to send to the destination
Return the node corresponding to given ID. No bounds checking is done for validity of ID. NULL is a valid return value for parallel simulation since it means node belongs to another process
Parameters
nid The ID of the node object to get
Returns
The node object or NULL, if ID is not found
Definition at line 32 of file interconnect.h.
References sstmac::hw::DeclareFactory2InitParams(), sstmac::hw::init_factory_params(), sstmac::event_loc_id::null, and sstmac::hw::set_event_manager().