SST/macro: sstmac::hw Namespace Reference
sstmac::hw Namespace Reference
Namespaces
routing
Classes
class null_nic
class simple_interconnect
class simple_nic
A networkinterface is a delegate between a node and a server module.
class simple_param_expander
class simple_switch
class simple_topology
class clone_factory
class connectable
class connectable_component
class connectable_subcomponent
class fail_event
class failable
class packet
class packetizer_callback
class packetizer
class param_expander
class recv_cq
struct unique_event_id
class switch_interconnect_base
class macro_switch_interconnect
class null_memory_model
class simple_memory_model
class network_message
class netlink
class nic
A networkinterface is a delegate between a node and a server module.
class node
class null_node
A null node.
class simple_node
A stand-in node.
class noise_model
class gaussian_noise_model
class packet_allocator
The packet_allocator class Factory for creating packets.
class packet_flow_bandwidth_arbitrator
class packet_flow_null_arbitrator
class packet_flow_simple_arbitrator
class packet_flow_cut_through_arbitrator
class packet_flow_buffer
class packet_flow_finite_buffer
class packet_flow_infinite_buffer
class packet_flow_network_buffer
class packet_flow_eject_buffer
class packet_flow_injection_buffer
class packet_flow_NtoM_queue
class packet_flow_demuxer
class packet_flow_muxer
class packet_flow_crossbar
struct payload_queue
class packet_flow_handler
struct packet_flow_input
struct packet_flow_output
class memory_message
class packet_flow_memory_packetizer
class packet_flow_memory_model
class packet_flow_nic
Network interface compatible with sending packet trains.
class packet_flow_netlink
class packet_flow_packetizer
class packet_flow_nic_packetizer
class packet_flow_cut_through_packetizer
class packet_flow_simple_packetizer
class packet_flow_param_expander
class packet_flow_sender
struct packet_stats_st
class packet_sent_stats
class delay_histogram
class packet_delay_stats
class null_stats
class byte_hop_collector
class spyplot_and_delay_stats
class stat_bytes_sent
class bytes_sent_collector
class packet_flow_abstract_switch
class packet_flow_switch
A switch in the network that arbitrates/routes packet_trains to the next link in the network.
class packet_flow_tiled_switch
class instruction_processor
class processor
An interface for processor models.
class simple_processor
A very simple processor model.
class fat_tree_dmodk_router
The fat_tree_dmodk_router class Router encapsulating the special routing computations that must occur on a fat tree topology.
class fat_tree_global_adaptive_router
The fat_tree_global_adaptive_router class Router encapsulating the special routing computations that must occur on a fat tree topology.
class fat_tree_local_adaptive_router
The fat_tree_local_adaptive_router class Router encapsulating the special routing computations that must occur on a fat tree topology.
class fat_tree_router
The fat_tree_router class Router encapsulating the special routing computations that must occur on a fat tree topology.
class minimal_adaptive_router
The minimal_adaptive_router class Performs some amount of adaptive routing, choosing between the least congested of all possible minimal paths.
class minimal_router
The minimal_router class Router that performs.
class multipath_router
class structured_routable
class sdn_router
The sdn_router class Router encapsulating the special routing computations that must occur on a fat tree topology.
class structured_router
The structured_router class Implements a router that computes path on-the-fly using the geometry of the topology rather than using a table-based scheme with a table stored in the router.
class ugal_router
The ugal_router class Encapsulates a router that performs Univeral Globally Adaptive Load-balanced routing as described in PhD Thesis "Load-balanced in routing in interconnection networks" by A Singh.
class valiant_router
The valiant_router class Enacpsulates a router that performs oblivious, global routing according to "A Scheme for Fast Parallel Computation" by Valiant.
class dist_dummy_switch
The dist_dummy_switch class Encapsulates a switch that is a placeholder used in parallel simulation.
class abstract_butterfly
The abstract_butterfly class Encapsulates operations common to both butterfly and flattened_butterfly.
class butterfly
The butterfly class Encapsulates a butterfly topology as described in "High Performance Datacenter Networks" by Abts and Kim.
class cartesian_topology
The cartesian_topology class Encapsulates a topology like torus that can be naturally mapped onto an n-dimensional Cartesian (integer) coordinate system.
class coordinates
class crossbar
The crossbar network generates a network which connects all nodes with only two hops: those to and from the crossbar.
class dragonfly
class fake_topology
class abstract_fat_tree
class fat_tree
The fat tree network generates a k-ary fat tree with l tiers.
class simple_fat_tree
class flattened_butterfly
The flattened_butterfly class Encapsulates a flattened butterfly topology as described in "High Performance Datacenter Networks" by Abts and Kim.
class hdtorus
Implements a high dimensional torus network.
class hypercube
class index_subset
class structured_topology
Encapsulates a topology like torus, fat tree, butterfly which has a regular, well-defined structure.
class tiled_dragonfly
class tiled_torus
class traffic_pattern
class null_scheduler
class xpress_ring
Typedefs
typedef macro_switch_interconnect switch_interconnect
typedef unique_event_id memory_access_id
typedef unique_event_id network_id
Functions
std::size_t hash_value (const unique_event_id &id)
DeclareFactory1InitParam (nic, sprockit::factory_type *)
DeclareFactory (node)
DeclareIntegratedComponent (simple_node)
DeclareFactory (noise_model)
DeclareFactory (packet_flow_bandwidth_arbitrator)
virtual DeclareFactory(packet_sent_stats)
class congestion_spyplot void collect_single_event (const packet_stats_st &st)
virtual void collect_final_event (packet_flow_payload *pkt)
virtual void init_factory_params (sprockit::sim_parameters *params)
virtual void set_event_manager (event_manager *ev_mgr)
void collect (double delay_us, packet_flow_payload *pkt)
DeclareIntegratedComponent (packet_flow_switch)
DeclareFactory2InitParams (processor, memory_model *, node *)
Variables
stat_spyplot * congestion_spyplot_
Typedef Documentation
typedef unique_event_id sstmac::hw::memory_access_id
Definition at line 12 of file memory_id.h.
typedef unique_event_id sstmac::hw::network_id
Definition at line 11 of file network_id.h.
typedef macro_switch_interconnect sstmac::hw::switch_interconnect
Definition at line 11 of file switch_interconnect_fwd.h.
Function Documentation
void sstmac::hw::collect (double delay_us, packet_flow_payload * pkt) protected
virtual void sstmac::hw::collect_final_event (packet_flow_payload * pkt) virtual
virtual DeclareFactory (packet_sent_stats) class congestion_spyplot void sstmac::hw::collect_single_event (const packet_stats_st & st) virtual
sstmac::hw::DeclareFactory (noise_model)
sstmac::hw::DeclareFactory (packet_flow_bandwidth_arbitrator)
sstmac::hw::DeclareFactory (node)
Referenced by DeclareDebugSlot().
sstmac::hw::DeclareFactory1InitParam (nic , sprockit::factory_type *)
Referenced by DeclareDebugSlot().
sstmac::hw::DeclareFactory2InitParams (processor , memory_model * , node *)
Referenced by DeclareDebugSlot().
sstmac::hw::DeclareIntegratedComponent (simple_node)
sstmac::hw::DeclareIntegratedComponent (packet_flow_switch)
std::size_t sstmac::hw::hash_value (const unique_event_id & id) inline
Definition at line 88 of file unique_id.h.
virtual void sstmac::hw::init_factory_params (sprockit::sim_parameters * params) virtual
Referenced by DeclareDebugSlot(), and sstmac::hw::multipath_router< ParentRouter >::init_factory_params().
virtual void sstmac::hw::set_event_manager (event_manager * ev_mgr) virtual
Referenced by DeclareDebugSlot(), and sstmac::hw::spyplot_and_delay_stats::set_event_manager().
Variable Documentation
stat_spyplot* sstmac::hw::congestion_spyplot_
Definition at line 87 of file packet_flow_stats.h.