SST/macro: sstmac::sw Namespace Reference
sstmac::sw Namespace Reference
Namespaces
P
Namespace for internal utility print routines.
Classes
class api
class API
class APIBase
class app
The app derived class adds to the thread base class by providing facilities to allow applications to simulate computation.
class app_factory
class app_ftq_calendar
class app_launch
class arrive_message
class blas_api
class blas_kernel
class block_task_mapper
An index strategy that allocates indices using a round robin.
class callback_waiter
class cart_allocation
class compute_event
Input for processor models that use performance counter data.
class coordinate_allocation
class coordinate_task_mapper
class cpuset_compute_scheduler
class dumpi_allocation
class dumpi_meta
class dumpi_task_mapper
struct event_node
class first_available_allocation
class ftq_calendar
class ftq_epoch
union funcptr
Pack a function pointer of the form void(*)(void*) as a pair of integers.
class graph_viz
class graph_viz_increment_stack
class hostname_allocation
class hostname_task_mapper
struct intpair
A set of utilities to deal with the odd arguments to makecontext.
class job_launch_event
class job_launcher
The job_launcher class performs the combined operations a queue scheduler like PBS or MOAB and a job launcher like SLURM (srun) or ALPS (aprun).
class key
A base type and default (empty) implementation of a handle to block and unblock processes.
class launch_event
class launcher
A launcher that can be cooperatively scheduled by a very naive scheduler.
class lib_compute_inst
class lib_compute_loops
class lib_compute_matrix
class lib_compute_memmove
class lib_compute_time
class lib_hybrid_compute
class lib_sleep
class library
class library_builder
class library_builder_tmpl
class machine_descriptor
class mutex_t
class node_allocator
Strategy type for assigning processes to nodes in a parallel run.
class node_id_allocation
class node_id_task_mapper
class operating_system
struct process_context
class process_manager
class pthread_runner
class random_allocation
class random_task_mapper
An index strategy that allocates indices using a round robin.
class round_robin_task_mapper
An index strategy that allocates indices using a round robin.
class service
class service_factory
class simple_compute_scheduler
struct software_id
A wrapper for an appid, taskid pair.
class sstmac_global
class sstmac_global_builtin
class sstmac_global_builtin< T * >
class sstmac_global_builtin_arr
class sstmac_global_builtin_arr< T *, N >
class sstmac_global_struct
class sstmac_global_struct< T * >
class stack_alloc
A management type to handle dividing mmap-ed memory for use as ucontext stack(s).
class task_ftq_calendar
class task_mapper
Base class for strategies regarding how to sequentially number nodes in a parallel simulation.
class thread
struct threadinfo
Base class for tasks that can be cooperative scheduled using threadcontext.
class threading_interface
class threading_pth
class timeout_event
class Timer
class unblock_event
class user_app_cxx_empty_main
class user_app_cxx_full_main
union voidptr
Pack a void* argument into a pair of integers.
class waiter
The main interface for something that can wait in a certain way for an event that is important to it.
Typedefs
typedef std::set< node_id > ordered_node_set
typedef std::map< long, mutex_t * > condition_t
typedef int app_id
typedef int flow_id
typedef int task_id
typedef std::pair< threading_interface *, thread * > thread_data_t
typedef int thread_id
Functions
std::ostream & operator<< (std::ostream &os, const dumpi_status &status)
Print status info.
std::ostream & operator<< (std::ostream &os, const dumpi_clock &tt)
Dumpi timestamp.
std::ostream & operator<< (std::ostream &os, const dumpi_time &tt)
Dumpi time value.
std::ostream & operator<< (std::ostream &os, const dumpi_func_call &dd)
C++ IO for a function call.
std::ostream & operator<< (std::ostream &os, const dumpi_send &dd)
C++ IO for a send operation.
std::ostream & operator<< (std::ostream &os, const dumpi_recv &dd)
C++ IO for a recv operation.
std::ostream & operator<< (std::ostream &os, const dumpi_get_count &dd)
C++ IO for a get_count operation.
std::ostream & operator<< (std::ostream &os, const dumpi_bsend &dd)
C++ IO for a bsend operation.
std::ostream & operator<< (std::ostream &os, const dumpi_ssend &dd)
C++ IO for a ssend operation.
std::ostream & operator<< (std::ostream &os, const dumpi_rsend &dd)
C++ IO for a rsend operation.
std::ostream & operator<< (std::ostream &os, const dumpi_buffer_attach &dd)
C++ IO for a buffer_attach operation.
std::ostream & operator<< (std::ostream &os, const dumpi_buffer_detach &dd)
C++ IO for a buffer_detach operation.
std::ostream & operator<< (std::ostream &os, const dumpi_isend &dd)
C++ IO for a isend operation.
std::ostream & operator<< (std::ostream &os, const dumpi_ibsend &dd)
C++ IO for a ibsend operation.
std::ostream & operator<< (std::ostream &os, const dumpi_issend &dd)
C++ IO for a issend operation.
std::ostream & operator<< (std::ostream &os, const dumpi_irsend &dd)
C++ IO for a irsend operation.
std::ostream & operator<< (std::ostream &os, const dumpi_irecv &dd)
C++ IO for a irecv operation.
std::ostream & operator<< (std::ostream &os, const dumpi_wait &dd)
C++ IO for a wait operation.
std::ostream & operator<< (std::ostream &os, const dumpi_test &dd)
C++ IO for a test operation.
std::ostream & operator<< (std::ostream &os, const dumpi_request_free &dd)
C++ IO for a request_free operation.
std::ostream & operator<< (std::ostream &os, const dumpi_waitany &dd)
C++ IO for a waitany operation.
std::ostream & operator<< (std::ostream &os, const dumpi_testany &dd)
C++ IO for a testany operation.
std::ostream & operator<< (std::ostream &os, const dumpi_waitall &dd)
C++ IO for a waitall operation.
std::ostream & operator<< (std::ostream &os, const dumpi_testall &dd)
C++ IO for a testall operation.
std::ostream & operator<< (std::ostream &os, const dumpi_waitsome &dd)
C++ IO for a waitsome operation.
std::ostream & operator<< (std::ostream &os, const dumpi_testsome &dd)
C++ IO for a testsome operation.
std::ostream & operator<< (std::ostream &os, const dumpi_iprobe &dd)
C++ IO for a iprobe operation.
std::ostream & operator<< (std::ostream &os, const dumpi_probe &dd)
C++ IO for a probe operation.
std::ostream & operator<< (std::ostream &os, const dumpi_cancel &dd)
C++ IO for a cancel operation.
std::ostream & operator<< (std::ostream &os, const dumpi_test_cancelled &dd)
C++ IO for a test_cancelled operation.
std::ostream & operator<< (std::ostream &os, const dumpi_send_init &dd)
C++ IO for a send_init operation.
std::ostream & operator<< (std::ostream &os, const dumpi_bsend_init &dd)
C++ IO for a bsend_init operation.
std::ostream & operator<< (std::ostream &os, const dumpi_ssend_init &dd)
C++ IO for a ssend_init operation.
std::ostream & operator<< (std::ostream &os, const dumpi_rsend_init &dd)
C++ IO for a rsend_init operation.
std::ostream & operator<< (std::ostream &os, const dumpi_recv_init &dd)
C++ IO for a recv_init operation.
std::ostream & operator<< (std::ostream &os, const dumpi_start &dd)
C++ IO for a start operation.
std::ostream & operator<< (std::ostream &os, const dumpi_startall &dd)
C++ IO for a startall operation.
std::ostream & operator<< (std::ostream &os, const dumpi_sendrecv &dd)
C++ IO for a sendrecv operation.
std::ostream & operator<< (std::ostream &os, const dumpi_sendrecv_replace &dd)
C++ IO for a sendrecv_replace operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_contiguous &dd)
C++ IO for a type_contiguous operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_vector &dd)
C++ IO for a type_vector operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_hvector &dd)
C++ IO for a type_hvector operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_indexed &dd)
C++ IO for a type_indexed operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_hindexed &dd)
C++ IO for a type_hindexed operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_struct &dd)
C++ IO for a type_struct operation.
std::ostream & operator<< (std::ostream &os, const dumpi_address &dd)
C++ IO for a address operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_extent &dd)
C++ IO for a type_extent operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_size &dd)
C++ IO for a type_size operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_lb &dd)
C++ IO for a type_lb operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_ub &dd)
C++ IO for a type_ub operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_commit &dd)
C++ IO for a type_commit operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_free &dd)
C++ IO for a type_free operation.
std::ostream & operator<< (std::ostream &os, const dumpi_get_elements &dd)
C++ IO for a get_elements operation.
std::ostream & operator<< (std::ostream &os, const dumpi_pack &dd)
C++ IO for a pack operation.
std::ostream & operator<< (std::ostream &os, const dumpi_unpack &dd)
C++ IO for a unpack operation.
std::ostream & operator<< (std::ostream &os, const dumpi_pack_size &dd)
C++ IO for a pack_size operation.
std::ostream & operator<< (std::ostream &os, const dumpi_barrier &dd)
C++ IO for a barrier operation.
std::ostream & operator<< (std::ostream &os, const dumpi_bcast &dd)
C++ IO for a bcast operation.
std::ostream & operator<< (std::ostream &os, const dumpi_gather &dd)
C++ IO for a gather operation.
std::ostream & operator<< (std::ostream &os, const dumpi_gatherv &dd)
C++ IO for a gatherv operation.
std::ostream & operator<< (std::ostream &os, const dumpi_scatter &dd)
C++ IO for a scatter operation.
std::ostream & operator<< (std::ostream &os, const dumpi_scatterv &dd)
C++ IO for a scatterv operation.
std::ostream & operator<< (std::ostream &os, const dumpi_allgather &dd)
C++ IO for a allgather operation.
std::ostream & operator<< (std::ostream &os, const dumpi_allgatherv &dd)
C++ IO for a allgatherv operation.
std::ostream & operator<< (std::ostream &os, const dumpi_alltoall &dd)
C++ IO for a alltoall operation.
std::ostream & operator<< (std::ostream &os, const dumpi_alltoallv &dd)
C++ IO for a alltoallv operation.
std::ostream & operator<< (std::ostream &os, const dumpi_reduce &dd)
C++ IO for a reduce operation.
std::ostream & operator<< (std::ostream &os, const dumpi_op_create &dd)
C++ IO for a op_create operation.
std::ostream & operator<< (std::ostream &os, const dumpi_op_free &dd)
C++ IO for a op_free operation.
std::ostream & operator<< (std::ostream &os, const dumpi_allreduce &dd)
C++ IO for a allreduce operation.
std::ostream & operator<< (std::ostream &os, const dumpi_reduce_scatter &dd)
C++ IO for a reduce_scatter operation.
std::ostream & operator<< (std::ostream &os, const dumpi_scan &dd)
C++ IO for a scan operation.
std::ostream & operator<< (std::ostream &os, const dumpi_group_size &dd)
C++ IO for a group_size operation.
std::ostream & operator<< (std::ostream &os, const dumpi_group_rank &dd)
C++ IO for a group_rank operation.
std::ostream & operator<< (std::ostream &os, const dumpi_group_translate_ranks &dd)
C++ IO for a group_translate_ranks operation.
std::ostream & operator<< (std::ostream &os, const dumpi_group_compare &dd)
C++ IO for a group_compare operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_group &dd)
C++ IO for a comm_group operation.
std::ostream & operator<< (std::ostream &os, const dumpi_group_union &dd)
C++ IO for a group_union operation.
std::ostream & operator<< (std::ostream &os, const dumpi_group_intersection &dd)
C++ IO for a group_intersection operation.
std::ostream & operator<< (std::ostream &os, const dumpi_group_difference &dd)
C++ IO for a group_difference operation.
std::ostream & operator<< (std::ostream &os, const dumpi_group_incl &dd)
C++ IO for a group_incl operation.
std::ostream & operator<< (std::ostream &os, const dumpi_group_excl &dd)
C++ IO for a group_excl operation.
std::ostream & operator<< (std::ostream &os, const dumpi_group_range_incl &dd)
C++ IO for a group_range_incl operation.
std::ostream & operator<< (std::ostream &os, const dumpi_group_range_excl &dd)
C++ IO for a group_range_excl operation.
std::ostream & operator<< (std::ostream &os, const dumpi_group_free &dd)
C++ IO for a group_free operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_size &dd)
C++ IO for a comm_size operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_rank &dd)
C++ IO for a comm_rank operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_compare &dd)
C++ IO for a comm_compare operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_dup &dd)
C++ IO for a comm_dup operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_create &dd)
C++ IO for a comm_create operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_split &dd)
C++ IO for a comm_split operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_free &dd)
C++ IO for a comm_free operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_test_inter &dd)
C++ IO for a comm_test_inter operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_remote_size &dd)
C++ IO for a comm_remote_size operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_remote_group &dd)
C++ IO for a comm_remote_group operation.
std::ostream & operator<< (std::ostream &os, const dumpi_intercomm_create &dd)
C++ IO for a intercomm_create operation.
std::ostream & operator<< (std::ostream &os, const dumpi_intercomm_merge &dd)
C++ IO for a intercomm_merge operation.
std::ostream & operator<< (std::ostream &os, const dumpi_keyval_create &dd)
C++ IO for a keyval_create operation.
std::ostream & operator<< (std::ostream &os, const dumpi_keyval_free &dd)
C++ IO for a keyval_free operation.
std::ostream & operator<< (std::ostream &os, const dumpi_attr_put &dd)
C++ IO for a attr_put operation.
std::ostream & operator<< (std::ostream &os, const dumpi_attr_get &dd)
C++ IO for a attr_get operation.
std::ostream & operator<< (std::ostream &os, const dumpi_attr_delete &dd)
C++ IO for a attr_delete operation.
std::ostream & operator<< (std::ostream &os, const dumpi_topo_test &dd)
C++ IO for a topo_test operation.
std::ostream & operator<< (std::ostream &os, const dumpi_cart_create &dd)
C++ IO for a cart_create operation.
std::ostream & operator<< (std::ostream &os, const dumpi_dims_create &dd)
C++ IO for a dims_create operation.
std::ostream & operator<< (std::ostream &os, const dumpi_graph_create &dd)
C++ IO for a graph_create operation.
std::ostream & operator<< (std::ostream &os, const dumpi_graphdims_get &dd)
C++ IO for a graphdims_get operation.
std::ostream & operator<< (std::ostream &os, const dumpi_graph_get &dd)
C++ IO for a graph_get operation.
std::ostream & operator<< (std::ostream &os, const dumpi_cartdim_get &dd)
C++ IO for a cartdim_get operation.
std::ostream & operator<< (std::ostream &os, const dumpi_cart_get &dd)
C++ IO for a cart_get operation.
std::ostream & operator<< (std::ostream &os, const dumpi_cart_rank &dd)
C++ IO for a cart_rank operation.
std::ostream & operator<< (std::ostream &os, const dumpi_cart_coords &dd)
C++ IO for a cart_coords operation.
std::ostream & operator<< (std::ostream &os, const dumpi_graph_neighbors_count &dd)
C++ IO for a graph_neighbors_count operation.
std::ostream & operator<< (std::ostream &os, const dumpi_graph_neighbors &dd)
C++ IO for a graph_neighbors operation.
std::ostream & operator<< (std::ostream &os, const dumpi_cart_shift &dd)
C++ IO for a cart_shift operation.
std::ostream & operator<< (std::ostream &os, const dumpi_cart_sub &dd)
C++ IO for a cart_sub operation.
std::ostream & operator<< (std::ostream &os, const dumpi_cart_map &dd)
C++ IO for a cart_map operation.
std::ostream & operator<< (std::ostream &os, const dumpi_graph_map &dd)
C++ IO for a graph_map operation.
std::ostream & operator<< (std::ostream &os, const dumpi_get_processor_name &dd)
C++ IO for a get_processor_name operation.
std::ostream & operator<< (std::ostream &os, const dumpi_get_version &dd)
C++ IO for a get_version operation.
std::ostream & operator<< (std::ostream &os, const dumpi_errhandler_create &dd)
C++ IO for a errhandler_create operation.
std::ostream & operator<< (std::ostream &os, const dumpi_errhandler_set &dd)
C++ IO for a errhandler_set operation.
std::ostream & operator<< (std::ostream &os, const dumpi_errhandler_get &dd)
C++ IO for a errhandler_get operation.
std::ostream & operator<< (std::ostream &os, const dumpi_errhandler_free &dd)
C++ IO for a errhandler_free operation.
std::ostream & operator<< (std::ostream &os, const dumpi_error_string &dd)
C++ IO for a error_string operation.
std::ostream & operator<< (std::ostream &os, const dumpi_error_class &dd)
C++ IO for a error_class operation.
std::ostream & operator<< (std::ostream &os, const dumpi_wtime &dd)
C++ IO for a wtime operation.
std::ostream & operator<< (std::ostream &os, const dumpi_wtick &dd)
C++ IO for a wtick operation.
std::ostream & operator<< (std::ostream &os, const dumpi_init &dd)
C++ IO for a init operation.
std::ostream & operator<< (std::ostream &os, const dumpi_finalize &dd)
C++ IO for a finalize operation.
std::ostream & operator<< (std::ostream &os, const dumpi_initialized &dd)
C++ IO for a initialized operation.
std::ostream & operator<< (std::ostream &os, const dumpi_abort &dd)
C++ IO for a abort operation.
std::ostream & operator<< (std::ostream &os, const dumpi_close_port &dd)
C++ IO for a close_port operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_accept &dd)
C++ IO for a comm_accept operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_connect &dd)
C++ IO for a comm_connect operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_disconnect &dd)
C++ IO for a comm_disconnect operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_get_parent &dd)
C++ IO for a comm_get_parent operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_join &dd)
C++ IO for a comm_join operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_spawn &dd)
C++ IO for a comm_spawn operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_spawn_multiple &dd)
C++ IO for a comm_spawn_multiple operation.
std::ostream & operator<< (std::ostream &os, const dumpi_lookup_name &dd)
C++ IO for a lookup_name operation.
std::ostream & operator<< (std::ostream &os, const dumpi_open_port &dd)
C++ IO for a open_port operation.
std::ostream & operator<< (std::ostream &os, const dumpi_publish_name &dd)
C++ IO for a publish_name operation.
std::ostream & operator<< (std::ostream &os, const dumpi_unpublish_name &dd)
C++ IO for a unpublish_name operation.
std::ostream & operator<< (std::ostream &os, const dumpi_accumulate &dd)
C++ IO for a accumulate operation.
std::ostream & operator<< (std::ostream &os, const dumpi_get &dd)
C++ IO for a get operation.
std::ostream & operator<< (std::ostream &os, const dumpi_put &dd)
C++ IO for a put operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_complete &dd)
C++ IO for a win_complete operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_create &dd)
C++ IO for a win_create operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_fence &dd)
C++ IO for a win_fence operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_free &dd)
C++ IO for a win_free operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_get_group &dd)
C++ IO for a win_get_group operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_lock &dd)
C++ IO for a win_lock operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_post &dd)
C++ IO for a win_post operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_start &dd)
C++ IO for a win_start operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_test &dd)
C++ IO for a win_test operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_unlock &dd)
C++ IO for a win_unlock operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_wait &dd)
C++ IO for a win_wait operation.
std::ostream & operator<< (std::ostream &os, const dumpi_alltoallw &dd)
C++ IO for a alltoallw operation.
std::ostream & operator<< (std::ostream &os, const dumpi_exscan &dd)
C++ IO for a exscan operation.
std::ostream & operator<< (std::ostream &os, const dumpi_add_error_class &dd)
C++ IO for a add_error_class operation.
std::ostream & operator<< (std::ostream &os, const dumpi_add_error_code &dd)
C++ IO for a add_error_code operation.
std::ostream & operator<< (std::ostream &os, const dumpi_add_error_string &dd)
C++ IO for a add_error_string operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_call_errhandler &dd)
C++ IO for a comm_call_errhandler operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_create_keyval &dd)
C++ IO for a comm_create_keyval operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_delete_attr &dd)
C++ IO for a comm_delete_attr operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_free_keyval &dd)
C++ IO for a comm_free_keyval operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_get_attr &dd)
C++ IO for a comm_get_attr operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_get_name &dd)
C++ IO for a comm_get_name operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_set_attr &dd)
C++ IO for a comm_set_attr operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_set_name &dd)
C++ IO for a comm_set_name operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_call_errhandler &dd)
C++ IO for a file_call_errhandler operation.
std::ostream & operator<< (std::ostream &os, const dumpi_grequest_complete &dd)
C++ IO for a grequest_complete operation.
std::ostream & operator<< (std::ostream &os, const dumpi_grequest_start &dd)
C++ IO for a grequest_start operation.
std::ostream & operator<< (std::ostream &os, const dumpi_init_thread &dd)
C++ IO for a init_thread operation.
std::ostream & operator<< (std::ostream &os, const dumpi_is_thread_main &dd)
C++ IO for a is_thread_main operation.
std::ostream & operator<< (std::ostream &os, const dumpi_query_thread &dd)
C++ IO for a query_thread operation.
std::ostream & operator<< (std::ostream &os, const dumpi_status_set_cancelled &dd)
C++ IO for a status_set_cancelled operation.
std::ostream & operator<< (std::ostream &os, const dumpi_status_set_elements &dd)
C++ IO for a status_set_elements operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_create_keyval &dd)
C++ IO for a type_create_keyval operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_delete_attr &dd)
C++ IO for a type_delete_attr operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_dup &dd)
C++ IO for a type_dup operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_free_keyval &dd)
C++ IO for a type_free_keyval operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_get_attr &dd)
C++ IO for a type_get_attr operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_get_contents &dd)
C++ IO for a type_get_contents operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_get_envelope &dd)
C++ IO for a type_get_envelope operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_get_name &dd)
C++ IO for a type_get_name operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_set_attr &dd)
C++ IO for a type_set_attr operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_set_name &dd)
C++ IO for a type_set_name operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_match_size &dd)
C++ IO for a type_match_size operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_call_errhandler &dd)
C++ IO for a win_call_errhandler operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_create_keyval &dd)
C++ IO for a win_create_keyval operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_delete_attr &dd)
C++ IO for a win_delete_attr operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_free_keyval &dd)
C++ IO for a win_free_keyval operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_get_attr &dd)
C++ IO for a win_get_attr operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_get_name &dd)
C++ IO for a win_get_name operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_set_attr &dd)
C++ IO for a win_set_attr operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_set_name &dd)
C++ IO for a win_set_name operation.
std::ostream & operator<< (std::ostream &os, const dumpi_alloc_mem &dd)
C++ IO for a alloc_mem operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_create_errhandler &dd)
C++ IO for a comm_create_errhandler operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_get_errhandler &dd)
C++ IO for a comm_get_errhandler operation.
std::ostream & operator<< (std::ostream &os, const dumpi_comm_set_errhandler &dd)
C++ IO for a comm_set_errhandler operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_create_errhandler &dd)
C++ IO for a file_create_errhandler operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_get_errhandler &dd)
C++ IO for a file_get_errhandler operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_set_errhandler &dd)
C++ IO for a file_set_errhandler operation.
std::ostream & operator<< (std::ostream &os, const dumpi_finalized &dd)
C++ IO for a finalized operation.
std::ostream & operator<< (std::ostream &os, const dumpi_free_mem &dd)
C++ IO for a free_mem operation.
std::ostream & operator<< (std::ostream &os, const dumpi_get_address &dd)
C++ IO for a get_address operation.
std::ostream & operator<< (std::ostream &os, const dumpi_info_create &dd)
C++ IO for a info_create operation.
std::ostream & operator<< (std::ostream &os, const dumpi_info_delete &dd)
C++ IO for a info_delete operation.
std::ostream & operator<< (std::ostream &os, const dumpi_info_dup &dd)
C++ IO for a info_dup operation.
std::ostream & operator<< (std::ostream &os, const dumpi_info_free &dd)
C++ IO for a info_free operation.
std::ostream & operator<< (std::ostream &os, const dumpi_info_get &dd)
C++ IO for a info_get operation.
std::ostream & operator<< (std::ostream &os, const dumpi_info_get_nkeys &dd)
C++ IO for a info_get_nkeys operation.
std::ostream & operator<< (std::ostream &os, const dumpi_info_get_nthkey &dd)
C++ IO for a info_get_nthkey operation.
std::ostream & operator<< (std::ostream &os, const dumpi_info_get_valuelen &dd)
C++ IO for a info_get_valuelen operation.
std::ostream & operator<< (std::ostream &os, const dumpi_info_set &dd)
C++ IO for a info_set operation.
std::ostream & operator<< (std::ostream &os, const dumpi_pack_external &dd)
C++ IO for a pack_external operation.
std::ostream & operator<< (std::ostream &os, const dumpi_pack_external_size &dd)
C++ IO for a pack_external_size operation.
std::ostream & operator<< (std::ostream &os, const dumpi_request_get_status &dd)
C++ IO for a request_get_status operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_create_darray &dd)
C++ IO for a type_create_darray operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_create_hindexed &dd)
C++ IO for a type_create_hindexed operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_create_hvector &dd)
C++ IO for a type_create_hvector operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_create_indexed_block &dd)
C++ IO for a type_create_indexed_block operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_create_resized &dd)
C++ IO for a type_create_resized operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_create_struct &dd)
C++ IO for a type_create_struct operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_create_subarray &dd)
C++ IO for a type_create_subarray operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_get_extent &dd)
C++ IO for a type_get_extent operation.
std::ostream & operator<< (std::ostream &os, const dumpi_type_get_true_extent &dd)
C++ IO for a type_get_true_extent operation.
std::ostream & operator<< (std::ostream &os, const dumpi_unpack_external &dd)
C++ IO for a unpack_external operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_create_errhandler &dd)
C++ IO for a win_create_errhandler operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_get_errhandler &dd)
C++ IO for a win_get_errhandler operation.
std::ostream & operator<< (std::ostream &os, const dumpi_win_set_errhandler &dd)
C++ IO for a win_set_errhandler operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_open &dd)
C++ IO for a file_open operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_close &dd)
C++ IO for a file_close operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_delete &dd)
C++ IO for a file_delete operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_set_size &dd)
C++ IO for a file_set_size operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_preallocate &dd)
C++ IO for a file_preallocate operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_get_size &dd)
C++ IO for a file_get_size operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_get_group &dd)
C++ IO for a file_get_group operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_get_amode &dd)
C++ IO for a file_get_amode operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_set_info &dd)
C++ IO for a file_set_info operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_get_info &dd)
C++ IO for a file_get_info operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_set_view &dd)
C++ IO for a file_set_view operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_get_view &dd)
C++ IO for a file_get_view operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_read_at &dd)
C++ IO for a file_read_at operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_read_at_all &dd)
C++ IO for a file_read_at_all operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_write_at &dd)
C++ IO for a file_write_at operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_write_at_all &dd)
C++ IO for a file_write_at_all operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_iread_at &dd)
C++ IO for a file_iread_at operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_iwrite_at &dd)
C++ IO for a file_iwrite_at operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_read &dd)
C++ IO for a file_read operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_read_all &dd)
C++ IO for a file_read_all operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_write &dd)
C++ IO for a file_write operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_write_all &dd)
C++ IO for a file_write_all operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_iread &dd)
C++ IO for a file_iread operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_iwrite &dd)
C++ IO for a file_iwrite operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_seek &dd)
C++ IO for a file_seek operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_get_position &dd)
C++ IO for a file_get_position operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_get_byte_offset &dd)
C++ IO for a file_get_byte_offset operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_read_shared &dd)
C++ IO for a file_read_shared operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_write_shared &dd)
C++ IO for a file_write_shared operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_iread_shared &dd)
C++ IO for a file_iread_shared operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_iwrite_shared &dd)
C++ IO for a file_iwrite_shared operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_read_ordered &dd)
C++ IO for a file_read_ordered operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_write_ordered &dd)
C++ IO for a file_write_ordered operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_seek_shared &dd)
C++ IO for a file_seek_shared operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_get_position_shared &dd)
C++ IO for a file_get_position_shared operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_read_at_all_begin &dd)
C++ IO for a file_read_at_all_begin operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_read_at_all_end &dd)
C++ IO for a file_read_at_all_end operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_write_at_all_begin &dd)
C++ IO for a file_write_at_all_begin operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_write_at_all_end &dd)
C++ IO for a file_write_at_all_end operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_read_all_begin &dd)
C++ IO for a file_read_all_begin operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_read_all_end &dd)
C++ IO for a file_read_all_end operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_write_all_begin &dd)
C++ IO for a file_write_all_begin operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_write_all_end &dd)
C++ IO for a file_write_all_end operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_read_ordered_begin &dd)
C++ IO for a file_read_ordered_begin operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_read_ordered_end &dd)
C++ IO for a file_read_ordered_end operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_write_ordered_begin &dd)
C++ IO for a file_write_ordered_begin operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_write_ordered_end &dd)
C++ IO for a file_write_ordered_end operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_get_type_extent &dd)
C++ IO for a file_get_type_extent operation.
std::ostream & operator<< (std::ostream &os, const dumpi_register_datarep &dd)
C++ IO for a register_datarep operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_set_atomicity &dd)
C++ IO for a file_set_atomicity operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_get_atomicity &dd)
C++ IO for a file_get_atomicity operation.
std::ostream & operator<< (std::ostream &os, const dumpi_file_sync &dd)
C++ IO for a file_sync operation.
std::ostream & operator<< (std::ostream &os, const dumpio_test &dd)
C++ IO for an IO test operation.
std::ostream & operator<< (std::ostream &os, const dumpio_wait &dd)
C++ IO for an IO wait operation.
std::ostream & operator<< (std::ostream &os, const dumpio_testall &dd)
C++ IO for an IO testall operation.
std::ostream & operator<< (std::ostream &os, const dumpio_waitall &dd)
C++ IO for an IO waitall operation.
std::ostream & operator<< (std::ostream &os, const dumpio_testany &dd)
C++ IO for an IO testany operation.
std::ostream & operator<< (std::ostream &os, const dumpio_waitany &dd)
C++ IO for an IO waitany operation.
std::ostream & operator<< (std::ostream &os, const dumpio_waitsome &dd)
C++ IO for an IO waitsome operation.
std::ostream & operator<< (std::ostream &os, const dumpio_testsome &dd)
C++ IO for an IO testsome operation.
std::string dumpi_file_name (int rank, std::string fileroot_)
int getnumprocs (dumpi_meta *dmeta_)
DeclareFactory (blas_kernel)
DeclareFactory1InitParam (api, software_id)
DeclareFactory2InitParams (app_launch, sw::app_id, parallel_runtime *)
DeclareFactory1InitParam (node_allocator, parallel_runtime *)
DeclareFactory1InitParam (task_mapper, parallel_runtime *)
void compute_time (double tsec)
utility function for computing stuff
template<typename T , typename U >
U operator/ (const sstmac_global_builtin< U > &b, const sstmac_global_builtin< T > &t)
template<typename T , typename U >
U operator+ (const sstmac_global_builtin< U > &b, const sstmac_global_builtin< T > &t)
template<typename T , typename U >
U operator- (const sstmac_global_builtin< U > &b, const sstmac_global_builtin< T > &t)
template<typename T , typename U >
U operator/ (const U &b, const sstmac_global_builtin< T > &t)
template<typename T , typename U >
U operator+ (const U &b, const sstmac_global_builtin< T > &t)
template<typename T , typename U >
U operator- (const U &b, const sstmac_global_builtin< T > &t)
template<typename T , typename U >
U operator% (const U &b, const sstmac_global_builtin< T > &t)
template<typename T , typename U >
U operator+= (U &b, const sstmac_global_builtin< T > &t)
template<typename T , typename U >
U operator-= (const U &b, const sstmac_global_builtin< T > &t)
template<typename T , typename U >
bool operator< (const U &b, const sstmac_global_builtin< T > &t)
template<typename T , typename U >
bool operator> (const U &b, const sstmac_global_builtin< T > &t)
template<typename T >
std::ostream & operator<< (std::ostream &os, const sstmac_global_builtin< T > &t)
bool operator== (const software_id &a, const software_id &b)
bool operator!= (const software_id &a, const software_id &b)
bool operator< (const software_id &a, const software_id &b)
bool operator> (const software_id &a, const software_id &b)
std::ostream & operator<< (std::ostream &os, const software_id &n)
void context_springboard (int func_ptr_a, int func_ptr_b, int arg_ptr_a, int arg_ptr_b)
Springboard routine to wrap a makecontext call.
Typedef Documentation
typedef int sstmac::sw::app_id
Definition at line 20 of file app_id.h.
typedef std::map<long, mutex_t*> sstmac::sw::condition_t
Definition at line 47 of file app.h.
typedef int sstmac::sw::flow_id
Definition at line 20 of file flow_id.h.
typedef std::set<node_id> sstmac::sw::ordered_node_set
Definition at line 10 of file node_set.h.
typedef int sstmac::sw::task_id
Definition at line 20 of file task_id.h.
typedef std::pair<threading_interface*, thread*> sstmac::sw::thread_data_t
Definition at line 14 of file thread_data.h.
typedef int sstmac::sw::thread_id
Definition at line 21 of file thread_id.h.
Function Documentation
void sstmac::sw::compute_time (double tsec)
utility function for computing stuff
void sstmac::sw::context_springboard (int func_ptr_a, int func_ptr_b, int arg_ptr_a, int arg_ptr_b)
Springboard routine to wrap a makecontext call.
We have to be able to take a pointer to this function (so no inline).
Referenced by sstmac::sw::funcptr::call().
sstmac::sw::DeclareFactory (blas_kernel)
sstmac::sw::DeclareFactory1InitParam (node_allocator , parallel_runtime *)
sstmac::sw::DeclareFactory1InitParam (task_mapper , parallel_runtime *)
sstmac::sw::DeclareFactory1InitParam (api , software_id)
sstmac::sw::DeclareFactory2InitParams (app_launch , sw::app_id , parallel_runtime *)
std::string sstmac::sw::dumpi_file_name (int rank, std::string fileroot_)
int sstmac::sw::getnumprocs (dumpi_meta * dmeta_)
bool sstmac::sw::operator!= (const software_id & a, const software_id & b) inline
Definition at line 49 of file software_id.h.
References sstmac::sw::software_id::app_, sstmac::sw::software_id::task_, and sstmac::sw::software_id::thread_.
template<typename T , typename U > U sstmac::sw::operator% (const U & b, const sstmac_global_builtin< T > & t)
Definition at line 393 of file global_builtin.h.
template<typename T , typename U > U sstmac::sw::operator+ (const sstmac_global_builtin< U > & b, const sstmac_global_builtin< T > & t)
Definition at line 321 of file global_builtin.h.
template<typename T , typename U > U sstmac::sw::operator+ (const U & b, const sstmac_global_builtin< T > & t)
Definition at line 370 of file global_builtin.h.
template<typename T , typename U > U sstmac::sw::operator+= (U & b, const sstmac_global_builtin< T > & t)
Definition at line 400 of file global_builtin.h.
template<typename T , typename U > U sstmac::sw::operator- (const sstmac_global_builtin< U > & b, const sstmac_global_builtin< T > & t)
Definition at line 329 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::operator*().
template<typename T , typename U > U sstmac::sw::operator- (const U & b, const sstmac_global_builtin< T > & t)
Definition at line 377 of file global_builtin.h.
References sstmac::sw::sstmac_global_builtin< T >::operator*().
template<typename T , typename U > U sstmac::sw::operator-= (const U & b, const sstmac_global_builtin< T > & t)
Definition at line 408 of file global_builtin.h.
template<typename T , typename U > U sstmac::sw::operator/ (const sstmac_global_builtin< U > & b, const sstmac_global_builtin< T > & t)
Definition at line 313 of file global_builtin.h.
template<typename T , typename U > U sstmac::sw::operator/ (const U & b, const sstmac_global_builtin< T > & t)
Definition at line 363 of file global_builtin.h.
bool sstmac::sw::operator< (const software_id & a, const software_id & b) inline
Definition at line 53 of file software_id.h.
References sstmac::sw::software_id::task_.
template<typename T , typename U > bool sstmac::sw::operator< (const U & b, const sstmac_global_builtin< T > & t)
Definition at line 416 of file global_builtin.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_status & status) inline
Print status info.
Definition at line 33 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_clock & tt) inline
Dumpi timestamp.
Definition at line 53 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const software_id & n) inline
Definition at line 63 of file software_id.h.
References sstmac::sw::software_id::to_string().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_time & tt) inline
Dumpi time value.
Definition at line 64 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_func_call & dd) inline
C++ IO for a function call.
Definition at line 244 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_send & dd) inline
C++ IO for a send operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 258 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_recv & dd) inline
C++ IO for a recv operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 281 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_get_count & dd) inline
C++ IO for a get_count operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 306 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_bsend & dd) inline
C++ IO for a bsend operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 325 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_ssend & dd) inline
C++ IO for a ssend operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 348 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_rsend & dd) inline
C++ IO for a rsend operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 371 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_buffer_attach & dd) inline
C++ IO for a buffer_attach operation.
Argument value before PMPI call
Definition at line 394 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_buffer_detach & dd) inline
C++ IO for a buffer_detach operation.
Argument value after PMPI call
Definition at line 410 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_isend & dd) inline
C++ IO for a isend operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 426 of file dumpi_type_io.h.
template<typename T > std::ostream& sstmac::sw::operator<< (std::ostream & os, const sstmac_global_builtin< T > & t) inline
Definition at line 430 of file global_builtin.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_ibsend & dd) inline
C++ IO for a ibsend operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 451 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_issend & dd) inline
C++ IO for a issend operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 476 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_irsend & dd) inline
C++ IO for a irsend operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 501 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_irecv & dd) inline
C++ IO for a irecv operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 526 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_wait & dd) inline
C++ IO for a wait operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 551 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_test & dd) inline
C++ IO for a test operation.
Argument value before PMPI call
Argument value after PMPI call
Argument value before PMPI call. Only stored if(flag != 0)
Definition at line 569 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_request_free & dd) inline
C++ IO for a request_free operation.
Argument value before PMPI call
Definition at line 589 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_waitany & dd) inline
C++ IO for a waitany operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Argument value before PMPI call. Only stored if(index != MPI_UNDEFINED)
Definition at line 605 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_testany & dd) inline
C++ IO for a testany operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Argument value after PMPI call
Argument value before PMPI call. Only stored if(flag != 0)
Definition at line 627 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_waitall & dd) inline
C++ IO for a waitall operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call. Array of length [count]
Definition at line 651 of file dumpi_type_io.h.
References sstmac::sw::P::ints(), and sstmac::sw::P::statuses().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_testall & dd) inline
C++ IO for a testall operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Argument value after PMPI call. Array of length [count]. Only stored if(flag != 0)
Definition at line 671 of file dumpi_type_io.h.
References sstmac::sw::P::ints(), and sstmac::sw::P::statuses().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_waitsome & dd) inline
C++ IO for a waitsome operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Argument value after PMPI call. Array of length [*outcount]
Argument value after PMPI call. Array of length [*outcount]
Definition at line 696 of file dumpi_type_io.h.
References sstmac::sw::P::ints(), and sstmac::sw::P::statuses().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_testsome & dd) inline
C++ IO for a testsome operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Argument value after PMPI call. Array of length [*outcount]
Argument value after PMPI call. Array of length [*outcount]
Definition at line 720 of file dumpi_type_io.h.
References sstmac::sw::P::ints(), and sstmac::sw::P::statuses().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_iprobe & dd) inline
C++ IO for a iprobe operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Argument value before PMPI call. Only stored if(flag != 0)
Definition at line 744 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_probe & dd) inline
C++ IO for a probe operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 768 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_cancel & dd) inline
C++ IO for a cancel operation.
Argument value before PMPI call
Definition at line 790 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_test_cancelled & dd) inline
C++ IO for a test_cancelled operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 806 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_send_init & dd) inline
C++ IO for a send_init operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 825 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_bsend_init & dd) inline
C++ IO for a bsend_init operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 851 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_ssend_init & dd) inline
C++ IO for a ssend_init operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 877 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_rsend_init & dd) inline
C++ IO for a rsend_init operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 903 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_recv_init & dd) inline
C++ IO for a recv_init operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 929 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_start & dd) inline
C++ IO for a start operation.
Argument value after PMPI call
Definition at line 955 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_startall & dd) inline
C++ IO for a startall operation.
Argument value before PMPI call
Argument value after PMPI call. Array of length [count]
Definition at line 971 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_sendrecv & dd) inline
C++ IO for a sendrecv operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 989 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_sendrecv_replace & dd) inline
C++ IO for a sendrecv_replace operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1022 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_contiguous & dd) inline
C++ IO for a type_contiguous operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1052 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_vector & dd) inline
C++ IO for a type_vector operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1072 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_hvector & dd) inline
C++ IO for a type_hvector operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1095 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_indexed & dd) inline
C++ IO for a type_indexed operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value before PMPI call. Array of length [count]
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1118 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_hindexed & dd) inline
C++ IO for a type_hindexed operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value before PMPI call. Array of length [count]
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1141 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_struct & dd) inline
C++ IO for a type_struct operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Definition at line 1165 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_address & dd) inline
C++ IO for a address operation.
Argument value after PMPI call
Definition at line 1188 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_extent & dd) inline
C++ IO for a type_extent operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1203 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_size & dd) inline
C++ IO for a type_size operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1220 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_lb & dd) inline
C++ IO for a type_lb operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1237 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_ub & dd) inline
C++ IO for a type_ub operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1254 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_commit & dd) inline
C++ IO for a type_commit operation.
Argument value before PMPI call
Definition at line 1271 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_free & dd) inline
C++ IO for a type_free operation.
Argument value before PMPI call
Definition at line 1286 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_get_elements & dd) inline
C++ IO for a get_elements operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1301 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_pack & dd) inline
C++ IO for a pack operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before and after PMPI call.
Argument value before PMPI call
Definition at line 1320 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_unpack & dd) inline
C++ IO for a unpack operation.
Argument value before PMPI call
Argument value before and after PMPI call.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1344 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_pack_size & dd) inline
C++ IO for a pack_size operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1368 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_barrier & dd) inline
C++ IO for a barrier operation.
Argument value before PMPI call
Definition at line 1389 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_bcast & dd) inline
C++ IO for a bcast operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1404 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_gather & dd) inline
C++ IO for a gather operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. Only stored if(commrank==root)
Argument value before PMPI call. Only stored if(commrank==root)
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1425 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_gatherv & dd) inline
C++ IO for a gatherv operation.
Not an MPI argument. Added to index relevant data in the struct.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. Array of length [commsize]. Only stored if(commrank==root)
Argument value before PMPI call. Array of length [commsize]. Only stored if(commrank==root)
Argument value before PMPI call. Only stored if(commrank==root)
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1452 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_scatter & dd) inline
C++ IO for a scatter operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call. Only stored if(commrank==root)
Argument value before PMPI call. Only stored if(commrank==root)
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1493 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_scatterv & dd) inline
C++ IO for a scatterv operation.
Not an MPI argument. Added to index relevant data in the struct.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call. Array of length [commsize]. Only stored if(commrank==root)
Argument value before PMPI call. Array of length [commsize]. Only stored if(commrank==root)
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1520 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_allgather & dd) inline
C++ IO for a allgather operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1561 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_allgatherv & dd) inline
C++ IO for a allgatherv operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1584 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_alltoall & dd) inline
C++ IO for a alltoall operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1611 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_alltoallv & dd) inline
C++ IO for a alltoallv operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1634 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_reduce & dd) inline
C++ IO for a reduce operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1663 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_op_create & dd) inline
C++ IO for a op_create operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1686 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_op_free & dd) inline
C++ IO for a op_free operation.
Argument value before PMPI call
Definition at line 1704 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_allreduce & dd) inline
C++ IO for a allreduce operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1719 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_reduce_scatter & dd) inline
C++ IO for a reduce_scatter operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1740 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_scan & dd) inline
C++ IO for a scan operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 1764 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_group_size & dd) inline
C++ IO for a group_size operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1785 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_group_rank & dd) inline
C++ IO for a group_rank operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1802 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_group_translate_ranks & dd) inline
C++ IO for a group_translate_ranks operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value before PMPI call
Argument value after PMPI call. Array of length [count]
Definition at line 1819 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_group_compare & dd) inline
C++ IO for a group_compare operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1843 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_group & dd) inline
C++ IO for a comm_group operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1863 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_group_union & dd) inline
C++ IO for a group_union operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1880 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_group_intersection & dd) inline
C++ IO for a group_intersection operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1899 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_group_difference & dd) inline
C++ IO for a group_difference operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 1919 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_group_incl & dd) inline
C++ IO for a group_incl operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Definition at line 1939 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_group_excl & dd) inline
C++ IO for a group_excl operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Definition at line 1960 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_group_range_incl & dd) inline
C++ IO for a group_range_incl operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. 2D-aray of length [count][3]
Argument value after PMPI call
Definition at line 1981 of file dumpi_type_io.h.
References sstmac::sw::P::ints2d().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_group_range_excl & dd) inline
C++ IO for a group_range_excl operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. 2D-array of length [count][3]
Argument value after PMPI call
Definition at line 2003 of file dumpi_type_io.h.
References sstmac::sw::P::ints2d().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_group_free & dd) inline
C++ IO for a group_free operation.
Argument value before PMPI call
Definition at line 2025 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_size & dd) inline
C++ IO for a comm_size operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2040 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_rank & dd) inline
C++ IO for a comm_rank operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2057 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_compare & dd) inline
C++ IO for a comm_compare operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2074 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_dup & dd) inline
C++ IO for a comm_dup operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2093 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_create & dd) inline
C++ IO for a comm_create operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2110 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_split & dd) inline
C++ IO for a comm_split operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2129 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_free & dd) inline
C++ IO for a comm_free operation.
Argument value before PMPI call
Definition at line 2150 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_test_inter & dd) inline
C++ IO for a comm_test_inter operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2165 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_remote_size & dd) inline
C++ IO for a comm_remote_size operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2183 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_remote_group & dd) inline
C++ IO for a comm_remote_group operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2201 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_intercomm_create & dd) inline
C++ IO for a intercomm_create operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2219 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_intercomm_merge & dd) inline
C++ IO for a intercomm_merge operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2245 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_keyval_create & dd) inline
C++ IO for a keyval_create operation.
Argument value after PMPI call
Definition at line 2265 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_keyval_free & dd) inline
C++ IO for a keyval_free operation.
Argument value before PMPI call
Definition at line 2281 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_attr_put & dd) inline
C++ IO for a attr_put operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 2296 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_attr_get & dd) inline
C++ IO for a attr_get operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2313 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_attr_delete & dd) inline
C++ IO for a attr_delete operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 2332 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_topo_test & dd) inline
C++ IO for a topo_test operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2349 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_cart_create & dd) inline
C++ IO for a cart_create operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. Array of length [ndim]
Argument value before PMPI call. Array of length [ndim]
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2366 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_dims_create & dd) inline
C++ IO for a dims_create operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before and after PMPI call. Array of lenght [ndim]
Definition at line 2391 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_graph_create & dd) inline
C++ IO for a graph_create operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. Array of length [nodes]
Argument value before PMPI call. Array of length [numedges]
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2412 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_graphdims_get & dd) inline
C++ IO for a graphdims_get operation.
Argument value before PMPI call
Argument value after PMPI call
Argument value after PMPI call
Definition at line 2439 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_graph_get & dd) inline
C++ IO for a graph_get operation.
Not an MPI argument. Added to index relevant data in the struct.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call. Array of length [totnodes]
Argument value after PMPI call. Array of length [totedges]
Definition at line 2459 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_cartdim_get & dd) inline
C++ IO for a cartdim_get operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2486 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_cart_get & dd) inline
C++ IO for a cart_get operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call. Array of length [ndim]
Argument value after PMPI call. Array of length [ndim]
Argument value after PMPI call
Definition at line 2503 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_cart_rank & dd) inline
C++ IO for a cart_rank operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call
Argument value before PMPI call. Array of length [ndim]
Argument value after PMPI call
Definition at line 2528 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_cart_coords & dd) inline
C++ IO for a cart_coords operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call. Array of length [ndim]
Definition at line 2549 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_graph_neighbors_count & dd) inline
C++ IO for a graph_neighbors_count operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2572 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_graph_neighbors & dd) inline
C++ IO for a graph_neighbors operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call. Array of length [nneigh]
Definition at line 2592 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_cart_shift & dd) inline
C++ IO for a cart_shift operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Argument value after PMPI call
Definition at line 2616 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_cart_sub & dd) inline
C++ IO for a cart_sub operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call
Argument value before PMPI call. Array of length [ndim]
Argument value after PMPI call
Definition at line 2639 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_cart_map & dd) inline
C++ IO for a cart_map operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. Array of length [ndim]
Argument value before PMPI call. Array of length [ndim]
Argument value after PMPI call
Definition at line 2660 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_graph_map & dd) inline
C++ IO for a graph_map operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. Array of length [nodes]
Argument value before PMPI call. Array of length [numedges]
Argument value after PMPI call
Definition at line 2683 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_get_processor_name & dd) inline
C++ IO for a get_processor_name operation.
Argument value after PMPI call. Array of length [*resultlen]
Argument value after PMPI call
Definition at line 2708 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_get_version & dd) inline
C++ IO for a get_version operation.
Argument value after PMPI call
Argument value after PMPI call
Definition at line 2726 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_errhandler_create & dd) inline
C++ IO for a errhandler_create operation.
Argument value after PMPI call
Definition at line 2743 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_errhandler_set & dd) inline
C++ IO for a errhandler_set operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 2759 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_errhandler_get & dd) inline
C++ IO for a errhandler_get operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2777 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_errhandler_free & dd) inline
C++ IO for a errhandler_free operation.
Argument value before PMPI call
Definition at line 2795 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_error_string & dd) inline
C++ IO for a error_string operation.
Argument value before PMPI call
Argument value after PMPI call. Array of length [*resultlen]
Argument value after PMPI call
Definition at line 2811 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_error_class & dd) inline
C++ IO for a error_class operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2830 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_wtime & dd) inline
C++ IO for a wtime operation.
Definition at line 2847 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_wtick & dd) inline
C++ IO for a wtick operation.
Definition at line 2861 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_init & dd) inline
C++ IO for a init operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [argc] containing NUL-terminated std::strings.
Definition at line 2875 of file dumpi_type_io.h.
References sstmac::sw::P::stringarray().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_finalize & dd) inline
C++ IO for a finalize operation.
Definition at line 2895 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_initialized & dd) inline
C++ IO for a initialized operation.
Argument value after PMPI call
Definition at line 2909 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_abort & dd) inline
C++ IO for a abort operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 2924 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_close_port & dd) inline
C++ IO for a close_port operation.
Argument value before PMPI call. NUL-terminated std::string
Definition at line 2941 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_accept & dd) inline
C++ IO for a comm_accept operation.
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2956 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_connect & dd) inline
C++ IO for a comm_connect operation.
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 2979 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_disconnect & dd) inline
C++ IO for a comm_disconnect operation.
Argument value before PMPI call
Definition at line 3002 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_get_parent & dd) inline
C++ IO for a comm_get_parent operation.
Argument value after PMPI call
Definition at line 3018 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_join & dd) inline
C++ IO for a comm_join operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 3034 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_spawn & dd) inline
C++ IO for a comm_spawn operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call. NUL-terminated std::string. Only stored if(oldcommrank==root)
Argument value before PMPI call. Null-terminated array of containing NUL-terminated std::strings. Only stored if(oldcommrank==root)
Argument value before PMPI call. Only stored if(oldcommrank==root)
Argument value before PMPI call. Only stored if(oldcommrank==root)
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Argument value after PMPI call. Array of length [maxprocs]. Only stored if(oldcommrank==root)
Definition at line 3051 of file dumpi_type_io.h.
References sstmac::sw::P::ints(), and sstmac::sw::P::stringarraynull().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_spawn_multiple & dd) inline
C++ IO for a comm_spawn_multiple operation.
Not an MPI argument. Added to index relevant data in the struct.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call. Only stored if(oldcommrank==root)
Argument value before PMPI call. Array of length [count] containing NUL-terminated std::strings. Only stored if(oldcommrank==root)
Argument value before PMPI call. 3D-array of length [count], with second-dimension NULL-terminated, and third dimension NUL-terminated strings (MPI_Comm_spawn_multiple is completely insane). Only stored if(oldcommrank==root)
Argument value before PMPI call. Array of length [count]. Only stored if(oldcommrank==root)
Argument value before PMPI call. Array of length [count]. Only stored if(oldcommrank==root)
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Argument value after PMPI call. Array of length [totprocs]. Only stored if(oldcommrank==root)
Definition at line 3095 of file dumpi_type_io.h.
References sstmac::sw::P::ints(), sstmac::sw::P::stringarray(), and sstmac::sw::P::stringarraynull2d().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_lookup_name & dd) inline
C++ IO for a lookup_name operation.
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call
Argument value after PMPI call. NUL-terminated std::string.
Definition at line 3159 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_open_port & dd) inline
C++ IO for a open_port operation.
Argument value before PMPI call
Argument value after PMPI call. NUL-terminated std::string
Definition at line 3178 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_publish_name & dd) inline
C++ IO for a publish_name operation.
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call
Argument value before PMPI call. NUL-terminated std::string
Definition at line 3195 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_unpublish_name & dd) inline
C++ IO for a unpublish_name operation.
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call
Argument value before PMPI call. NUL-terminated std::string
Definition at line 3214 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_accumulate & dd) inline
C++ IO for a accumulate operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3234 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_get & dd) inline
C++ IO for a get operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3263 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_put & dd) inline
C++ IO for a put operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3290 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_complete & dd) inline
C++ IO for a win_complete operation.
Argument value before PMPI call
Definition at line 3317 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_create & dd) inline
C++ IO for a win_create operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 3332 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_fence & dd) inline
C++ IO for a win_fence operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3355 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_free & dd) inline
C++ IO for a win_free operation.
Argument value before PMPI call
Definition at line 3372 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_get_group & dd) inline
C++ IO for a win_get_group operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 3387 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_lock & dd) inline
C++ IO for a win_lock operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3405 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_post & dd) inline
C++ IO for a win_post operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3426 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_start & dd) inline
C++ IO for a win_start operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3445 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_test & dd) inline
C++ IO for a win_test operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 3464 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_unlock & dd) inline
C++ IO for a win_unlock operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3481 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_wait & dd) inline
C++ IO for a win_wait operation.
Argument value before PMPI call
Definition at line 3498 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_alltoallw & dd) inline
C++ IO for a alltoallw operation.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call. Array of length [commsize]
Argument value before PMPI call
Definition at line 3513 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_exscan & dd) inline
C++ IO for a exscan operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3542 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_add_error_class & dd) inline
C++ IO for a add_error_class operation.
Argument value after PMPI call
Definition at line 3563 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_add_error_code & dd) inline
C++ IO for a add_error_code operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 3579 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_add_error_string & dd) inline
C++ IO for a add_error_string operation.
Argument value before PMPI call
Argument value before PMPI call. NUL-terminated std::string
Definition at line 3597 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_call_errhandler & dd) inline
C++ IO for a comm_call_errhandler operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3615 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_create_keyval & dd) inline
C++ IO for a comm_create_keyval operation.
Argument value after PMPI call
Definition at line 3633 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_delete_attr & dd) inline
C++ IO for a comm_delete_attr operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3649 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_free_keyval & dd) inline
C++ IO for a comm_free_keyval operation.
Argument value before PMPI call
Definition at line 3667 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_get_attr & dd) inline
C++ IO for a comm_get_attr operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 3683 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_get_name & dd) inline
C++ IO for a comm_get_name operation.
Argument value before PMPI call
Argument value after PMPI call. Array of length [*resultlen]
Argument value after PMPI call
Definition at line 3703 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_set_attr & dd) inline
C++ IO for a comm_set_attr operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3723 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_set_name & dd) inline
C++ IO for a comm_set_name operation.
Argument value before PMPI call
Argument value before PMPI call. NUL-terminated std::string
Definition at line 3741 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_call_errhandler & dd) inline
C++ IO for a file_call_errhandler operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3759 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_grequest_complete & dd) inline
C++ IO for a grequest_complete operation.
Argument value before PMPI call
Definition at line 3777 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_grequest_start & dd) inline
C++ IO for a grequest_start operation.
Argument value after PMPI call
Definition at line 3793 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_init_thread & dd) inline
C++ IO for a init_thread operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [argc] containing NUL-terminated std::strings.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 3809 of file dumpi_type_io.h.
References sstmac::sw::P::stringarray().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_is_thread_main & dd) inline
C++ IO for a is_thread_main operation.
Argument value after PMPI call
Definition at line 3833 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_query_thread & dd) inline
C++ IO for a query_thread operation.
Argument value after PMPI call
Definition at line 3849 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_status_set_cancelled & dd) inline
C++ IO for a status_set_cancelled operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3864 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_status_set_elements & dd) inline
C++ IO for a status_set_elements operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3882 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_create_keyval & dd) inline
C++ IO for a type_create_keyval operation.
Argument value after PMPI call
Definition at line 3902 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_delete_attr & dd) inline
C++ IO for a type_delete_attr operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 3918 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_dup & dd) inline
C++ IO for a type_dup operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 3936 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_free_keyval & dd) inline
C++ IO for a type_free_keyval operation.
Argument value before PMPI call
Definition at line 3953 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_get_attr & dd) inline
C++ IO for a type_get_attr operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 3969 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_get_contents & dd) inline
C++ IO for a type_get_contents operation.
Not an MPI argument. Added to index relevant data in the struct.
Not an MPI argument. Added to index relevant data in the struct.
Not an MPI argument. Added to index relevant data in the struct.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call. Array of length [numintegers]
Argument value after PMPI call. Array of length [numaddresses]
Argument value after PMPI call. Array of length [numdatatypes]
Definition at line 3989 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_get_envelope & dd) inline
C++ IO for a type_get_envelope operation.
Argument value before PMPI call
Argument value after PMPI call
Argument value after PMPI call
Argument value after PMPI call
Argument value after PMPI call
Definition at line 4026 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_get_name & dd) inline
C++ IO for a type_get_name operation.
Argument value before PMPI call
Argument value after PMPI call. NUL-terminated std::string.
Argument value after PMPI call
Definition at line 4050 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_set_attr & dd) inline
C++ IO for a type_set_attr operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 4070 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_set_name & dd) inline
C++ IO for a type_set_name operation.
Argument value before PMPI call
Argument value before PMPI call. NUL-terminated std::string
Definition at line 4088 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_match_size & dd) inline
C++ IO for a type_match_size operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4106 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_call_errhandler & dd) inline
C++ IO for a win_call_errhandler operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 4126 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_create_keyval & dd) inline
C++ IO for a win_create_keyval operation.
Argument value after PMPI call
Definition at line 4144 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_delete_attr & dd) inline
C++ IO for a win_delete_attr operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 4160 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_free_keyval & dd) inline
C++ IO for a win_free_keyval operation.
Argument value before PMPI call
Definition at line 4178 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_get_attr & dd) inline
C++ IO for a win_get_attr operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4194 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_get_name & dd) inline
C++ IO for a win_get_name operation.
Argument value before PMPI call
Argument value after PMPI call. NUL-terminated std::string.
Argument value after PMPI call
Definition at line 4213 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_set_attr & dd) inline
C++ IO for a win_set_attr operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 4232 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_set_name & dd) inline
C++ IO for a win_set_name operation.
Argument value before PMPI call
Argument value before PMPI call. NUL-terminated std::string
Definition at line 4249 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_alloc_mem & dd) inline
C++ IO for a alloc_mem operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 4266 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_create_errhandler & dd) inline
C++ IO for a comm_create_errhandler operation.
Argument value after PMPI call
Definition at line 4283 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_get_errhandler & dd) inline
C++ IO for a comm_get_errhandler operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4299 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_comm_set_errhandler & dd) inline
C++ IO for a comm_set_errhandler operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 4317 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_create_errhandler & dd) inline
C++ IO for a file_create_errhandler operation.
Argument value after PMPI call
Definition at line 4335 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_get_errhandler & dd) inline
C++ IO for a file_get_errhandler operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4351 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_set_errhandler & dd) inline
C++ IO for a file_set_errhandler operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 4369 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_finalized & dd) inline
C++ IO for a finalized operation.
Argument value after PMPI call
Definition at line 4387 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_free_mem & dd) inline
C++ IO for a free_mem operation.
Definition at line 4402 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_get_address & dd) inline
C++ IO for a get_address operation.
Argument value after PMPI call
Definition at line 4416 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_info_create & dd) inline
C++ IO for a info_create operation.
Argument value after PMPI call
Definition at line 4431 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_info_delete & dd) inline
C++ IO for a info_delete operation.
Argument value before PMPI call
Argument value before PMPI call. NUL-terminated std::string
Definition at line 4446 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_info_dup & dd) inline
C++ IO for a info_dup operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4463 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_info_free & dd) inline
C++ IO for a info_free operation.
Argument value before PMPI call
Definition at line 4480 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_info_get & dd) inline
C++ IO for a info_get operation.
Argument value before PMPI call
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call
Argument value after PMPI call. NUL-terminated std::string.
Argument value after PMPI call
Definition at line 4495 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_info_get_nkeys & dd) inline
C++ IO for a info_get_nkeys operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4518 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_info_get_nthkey & dd) inline
C++ IO for a info_get_nthkey operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call. NUL-terminated std::string
Definition at line 4536 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_info_get_valuelen & dd) inline
C++ IO for a info_get_valuelen operation.
Argument value before PMPI call
Argument value before PMPI call. NUL-terminated std::string
Argument value after PMPI call
Argument value after PMPI call
Definition at line 4556 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_info_set & dd) inline
C++ IO for a info_set operation.
Argument value before PMPI call
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call. NUL-terminated std::string
Definition at line 4578 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_pack_external & dd) inline
C++ IO for a pack_external operation.
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before and after PMPI call.
Definition at line 4597 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_pack_external_size & dd) inline
C++ IO for a pack_external_size operation.
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4623 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_request_get_status & dd) inline
C++ IO for a request_get_status operation.
Argument value before PMPI call
Argument value after PMPI call
Argument value before PMPI call. Only stored if(flag!=0)
Definition at line 4645 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_create_darray & dd) inline
C++ IO for a type_create_darray operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. Array of length [ndims]
Argument value before PMPI call. Array of length [ndims]
Argument value before PMPI call. Array of length [ndims]
Argument value before PMPI call. Array of length [ndims]
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4665 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_create_hindexed & dd) inline
C++ IO for a type_create_hindexed operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value before PMPI call. Array of length [count]
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4699 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_create_hvector & dd) inline
C++ IO for a type_create_hvector operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4724 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_create_indexed_block & dd) inline
C++ IO for a type_create_indexed_block operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4748 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_create_resized & dd) inline
C++ IO for a type_create_resized operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4772 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_create_struct & dd) inline
C++ IO for a type_create_struct operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value before PMPI call. Array of length [count]
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Definition at line 4794 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_create_subarray & dd) inline
C++ IO for a type_create_subarray operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [ndims]
Argument value before PMPI call. Array of length [ndims]
Argument value before PMPI call. Array of length [ndims]
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4818 of file dumpi_type_io.h.
References sstmac::sw::P::ints().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_get_extent & dd) inline
C++ IO for a type_get_extent operation.
Argument value before PMPI call
Argument value after PMPI call
Argument value after PMPI call
Definition at line 4846 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_type_get_true_extent & dd) inline
C++ IO for a type_get_true_extent operation.
Argument value before PMPI call
Argument value after PMPI call
Argument value after PMPI call
Definition at line 4866 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_unpack_external & dd) inline
C++ IO for a unpack_external operation.
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call
Argument value before and after PMPI call.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 4886 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_create_errhandler & dd) inline
C++ IO for a win_create_errhandler operation.
Argument value after PMPI call
Definition at line 4911 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_get_errhandler & dd) inline
C++ IO for a win_get_errhandler operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4927 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_win_set_errhandler & dd) inline
C++ IO for a win_set_errhandler operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4945 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_open & dd) inline
C++ IO for a file_open operation.
Argument value before PMPI call
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 4963 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_close & dd) inline
C++ IO for a file_close operation.
Argument value before PMPI call
Definition at line 4986 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_delete & dd) inline
C++ IO for a file_delete operation.
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call
Definition at line 5001 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_set_size & dd) inline
C++ IO for a file_set_size operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 5018 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_preallocate & dd) inline
C++ IO for a file_preallocate operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 5036 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_get_size & dd) inline
C++ IO for a file_get_size operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5054 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_get_group & dd) inline
C++ IO for a file_get_group operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5072 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_get_amode & dd) inline
C++ IO for a file_get_amode operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5090 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_set_info & dd) inline
C++ IO for a file_set_info operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 5108 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_get_info & dd) inline
C++ IO for a file_get_info operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5126 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_set_view & dd) inline
C++ IO for a file_set_view operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call. NUL-terminated std::string
Argument value before PMPI call
Definition at line 5144 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_get_view & dd) inline
C++ IO for a file_get_view operation.
Argument value before PMPI call
Argument value after PMPI call
Argument value after PMPI call
Argument value after PMPI call
Argument value after PMPI call. NUL-terminated std::string
Definition at line 5170 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_read_at & dd) inline
C++ IO for a file_read_at operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5194 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_read_at_all & dd) inline
C++ IO for a file_read_at_all operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5217 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_write_at & dd) inline
C++ IO for a file_write_at operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5241 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_write_at_all & dd) inline
C++ IO for a file_write_at_all operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5265 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_iread_at & dd) inline
C++ IO for a file_iread_at operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5289 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_iwrite_at & dd) inline
C++ IO for a file_iwrite_at operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5313 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_read & dd) inline
C++ IO for a file_read operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5337 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_read_all & dd) inline
C++ IO for a file_read_all operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5358 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_write & dd) inline
C++ IO for a file_write operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5380 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_write_all & dd) inline
C++ IO for a file_write_all operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5401 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_iread & dd) inline
C++ IO for a file_iread operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5423 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_iwrite & dd) inline
C++ IO for a file_iwrite operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5444 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_seek & dd) inline
C++ IO for a file_seek operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 5465 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_get_position & dd) inline
C++ IO for a file_get_position operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5484 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_get_byte_offset & dd) inline
C++ IO for a file_get_byte_offset operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5502 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_read_shared & dd) inline
C++ IO for a file_read_shared operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5522 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_write_shared & dd) inline
C++ IO for a file_write_shared operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5544 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_iread_shared & dd) inline
C++ IO for a file_iread_shared operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5566 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_iwrite_shared & dd) inline
C++ IO for a file_iwrite_shared operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5588 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_read_ordered & dd) inline
C++ IO for a file_read_ordered operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5610 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_write_ordered & dd) inline
C++ IO for a file_write_ordered operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5632 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_seek_shared & dd) inline
C++ IO for a file_seek_shared operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 5654 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_get_position_shared & dd) inline
C++ IO for a file_get_position_shared operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5674 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_read_at_all_begin & dd) inline
C++ IO for a file_read_at_all_begin operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 5692 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_read_at_all_end & dd) inline
C++ IO for a file_read_at_all_end operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5714 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_write_at_all_begin & dd) inline
C++ IO for a file_write_at_all_begin operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 5732 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_write_at_all_end & dd) inline
C++ IO for a file_write_at_all_end operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5754 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_read_all_begin & dd) inline
C++ IO for a file_read_all_begin operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 5772 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_read_all_end & dd) inline
C++ IO for a file_read_all_end operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5792 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_write_all_begin & dd) inline
C++ IO for a file_write_all_begin operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 5810 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_write_all_end & dd) inline
C++ IO for a file_write_all_end operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5830 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_read_ordered_begin & dd) inline
C++ IO for a file_read_ordered_begin operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 5848 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_read_ordered_end & dd) inline
C++ IO for a file_read_ordered_end operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5868 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_write_ordered_begin & dd) inline
C++ IO for a file_write_ordered_begin operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value before PMPI call
Definition at line 5886 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_write_ordered_end & dd) inline
C++ IO for a file_write_ordered_end operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5906 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_get_type_extent & dd) inline
C++ IO for a file_get_type_extent operation.
Argument value before PMPI call
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5924 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_register_datarep & dd) inline
C++ IO for a register_datarep operation.
Argument value before PMPI call. NUL-terminated std::string
Definition at line 5944 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_set_atomicity & dd) inline
C++ IO for a file_set_atomicity operation.
Argument value before PMPI call
Argument value before PMPI call
Definition at line 5960 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_get_atomicity & dd) inline
C++ IO for a file_get_atomicity operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 5978 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpi_file_sync & dd) inline
C++ IO for a file_sync operation.
Argument value before PMPI call
Definition at line 5996 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpio_test & dd) inline
C++ IO for an IO test operation.
Argument value before PMPI call
Argument value after PMPI call
Argument value before PMPI call. Only stored if(flag!=0)
Definition at line 6011 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpio_wait & dd) inline
C++ IO for an IO wait operation.
Argument value before PMPI call
Argument value after PMPI call
Definition at line 6030 of file dumpi_type_io.h.
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpio_testall & dd) inline
C++ IO for an IO testall operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Argument value after PMPI call. Array of length [count]. Only stored if(flag!=0)
Definition at line 6047 of file dumpi_type_io.h.
References sstmac::sw::P::ints(), and sstmac::sw::P::statuses().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpio_waitall & dd) inline
C++ IO for an IO waitall operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call. Array of length [count]
Definition at line 6071 of file dumpi_type_io.h.
References sstmac::sw::P::ints(), and sstmac::sw::P::statuses().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpio_testany & dd) inline
C++ IO for an IO testany operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value before PMPI call. Only stored if(flag!=0)
Argument value after PMPI call
Argument value after PMPI call. Array of length [count]. Only stored if(flag!=0)
Definition at line 6090 of file dumpi_type_io.h.
References sstmac::sw::P::ints(), and sstmac::sw::P::statuses().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpio_waitany & dd) inline
C++ IO for an IO waitany operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Argument value after PMPI call. Array of length [count]. Only stored if(index != MPI_UNDEFINED)
Definition at line 6116 of file dumpi_type_io.h.
References sstmac::sw::P::ints(), and sstmac::sw::P::statuses().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpio_waitsome & dd) inline
C++ IO for an IO waitsome operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Argument value after PMPI call. Array of length [*outcount]
Argument value after PMPI call. Array of length [*outcount]
Definition at line 6140 of file dumpi_type_io.h.
References sstmac::sw::P::ints(), and sstmac::sw::P::statuses().
std::ostream& sstmac::sw::operator<< (std::ostream & os, const dumpio_testsome & dd) inline
C++ IO for an IO testsome operation.
Argument value before PMPI call
Argument value before PMPI call. Array of length [count]
Argument value after PMPI call
Argument value after PMPI call. Array of length [*outcount]
Argument value after PMPI call. Array of length [*outcount]
Definition at line 6163 of file dumpi_type_io.h.
References sstmac::sw::P::ints(), and sstmac::sw::P::statuses().
bool sstmac::sw::operator== (const software_id & a, const software_id & b) inline
Definition at line 45 of file software_id.h.
References sstmac::sw::software_id::app_, sstmac::sw::software_id::task_, and sstmac::sw::software_id::thread_.
bool sstmac::sw::operator> (const software_id & a, const software_id & b) inline
Definition at line 57 of file software_id.h.
References sstmac::sw::software_id::task_.
template<typename T , typename U > bool sstmac::sw::operator> (const U & b, const sstmac_global_builtin< T > & t)
Definition at line 423 of file global_builtin.h.