SST/macro: sstmac Namespace Reference
sstmac Namespace Reference
SUMI = Simulator unified messagine interface It is also the name for a solid ink in Japanese - i.e.
Namespaces
ami
hw
mpi
native
sw
tutorial
Classes
class bitwisevaluepayload
Network payload consisting of a value with sensible copy semantics.
class block_partition
class bool_result
class bool_result< bool >
class bool_result< int >
class connectable_proxy_component
class connection_details
class deadlock_check
class deadlock_check_impl
class env
This class holds some global information about the simulation.
class event
class event_callback
The main interface for something that can respond to an event (sst_message).
class event_callback_1_args
class event_callback_2_args
class event_callback_instance
class event_handler
The main interface for something that can respond to an event (sst_message).
struct event_loc_id
class event_manager
Base type for implementations of an engine that is able to schedule events and advance simulation time in the right order.
class event_queue_entry
class event_scheduler
The interface for something that can schedule messages.
class event_subscheduler
class event_trace
class generic_event
class generic_event_0_args
class generic_event_1_args
class generic_event_2_args
class handler_event_queue_entry
class integrated_connectable_wrapper
class Labeler
class Labeler< const char * >
class library_interface
class location_trace
class lockable
class logger
Base class of things which track events in the simulation, and output in different ways.
class message
A class describing an event.
class message_buffer_cache
class metis_partition
class mutex_thread_lock
class occupied_block_partition
class pair_payload
Network payload consisting of a value with sensible copy semantics.
class pairpayloadvector
Network payload consisting of a value with sensible copy semantics.
class parallel_runtime
class partition
Class for storing all the partitions given to us by METIS.
class payload
Pure abstract base for payload that can be associated with a network send.
class runtime
class serial_partition
class sim_thread_lock
class Simulation
class SimulationQueue
class sleep_event
class SSTIntegratedComponent
class stat_collector
A type of logger that collects some kind of statistic and outputs to a file during or at the end of a simulation.
class stat_global_int
class stat_histogram
class stat_local_double
class stat_local_int
class stat_spyplot
this stat_collector class keeps a spy plot
class stat_spyplot_png
this stat_collector class keeps a spy plot, and outputs it as a png
class sumi_api
class sumi_queue
class sumi_server
class sumi_thread
class thread_info
class thread_safe_int_base
class thread_safe_int_t
class timed_interface
class timestamp
A basic container for time (subject to future transplant).
class topology_partition
class transport_message
class value_payload
Network payload consisting of a value with sensible copy semantics.
class vector1_payload
Network payload consisting of a boost multiarray.
class wrapper_payload
Network payload that wraps a raw buffer.
Typedefs
typedef uint32_t endpoint_id
typedef endpoint_id node_id
typedef int32_t topology_id
typedef topology_id switch_id
typedef endpoint_id netlink_id
typedef mutex_thread_lock thread_lock
typedef thread_safe_int_t< int > thread_safe_int
typedef thread_safe_int_t< long > thread_safe_long
typedef thread_safe_int_t< long long > thread_safe_long_long
typedef thread_safe_int_t< size_t > thread_safe_size_t
typedef int pipe_t[2]
Functions
DeclareFactory (parallel_runtime)
DeclareFactory1InitParam (partition, parallel_runtime *)
template<class Cls , typename Fxn >
event_callback * ev_callback (Cls *cls, Fxn fxn)
template<class Cls , typename Fxn >
event_callback * ev_callback (event_loc_id loc, Cls *cls, Fxn fxn)
template<class Cls , typename Fxn , typename Arg1 >
event_callback * ev_callback (event_loc_id loc, Cls *cls, Fxn fxn, const Arg1 &arg1)
template<class Cls , typename Fxn , typename Arg1 , typename Arg2 >
event_callback * ev_callback (event_loc_id loc, Cls *cls, Fxn fxn, const Arg1 &arg1, const Arg2 &arg2)
template<class Cls , typename Fxn , class Arg1 >
event_queue_entry * new_event (Cls *cls, Fxn fxn, const Arg1 &arg1)
template<class Cls , typename Fxn , class Arg1 , class Arg2 >
event_queue_entry * new_event (Cls *cls, Fxn fxn, const Arg1 &arg1, const Arg2 &arg2)
template<class Cls , typename Fxn >
event_queue_entry * new_event (event_loc_id local, Cls *cls, Fxn fxn)
template<class Cls , typename Fxn , class Arg1 >
event_queue_entry * new_event (event_loc_id local, Cls *cls, Fxn fxn, const Arg1 &arg1)
template<class Cls , typename Fxn , class Arg1 , class Arg2 >
event_queue_entry * new_event (event_loc_id local, Cls *cls, Fxn fxn, const Arg1 &arg1, const Arg2 &arg2)
bool operator== (const event_loc_id &a, const event_loc_id &b)
bool operator!= (const event_loc_id &a, const event_loc_id &b)
bool operator< (const event_loc_id &a, const event_loc_id &b)
std::ostream & operator<< (std::ostream &os, const event_loc_id &loc)
DeclareFactory1InitParam (event_manager, parallel_runtime *)
template<class T , class Fxn >
deadlock_check * new_deadlock_check (T *t, Fxn f)
DeclareFactory (stat_collector)
timestamp operator+ (const timestamp &a, const timestamp &b)
timestamp operator- (const timestamp &a, const timestamp &b)
timestamp operator* (const timestamp &t, double scaling)
timestamp operator* (double scaling, const timestamp &t)
timestamp operator/ (const timestamp &t, double scaling)
std::ostream & operator<< (std::ostream &os, const timestamp &t)
std::string to_printf_type (timestamp t)
template<class T >
int append_label (char *buffer, const T &t)
template<class T >
int extract_label (char *buffer, T &t)
parallel_runtime * init ()
void finalize (parallel_runtime *rt)
void init_opts (opts &oo, int argc, char **argv)
void init_params (parallel_runtime *rt, opts &oo, sprockit::sim_parameters *params, bool parallel)
void remap_deprecated_params (sprockit::sim_parameters *params)
void process_init_params (sprockit::sim_parameters *params, bool remap_params)
void run (opts &oo, sstmac::parallel_runtime *rt, sprockit::sim_parameters *params, sim_stats &stats, bool params_only)
void try_main (sprockit::sim_parameters *params, int argc, char **argv, bool params_only=false)
void run_params (parallel_runtime *rt, sprockit::sim_parameters *params, sim_stats &stats)
void init_first_run (parallel_runtime *rt, sprockit::sim_parameters *params)
void parse_port_name (const std::string &port_name, connection_details *dets)
sprockit::sim_parameters * make_sim_params_from_params (const SST::Params &map)
template<typename Mapping >
sprockit::sim_parameters * make_sim_params_from_mapping (Mapping &&map)
Detailed Description
SUMI = Simulator unified messagine interface It is also the name for a solid ink in Japanese - i.e.
"Fixed time quanta" collection of the amount of work done in particular time intervals over the course of the computation
the substrate for sending messages!
Typedef Documentation
typedef uint32_t sstmac::endpoint_id
Definition at line 19 of file node_address.h.
typedef endpoint_id sstmac::netlink_id
Definition at line 25 of file node_address.h.
typedef endpoint_id sstmac::node_id
Definition at line 20 of file node_address.h.
typedef int sstmac::pipe_t[2]
Definition at line 61 of file driver.h.
typedef topology_id sstmac::switch_id
Definition at line 23 of file node_address.h.
typedef mutex_thread_lock sstmac::thread_lock
Definition at line 66 of file thread_lock.h.
typedef thread_safe_int_t<int> sstmac::thread_safe_int
Definition at line 59 of file thread_safe_int.h.
typedef thread_safe_int_t<long> sstmac::thread_safe_long
Definition at line 60 of file thread_safe_int.h.
typedef thread_safe_int_t<long long> sstmac::thread_safe_long_long
Definition at line 61 of file thread_safe_int.h.
typedef thread_safe_int_t<size_t> sstmac::thread_safe_size_t
Definition at line 62 of file thread_safe_int.h.
typedef int32_t sstmac::topology_id
Definition at line 22 of file node_address.h.
Function Documentation
template<class T > int sstmac::append_label (char * buffer, const T & t)
Definition at line 50 of file driver.h.
References sstmac::Labeler< T >::assign_label().
sstmac::DeclareFactory (stat_collector)
sstmac::DeclareFactory (parallel_runtime)
sstmac::DeclareFactory1InitParam (partition , parallel_runtime *)
sstmac::DeclareFactory1InitParam (event_manager , parallel_runtime *)
template<class Cls , typename Fxn > event_callback* sstmac::ev_callback (Cls * cls, Fxn fxn)
Definition at line 125 of file event_callback.h.
template<class Cls , typename Fxn > event_callback* sstmac::ev_callback (event_loc_id loc, Cls * cls, Fxn fxn)
Definition at line 133 of file event_callback.h.
template<class Cls , typename Fxn , typename Arg1 > event_callback* sstmac::ev_callback (event_loc_id loc, Cls * cls, Fxn fxn, const Arg1 & arg1)
Definition at line 141 of file event_callback.h.
template<class Cls , typename Fxn , typename Arg1 , typename Arg2 > event_callback* sstmac::ev_callback (event_loc_id loc, Cls * cls, Fxn fxn, const Arg1 & arg1, const Arg2 & arg2)
Definition at line 151 of file event_callback.h.
template<class T > int sstmac::extract_label (char * buffer, T & t)
Definition at line 56 of file driver.h.
References sstmac::Labeler< T >::extract_label().
void sstmac::finalize (parallel_runtime * rt)
Referenced by sstmac::SimulationQueue::setNextWorker(), sim_stats::sim_stats(), and sstmac::Simulation::stats().
parallel_runtime* sstmac::init ()
Referenced by DeclareDebugSlot(), sstmac::hw::packet_flow_netlink::ejector(), sstmac::hw::packet_flow_netlink::injector(), sstmac::SimulationQueue::setNextWorker(), sim_stats::sim_stats(), sstmac::native::thread_barrier::thread_barrier(), and sstmac::event_scheduler::to_string().
void sstmac::init_first_run (parallel_runtime * rt, sprockit::sim_parameters * params)
Referenced by sim_stats::sim_stats().
void sstmac::init_opts (opts & oo, int argc, char ** argv)
Referenced by sim_stats::sim_stats().
void sstmac::init_params (parallel_runtime * rt, opts & oo, sprockit::sim_parameters * params, bool parallel)
Referenced by sim_stats::sim_stats().
template<typename Mapping > sprockit::sim_parameters* sstmac::make_sim_params_from_mapping (Mapping && map)
Definition at line 35 of file integrated_core.h.
sprockit::sim_parameters* sstmac::make_sim_params_from_params (const SST::Params & map) inline
Definition at line 20 of file integrated_core.h.
template<class T , class Fxn > deadlock_check* sstmac::new_deadlock_check (T * t, Fxn f)
Definition at line 36 of file runtime.h.
template<class Cls , typename Fxn , class Arg1 > event_queue_entry* sstmac::new_event (Cls * cls, Fxn fxn, const Arg1 & arg1)
Definition at line 257 of file event_callback.h.
template<class Cls , typename Fxn , class Arg1 , class Arg2 > event_queue_entry* sstmac::new_event (Cls * cls, Fxn fxn, const Arg1 & arg1, const Arg2 & arg2)
Definition at line 265 of file event_callback.h.
template<class Cls , typename Fxn > event_queue_entry* sstmac::new_event (event_loc_id local, Cls * cls, Fxn fxn)
Definition at line 273 of file event_callback.h.
template<class Cls , typename Fxn , class Arg1 > event_queue_entry* sstmac::new_event (event_loc_id local, Cls * cls, Fxn fxn, const Arg1 & arg1)
Definition at line 281 of file event_callback.h.
template<class Cls , typename Fxn , class Arg1 , class Arg2 > event_queue_entry* sstmac::new_event (event_loc_id local, Cls * cls, Fxn fxn, const Arg1 & arg1, const Arg2 & arg2)
Definition at line 289 of file event_callback.h.
bool sstmac::operator!= (const event_loc_id & a, const event_loc_id & b) inline
Definition at line 91 of file event_location.h.
References sstmac::event_loc_id::location.
timestamp sstmac::operator* (const timestamp & t, double scaling)
Referenced by sstmac::timestamp::operator>=().
timestamp sstmac::operator* (double scaling, const timestamp & t)
timestamp sstmac::operator+ (const timestamp & a, const timestamp & b)
Referenced by sstmac::timestamp::operator>=().
timestamp sstmac::operator- (const timestamp & a, const timestamp & b)
Referenced by sstmac::timestamp::operator>=().
timestamp sstmac::operator/ (const timestamp & t, double scaling)
Referenced by sstmac::timestamp::operator>=().
bool sstmac::operator< (const event_loc_id & a, const event_loc_id & b) inline
Definition at line 96 of file event_location.h.
References sstmac::event_loc_id::location.
std::ostream& sstmac::operator<< (std::ostream & os, const event_loc_id & loc) inline
Definition at line 101 of file event_location.h.
References sstmac::event_loc_id::convert_to_node_id(), sstmac::event_loc_id::convert_to_switch_id(), and sstmac::event_loc_id::is_node_id().
Referenced by sstmac::timestamp::operator>=().
std::ostream& sstmac::operator<< (std::ostream & os, const timestamp & t)
bool sstmac::operator== (const event_loc_id & a, const event_loc_id & b) inline
Definition at line 86 of file event_location.h.
References sstmac::event_loc_id::location.
void sstmac::parse_port_name (const std::string & port_name, connection_details * dets)
void sstmac::process_init_params (sprockit::sim_parameters * params, bool remap_params)
Referenced by sim_stats::sim_stats().
void sstmac::remap_deprecated_params (sprockit::sim_parameters * params)
Referenced by sim_stats::sim_stats().
void sstmac::run (opts & oo, sstmac::parallel_runtime * rt, sprockit::sim_parameters * params, sim_stats & stats, bool params_only)
Referenced by sstmac::sw::app::parent_app(), sstmac::SimulationQueue::setNextWorker(), sim_stats::sim_stats(), sstmac::native::thread_barrier::thread_barrier(), and sstmac::native::multithreaded_event_container::~multithreaded_event_container().
void sstmac::run_params (parallel_runtime * rt, sprockit::sim_parameters * params, sim_stats & stats)
Referenced by sim_stats::sim_stats().
std::string sstmac::to_printf_type (timestamp t)
Referenced by sstmac::timestamp::operator>=().
void sstmac::try_main (sprockit::sim_parameters * params, int argc, char ** argv, bool params_only = false)
Referenced by sim_stats::sim_stats().