SST/macro: sprockit::pvt Namespace Reference
sprockit::pvt Namespace Reference
Classes
class raw_ptr_wrapper
class ser_array_wrapper
class ser_buffer_accessor
class ser_buffer_overrun
class ser_packer
class ser_sizer
class ser_unpacker
Functions
void size_serializable (serializable *s, serializer &ser)
void pack_serializable (serializable *s, serializer &ser)
void unpack_serializable (serializable *&s, serializer &ser)
template<class Container , class T >
void serialize_container (Container &v, serializer &ser)
template<class Map , class Key , class Value >
void serialize_map (Map &m, serializer &ser)
template<class Set , class T >
void serialize_set (Set &v, serializer &ser)
Function Documentation
void sprockit::pvt::pack_serializable (serializable * s, serializer & ser)
Referenced by sprockit::serialize< serializable * >::operator()(), and sprockit::serialize_intrusive_ptr().
template<class Container , class T > void sprockit::pvt::serialize_container (Container & v, serializer & ser)
Definition at line 14 of file serialize_list.h.
References sprockit::serializer::mode(), sprockit::serializer::PACK, sprockit::serializer::pack(), sprockit::serializer::size(), sprockit::serializer::SIZER, sprockit::serializer::UNPACK, and sprockit::serializer::unpack().
template<class Map , class Key , class Value > void sprockit::pvt::serialize_map (Map & m, serializer & ser)
Definition at line 14 of file serialize_map.h.
References sprockit::serializer::mode(), sprockit::serializer::PACK, sprockit::serializer::pack(), sprockit::serializer::size(), sprockit::serializer::SIZER, sprockit::serializer::UNPACK, and sprockit::serializer::unpack().
template<class Set , class T > void sprockit::pvt::serialize_set (Set & v, serializer & ser)
Definition at line 14 of file serialize_set.h.
References sprockit::serializer::mode(), sprockit::serializer::PACK, sprockit::serializer::pack(), sprockit::serializer::size(), sprockit::serializer::SIZER, sprockit::serializer::UNPACK, and sprockit::serializer::unpack().
void sprockit::pvt::size_serializable (serializable * s, serializer & ser)
Referenced by sprockit::serialize< serializable * >::operator()(), and sprockit::serialize_intrusive_ptr().
void sprockit::pvt::unpack_serializable (serializable *& s, serializer & ser)
Referenced by sprockit::serialize< serializable * >::operator()(), and sprockit::serialize_intrusive_ptr().