SST/macro: sstmac::sw::P Namespace Reference
sstmac::sw::P Namespace Reference
Namespace for internal utility print routines.
Functions
template<typename T >
std::string ints (int len, const T *arr)
template<typename T >
std::string ints (bool do_output, int len, const T *arr)
template<typename T >
std::string ints2d (int xl, int yl, T **arr)
std::string statuses (int len, const dumpi_status *statuses)
std::string stringarray (int len, char **arr)
std::string stringarray (bool do_output, int len, char **arr)
std::string stringarraynull (char **arr)
std::string stringarraynull (bool do_output, char **arr)
std::string stringarraynull2d (bool do_output, int xl, char ***arr)
Detailed Description
Namespace for internal utility print routines.
Function Documentation
template<typename T > std::string sstmac::sw::P::ints (int len, const T * arr)
Definition at line 75 of file dumpi_type_io.h.
Referenced by ints(), ints2d(), and sstmac::sw::operator<<().
template<typename T > std::string sstmac::sw::P::ints (bool do_output, int len, const T * arr)
Definition at line 93 of file dumpi_type_io.h.
References ints().
template<typename T > std::string sstmac::sw::P::ints2d (int xl, int yl, T ** arr)
Definition at line 104 of file dumpi_type_io.h.
References ints().
Referenced by sstmac::sw::operator<<().
std::string sstmac::sw::P::statuses (int len, const dumpi_status * statuses) inline
Definition at line 129 of file dumpi_type_io.h.
Referenced by sstmac::sw::operator<<().
std::string sstmac::sw::P::stringarray (int len, char ** arr) inline
Definition at line 149 of file dumpi_type_io.h.
Referenced by sstmac::sw::operator<<(), and stringarray().
std::string sstmac::sw::P::stringarray (bool do_output, int len, char ** arr) inline
Definition at line 169 of file dumpi_type_io.h.
References stringarray().
std::string sstmac::sw::P::stringarraynull (char ** arr) inline
Definition at line 180 of file dumpi_type_io.h.
Referenced by sstmac::sw::operator<<(), stringarraynull(), and stringarraynull2d().
std::string sstmac::sw::P::stringarraynull (bool do_output, char ** arr) inline
Definition at line 200 of file dumpi_type_io.h.
References stringarraynull().
std::string sstmac::sw::P::stringarraynull2d (bool do_output, int xl, char *** arr) inline
Definition at line 211 of file dumpi_type_io.h.
References stringarraynull().
Referenced by sstmac::sw::operator<<().