SST/macro: sstmac/hardware/switch/network_switch.h File Reference
network_switch.h File Reference
#include <sprockit/factories/factory.h>
#include <sprockit/debug.h>
#include <sstmac/hardware/common/connection.h>
#include <sstmac/hardware/router/router_fwd.h>
#include <sstmac/hardware/topology/topology_fwd.h>
#include <sprockit/sim_parameters_fwd.h>
#include <vector>
Functions
DeclareDebugSlot (network_switch) namespace sstmac
Function Documentation
DeclareDebugSlot (network_switch)
The network_switch class A class encapsulating a network switch that packets must traverse on the network. The network switch performs both routing computations and congestion modeling.
rter
Returns
The router used for performing routing computations
queue_length Compute the number of packets waiting on the switch. The queue length is a multiple of the ``system'' packet size, which can be different from the packet size used by SST/macro congestion models. For example, the packet size of the system beings simulated might be 100B, but SST/macro might be doing congestion computations on units of 1024B.
Parameters
port The port to check the queue length of
Returns
The queue length as an integer number of packets waiting
Parameters
addr The destination node addr to eject to
Returns
The ejection port the node is connected on
Parameters
addr The source node addr to ack to
Returns
The injection port the node is connected on
The total hop latency to transit from input of one switch to the next (with zero congestion)
lookahead For parallel simulations, returns the maximum PDES lookahead possible between two network switches. This is usually (but not always) the sames as the hop latency
Returns
The PDES lookahead
The bandwidth observed hopping from switch to switch (with zero congestion)
connect
Parameters
src_outport The port that packets will exit on the source
dst_inport The port that packets will enter on the destination
ty The type of connection (usually just output or input) An output connection is a data link that carries payload from src to dst. An input connection is a control link that usually just carries credit/arbitration info from dst to src.
mod The dst (if output link) or src (if input link)
cfg An special configure options for the link
Definition at line 31 of file network_switch.h.
References DeclareFactory, sstmac::init(), sstmac::hw::init_factory_params(), and sstmac::hw::set_event_manager().