SST/macro: sprockit/sprockit/sim_parameters.h File Reference
sim_parameters.h File Reference
#include <sprockit/debug.h>
#include <sprockit/unordered.h>
#include <iostream>
#include <list>
#include <vector>
#include <set>
Functions
DeclareDebugSlot (params) DeclareDebugSlot(read_params) DeclareDebugSlot(write_params) namespace sprockit
Function Documentation
DeclareDebugSlot (params)
In a parallel environment (abstracted through a param_bcaster object), have rank 0 read params from a file and bcast result to all other ranks
Parameters
params A parameter object (already allocated)
me The rank of the calling process
nproc The total number of ranks
filename
bcaster
Return the value of the keyword if it exists. Otherwise return a default value.
Parameters
key gives the keyword
def gives the default value (used if has_param(key) is false)
Returns
the value if it exists, otherwise the default
Return the value of the keyword if it exists. Otherwise return a default value.
Parameters
key gives the keyword
def gives the default value (used if has_param(key) is false)
Returns
the value if it exists, otherwise the default
Returns the value of the key as a boolean.
Return the value of the keyword if it exists. Otherwise return a default value.
Parameters
key gives the keyword
def gives the default value (used if has_param(key) is false)
Returns
the value if it exists, otherwise the default
Parameters
key The parameter name
Returns
A value with units. This loops through bandwidth, frequency, time, etc to return any value that can have units. Everything is normalized to baseslines of B/s, s, Hz, etc
Return the value of the keyword if it exists. Otherwise return a default value.
Parameters
key gives the keyword
def gives the default value (used if has_param(key) is false)
Returns
the value if it exists, otherwise the default
Return the value of the keyword if it exists. Otherwise return a default value.
Parameters
key gives the keyword
def gives the default value (used if has_param(key) is false)
Returns
the value if it exists, otherwise the default
Parameters
key
value
fail_on_existing Fail if the parameter named by key already exists
Definition at line 24 of file sim_parameters.h.
References get_bool_param(), get_double_param(), get_int_param(), get_long_param(), get_optional_bool_param(), get_optional_double_param(), get_optional_int_param(), get_optional_long_param(), get_optional_param(), and get_param().