SST/macro: sstmac/main/sstmac.h File Reference
sstmac.h File Reference
#include <sprockit/sim_parameters_fwd.h>
#include <sstmac/backends/native/manager_fwd.h>
#include <sstmac/backends/common/parallel_runtime_fwd.h>
#include <string>
Classes
struct opts
struct sim_stats
Namespaces
sstmac
SUMI = Simulator unified messagine interface It is also the name for a solid ink in Japanese - i.e.
Macros
#define PARSE_OPT_SUCCESS 0
#define PARSE_OPT_EXIT_SUCCESS 1
#define PARSE_OPT_EXIT_FAIL 2
Functions
std::ostream & operator<< (std::ostream &os, const opts &oo)
int parse_opts (int argc, char **argv, opts &oo)
void print_help (int argc, char **argv)
void resize_topology (int max_nproc, sprockit::sim_parameters *params, bool verbose=true)
void map_env_params (sprockit::sim_parameters *params)
parallel_runtime * sstmac::init ()
void sstmac::finalize (parallel_runtime *rt)
void sstmac::init_opts (opts &oo, int argc, char **argv)
void sstmac::init_params (parallel_runtime *rt, opts &oo, sprockit::sim_parameters *params, bool parallel)
void sstmac::remap_deprecated_params (sprockit::sim_parameters *params)
void sstmac::remap_params (sprockit::sim_parameters *params, bool verbose=true)
void sstmac::run (opts &oo, sstmac::parallel_runtime *rt, sprockit::sim_parameters *params, sim_stats &stats)
void sstmac::try_main (sprockit::sim_parameters *params, int argc, char **argv, bool params_only=false)
void sstmac::run_params (parallel_runtime *rt, sprockit::sim_parameters *params, sim_stats &stats)
void sstmac::init_first_run (parallel_runtime *rt, sprockit::sim_parameters *params)
Macro Definition Documentation
#define PARSE_OPT_EXIT_FAIL 2
Definition at line 22 of file sstmac.h.
#define PARSE_OPT_EXIT_SUCCESS 1
Definition at line 21 of file sstmac.h.
#define PARSE_OPT_SUCCESS 0
Definition at line 20 of file sstmac.h.
Function Documentation
void map_env_params (sprockit::sim_parameters * params)
Referenced by sim_stats::sim_stats().
std::ostream& operator<< (std::ostream & os, const opts & oo)
Referenced by opts::opts().
int parse_opts (int argc, char ** argv, opts & oo)
Referenced by sim_stats::sim_stats().
void print_help (int argc, char ** argv)
Referenced by sim_stats::sim_stats().
void resize_topology (int max_nproc, sprockit::sim_parameters * params, bool verbose = true)
Referenced by sim_stats::sim_stats().