SST/macro: sprockit/sprockit/stl_string.h File Reference
stl_string.h File Reference
#include <set>
#include <vector>
#include <list>
#include <map>
#include <sstream>
Functions
template<class Container >
std::string one_dim_string (const Container &c, const char *open, const char *close)
template<class T >
std::string stl_string (const std::set< T > &t)
template<class T >
std::string stl_string (const std::vector< T > &t)
template<class T >
std::string stl_string (const std::list< T > &t)
Function Documentation
template<class Container > std::string one_dim_string (const Container & c, const char * open, const char * close)
Definition at line 12 of file stl_string.h.
Referenced by stl_string().
template<class T > std::string stl_string (const std::set< T > & t)
Definition at line 25 of file stl_string.h.
References one_dim_string().
template<class T > std::string stl_string (const std::vector< T > & t)
Definition at line 31 of file stl_string.h.
References one_dim_string().
template<class T > std::string stl_string (const std::list< T > & t)
Definition at line 37 of file stl_string.h.
References one_dim_string().