SST/macro: sstmac::hw::structured_routable::path Struct Reference
sstmac::hw::structured_routable::path Struct Reference
#include <routable.h>
Public Member Functions
path ()
bool metadata_bit (metadata_slot slot) const
void set_metadata_bit (metadata_slot slot)
void unset_metadata_bit (metadata_slot slot)
void clear_metadata ()
Public Attributes
int outport
int vc
int geometric_id
An identifier indicating what geometric path on the topology this is following.
sprockit::metadata_bits< uint32_t > metadata
Detailed Description
Definition at line 20 of file routable.h.
Constructor & Destructor Documentation
sstmac::hw::structured_routable::path::path () inline
Definition at line 27 of file routable.h.
Member Function Documentation
void sstmac::hw::structured_routable::path::clear_metadata () inline
Definition at line 53 of file routable.h.
References sprockit::metadata_bits< integer >::clear(), and metadata.
bool sstmac::hw::structured_routable::path::metadata_bit (metadata_slot slot) const inline
Definition at line 38 of file routable.h.
References sprockit::metadata_bits< integer >::bit(), and metadata.
void sstmac::hw::structured_routable::path::set_metadata_bit (metadata_slot slot) inline
Definition at line 43 of file routable.h.
References metadata, and sprockit::metadata_bits< integer >::set_bit().
void sstmac::hw::structured_routable::path::unset_metadata_bit (metadata_slot slot) inline
Definition at line 48 of file routable.h.
References metadata, and sprockit::metadata_bits< integer >::unset_bit().
Member Data Documentation
int sstmac::hw::structured_routable::path::geometric_id
An identifier indicating what geometric path on the topology this is following.
Definition at line 24 of file routable.h.
sprockit::metadata_bits<uint32_t> sstmac::hw::structured_routable::path::metadata
Definition at line 25 of file routable.h.
Referenced by clear_metadata(), metadata_bit(), set_metadata_bit(), and unset_metadata_bit().
int sstmac::hw::structured_routable::path::outport
Definition at line 21 of file routable.h.
Referenced by sstmac::hw::structured_routable::port().
int sstmac::hw::structured_routable::path::vc
Definition at line 22 of file routable.h.
Referenced by sstmac::hw::structured_routable::check_vc(), and sstmac::hw::structured_routable::vc().
The documentation for this struct was generated from the following file:
sstmac/hardware/router/routable.h