SST/macro: sstmac::hw::routing_info::path Struct Reference
sstmac::hw::routing_info::path Struct Reference
#include <routing_info.h>
Public Member Functions
path ()
bool metadata_bit (metadata_slot slot) const
void set_metadata_bit (metadata_slot slot)
void unset_metadata_bit (metadata_slot slot)
void clear_metadata ()
Public Attributes
int outport
int vc
int geometric_id
An identifier indicating what geometric path on the topology this is following.
sprockit::metadata_bits< uint32_t > metadata
Detailed Description
Definition at line 37 of file routing_info.h.
Constructor & Destructor Documentation
sstmac::hw::routing_info::path::path () inline
Definition at line 44 of file routing_info.h.
Member Function Documentation
void sstmac::hw::routing_info::path::clear_metadata () inline
Definition at line 70 of file routing_info.h.
References sprockit::metadata_bits< integer >::clear().
bool sstmac::hw::routing_info::path::metadata_bit (metadata_slot slot) const inline
Definition at line 55 of file routing_info.h.
References sprockit::metadata_bits< integer >::bit().
void sstmac::hw::routing_info::path::set_metadata_bit (metadata_slot slot) inline
Definition at line 60 of file routing_info.h.
References sprockit::metadata_bits< integer >::set_bit().
void sstmac::hw::routing_info::path::unset_metadata_bit (metadata_slot slot) inline
Definition at line 65 of file routing_info.h.
References sprockit::metadata_bits< integer >::unset_bit().
Member Data Documentation
int sstmac::hw::routing_info::path::geometric_id
An identifier indicating what geometric path on the topology this is following.
Definition at line 41 of file routing_info.h.
sprockit::metadata_bits<uint32_t> sstmac::hw::routing_info::path::metadata
Definition at line 42 of file routing_info.h.
int sstmac::hw::routing_info::path::outport
Definition at line 38 of file routing_info.h.
Referenced by sstmac::hw::routing_info::port().
int sstmac::hw::routing_info::path::vc
Definition at line 39 of file routing_info.h.
Referenced by sstmac::hw::routing_info::check_vc(), and sstmac::hw::routing_info::vc().
The documentation for this struct was generated from the following file:
sstmac/hardware/router/routing_info.h