SST/macro: opts Struct Reference
opts Struct Reference
#include <sstmac.h>
Public Member Functions
opts ()
~opts ()
Public Attributes
int help
std::string debug
std::string configfile
sprockit::sim_parameters * params
bool print_walltime
bool print_params
bool low_res_timer
std::string cpu_affinity
Detailed Description
Definition at line 24 of file sstmac.h.
Constructor & Destructor Documentation
opts::opts () inline
Definition at line 34 of file sstmac.h.
References operator<<(), and ~opts().
opts::~opts ()
Referenced by opts().
Member Data Documentation
std::string opts::configfile
Definition at line 27 of file sstmac.h.
std::string opts::cpu_affinity
Definition at line 32 of file sstmac.h.
std::string opts::debug
Definition at line 26 of file sstmac.h.
int opts::help
Definition at line 25 of file sstmac.h.
bool opts::low_res_timer
Definition at line 31 of file sstmac.h.
sprockit::sim_parameters* opts::params
Definition at line 28 of file sstmac.h.
Referenced by sim_stats::sim_stats().
bool opts::print_params
Definition at line 30 of file sstmac.h.
bool opts::print_walltime
Definition at line 29 of file sstmac.h.
The documentation for this struct was generated from the following file:
sstmac/main/sstmac.h