SST/macro: sstmac::hw::geometry_routable::path Struct Reference
sstmac::hw::geometry_routable::path Struct Reference
#include <routable.h>
Classes
struct Hop
Public Member Functions
path ()
bool metadata_bit (metadata_slot slot) const
void set_metadata_bit (metadata_slot slot)
void unset_metadata_bit (metadata_slot slot)
void clear_metadata ()
Public Attributes
int outport
int vc
int geometric_id
An identifier indicating what geometric path on the topology this is following.
sprockit::metadata_bits< uint32_t > metadata
std::vector< Hop > chosen
Detailed Description
Definition at line 20 of file routable.h.
Constructor & Destructor Documentation
sstmac::hw::geometry_routable::path::path () inline
Definition at line 39 of file routable.h.
Member Function Documentation
void sstmac::hw::geometry_routable::path::clear_metadata () inline
Definition at line 65 of file routable.h.
References sprockit::metadata_bits< integer >::clear().
bool sstmac::hw::geometry_routable::path::metadata_bit (metadata_slot slot) const inline
Definition at line 50 of file routable.h.
References sprockit::metadata_bits< integer >::bit().
void sstmac::hw::geometry_routable::path::set_metadata_bit (metadata_slot slot) inline
Definition at line 55 of file routable.h.
References sprockit::metadata_bits< integer >::set_bit().
void sstmac::hw::geometry_routable::path::unset_metadata_bit (metadata_slot slot) inline
Definition at line 60 of file routable.h.
References sprockit::metadata_bits< integer >::unset_bit().
Member Data Documentation
std::vector<Hop> sstmac::hw::geometry_routable::path::chosen
Definition at line 37 of file routable.h.
int sstmac::hw::geometry_routable::path::geometric_id
An identifier indicating what geometric path on the topology this is following.
Definition at line 24 of file routable.h.
sprockit::metadata_bits<uint32_t> sstmac::hw::geometry_routable::path::metadata
Definition at line 25 of file routable.h.
int sstmac::hw::geometry_routable::path::outport
Definition at line 21 of file routable.h.
Referenced by sstmac::hw::geometry_routable::port().
int sstmac::hw::geometry_routable::path::vc
Definition at line 22 of file routable.h.
Referenced by sstmac::hw::geometry_routable::check_vc(), and sstmac::hw::geometry_routable::vc().
The documentation for this struct was generated from the following file:
sstmac/hardware/router/routable.h