SST/macro: sstmac::native::event_map::event_compare Struct Reference
sstmac::native::event_map::event_compare Struct Reference
#include <event_map.h>
Public Member Functions
bool operator() (event_queue_entry *lhs, event_queue_entry *rhs)
Detailed Description
Definition at line 59 of file event_map.h.
Member Function Documentation
bool sstmac::native::event_map::event_compare::operator() (event_queue_entry * lhs, event_queue_entry * rhs) inline
Definition at line 60 of file event_map.h.
References sstmac::event_queue_entry::seqnum(), sstmac::event_queue_entry::src_location(), and sstmac::event_queue_entry::time().
The documentation for this struct was generated from the following file:
sstmac/backends/native/event_map.h