SST/macro: sim_stats Struct Reference
sim_stats Struct Reference
#include <sstmac.h>
Public Member Functions
sim_stats ()
Public Attributes
double wallTime
double simulatedTime
int numResults
Detailed Description
Definition at line 51 of file sstmac.h.
Constructor & Destructor Documentation
sim_stats::sim_stats () inline
Definition at line 55 of file sstmac.h.
References sstmac::finalize(), sstmac::init(), sstmac::init_first_run(), sstmac::init_opts(), sstmac::init_params(), map_env_params(), opts::params, parse_opts(), print_help(), sstmac::remap_deprecated_params(), sstmac::remap_params(), resize_topology(), sstmac::run(), sstmac::run_params(), and sstmac::try_main().
Member Data Documentation
int sim_stats::numResults
Definition at line 54 of file sstmac.h.
Referenced by sstmac::Simulation::allocateResults(), sstmac::Simulation::numResults(), and sstmac::Simulation::setResults().
double sim_stats::simulatedTime
Definition at line 53 of file sstmac.h.
Referenced by sstmac::Simulation::simulatedTime().
double sim_stats::wallTime
Definition at line 52 of file sstmac.h.
Referenced by sstmac::Simulation::wallTime().
The documentation for this struct was generated from the following file:
sstmac/main/sstmac.h