SST/macro: sstmac::event_loc_id Struct Reference
sstmac::event_loc_id Struct Reference
#include <event_location.h>
Public Member Functions
event_loc_id ()
event_loc_id (topology_id id)
event_loc_id (endpoint_id id)
bool is_node_id () const
bool is_switch_id () const
node_id convert_to_node_id () const
switch_id convert_to_switch_id () const
bool is_null () const
event_loc_id & operator= (topology_id id)
event_loc_id & operator= (endpoint_id id)
Public Attributes
int32_t location
Static Public Attributes
static event_loc_id null
static event_loc_id uninitialized
Detailed Description
Definition at line 9 of file event_location.h.
Constructor & Destructor Documentation
sstmac::event_loc_id::event_loc_id () inline
Definition at line 14 of file event_location.h.
sstmac::event_loc_id::event_loc_id (topology_id id) inline explicit
Definition at line 18 of file event_location.h.
sstmac::event_loc_id::event_loc_id (endpoint_id id) inline explicit
Definition at line 22 of file event_location.h.
Member Function Documentation
node_id sstmac::event_loc_id::convert_to_node_id () const inline
Definition at line 37 of file event_location.h.
References is_null(), is_switch_id(), and spkt_throw.
Referenced by sstmac::operator<<().
switch_id sstmac::event_loc_id::convert_to_switch_id () const inline
Definition at line 52 of file event_location.h.
References is_node_id(), is_null(), and spkt_throw.
Referenced by sstmac::operator<<().
bool sstmac::event_loc_id::is_node_id () const inline
Definition at line 27 of file event_location.h.
Referenced by convert_to_switch_id(), and sstmac::operator<<().
bool sstmac::event_loc_id::is_null () const inline
Definition at line 67 of file event_location.h.
References location.
Referenced by convert_to_node_id(), and convert_to_switch_id().
bool sstmac::event_loc_id::is_switch_id () const inline
Definition at line 32 of file event_location.h.
References location.
Referenced by convert_to_node_id().
event_loc_id& sstmac::event_loc_id::operator= (topology_id id) inline
Definition at line 72 of file event_location.h.
event_loc_id& sstmac::event_loc_id::operator= (endpoint_id id) inline
Definition at line 78 of file event_location.h.
Member Data Documentation
int32_t sstmac::event_loc_id::location
Definition at line 10 of file event_location.h.
Referenced by is_null(), is_switch_id(), sstmac::operator!=(), sstmac::operator<(), and sstmac::operator==().
event_loc_id sstmac::event_loc_id::null static
Definition at line 11 of file event_location.h.
Referenced by DeclareDebugSlot(), sstmac::hw::simple_interconnect::event_location(), sstmac::integrated_connectable_wrapper::event_location(), sstmac::connectable_proxy_component::event_location(), and sstmac::hw::macro_switch_interconnect::event_location().
event_loc_id sstmac::event_loc_id::uninitialized static
Definition at line 12 of file event_location.h.
The documentation for this struct was generated from the following file:
sstmac/common/event_location.h